/**
 * Image-URL fields in non-EN locale JSON files were generated by tooling that
 * dropped Unsplash placeholders in place of the hand-curated EN photography
 * (visitjeju / visitkorea / Supabase). Switching languages therefore swaps
 * every photo on the tour-product detail page.
 *
 * `overrideImageFieldsFromEn` walks a merged document and replaces any string
 * value that looks like an image URL with the EN document's value at the same
 * structural path — so locale text stays localized, but photography always
 * comes from EN. Array entries are matched by index; if the locale array has
 * more items than EN, the surplus entries keep their original (placeholder)
 * value rather than being deleted.
 *
 * Detection is conservative: only strings that are obvious image URLs (image
 * file extensions or one of the known image hosts) are treated as overridable.
 * This keeps copy strings, slugs, and arbitrary URL fields from being touched
 * by accident.
 */

const IMAGE_HOST_PATTERN =
  /unsplash\.com|pexels\.com|visitjeju|visitkorea|googleusercontent|\.supabase\.(?:co|in)|^https?:\/\/[^/]*cdn\./i;

const IMAGE_EXTENSION_PATTERN = /\.(?:jpe?g|png|webp|avif|gif)(?:\?|#|$)/i;

/** True when the value is a string that almost certainly points at an image asset. */
export function isImageUrl(v: unknown): v is string {
  if (typeof v !== "string") return false;
  if (v.length === 0) return false;
  if (v.startsWith("/images/")) return true;
  if (!/^https?:\/\//i.test(v)) return false;
  if (IMAGE_EXTENSION_PATTERN.test(v)) return true;
  return IMAGE_HOST_PATTERN.test(v);
}

/**
 * Recursively replace image-URL string fields in `target` with the value from
 * `enSource` at the same structural path. Non-image strings, numbers, booleans,
 * and structurally-mismatched branches are left as-is.
 *
 * The function returns a new object/array tree; the input is not mutated.
 */
export function overrideImageFieldsFromEn<T>(target: T, enSource: unknown): T {
  if (target === null || target === undefined) return target;

  if (Array.isArray(target)) {
    const enArr = Array.isArray(enSource) ? (enSource as readonly unknown[]) : undefined;
    return target.map((v, i) => overrideImageFieldsFromEn(v, enArr?.[i])) as unknown as T;
  }

  if (typeof target === "object") {
    const enObj =
      typeof enSource === "object" && enSource !== null && !Array.isArray(enSource)
        ? (enSource as Record<string, unknown>)
        : undefined;
    const out: Record<string, unknown> = { ...(target as Record<string, unknown>) };
    for (const k of Object.keys(target as object)) {
      const tv = (target as Record<string, unknown>)[k];
      const sv = enObj?.[k];
      if (isImageUrl(tv)) {
        if (isImageUrl(sv)) out[k] = sv;
        // EN doesn't have a value at this path → leave the locale value alone.
      } else if (typeof tv === "object" && tv !== null) {
        out[k] = overrideImageFieldsFromEn(tv, sv);
      }
    }
    return out as T;
  }

  return target;
}
