/**
 * Image-URL fields in non-EN locale JSON files were generated by tooling that
 * dropped Unsplash placeholders in place of the hand-curated EN photography
 * (visitjeju / visitkorea / Supabase). Switching languages therefore swaps
 * every photo on the tour-product detail page.
 *
 * `overrideImageFieldsFromEn` walks a merged document and replaces any string
 * value that looks like an image URL with the EN document's value at the same
 * structural path — so locale text stays localized, but photography always
 * comes from EN. Array entries are matched by index; if the locale array has
 * more items than EN, the surplus entries keep their original (placeholder)
 * value rather than being deleted.
 *
 * Detection is conservative: only strings that are obvious image URLs (image
 * file extensions or one of the known image hosts) are treated as overridable.
 * This keeps copy strings, slugs, and arbitrary URL fields from being touched
 * by accident.
 */

const IMAGE_HOST_PATTERN =
  /unsplash\.com|pexels\.com|visitjeju|visitkorea|googleusercontent|\.supabase\.(?:co|in)|^https?:\/\/[^/]*cdn\./i;

const IMAGE_EXTENSION_PATTERN = /\.(?:jpe?g|png|webp|avif|gif)(?:\?|#|$)/i;

/** True when the value is a string that almost certainly points at an image asset. */
export function isImageUrl(v: unknown): v is string {
  if (typeof v !== "string") return false;
  if (v.length === 0) return false;
  if (v.startsWith("/images/")) return true;
  if (!/^https?:\/\//i.test(v)) return false;
  if (IMAGE_EXTENSION_PATTERN.test(v)) return true;
  return IMAGE_HOST_PATTERN.test(v);
}

/** True when the value is an array of image URL strings (gallery field). */
function isImageUrlArray(v: unknown): v is string[] {
  return Array.isArray(v) && v.length > 0 && v.every((item) => isImageUrl(item));
}

/** True when the value should be considered an image asset (single URL or gallery array). */
function isImageAsset(v: unknown): v is string | string[] {
  return isImageUrl(v) || isImageUrlArray(v);
}

/**
 * Recursively replace image-URL fields in `target` with the value from
 * `enSource` at the same structural path. Handles both single-URL strings
 * (e.g. stop.image) and arrays of URLs (e.g. stop.images[]).
 *
 * Three cases the function handles:
 * 1. Target has an image asset + EN has one → use EN (locale photos were
 *    auto-generated Unsplash placeholders; EN is the curator).
 * 2. Target has empty/missing/null image value (incl. empty array) + EN
 *    has one → populate from EN. Lets authoring write image paths only in
 *    the EN file and have all other locales inherit at load time.
 * 3. EN has an image asset at a key that does not exist in target at all
 *    → add it to target. Same intent as case 2; supports "EN-only"
 *    authoring where the locale JSON hasn't been touched.
 *
 * The function returns a new object/array tree; the input is not mutated.
 */
export function overrideImageFieldsFromEn<T>(target: T, enSource: unknown): T {
  if (target === null || target === undefined) return target;

  if (Array.isArray(target)) {
    const enArr = Array.isArray(enSource) ? (enSource as readonly unknown[]) : undefined;
    return target.map((v, i) => overrideImageFieldsFromEn(v, enArr?.[i])) as unknown as T;
  }

  if (typeof target === "object") {
    const enObj =
      typeof enSource === "object" && enSource !== null && !Array.isArray(enSource)
        ? (enSource as Record<string, unknown>)
        : undefined;
    const out: Record<string, unknown> = { ...(target as Record<string, unknown>) };
    const localeKeys = new Set(Object.keys(target as object));

    // Walk locale keys first — overrides (case 1) and fills (case 2).
    for (const k of localeKeys) {
      const tv = (target as Record<string, unknown>)[k];
      const sv = enObj?.[k];
      if (isImageAsset(tv)) {
        // Case 1: locale already has an image asset — replace with EN's
        // version (also asset) so the gallery composition stays curated.
        if (isImageAsset(sv)) out[k] = sv;
      } else if (
        tv === "" ||
        tv === null ||
        tv === undefined ||
        (Array.isArray(tv) && tv.length === 0)
      ) {
        // Case 2: empty slot — populate from EN if EN has an asset.
        if (isImageAsset(sv)) out[k] = sv;
      } else if (typeof tv === "object" && tv !== null) {
        out[k] = overrideImageFieldsFromEn(tv, sv);
      }
    }

    // Walk EN-only keys (case 3) — keys present in EN but missing in target.
    if (enObj) {
      for (const k of Object.keys(enObj)) {
        if (localeKeys.has(k)) continue;
        const sv = enObj[k];
        if (isImageAsset(sv)) out[k] = sv;
      }
    }

    return out as T;
  }

  return target;
}
