/**
 * Slug → per-locale `tour_product_full_page_v1` JSON bundle registry.
 *
 * The catch-all `app/tour-product/[slug]/page.tsx` reads from here to resolve
 * the static JSON fallback when Supabase is unavailable or `detail_payload` is
 * incomplete. v17 batch shipped EN-only; v3 master pack (2026-05-01) restores
 * ko/ja/zh/zh-TW/es overlays for all 30 tours.
 *
 * T2 (2026-07-04): entries are LAZY `import()` loaders instead of 204 static
 * imports. The static form inlined ~5.5MB of JSON into the server bundle of
 * every consumer (detail page, assistant route, RAG indexer), inflating
 * serverless cold starts; now each (slug, locale) JSON is its own chunk loaded
 * on first use and cached by the module system. `getStaticTourProductFullPageJson`
 * is async as a result — slug REGISTRATION checks stay sync via
 * `tourProductBundleSlugs.ts`.
 */

import type { TourProductPageLocale } from "@/lib/tour-product/resolveTourProductDbLocale";
import type { StaticTourProductBundleSlug } from "./tourProductBundleSlugs";
import { STATIC_TOUR_PRODUCT_BUNDLE_SLUG_LIST } from "./tourProductBundleSlugs";
import type { TourProductFullPageJson } from "./tourProductFullPageJsonTypes";
import { overrideImageFieldsFromEn } from "./imageFieldFallback";

type BundleLoader = () => Promise<TourProductFullPageJson>;

export type TourProductLocaleBundle = Partial<Record<TourProductPageLocale, BundleLoader>> & {
  en: BundleLoader;
};

/**
 * JSON module namespaces come through as deeply-narrowed tuple literals; the
 * authoring-side contract only cares about the structural shape, so we bridge
 * through `unknown`.
 */
function loadJson(mod: Promise<{ default: unknown }>): Promise<TourProductFullPageJson> {
  return mod.then((m) => m.default as TourProductFullPageJson);
}

/**
 * Shallow merge with `en` as base so locale files can override e.g. `bookingSupportSteps` only.
 *
 * After merging, every image-URL field is forced back to the EN value at the same
 * path. Locale JSONs were generated by tooling that dropped Unsplash/CDN
 * placeholders into the photo slots, so without this step every language switch
 * would also swap every photo on the page. See `imageFieldFallback.ts`.
 */
function mergeFullPageWithLocaleBase(
  en: TourProductFullPageJson,
  loc: TourProductFullPageJson,
): TourProductFullPageJson {
  const merged: TourProductFullPageJson = { ...en, ...loc };
  if (loc.sectionUi && typeof loc.sectionUi === "object" && en.sectionUi && typeof en.sectionUi === "object") {
    merged.sectionUi = {
      ...(en.sectionUi as Record<string, string>),
      ...(loc.sectionUi as Record<string, string>),
    } as TourProductFullPageJson["sectionUi"];
  } else if (loc.sectionUi) {
    merged.sectionUi = loc.sectionUi as TourProductFullPageJson["sectionUi"];
  }
  return overrideImageFieldsFromEn(merged, en);
}

/**
 * 30 tours × 6 locales (en/ko/zh/zh-TW/es/ja). EN remains the canonical base;
 * non-EN entries are shallow-merged on top via `mergeFullPageWithLocaleBase`.
 */
export const STATIC_TOUR_PRODUCT_BUNDLES: Record<StaticTourProductBundleSlug, TourProductLocaleBundle> = {
  "busan-gyeongju-unesco-legacy-tour-national-museum": {
    en: () => loadJson(import("@/components/product-tour-static/busan-gyeongju-unesco-legacy-tour-national-museum/busan-gyeongju-unesco-legacy-tour-national-museum.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/busan-gyeongju-unesco-legacy-tour-national-museum/busan-gyeongju-unesco-legacy-tour-national-museum.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/busan-gyeongju-unesco-legacy-tour-national-museum/busan-gyeongju-unesco-legacy-tour-national-museum.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/busan-gyeongju-unesco-legacy-tour-national-museum/busan-gyeongju-unesco-legacy-tour-national-museum.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/busan-gyeongju-unesco-legacy-tour-national-museum/busan-gyeongju-unesco-legacy-tour-national-museum.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/busan-gyeongju-unesco-legacy-tour-national-museum/busan-gyeongju-unesco-legacy-tour-national-museum.ja.json")),
  },
  "busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju": {
    en: () => loadJson(import("@/components/product-tour-static/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju/busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju.ja.json")),
  },
  "busan-outskirts-tongdosa-amethyst-yeongnam-day-tour": {
    en: () => loadJson(import("@/components/product-tour-static/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour/busan-outskirts-tongdosa-amethyst-yeongnam-day-tour.ja.json")),
  },
  "busan-cruise-shore-excursion-bus-tour": {
    en: () => loadJson(import("@/components/product-tour-static/busan-cruise-shore-excursion-bus-tour/busan-cruise-shore-excursion-bus-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/busan-cruise-shore-excursion-bus-tour/busan-cruise-shore-excursion-bus-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/busan-cruise-shore-excursion-bus-tour/busan-cruise-shore-excursion-bus-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/busan-cruise-shore-excursion-bus-tour/busan-cruise-shore-excursion-bus-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/busan-cruise-shore-excursion-bus-tour/busan-cruise-shore-excursion-bus-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/busan-cruise-shore-excursion-bus-tour/busan-cruise-shore-excursion-bus-tour.ja.json")),
  },
  "busan-private-car-charter-cruise-shore": {
    en: () => loadJson(import("@/components/product-tour-static/busan-private-car-charter-cruise-shore/busan-private-car-charter-cruise-shore.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/busan-private-car-charter-cruise-shore/busan-private-car-charter-cruise-shore.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/busan-private-car-charter-cruise-shore/busan-private-car-charter-cruise-shore.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/busan-private-car-charter-cruise-shore/busan-private-car-charter-cruise-shore.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/busan-private-car-charter-cruise-shore/busan-private-car-charter-cruise-shore.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/busan-private-car-charter-cruise-shore/busan-private-car-charter-cruise-shore.ja.json")),
  },
  "busan-small-group-sightseeing-tour-cruise-passengers": {
    en: () => loadJson(import("@/components/product-tour-static/busan-small-group-sightseeing-tour-cruise-passengers/busan-small-group-sightseeing-tour-cruise-passengers.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/busan-small-group-sightseeing-tour-cruise-passengers/busan-small-group-sightseeing-tour-cruise-passengers.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/busan-small-group-sightseeing-tour-cruise-passengers/busan-small-group-sightseeing-tour-cruise-passengers.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/busan-small-group-sightseeing-tour-cruise-passengers/busan-small-group-sightseeing-tour-cruise-passengers.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/busan-small-group-sightseeing-tour-cruise-passengers/busan-small-group-sightseeing-tour-cruise-passengers.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/busan-small-group-sightseeing-tour-cruise-passengers/busan-small-group-sightseeing-tour-cruise-passengers.ja.json")),
  },
  "busan-spring-cherry-blossom-gyeongju-highlights-day-tour": {
    en: () => loadJson(import("@/components/product-tour-static/busan-spring-cherry-blossom-gyeongju-highlights-day-tour/busan-spring-cherry-blossom-gyeongju-highlights-day-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/busan-spring-cherry-blossom-gyeongju-highlights-day-tour/busan-spring-cherry-blossom-gyeongju-highlights-day-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/busan-spring-cherry-blossom-gyeongju-highlights-day-tour/busan-spring-cherry-blossom-gyeongju-highlights-day-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/busan-spring-cherry-blossom-gyeongju-highlights-day-tour/busan-spring-cherry-blossom-gyeongju-highlights-day-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/busan-spring-cherry-blossom-gyeongju-highlights-day-tour/busan-spring-cherry-blossom-gyeongju-highlights-day-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/busan-spring-cherry-blossom-gyeongju-highlights-day-tour/busan-spring-cherry-blossom-gyeongju-highlights-day-tour.ja.json")),
  },
  "busan-top-attractions-day-tour": {
    en: () => loadJson(import("@/components/product-tour-static/busan-top-attractions-day-tour/busan-top-attractions-day-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/busan-top-attractions-day-tour/busan-top-attractions-day-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/busan-top-attractions-day-tour/busan-top-attractions-day-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/busan-top-attractions-day-tour/busan-top-attractions-day-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/busan-top-attractions-day-tour/busan-top-attractions-day-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/busan-top-attractions-day-tour/busan-top-attractions-day-tour.ja.json")),
  },
  "east-signature-nature-core": {
    en: () => loadJson(import("@/components/product-tour-static/east-signature-nature-core/east-signature-nature-core.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/east-signature-nature-core/east-signature-nature-core.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/east-signature-nature-core/east-signature-nature-core.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/east-signature-nature-core/east-signature-nature-core.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/east-signature-nature-core/east-signature-nature-core.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/east-signature-nature-core/east-signature-nature-core.ja.json")),
  },
  "from-busan-gyeongju-ancient-capital-day-tour": {
    en: () => loadJson(import("@/components/product-tour-static/from-busan-gyeongju-ancient-capital-day-tour/from-busan-gyeongju-ancient-capital-day-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/from-busan-gyeongju-ancient-capital-day-tour/from-busan-gyeongju-ancient-capital-day-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/from-busan-gyeongju-ancient-capital-day-tour/from-busan-gyeongju-ancient-capital-day-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/from-busan-gyeongju-ancient-capital-day-tour/from-busan-gyeongju-ancient-capital-day-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/from-busan-gyeongju-ancient-capital-day-tour/from-busan-gyeongju-ancient-capital-day-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/from-busan-gyeongju-ancient-capital-day-tour/from-busan-gyeongju-ancient-capital-day-tour.ja.json")),
  },
  "from-incheon-seoul-day-tour-cruise-guests": {
    en: () => loadJson(import("@/components/product-tour-static/from-incheon-seoul-day-tour-cruise-guests/from-incheon-seoul-day-tour-cruise-guests.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/from-incheon-seoul-day-tour-cruise-guests/from-incheon-seoul-day-tour-cruise-guests.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/from-incheon-seoul-day-tour-cruise-guests/from-incheon-seoul-day-tour-cruise-guests.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/from-incheon-seoul-day-tour-cruise-guests/from-incheon-seoul-day-tour-cruise-guests.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/from-incheon-seoul-day-tour-cruise-guests/from-incheon-seoul-day-tour-cruise-guests.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/from-incheon-seoul-day-tour-cruise-guests/from-incheon-seoul-day-tour-cruise-guests.ja.json")),
  },
  "incheon-seoul-private-car-shore-excursion-cruise": {
    en: () => loadJson(import("@/components/product-tour-static/incheon-seoul-private-car-shore-excursion-cruise/incheon-seoul-private-car-shore-excursion-cruise.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/incheon-seoul-private-car-shore-excursion-cruise/incheon-seoul-private-car-shore-excursion-cruise.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/incheon-seoul-private-car-shore-excursion-cruise/incheon-seoul-private-car-shore-excursion-cruise.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/incheon-seoul-private-car-shore-excursion-cruise/incheon-seoul-private-car-shore-excursion-cruise.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/incheon-seoul-private-car-shore-excursion-cruise/incheon-seoul-private-car-shore-excursion-cruise.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/incheon-seoul-private-car-shore-excursion-cruise/incheon-seoul-private-car-shore-excursion-cruise.ja.json")),
  },
  "jeju-cherry-blossom-tour-east-route": {
    en: () => loadJson(import("@/components/product-tour-static/jeju-cherry-blossom-tour-east-route/jeju-cherry-blossom-tour-east-route.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/jeju-cherry-blossom-tour-east-route/jeju-cherry-blossom-tour-east-route.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/jeju-cherry-blossom-tour-east-route/jeju-cherry-blossom-tour-east-route.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/jeju-cherry-blossom-tour-east-route/jeju-cherry-blossom-tour-east-route.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/jeju-cherry-blossom-tour-east-route/jeju-cherry-blossom-tour-east-route.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/jeju-cherry-blossom-tour-east-route/jeju-cherry-blossom-tour-east-route.ja.json")),
  },
  "jeju-cruise-shore-excursion-bus-tour": {
    en: () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-bus-tour/jeju-cruise-shore-excursion-bus-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-bus-tour/jeju-cruise-shore-excursion-bus-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-bus-tour/jeju-cruise-shore-excursion-bus-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-bus-tour/jeju-cruise-shore-excursion-bus-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-bus-tour/jeju-cruise-shore-excursion-bus-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-bus-tour/jeju-cruise-shore-excursion-bus-tour.ja.json")),
  },
  "jeju-cruise-shore-excursion-small-group-tour": {
    en: () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-small-group-tour/jeju-cruise-shore-excursion-small-group-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-small-group-tour/jeju-cruise-shore-excursion-small-group-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-small-group-tour/jeju-cruise-shore-excursion-small-group-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-small-group-tour/jeju-cruise-shore-excursion-small-group-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-small-group-tour/jeju-cruise-shore-excursion-small-group-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/jeju-cruise-shore-excursion-small-group-tour/jeju-cruise-shore-excursion-small-group-tour.ja.json")),
  },
  "jeju-eastern-unesco-spots-day-tour": {
    en: () => loadJson(import("@/components/product-tour-static/jeju-eastern-unesco-spots-day-tour/jeju-eastern-unesco-spots-day-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/jeju-eastern-unesco-spots-day-tour/jeju-eastern-unesco-spots-day-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/jeju-eastern-unesco-spots-day-tour/jeju-eastern-unesco-spots-day-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/jeju-eastern-unesco-spots-day-tour/jeju-eastern-unesco-spots-day-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/jeju-eastern-unesco-spots-day-tour/jeju-eastern-unesco-spots-day-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/jeju-eastern-unesco-spots-day-tour/jeju-eastern-unesco-spots-day-tour.ja.json")),
  },
  "jeju-grand-highlights-loop": {
    en: () => loadJson(import("@/components/product-tour-static/jeju-grand-highlights-loop/jeju-grand-highlights-loop.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/jeju-grand-highlights-loop/jeju-grand-highlights-loop.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/jeju-grand-highlights-loop/jeju-grand-highlights-loop.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/jeju-grand-highlights-loop/jeju-grand-highlights-loop.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/jeju-grand-highlights-loop/jeju-grand-highlights-loop.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/jeju-grand-highlights-loop/jeju-grand-highlights-loop.ja.json")),
  },
  "jeju-hydrangea-festival-tour-east-route": {
    en: () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-east-route/jeju-hydrangea-festival-tour-east-route.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-east-route/jeju-hydrangea-festival-tour-east-route.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-east-route/jeju-hydrangea-festival-tour-east-route.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-east-route/jeju-hydrangea-festival-tour-east-route.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-east-route/jeju-hydrangea-festival-tour-east-route.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-east-route/jeju-hydrangea-festival-tour-east-route.ja.json")),
  },
  "jeju-hydrangea-festival-tour-southwest-route": {
    en: () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-southwest-route/jeju-hydrangea-festival-tour-southwest-route.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-southwest-route/jeju-hydrangea-festival-tour-southwest-route.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-southwest-route/jeju-hydrangea-festival-tour-southwest-route.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-southwest-route/jeju-hydrangea-festival-tour-southwest-route.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-southwest-route/jeju-hydrangea-festival-tour-southwest-route.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/jeju-hydrangea-festival-tour-southwest-route/jeju-hydrangea-festival-tour-southwest-route.ja.json")),
  },
  "jeju-island-private-car-charter-tour": {
    en: () => loadJson(import("@/components/product-tour-static/jeju-island-private-car-charter-tour/jeju-island-private-car-charter-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/jeju-island-private-car-charter-tour/jeju-island-private-car-charter-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/jeju-island-private-car-charter-tour/jeju-island-private-car-charter-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/jeju-island-private-car-charter-tour/jeju-island-private-car-charter-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/jeju-island-private-car-charter-tour/jeju-island-private-car-charter-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/jeju-island-private-car-charter-tour/jeju-island-private-car-charter-tour.ja.json")),
  },
  "jeju-southern-top-unesco-spots-tour": {
    en: () => loadJson(import("@/components/product-tour-static/jeju-southern-top-unesco-spots-tour/jeju-southern-top-unesco-spots-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/jeju-southern-top-unesco-spots-tour/jeju-southern-top-unesco-spots-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/jeju-southern-top-unesco-spots-tour/jeju-southern-top-unesco-spots-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/jeju-southern-top-unesco-spots-tour/jeju-southern-top-unesco-spots-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/jeju-southern-top-unesco-spots-tour/jeju-southern-top-unesco-spots-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/jeju-southern-top-unesco-spots-tour/jeju-southern-top-unesco-spots-tour.ja.json")),
  },
  "jeju-west-south-full-day-authentic-tour": {
    en: () => loadJson(import("@/components/product-tour-static/jeju-west-south-full-day-authentic-tour/jeju-west-south-full-day-authentic-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/jeju-west-south-full-day-authentic-tour/jeju-west-south-full-day-authentic-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/jeju-west-south-full-day-authentic-tour/jeju-west-south-full-day-authentic-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/jeju-west-south-full-day-authentic-tour/jeju-west-south-full-day-authentic-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/jeju-west-south-full-day-authentic-tour/jeju-west-south-full-day-authentic-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/jeju-west-south-full-day-authentic-tour/jeju-west-south-full-day-authentic-tour.ja.json")),
  },
  "jeju-winter-southwest-tangerine-snow-camellia-tour": {
    en: () => loadJson(import("@/components/product-tour-static/jeju-winter-southwest-tangerine-snow-camellia-tour/jeju-winter-southwest-tangerine-snow-camellia-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/jeju-winter-southwest-tangerine-snow-camellia-tour/jeju-winter-southwest-tangerine-snow-camellia-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/jeju-winter-southwest-tangerine-snow-camellia-tour/jeju-winter-southwest-tangerine-snow-camellia-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/jeju-winter-southwest-tangerine-snow-camellia-tour/jeju-winter-southwest-tangerine-snow-camellia-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/jeju-winter-southwest-tangerine-snow-camellia-tour/jeju-winter-southwest-tangerine-snow-camellia-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/jeju-winter-southwest-tangerine-snow-camellia-tour/jeju-winter-southwest-tangerine-snow-camellia-tour.ja.json")),
  },
  "pocheon-sanjeong-lake-herb-island-art-valley": {
    en: () => loadJson(import("@/components/product-tour-static/pocheon-sanjeong-lake-herb-island-art-valley/pocheon-sanjeong-lake-herb-island-art-valley.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/pocheon-sanjeong-lake-herb-island-art-valley/pocheon-sanjeong-lake-herb-island-art-valley.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/pocheon-sanjeong-lake-herb-island-art-valley/pocheon-sanjeong-lake-herb-island-art-valley.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/pocheon-sanjeong-lake-herb-island-art-valley/pocheon-sanjeong-lake-herb-island-art-valley.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/pocheon-sanjeong-lake-herb-island-art-valley/pocheon-sanjeong-lake-herb-island-art-valley.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/pocheon-sanjeong-lake-herb-island-art-valley/pocheon-sanjeong-lake-herb-island-art-valley.ja.json")),
  },
  "seoul-dmz-private-3rd-tunnel-suspension-bridge": {
    en: () => loadJson(import("@/components/product-tour-static/seoul-dmz-private-3rd-tunnel-suspension-bridge/seoul-dmz-private-3rd-tunnel-suspension-bridge.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/seoul-dmz-private-3rd-tunnel-suspension-bridge/seoul-dmz-private-3rd-tunnel-suspension-bridge.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/seoul-dmz-private-3rd-tunnel-suspension-bridge/seoul-dmz-private-3rd-tunnel-suspension-bridge.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/seoul-dmz-private-3rd-tunnel-suspension-bridge/seoul-dmz-private-3rd-tunnel-suspension-bridge.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/seoul-dmz-private-3rd-tunnel-suspension-bridge/seoul-dmz-private-3rd-tunnel-suspension-bridge.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/seoul-dmz-private-3rd-tunnel-suspension-bridge/seoul-dmz-private-3rd-tunnel-suspension-bridge.ja.json")),
  },
  "seoul-private-nami-morning-calm-petite-france": {
    en: () => loadJson(import("@/components/product-tour-static/seoul-private-nami-morning-calm-petite-france/seoul-private-nami-morning-calm-petite-france.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/seoul-private-nami-morning-calm-petite-france/seoul-private-nami-morning-calm-petite-france.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/seoul-private-nami-morning-calm-petite-france/seoul-private-nami-morning-calm-petite-france.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/seoul-private-nami-morning-calm-petite-france/seoul-private-nami-morning-calm-petite-france.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/seoul-private-nami-morning-calm-petite-france/seoul-private-nami-morning-calm-petite-france.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/seoul-private-nami-morning-calm-petite-france/seoul-private-nami-morning-calm-petite-france.ja.json")),
  },
  "seoul-seoraksan-naksansa-temple-naksan-beach-day-trip": {
    en: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip/seoul-seoraksan-naksansa-temple-naksan-beach-day-trip.ja.json")),
  },
  "seoul-seoraksan-nami-island-morning-calm-day-tour": {
    en: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-nami-island-morning-calm-day-tour/seoul-seoraksan-nami-island-morning-calm-day-tour.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-nami-island-morning-calm-day-tour/seoul-seoraksan-nami-island-morning-calm-day-tour.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-nami-island-morning-calm-day-tour/seoul-seoraksan-nami-island-morning-calm-day-tour.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-nami-island-morning-calm-day-tour/seoul-seoraksan-nami-island-morning-calm-day-tour.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-nami-island-morning-calm-day-tour/seoul-seoraksan-nami-island-morning-calm-day-tour.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-nami-island-morning-calm-day-tour/seoul-seoraksan-nami-island-morning-calm-day-tour.ja.json")),
  },
  "seoul-seoraksan-national-park-sokcho-beach-day-trip": {
    en: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-national-park-sokcho-beach-day-trip/seoul-seoraksan-national-park-sokcho-beach-day-trip.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-national-park-sokcho-beach-day-trip/seoul-seoraksan-national-park-sokcho-beach-day-trip.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-national-park-sokcho-beach-day-trip/seoul-seoraksan-national-park-sokcho-beach-day-trip.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-national-park-sokcho-beach-day-trip/seoul-seoraksan-national-park-sokcho-beach-day-trip.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-national-park-sokcho-beach-day-trip/seoul-seoraksan-national-park-sokcho-beach-day-trip.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/seoul-seoraksan-national-park-sokcho-beach-day-trip/seoul-seoraksan-national-park-sokcho-beach-day-trip.ja.json")),
  },
  "seoul-suburbs-private-chartered-car-10hr": {
    en: () => loadJson(import("@/components/product-tour-static/seoul-suburbs-private-chartered-car-10hr/seoul-suburbs-private-chartered-car-10hr.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/seoul-suburbs-private-chartered-car-10hr/seoul-suburbs-private-chartered-car-10hr.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/seoul-suburbs-private-chartered-car-10hr/seoul-suburbs-private-chartered-car-10hr.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/seoul-suburbs-private-chartered-car-10hr/seoul-suburbs-private-chartered-car-10hr.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/seoul-suburbs-private-chartered-car-10hr/seoul-suburbs-private-chartered-car-10hr.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/seoul-suburbs-private-chartered-car-10hr/seoul-suburbs-private-chartered-car-10hr.ja.json")),
  },
  "seoul-suwon-hwaseong-folk-village-starfield-library": {
    en: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-folk-village-starfield-library/seoul-suwon-hwaseong-folk-village-starfield-library.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-folk-village-starfield-library/seoul-suwon-hwaseong-folk-village-starfield-library.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-folk-village-starfield-library/seoul-suwon-hwaseong-folk-village-starfield-library.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-folk-village-starfield-library/seoul-suwon-hwaseong-folk-village-starfield-library.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-folk-village-starfield-library/seoul-suwon-hwaseong-folk-village-starfield-library.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-folk-village-starfield-library/seoul-suwon-hwaseong-folk-village-starfield-library.ja.json")),
  },
  "seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library": {
    en: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library/seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library.ja.json")),
  },
  "seoul-suwon-hwaseong-waujeongsa-starfield": {
    en: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-waujeongsa-starfield/seoul-suwon-hwaseong-waujeongsa-starfield.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-waujeongsa-starfield/seoul-suwon-hwaseong-waujeongsa-starfield.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-waujeongsa-starfield/seoul-suwon-hwaseong-waujeongsa-starfield.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-waujeongsa-starfield/seoul-suwon-hwaseong-waujeongsa-starfield.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-waujeongsa-starfield/seoul-suwon-hwaseong-waujeongsa-starfield.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/seoul-suwon-hwaseong-waujeongsa-starfield/seoul-suwon-hwaseong-waujeongsa-starfield.ja.json")),
  },
  "southwest-hallasan-osulloc-aewol": {
    en: () => loadJson(import("@/components/product-tour-static/southwest-hallasan-osulloc-aewol/southwest-hallasan-osulloc-aewol.en.json")),
    ko: () => loadJson(import("@/components/product-tour-static/southwest-hallasan-osulloc-aewol/southwest-hallasan-osulloc-aewol.ko.json")),
    zh: () => loadJson(import("@/components/product-tour-static/southwest-hallasan-osulloc-aewol/southwest-hallasan-osulloc-aewol.zh.json")),
    "zh-TW": () => loadJson(import("@/components/product-tour-static/southwest-hallasan-osulloc-aewol/southwest-hallasan-osulloc-aewol.zh-TW.json")),
    es: () => loadJson(import("@/components/product-tour-static/southwest-hallasan-osulloc-aewol/southwest-hallasan-osulloc-aewol.es.json")),
    ja: () => loadJson(import("@/components/product-tour-static/southwest-hallasan-osulloc-aewol/southwest-hallasan-osulloc-aewol.ja.json")),
  },
};

/**
 * @returns The locale-specific bundle, falling back to `en` if missing.
 *          `null` when the slug is not registered.
 *
 * Async since T2 — the per-locale JSON is a lazy chunk. Node's module cache
 * makes repeat loads of the same (slug, locale) effectively free; the merge
 * re-runs per call exactly as it did in the sync version.
 */
export async function getStaticTourProductFullPageJson(
  slug: string,
  locale: TourProductPageLocale,
): Promise<TourProductFullPageJson | null> {
  const bundle = (STATIC_TOUR_PRODUCT_BUNDLES as Record<string, TourProductLocaleBundle | undefined>)[slug];
  if (!bundle) return null;
  const localeLoader = locale === "en" ? undefined : bundle[locale];
  if (!localeLoader) {
    return bundle.en();
  }
  const [en, loc] = await Promise.all([bundle.en(), localeLoader()]);
  return mergeFullPageWithLocaleBase(en, loc);
}

export function isStaticTourProductBundleRegistered(slug: string): boolean {
  return Object.prototype.hasOwnProperty.call(STATIC_TOUR_PRODUCT_BUNDLES, slug);
}

export function listStaticTourProductBundleSlugs(): readonly string[] {
  return STATIC_TOUR_PRODUCT_BUNDLE_SLUG_LIST;
}
