-- =============================================================================
-- Busan Top Attractions Day Tour — pickup order + times (owner instruction 2026-08-05)
-- =============================================================================
-- Generated by scripts/gen-busan-top-attractions-pickup-sql-2026-08.mjs from the
-- bundles rewritten by scripts/align-busan-top-attractions-pickup-2026-08.mjs.
--
--   1) 08:10  Busan Station Exit 4   (subway Line 1 exit — NOT the KTX gate)
--   2) 08:30  Seomyeon Station Exit 4
--   3) 09:10  Haeundae Station Exit 5
--
-- WAS: Seomyeon 08:30 → Busan Station 08:50 → Haeundae 09:30, and the page told
-- that story three different ways (pickup_dropoff said Seomyeon first, the
-- itinerary said Busan Station first at ~09:00, page_sections said Busan Station
-- first at 08:30). All three now say the same thing.
--
-- 🔴 WITHOUT THIS FILE THE REPO CHANGE IS INVISIBLE. TOUR_PRODUCT_USE_SUPABASE=1,
--    so the page renders tour_product_pages.detail_payload, not the bundle.
--
-- NOT IN THIS FILE, on purpose:
--   * drop-off times and every downstream stop time — the owner asked about
--     pickup; re-timing the rest of the day would be inventing numbers.
--   * the "10.5 hours" label (tours.duration, tour_product_pages.duration_label,
--     catalog_card.duration, seo.metaDescription). 08:10 → ≈19:00 is ≈10.8 h, so
--     the rounded label now understates by ~20 min. Raising it to 11 h is an
--     owner call.
--   * price, is_active, is_published — untouched.
--   * page_sections.* mirrors — segments.ts marks that block DEAD and a test
--     asserts the render path never reads it.
--
-- Idempotent: every UPDATE is guarded on the pre-change value, so re-running is
-- a no-op and a value already edited through the admin Product Editor is left
-- alone rather than clobbered.
--
-- AFTER APPLYING:
--   node scripts/import-match-v18.mjs --single busan-top-attractions-day-tour
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- tours — the card / checkout schedule mirrors stop 1's time
-- ---------------------------------------------------------------------------
UPDATE public.tours SET
  schedule = jsonb_set(schedule, '{0,time}', '"≈ 08:10"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour'
  AND schedule #>> '{0,time}' = '≈ 09:00';

-- ---------------------------------------------------------------------------
-- locale = en
-- ---------------------------------------------------------------------------
UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"hero","meta","duration"}', '"10.5 hours (08:10 first pickup, ≈ 19:00 last drop)"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"hero","meta","duration"}' = '10.5 hours (08:30 first pickup, ≈ 19:00 last drop)';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"routeShapeIntro","subtitle"}', '"Northeast coastal temple first, blue line park, UN memorial mid-day, Gamcheon village with lunch, then close at Jagalchi market in central Busan. 08:10 to 18:00."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"routeShapeIntro","subtitle"}' = 'Northeast coastal temple first, blue line park, UN memorial mid-day, Gamcheon village with lunch, then close at Jagalchi market in central Busan. 08:30 to 18:00.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","time"}', '"≈ 08:10"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"itineraryStops","0","time"}' = '≈ 09:00';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","duration"}', '"65 min"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"itineraryStops","0","duration"}' = '30 min';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","timeUsed"}', '["Busan Station pickup (~08:10, ~5 min)","Drive to Seomyeon Station (~15 min)","Seomyeon pickup (~08:30, ~5 min)","Drive to Haeundae Station (~35 min)","Haeundae pickup (~09:10, ~5 min)"]'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #> '{"itineraryStops","0","timeUsed"}' = '["Busan Station pickup (~09:00, ~5 min)","Drive to Seomyeon Station (~10 min)","Seomyeon pickup (~09:15, ~5 min)","Drive to Haeundae Station (~15 min)","Haeundae pickup (~09:30, ~5 min)"]'::jsonb;

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","whyOnRoute"}', '"Three pickup points cover Busan''s three main hotel zones (KTX/Nampo, Seomyeon mid-city, Haeundae beachfront) without forcing guests to transit across the city in the morning. Sequencing west→east minimizes coach distance and lands the group at Haedong Yonggungsa around 09:50 — early enough to beat the busiest tour-bus arrivals."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"itineraryStops","0","whyOnRoute"}' = 'Three pickup points cover Busan''s three main hotel zones (KTX/Nampo, Seomyeon mid-city, Haeundae beachfront) without forcing guests to transit across the city in the morning. Sequencing northwest→east minimizes coach distance and lands the group at Haedong Yonggungsa around 10:00 — early enough to beat the busiest tour-bus arrivals.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","description"}', '"Pickup is consolidated at three central Busan transit hubs to keep the day manageable without crisscrossing the city: **Busan Station (Line 1)** for guests staying near the KTX terminal or in the Choryang/Nampo-dong area; **Seomyeon Station (Lines 1 & 2)** — Busan''s busiest subway interchange, central for guests in mid-city hotels around Lotte Hotel Busan or the Seomyeon Medical Street; and **Haeundae Station (Line 2)** for guests in the beachfront resort district near Westin Josun, Park Hyatt, or Signiel Busan. \n\nThe coach picks up at all three in sequence (Busan Station Exit 4 at 08:10, Seomyeon Station Exit 4 at 08:30, Haeundae Station Exit 5 at 09:10) and then heads northeast along the coastal Gwangan Bridge route toward Gijang-gun for the day''s first stop. \n\nTotal transit from final pickup to Haedong Yonggungsa: ~30-40 minutes depending on traffic. Driver will share a printed Korean-English itinerary card with timings; please be at your pickup point 5 minutes before the scheduled time to keep the day on track for the later UN Memorial Cemetery and Gamcheon stops, which have stricter operating windows."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"itineraryStops","0","description"}' = 'Pickup is consolidated at three central Busan transit hubs to keep the day manageable without crisscrossing the city: **Busan Station (Line 1)** for guests staying near the KTX terminal or in the Choryang/Nampo-dong area; **Seomyeon Station (Lines 1 & 2)** — Busan''s busiest subway interchange, central for guests in mid-city hotels around Lotte Hotel Busan or the Seomyeon Medical Street; and **Haeundae Station (Line 2)** for guests in the beachfront resort district near Westin Josun, Park Hyatt, or Signiel Busan. 

The coach picks up at all three in sequence (typically Busan Station first ~09:00, Seomyeon ~09:15, Haeundae ~09:30) and then heads northeast along the coastal Gwangan Bridge route toward Gijang-gun for the day''s first stop. 

Total transit from final pickup to Haedong Yonggungsa: ~30-40 minutes depending on traffic. Driver will share a printed Korean-English itinerary card with timings; please be at your pickup point 5 minutes before the scheduled time to keep the day on track for the later UN Memorial Cemetery and Gamcheon stops, which have stricter operating windows.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"whyTourWorks","routeLogicSections","1","items","2","detail"}', '"Pickup at Busan Station, Seomyeon, or Haeundae — accessible from most central-Busan accommodations. Choose the exit closest to your hotel; your effective tour length varies by about 15 minutes depending on which one you pick."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"whyTourWorks","routeLogicSections","1","items","2","detail"}' = 'Pickup at Seomyeon, Busan Station, or Haeundae — accessible from most central-Busan accommodations. Choose the exit closest to your hotel; tour duration adjusts ±30 min based on pickup point.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","preview"}', '"Three pickup points along Busan Subway: Busan Station Exit 4 (08:10), Seomyeon Station…"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"practicalAccordionItems","0","preview"}' = 'Three pickup points along Busan Subway: Seomyeon Station Exit 4 (08:30), Busan Station…';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","0"}', '"Three pickup points along Busan Subway: Busan Station Exit 4 — not the KTX gate (08:10), Seomyeon Station Exit 4 (08:30), Haeundae Station Exit 5 (09:10)."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","0"}' = 'Three pickup points along Busan Subway: Seomyeon Station Exit 4 (08:30), Busan Station Exit 4 — not the KTX gate (08:50), Haeundae Station Exit 5 (09:30).';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","2"}', '"Your effective tour duration depends on pickup point: Busan Station and Seomyeon ≈10 h, Haeundae just under 10 h."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","2"}' = 'Your effective tour duration depends on pickup point: Seomyeon ≈10 h, Haeundae ≈9.5 h.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"staticQuestions","8","answer"}', '"Three central-Busan stations: Busan Station Exit 4 — not the KTX gate (08:10), Seomyeon Station Exit 4 (08:30), Haeundae Station Exit 5 (09:10). Choose the exit closest to your hotel at booking."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"staticQuestions","8","answer"}' = 'Three central-Busan stations: Seomyeon Station Exit 4 (08:30), Busan Station Exit 4 — not the KTX gate (08:50), Haeundae Station Exit 5 (09:30). Choose the exit closest to your hotel at booking.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"pickup_dropoff"}', '{"departure":[{"order":1,"time":"08:10","name":"Busan Station Exit 4 (not the KTX gate)","type":"station","lat":35.11449,"lng":129.03933},{"order":2,"time":"08:30","name":"Seomyeon Station (Exit 4)","type":"station","lat":35.15782,"lng":129.06003},{"order":3,"time":"09:10","name":"Haeundae Station (Exit 5)","type":"station","lat":35.16396,"lng":129.15853}],"return":[{"order":1,"name":"Nampo-dong / Jagalchi area","type":"station","lat":35.09663,"lng":129.0308},{"order":2,"name":"Busan Station (Exit 4)","type":"station","lat":35.11449,"lng":129.03933},{"order":3,"name":"Seomyeon Station (Exit 4)","type":"station","lat":35.15782,"lng":129.06003},{"order":4,"name":"Haeundae Station (Exit 5)","type":"station","lat":35.16396,"lng":129.15853}],"notes":["Choose the pickup exit closest to your hotel at booking. Drop-offs are sequential along the return route; passengers boarding at Busan Station (08:10) or Seomyeon (08:30) have the longest day (≈10 hours), Haeundae passengers the shortest (just under 10 hours)."]}'::jsonb, true),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'en'
  AND detail_payload #>> '{"pickup_dropoff","departure","0","time"}' IS DISTINCT FROM '08:10';

-- ---------------------------------------------------------------------------
-- locale = ko
-- ---------------------------------------------------------------------------
UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"hero","meta","duration"}', '"10.5시간 (첫 픽업 08:10, 마지막 하차 약 19:00)"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"hero","meta","duration"}' = '10.5시간 (첫 픽업 08:30, 마지막 하차 약 19:00)';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"routeShapeIntro","subtitle"}', '"동북쪽 해안 사찰 시작 → 블루라인파크 → UN 기념 공원 → 감천문화마을 (점심 포함) → 부산 중심가 자갈치 시장에서 마무리. 오전 8:10 ~ 오후 6:00."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"routeShapeIntro","subtitle"}' = '동북쪽 해안 사찰 시작 → 블루라인파크 → UN 기념 공원 → 감천문화마을 (점심 포함) → 부산 중심가 자갈치 시장에서 마무리. 오전 8:30 ~ 오후 6:00.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","time"}', '"≈ 08:10"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"itineraryStops","0","time"}' = '≈ 09:00';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","duration"}', '"65분"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"itineraryStops","0","duration"}' = '30분';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","timeUsed"}', '["부산역 탑승 (약 08:10, 약 5분)","서면역까지 이동 (약 15분)","서면 탑승 (약 08:30, 약 5분)","해운대역까지 이동 (약 35분)","해운대 탑승 (약 09:10, 약 5분)"]'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #> '{"itineraryStops","0","timeUsed"}' = '["부산역 탑승 (약 09:00, 약 5분)","서면역까지 이동 (약 10분)","서면 탑승 (약 09:15, 약 5분)","해운대역까지 이동 (약 15분)","해운대 탑승 (약 09:30, 약 5분)"]'::jsonb;

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","whyOnRoute"}', '"세 곳의 탑승 지점은 부산의 주요 호텔 밀집 지역 (KTX/남포, 서면 도심, 해운대 해변)을 커버하므로, 투숙객들이 아침 일찍 도시를 가로질러 이동할 필요가 없습니다. 서→동 순서로 경유함으로써 차량 이동 거리를 최소화하고, 오전 9시 50분경 해동 용궁사에 도착할 수 있어 관광버스 혼잡이 심해지기 전에 방문이 가능합니다."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"itineraryStops","0","whyOnRoute"}' = '세 곳의 탑승 지점은 부산의 주요 호텔 밀집 지역 (KTX/남포, 서면 도심, 해운대 해변)을 커버하므로, 투숙객들이 아침 일찍 도시를 가로질러 이동할 필요가 없습니다. 북서→동쪽 순서로 경유함으로써 차량 이동 거리를 최소화하고, 오전 10시경 해동 용궁사에 도착할 수 있어 관광버스 혼잡이 심해지기 전에 방문이 가능합니다.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","description"}', '"탑승 장소는 하루 일정을 효율적으로 진행하기 위해 도심 내 세 곳의 주요 교통 거점으로 통합됩니다. **부산역 (1호선)**은 KTX 터미널 인근 또는 초량·남포동 일대에 숙박하시는 분들을 위한 거점이며, **서면역 (1·2호선)**은 부산에서 가장 분주한 지하철 환승역으로 롯데호텔 부산 및 서면 의료거리 주변 도심 호텔 투숙객에게 최적의 위치입니다. \n\n**해운대역 (2호선)**은 웨스틴조선, 파크하얏트, 시그니엘 부산 등 해변 리조트 지구에 숙박하시는 분들을 위한 거점입니다. 차량은 세 곳을 순서대로 경유합니다 (부산역 4번 출구 08:10, 서면역 4번 출구 08:30, 해운대역 5번 출구 09:10). 이후 해안 광안대교 경로를 따라 기장군 방면으로 이동하여 당일 첫 번째 목적지로 향합니다. 마지막 탑승 지점에서 해동 용궁사까지의 총 이동 시간은 교통 상황에 따라 약 30~40분입니다. \n\n기사님이 한국어·영어 병기 일정표 카드를 배포해 드리오니, 이후 UN기념공원 및 감천문화마을 방문 일정을 원활히 진행하기 위해 예정 시각 5분 전에 탑승 장소에 나와 계시기 바랍니다. 해당 방문지들은 운영 시간이 제한적입니다."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"itineraryStops","0","description"}' = '탑승 장소는 하루 일정을 효율적으로 진행하기 위해 도심 내 세 곳의 주요 교통 거점으로 통합됩니다. **부산역 (1호선)**은 KTX 터미널 인근 또는 초량·남포동 일대에 숙박하시는 분들을 위한 거점이며, **서면역 (1·2호선)**은 부산에서 가장 분주한 지하철 환승역으로 롯데호텔 부산 및 서면 의료거리 주변 도심 호텔 투숙객에게 최적의 위치입니다. 

**해운대역 (2호선)**은 웨스틴조선, 파크하얏트, 시그니엘 부산 등 해변 리조트 지구에 숙박하시는 분들을 위한 거점입니다. 차량은 세 곳을 순서대로 경유합니다 (일반적으로 부산역 약 09:00, 서면 약 09:15, 해운대 약 09:30). 이후 해안 광안대교 경로를 따라 기장군 방면으로 이동하여 당일 첫 번째 목적지로 향합니다. 마지막 탑승 지점에서 해동 용궁사까지의 총 이동 시간은 교통 상황에 따라 약 30~40분입니다. 

기사님이 한국어·영어 병기 일정표 카드를 배포해 드리오니, 이후 UN기념공원 및 감천문화마을 방문 일정을 원활히 진행하기 위해 예정 시각 5분 전에 탑승 장소에 나와 계시기 바랍니다. 해당 방문지들은 운영 시간이 제한적입니다.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"whyTourWorks","routeLogicSections","1","items","2","detail"}', '"부산역, 서면, 해운대에서 픽업 — 부산 중심부 대부분의 숙소에서 접근하기 편리합니다. 숙소와 가장 가까운 출구를 선택하세요. 픽업 지점에 따라 실질 투어 시간은 약 15분 차이가 납니다."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"whyTourWorks","routeLogicSections","1","items","2","detail"}' = '서면, 부산역, 해운대에서 픽업 — 부산 중심부 대부분의 숙소에서 접근하기 편리합니다. 숙소와 가장 가까운 출구를 선택하세요. 픽업 지점에 따라 투어 시간은 ±30분 조정됩니다.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","preview"}', '"부산 도시철도 연선의 픽업 장소 3곳: 부산역 4번 출구 (08:10), 서면역…"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"practicalAccordionItems","0","preview"}' = '부산 도시철도 연선의 픽업 장소 3곳: 서면역 4번 출구 (08:30), 부산역…';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","0"}', '"부산 도시철도 연선의 픽업 장소 3곳: 부산역 4번 출구 — KTX 개찰구 아님 (08:10), 서면역 4번 출구 (08:30), 해운대역 5번 출구 (09:10)."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","0"}' = '부산 도시철도 연선의 픽업 장소 3곳: 서면역 4번 출구 (08:30), 부산역 4번 출구 — KTX 개찰구 아님 (08:50), 해운대역 5번 출구 (09:30).';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","2"}', '"실질적인 투어 시간은 픽업 지점에 따라 다릅니다: 부산역·서면 ≈10시간, 해운대 ≈10시간 미만."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","2"}' = '실질적인 투어 시간은 픽업 지점에 따라 다릅니다: 서면 ≈10시간, 해운대 ≈9.5시간.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"staticQuestions","8","answer"}', '"부산 중심부 세 곳의 지하철역: 부산역 4번 출구 — KTX 게이트 아님(08:10), 서면역 4번 출구(08:30), 해운대역 5번 출구(09:10). 예약 시 숙소와 가장 가까운 출구를 선택하세요."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"staticQuestions","8","answer"}' = '부산 중심부 세 곳의 지하철역: 서면역 4번 출구(08:30), 부산역 4번 출구 — KTX 게이트 아님(08:50), 해운대역 5번 출구(09:30). 예약 시 숙소와 가장 가까운 출구를 선택하세요.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"pickup_dropoff"}', '{"departure":[{"order":1,"time":"08:10","name":"부산역 4번 출구 (KTX 개찰구 아님)","type":"station","lat":35.11449,"lng":129.03933},{"order":2,"time":"08:30","name":"서면역 4번 출구","type":"station","lat":35.15782,"lng":129.06003},{"order":3,"time":"09:10","name":"해운대역 5번 출구","type":"station","lat":35.16396,"lng":129.15853}],"return":[{"order":1,"name":"남포동 / 자갈치","type":"station","lat":35.09663,"lng":129.0308},{"order":2,"name":"부산역 4번 출구","type":"station","lat":35.11449,"lng":129.03933},{"order":3,"name":"서면역 4번 출구","type":"station","lat":35.15782,"lng":129.06003},{"order":4,"name":"해운대역 5번 출구","type":"station","lat":35.16396,"lng":129.15853}],"notes":["예약 시 숙소에서 가장 가까운 출구를 선택해 주세요. 하차는 복귀 경로를 따라 순차적으로 진행됩니다. 부산역(08:10) 또는 서면(08:30)에서 탑승하시면 하루가 가장 길고(약 10시간), 해운대 탑승이 가장 짧습니다(10시간 조금 못 미침)."]}'::jsonb, true),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ko'
  AND detail_payload #>> '{"pickup_dropoff","departure","0","time"}' IS DISTINCT FROM '08:10';

-- ---------------------------------------------------------------------------
-- locale = ja
-- ---------------------------------------------------------------------------
UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"hero","meta","duration"}', '"10.5時間（最初の乗車 08:10、最終送迎 約19:00）"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"hero","meta","duration"}' = '10.5時間（最初の乗車 08:30、最終送迎 約19:00）';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"routeShapeIntro","subtitle"}', '"まず北東部の海岸沿いの寺院、続いてブルーラインパーク、午後は国連記念公園、ランチを兼ねた甘川文化村、最後に釜山中心部のチャガルチ市場で締めくくり。08:10〜18:00。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"routeShapeIntro","subtitle"}' = 'まず北東部の海岸沿いの寺院、続いてブルーラインパーク、午後は国連記念公園、ランチを兼ねた甘川文化村、最後に釜山中心部のチャガルチ市場で締めくくり。08:30〜18:00。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","time"}', '"≈ 08:10"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"itineraryStops","0","time"}' = '≈ 09:00';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","duration"}', '"65分"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"itineraryStops","0","duration"}' = '30分';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","timeUsed"}', '["釜山駅乗車（~08:10、~5分）","西面駅へ移動（~15分）","西面乗車（~08:30、~5分）","海雲台駅へ移動（~35分）","海雲台乗車（~09:10、~5分）"]'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #> '{"itineraryStops","0","timeUsed"}' = '["釜山駅乗車（~09:00、~5分）","西面駅へ移動（~10分）","西面乗車（~09:15、~5分）","海雲台駅へ移動（~15分）","海雲台乗車（~09:30、~5分）"]'::jsonb;

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","whyOnRoute"}', '"3か所の乗車ポイントは釜山の3つの主要ホテルゾーン（KTX・南浦、西面市街中心部、海雲台ビーチフロント）をカバーしており、朝に市内を横断する必要がありません。西から東へのルート順によりコーチの走行距離を最小化し、グループは海東龍宮寺に09:50頃到着できます——最も混雑する観光バスの時間帯より早めに到着できるよう設定しています。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"itineraryStops","0","whyOnRoute"}' = '3か所の乗車ポイントは釜山の3つの主要ホテルゾーン（KTX・南浦、西面市街中心部、海雲台ビーチフロント）をカバーしており、朝に市内を横断する必要がありません。北西から東へのルート順によりコーチの走行距離を最小化し、グループは海東龍宮寺に10:00頃到着できます——最も混雑する観光バスの時間帯より早めに到着できるよう設定しています。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","description"}', '"市内を行き来することなく一日をスムーズに進めるため、乗車場所は釜山中心部の3つの主要交通拠点に集約されています。**釜山駅（1号線）**はKTX乗り場近くや草梁（チョリャン）・南浦洞（ナンポドン）エリアにご滞在のお客様向け。**西面駅（1・2号線）**は釜山で最も利用者の多い地下鉄乗換駅で、ロッテホテル釜山や西面医療ストリート周辺の市街中心部のホテルにご滞在のお客様に便利です。\n\n**海雲台駅（2号線）**はウェスティン朝鮮、パーク・ハイアット、シグニエル釜山などビーチフロントのリゾートエリアにご滞在のお客様向けです。コーチは3か所を順番に（釜山駅4番出口 08:10、西面駅4番出口 08:30、海雲台駅5番出口 09:10）乗車し、その後、沿岸の広安大橋ルートを北東方向に進み、機張郡（キジャングン）へ向かいます。最終乗車地点から海東龍宮寺までの所要時間：交通状況によって~30〜40分。\n\nドライバーが乗車時に時刻入りの韓国語・英語対照スケジュールカードをお渡しします。UN記念公園や甘川（カムチョン）への訪問は時間の制約が厳しいため、予定時刻の5分前には乗車場所でお待ちください。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"itineraryStops","0","description"}' = '市内を行き来することなく一日をスムーズに進めるため、乗車場所は釜山中心部の3つの主要交通拠点に集約されています。**釜山駅（1号線）**はKTX乗り場近くや草梁（チョリャン）・南浦洞（ナンポドン）エリアにご滞在のお客様向け。**西面駅（1・2号線）**は釜山で最も利用者の多い地下鉄乗換駅で、ロッテホテル釜山や西面医療ストリート周辺の市街中心部のホテルにご滞在のお客様に便利です。

**海雲台駅（2号線）**はウェスティン朝鮮、パーク・ハイアット、シグニエル釜山などビーチフロントのリゾートエリアにご滞在のお客様向けです。コーチは3か所を順番に（通常、釜山駅が最初~09:00、西面~09:15、海雲台~09:30）乗車し、その後、沿岸の広安大橋ルートを北東方向に進み、機張郡（キジャングン）へ向かいます。最終乗車地点から海東龍宮寺までの所要時間：交通状況によって~30〜40分。

ドライバーが乗車時に時刻入りの韓国語・英語対照スケジュールカードをお渡しします。UN記念公園や甘川（カムチョン）への訪問は時間の制約が厳しいため、予定時刻の5分前には乗車場所でお待ちください。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"whyTourWorks","routeLogicSections","1","items","2","detail"}', '"乗車地は釜山駅、西面（ソミョン）、または海雲台（ヘウンデ）から選択可能で、釜山中心部のほとんどの宿泊施設からアクセスできます。ホテルに最も近い出口をお選びください。実質のツアー所要時間は乗車地によって約15分の差があります。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"whyTourWorks","routeLogicSections","1","items","2","detail"}' = '乗車地は西面（ソミョン）、釜山駅、または海雲台（ヘウンデ）から選択可能で、釜山中心部のほとんどの宿泊施設からアクセスできます。ホテルに最も近い出口をお選びください。乗車地によってツアー所要時間は±30分調整されます。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","preview"}', '"釜山地下鉄沿いの3か所の乗車地：釜山駅4番出口（08:10）、西面駅…"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"practicalAccordionItems","0","preview"}' = '釜山地下鉄沿いの3か所の乗車地：西面駅4番出口（08:30）、釜山駅…';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","0"}', '"釜山地下鉄沿いの3か所の乗車地：釜山駅4番出口——KTX改札ではありません（08:10）、西面駅4番出口（08:30）、海雲台駅5番出口（09:10）。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","0"}' = '釜山地下鉄沿いの3か所の乗車地：西面駅4番出口（08:30）、釜山駅4番出口——KTX改札ではありません（08:50）、海雲台駅5番出口（09:30）。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","2"}', '"ツアーの実質所要時間は乗車地によって異なります：釜山駅・西面 約10時間、海雲台 約10時間弱。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","2"}' = 'ツアーの実質所要時間は乗車地によって異なります：西面 約10時間、海雲台 約9.5時間。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"staticQuestions","8","answer"}', '"釜山中心部の3つの駅：釜山駅4番出口 — KTX改札ではありません（08:10）、西面駅4番出口（08:30）、海雲台駅5番出口（09:10）。ご予約時にホテルに最も近い出口をお選びください。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"staticQuestions","8","answer"}' = '釜山中心部の3つの駅：西面駅4番出口（08:30）、釜山駅4番出口 — KTX改札ではありません（08:50）、海雲台駅5番出口（09:30）。ご予約時にホテルに最も近い出口をお選びください。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"pickup_dropoff"}', '{"departure":[{"order":1,"time":"08:10","name":"釜山駅4番出口（KTX改札ではありません）","type":"station","lat":35.11449,"lng":129.03933},{"order":2,"time":"08:30","name":"西面駅4番出口","type":"station","lat":35.15782,"lng":129.06003},{"order":3,"time":"09:10","name":"海雲台駅5番出口","type":"station","lat":35.16396,"lng":129.15853}],"return":[{"order":1,"name":"南浦洞／チャガルチ","type":"station","lat":35.09663,"lng":129.0308},{"order":2,"name":"釜山駅4番出口","type":"station","lat":35.11449,"lng":129.03933},{"order":3,"name":"西面駅4番出口","type":"station","lat":35.15782,"lng":129.06003},{"order":4,"name":"海雲台駅5番出口","type":"station","lat":35.16396,"lng":129.15853}],"notes":["ご予約時にホテルに最も近い出口をお選びください。降車は復路のルートに沿って順番に行われます。釜山駅（08:10）または西面（08:30）からご乗車の場合が最も長い一日（約10時間）となり、海雲台からのご乗車が最短（10時間弱）です。"]}'::jsonb, true),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'ja'
  AND detail_payload #>> '{"pickup_dropoff","departure","0","time"}' IS DISTINCT FROM '08:10';

-- ---------------------------------------------------------------------------
-- locale = es
-- ---------------------------------------------------------------------------
UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"hero","meta","duration"}', '"10,5 horas (primera recogida a las 08:10, última entrega ≈ 19:00)"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"hero","meta","duration"}' = '10,5 horas (primera recogida a las 08:30, última entrega ≈ 19:00)';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"routeShapeIntro","subtitle"}', '"Primero el templo costero del noreste, luego el parque Blue Line, el memorial de la ONU a mediodía, el pueblo de Gamcheon con almuerzo y cierre en el mercado Jagalchi en el centro de Busan. De 08:10 a 18:00."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"routeShapeIntro","subtitle"}' = 'Primero el templo costero del noreste, luego el parque Blue Line, el memorial de la ONU a mediodía, el pueblo de Gamcheon con almuerzo y cierre en el mercado Jagalchi en el centro de Busan. De 08:30 a 18:00.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","time"}', '"≈ 08:10"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"itineraryStops","0","time"}' = '≈ 09:00';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","duration"}', '"65 min"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"itineraryStops","0","duration"}' = '30 min';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","timeUsed"}', '["Recogida en la Estación de Busan (~08:10, ~5 min)","Traslado a la Estación de Seomyeon (~15 min)","Recogida en Seomyeon (~08:30, ~5 min)","Traslado a la Estación de Haeundae (~35 min)","Recogida en Haeundae (~09:10, ~5 min)"]'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #> '{"itineraryStops","0","timeUsed"}' = '["Recogida en la Estación de Busan (~09:00, ~5 min)","Traslado a la Estación de Seomyeon (~10 min)","Recogida en Seomyeon (~09:15, ~5 min)","Traslado a la Estación de Haeundae (~15 min)","Recogida en Haeundae (~09:30, ~5 min)"]'::jsonb;

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","whyOnRoute"}', '"Los tres puntos de recogida cubren las tres principales zonas hoteleras de Busan (KTX/Nampo, Seomyeon centro, playa de Haeundae) sin obligar a los huéspedes a cruzar la ciudad por la mañana. La secuencia oeste→este minimiza la distancia del autobús y lleva al grupo a Haedong Yonggungsa hacia las 09:50, con tiempo suficiente para adelantarse a la llegada de los autobuses turísticos más concurridos."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"itineraryStops","0","whyOnRoute"}' = 'Los tres puntos de recogida cubren las tres principales zonas hoteleras de Busan (KTX/Nampo, Seomyeon centro, playa de Haeundae) sin obligar a los huéspedes a cruzar la ciudad por la mañana. La secuencia noroeste→este minimiza la distancia del autobús y lleva al grupo a Haedong Yonggungsa hacia las 10:00, con tiempo suficiente para adelantarse a la llegada de los autobuses turísticos más concurridos.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","description"}', '"La recogida está centralizada en tres nodos de transporte del centro de Busan para facilitar el día sin tener que cruzar la ciudad de un extremo a otro: **Estación de Busan (Línea 1)** para los huéspedes alojados cerca de la terminal KTX o en la zona de Choryang/Nampo-dong; **Estación de Seomyeon (Líneas 1 y 2)** — el intercambiador de metro más transitado de Busan, céntrico para los huéspedes en hoteles del centro como el Lotte Hotel Busan o la calle médica de Seomyeon; y **Estación de Haeundae (Línea 2)** para los huéspedes en el distrito turístico frente al mar cerca del Westin Josun, Park Hyatt o Signiel Busan. \n\nEl autobús recoge en los tres puntos en secuencia (Estación de Busan Salida 4 a las 08:10, Estación Seomyeon Salida 4 a las 08:30, Estación Haeundae Salida 5 a las 09:10) y luego se dirige al noreste por la ruta costera del Puente Gwangan hacia Gijang-gun para la primera parada del día. Tiempo total de tránsito desde la última recogida hasta Haedong Yonggungsa: ~30-40 minutos según el tráfico. \n\nEl conductor repartirá una tarjeta impresa con el itinerario en coreano e inglés con los horarios; por favor, esté en su punto de recogida 5 minutos antes de la hora programada para mantener el ritmo del día, especialmente en las paradas posteriores del Cementerio Memorial de la ONU y Gamcheon, que tienen horarios de funcionamiento más estrictos."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"itineraryStops","0","description"}' = 'La recogida está centralizada en tres nodos de transporte del centro de Busan para facilitar el día sin tener que cruzar la ciudad de un extremo a otro: **Estación de Busan (Línea 1)** para los huéspedes alojados cerca de la terminal KTX o en la zona de Choryang/Nampo-dong; **Estación de Seomyeon (Líneas 1 y 2)** — el intercambiador de metro más transitado de Busan, céntrico para los huéspedes en hoteles del centro como el Lotte Hotel Busan o la calle médica de Seomyeon; y **Estación de Haeundae (Línea 2)** para los huéspedes en el distrito turístico frente al mar cerca del Westin Josun, Park Hyatt o Signiel Busan. 

El autobús recoge en los tres puntos en secuencia (generalmente Estación de Busan primero ~09:00, Seomyeon ~09:15, Haeundae ~09:30) y luego se dirige al noreste por la ruta costera del Puente Gwangan hacia Gijang-gun para la primera parada del día. Tiempo total de tránsito desde la última recogida hasta Haedong Yonggungsa: ~30-40 minutos según el tráfico. 

El conductor repartirá una tarjeta impresa con el itinerario en coreano e inglés con los horarios; por favor, esté en su punto de recogida 5 minutos antes de la hora programada para mantener el ritmo del día, especialmente en las paradas posteriores del Cementerio Memorial de la ONU y Gamcheon, que tienen horarios de funcionamiento más estrictos.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"whyTourWorks","routeLogicSections","1","items","2","detail"}', '"Recogida en la Estación de Busan, Seomyeon o Haeundae — accesible desde la mayoría de alojamientos en el centro de Busan. Elige la salida más cercana a tu hotel; la duración efectiva del tour varía unos 15 min según el punto de recogida."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"whyTourWorks","routeLogicSections","1","items","2","detail"}' = 'Recogida en Seomyeon, Estación de Busan o Haeundae — accesible desde la mayoría de alojamientos en el centro de Busan. Elige la salida más cercana a tu hotel; la duración del tour varía ±30 min según el punto de recogida.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","preview"}', '"Tres puntos de recogida a lo largo del Metro de Busan: Salida 4 de la Estación de Busan (08:10), Estación Seomyeon…"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"practicalAccordionItems","0","preview"}' = 'Tres puntos de recogida a lo largo del Metro de Busan: Salida 4 de la Estación Seomyeon (08:30), Estación de Busan…';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","0"}', '"Tres puntos de recogida a lo largo del Metro de Busan: Salida 4 de la Estación de Busan — no la puerta KTX (08:10), Salida 4 de la Estación Seomyeon (08:30), Salida 5 de la Estación Haeundae (09:10)."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","0"}' = 'Tres puntos de recogida a lo largo del Metro de Busan: Salida 4 de la Estación Seomyeon (08:30), Salida 4 de la Estación de Busan — no la puerta KTX (08:50), Salida 5 de la Estación Haeundae (09:30).';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","2"}', '"La duración efectiva del tour depende del punto de recogida: Estación de Busan y Seomyeon ≈10 h, Haeundae algo menos de 10 h."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","2"}' = 'La duración efectiva del tour depende del punto de recogida: Seomyeon ≈10 h, Haeundae ≈9,5 h.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"staticQuestions","8","answer"}', '"Tres estaciones del centro de Busan: Estación Busan Salida 4 — no la puerta del KTX (08:10), Estación Seomyeon Salida 4 (08:30), Estación Haeundae Salida 5 (09:10). Elige la salida más cercana a tu hotel al reservar."'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"staticQuestions","8","answer"}' = 'Tres estaciones del centro de Busan: Estación Seomyeon Salida 4 (08:30), Estación Busan Salida 4 — no la puerta del KTX (08:50), Estación Haeundae Salida 5 (09:30). Elige la salida más cercana a tu hotel al reservar.';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"pickup_dropoff"}', '{"departure":[{"order":1,"time":"08:10","name":"Estación de Busan, Salida 4 (no la puerta del KTX)","type":"station","lat":35.11449,"lng":129.03933},{"order":2,"time":"08:30","name":"Estación Seomyeon (Salida 4)","type":"station","lat":35.15782,"lng":129.06003},{"order":3,"time":"09:10","name":"Estación Haeundae (Salida 5)","type":"station","lat":35.16396,"lng":129.15853}],"return":[{"order":1,"name":"Nampo-dong / zona de Jagalchi","type":"station","lat":35.09663,"lng":129.0308},{"order":2,"name":"Estación de Busan (Salida 4)","type":"station","lat":35.11449,"lng":129.03933},{"order":3,"name":"Estación Seomyeon (Salida 4)","type":"station","lat":35.15782,"lng":129.06003},{"order":4,"name":"Estación Haeundae (Salida 5)","type":"station","lat":35.16396,"lng":129.15853}],"notes":["Elige la salida más cercana a tu hotel al reservar. Las bajadas siguen el orden de la ruta de regreso; quienes suben en la Estación de Busan (08:10) o en Seomyeon (08:30) tienen el día más largo (≈10 horas) y quienes suben en Haeundae, el más corto (algo menos de 10 horas)."]}'::jsonb, true),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'es'
  AND detail_payload #>> '{"pickup_dropoff","departure","0","time"}' IS DISTINCT FROM '08:10';

-- ---------------------------------------------------------------------------
-- locale = zh
-- ---------------------------------------------------------------------------
UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"hero","meta","duration"}', '"10.5小时（08:10首次接客，约19:00最终送达）"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"hero","meta","duration"}' = '10.5小时（08:30首次接客，约19:00最终送达）';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"routeShapeIntro","subtitle"}', '"先游览东北部海岸寺庙，再前往蓝线公园，正午参观联合国纪念公墓，午餐后游览甘川文化村，最后在釜山市中心的札嘎其市场收尾。08:10至18:00。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"routeShapeIntro","subtitle"}' = '先游览东北部海岸寺庙，再前往蓝线公园，正午参观联合国纪念公墓，午餐后游览甘川文化村，最后在釜山市中心的札嘎其市场收尾。08:30至18:00。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","time"}', '"≈ 08:10"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"itineraryStops","0","time"}' = '≈ 09:00';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","duration"}', '"65分钟"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"itineraryStops","0","duration"}' = '30分钟';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","timeUsed"}', '["釜山站接送（约08:10，约5分钟）","驾车前往西面站（约15分钟）","西面站接送（约08:30，约5分钟）","驾车前往海云台站（约35分钟）","海云台站接送（约09:10，约5分钟）"]'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #> '{"itineraryStops","0","timeUsed"}' = '["釜山站接送（约09:00，约5分钟）","驾车前往西面站（约10分钟）","西面站接送（约09:15，约5分钟）","驾车前往海云台站（约15分钟）","海云台站接送（约09:30，约5分钟）"]'::jsonb;

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","whyOnRoute"}', '"三个接送地点覆盖釜山三大主要酒店区（KTX/南浦洞、西面市中心、海云台海滨），无需宾客早晨跨城出行。自西向东的接送顺序使包车行驶距离最短，并于约09:50抵达海东龙宫寺——早于旅游大巴最拥挤的时段，抢先入场。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"itineraryStops","0","whyOnRoute"}' = '三个接送地点覆盖釜山三大主要酒店区（KTX/南浦洞、西面市中心、海云台海滨），无需宾客早晨跨城出行。从西北向东的接送顺序使包车行驶距离最短，并于约10:00抵达海东龙宫寺——早于旅游大巴最拥挤的时段，抢先入场。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","description"}', '"接送地点设于釜山市中心三个主要交通枢纽，方便行程安排，无需在城市间来回奔波：**釜山站（地铁1号线）** 适合住在KTX终点站附近或草梁洞/南浦洞一带的宾客；**西面站（地铁1、2号线）** — 釜山最繁忙的地铁换乘站，适合住在乐天酒店釜山或西面医疗街一带市中心酒店的宾客；**海云台站（地铁2号线）** 适合住在海滨度假区、威斯汀朝鲜酒店、柏悦酒店或信义釜山酒店附近的宾客。\n\n大巴按顺序依次接送（釜山站4号出口08:10、西面站4号出口08:30、海云台站5号出口09:10），随后沿海岸广安大桥路线向东北方向前往机张郡，开始当天的第一站。从最后一个接送点到海东龙宫寺的总行程时间：约30-40分钟（视路况而定）。司机将发放中韩双语行程时刻卡；请在预定时间前5分钟到达接送地点，以确保行程顺利推进，不耽误后续联合国纪念公园和甘川洞等开放时间较严格的景点。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"itineraryStops","0","description"}' = '接送地点设于釜山市中心三个主要交通枢纽，方便行程安排，无需在城市间来回奔波：**釜山站（地铁1号线）** 适合住在KTX终点站附近或草梁洞/南浦洞一带的宾客；**西面站（地铁1、2号线）** — 釜山最繁忙的地铁换乘站，适合住在乐天酒店釜山或西面医疗街一带市中心酒店的宾客；**海云台站（地铁2号线）** 适合住在海滨度假区、威斯汀朝鲜酒店、柏悦酒店或信义釜山酒店附近的宾客。

大巴按顺序依次接送（通常釜山站最先约09:00，西面约09:15，海云台约09:30），随后沿海岸广安大桥路线向东北方向前往机张郡，开始当天的第一站。从最后一个接送点到海东龙宫寺的总行程时间：约30-40分钟（视路况而定）。司机将发放中韩双语行程时刻卡；请在预定时间前5分钟到达接送地点，以确保行程顺利推进，不耽误后续联合国纪念公园和甘川洞等开放时间较严格的景点。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"whyTourWorks","routeLogicSections","1","items","2","detail"}', '"接送地点分别为釜山站、西面站或海云台站——可从釜山市中心大多数住宿处便捷抵达。请选择离您酒店最近的出口；实际行程时长因接送地点不同，相差约15分钟。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"whyTourWorks","routeLogicSections","1","items","2","detail"}' = '接送地点分别为西面站、釜山站或海云台站——可从釜山市中心大多数住宿处便捷抵达。请选择离您酒店最近的出口；行程总时长因接送地点不同，上下浮动约30分钟。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","preview"}', '"三处接送站均位于釜山地铁沿线：釜山站4号出口（08:10）、西面站……"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"practicalAccordionItems","0","preview"}' = '三处接送站均位于釜山地铁沿线：西面站4号出口（08:30）、釜山站……';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","0"}', '"三处接送站均位于釜山地铁沿线：釜山站4号出口（非KTX检票口）（08:10）、西面站4号出口（08:30）、海云台站5号出口（09:10）。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","0"}' = '三处接送站均位于釜山地铁沿线：西面站4号出口（08:30）、釜山站4号出口（非KTX检票口）（08:50）、海云台站5号出口（09:30）。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","2"}', '"实际游览时长因上车地点而异：釜山站与西面出发约10小时，海云台出发略少于10小时。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","2"}' = '实际游览时长因上车地点而异：西面出发约10小时，海云台出发约9.5小时。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"staticQuestions","8","answer"}', '"釜山市中心三处集合点：釜山站4号出口——非KTX检票口（08:10）、西面站4号出口（08:30）、海云台站5号出口（09:10）。请在预订时选择距您酒店最近的出口。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"staticQuestions","8","answer"}' = '釜山市中心三处集合点：西面站4号出口（08:30）、釜山站4号出口——非KTX检票口（08:50）、海云台站5号出口（09:30）。请在预订时选择距您酒店最近的出口。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"pickup_dropoff"}', '{"departure":[{"order":1,"time":"08:10","name":"釜山站4号出口（非KTX检票口）","type":"station","lat":35.11449,"lng":129.03933},{"order":2,"time":"08:30","name":"西面站4号出口","type":"station","lat":35.15782,"lng":129.06003},{"order":3,"time":"09:10","name":"海云台站5号出口","type":"station","lat":35.16396,"lng":129.15853}],"return":[{"order":1,"name":"南浦洞/札嘎其","type":"station","lat":35.09663,"lng":129.0308},{"order":2,"name":"釜山站4号出口","type":"station","lat":35.11449,"lng":129.03933},{"order":3,"name":"西面站4号出口","type":"station","lat":35.15782,"lng":129.06003},{"order":4,"name":"海云台站5号出口","type":"station","lat":35.16396,"lng":129.15853}],"notes":["预订时请选择距您酒店最近的出口。返程送达按回程路线顺序进行；在釜山站（08:10）或西面（08:30）上车的旅客当天行程最长（约10小时），海云台上车的最短（略少于10小时）。"]}'::jsonb, true),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh'
  AND detail_payload #>> '{"pickup_dropoff","departure","0","time"}' IS DISTINCT FROM '08:10';

-- ---------------------------------------------------------------------------
-- locale = zh-TW
-- ---------------------------------------------------------------------------
UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"hero","meta","duration"}', '"10.5小時（08:10首班接送，約19:00最後送返）"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"hero","meta","duration"}' = '10.5小時（08:30首班接送，約19:00最後送返）';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"routeShapeIntro","subtitle"}', '"先前往東北部海岸寺廟，再到藍線公園，午間參觀聯合國紀念公墓，於甘川文化村享用午餐，最後在釜山市中心的札嘎其市場結束行程。08:10 至 18:00。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"routeShapeIntro","subtitle"}' = '先前往東北部海岸寺廟，再到藍線公園，午間參觀聯合國紀念公墓，於甘川文化村享用午餐，最後在釜山市中心的札嘎其市場結束行程。08:30 至 18:00。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","time"}', '"≈ 08:10"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"itineraryStops","0","time"}' = '≈ 09:00';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","duration"}', '"65 分鐘"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"itineraryStops","0","duration"}' = '30 分鐘';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","timeUsed"}', '["釜山站接送（約 08:10，約 5 分鐘）","前往西面站（約 15 分鐘）","西面站接送（約 08:30，約 5 分鐘）","前往海雲台站（約 35 分鐘）","海雲台站接送（約 09:10，約 5 分鐘）"]'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #> '{"itineraryStops","0","timeUsed"}' = '["釜山站接送（約 09:00，約 5 分鐘）","前往西面站（約 10 分鐘）","西面站接送（約 09:15，約 5 分鐘）","前往海雲台站（約 15 分鐘）","海雲台站接送（約 09:30，約 5 分鐘）"]'::jsonb;

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","whyOnRoute"}', '"三個接送地點涵蓋釜山三大主要住宿區域（KTX／南浦洞、西面市中心、海雲台海濱），無需旅客在清晨橫越城市。由西向東的接送順序可縮短旅遊車行駛距離，並讓團體在約 09:50 抵達海東龍宮寺——足以趕在旅遊巴士最繁忙的時段之前。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"itineraryStops","0","whyOnRoute"}' = '三個接送地點涵蓋釜山三大主要住宿區域（KTX／南浦洞、西面市中心、海雲台海濱），無需旅客在清晨橫越城市。由西向東的接送順序可縮短旅遊車行駛距離，並讓團體在約 10:00 抵達海東龍宮寺——足以趕在旅遊巴士最繁忙的時段之前。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"itineraryStops","0","description"}', '"接送地點集中於釜山市中心三大交通樞紐，讓全日行程輕鬆順暢、無需在城市間來回奔波：**釜山站（1號線）**適合住在KTX總站附近或草梁洞／南浦洞一帶的旅客；**西面站（1號線及2號線）**——釜山最繁忙的地鐵轉乘站，便於入住樂天酒店釜山或西面醫療街一帶市中心酒店的旅客；以及**海雲台站（2號線）**，適合入住海濱度假區的旅客，如威斯汀朝鮮酒店、柏悅酒店或 Signiel 釜山。\n\n旅遊車將依序前往三個接送點（釜山站4號出口 08:10、西面站4號出口 08:30、海雲台站5號出口 09:10），隨後沿海岸廣安大橋路線向東北方前往機張郡，抵達當日第一個景點。從最後接送點至海東龍宮寺的總車程：視交通狀況約需 30 至 40 分鐘。司機將分發印有時間安排的韓英雙語行程卡；請在預定時間前 5 分鐘抵達接送地點，以確保後續聯合國紀念公墓及甘川洞等景點的行程順利進行，這些景點的開放時段較為嚴格。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"itineraryStops","0","description"}' = '接送地點集中於釜山市中心三大交通樞紐，讓全日行程輕鬆順暢、無需在城市間來回奔波：**釜山站（1號線）**適合住在KTX總站附近或草梁洞／南浦洞一帶的旅客；**西面站（1號線及2號線）**——釜山最繁忙的地鐵轉乘站，便於入住樂天酒店釜山或西面醫療街一帶市中心酒店的旅客；以及**海雲台站（2號線）**，適合入住海濱度假區的旅客，如威斯汀朝鮮酒店、柏悅酒店或 Signiel 釜山。

旅遊車將依序前往三個接送點（通常釜山站約 09:00，西面站約 09:15，海雲台站約 09:30），隨後沿海岸廣安大橋路線向東北方前往機張郡，抵達當日第一個景點。從最後接送點至海東龍宮寺的總車程：視交通狀況約需 30 至 40 分鐘。司機將分發印有時間安排的韓英雙語行程卡；請在預定時間前 5 分鐘抵達接送地點，以確保後續聯合國紀念公墓及甘川洞等景點的行程順利進行，這些景點的開放時段較為嚴格。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"whyTourWorks","routeLogicSections","1","items","2","detail"}', '"接送地點為釜山站、西面或海雲台——可從釜山市中心大多數住宿地點前往。請選擇距離飯店最近的出口；實際行程時長依接送地點約有15分鐘差異。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"whyTourWorks","routeLogicSections","1","items","2","detail"}' = '接送地點為西面、釜山站或海雲台——可從釜山市中心大多數住宿地點前往。請選擇距離飯店最近的出口；行程總時長將依接送地點增減約30分鐘。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","preview"}', '"沿釜山地鐵設有三個接送點：釜山站4號出口（08:10）、西面站……"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"practicalAccordionItems","0","preview"}' = '沿釜山地鐵設有三個接送點：西面站4號出口（08:30）、釜山站……';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","0"}', '"沿釜山地鐵設有三個接送點：釜山站4號出口（非KTX閘口，08:10）、西面站4號出口（08:30）、海雲台站5號出口（09:10）。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","0"}' = '沿釜山地鐵設有三個接送點：西面站4號出口（08:30）、釜山站4號出口（非KTX閘口，08:50）、海雲台站5號出口（09:30）。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"practicalAccordionItems","0","content","2"}', '"實際行程時長依接送地點而定：釜山站與西面約10小時，海雲台略少於10小時。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"practicalAccordionItems","0","content","2"}' = '實際行程時長依接送地點而定：西面約10小時，海雲台約9.5小時。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"staticQuestions","8","answer"}', '"釜山市中心共三個接送站：釜山站4號出口——非KTX閘口（08:10）、西面站4號出口（08:30）、海雲臺站5號出口（09:10）。預訂時請選擇距您住宿最近的出口。"'::jsonb, false),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"staticQuestions","8","answer"}' = '釜山市中心共三個接送站：西面站4號出口（08:30）、釜山站4號出口——非KTX閘口（08:50）、海雲臺站5號出口（09:30）。預訂時請選擇距您住宿最近的出口。';

UPDATE public.tour_product_pages SET
  detail_payload = jsonb_set(detail_payload, '{"pickup_dropoff"}', '{"departure":[{"order":1,"time":"08:10","name":"釜山站4號出口（非KTX閘口）","type":"station","lat":35.11449,"lng":129.03933},{"order":2,"time":"08:30","name":"西面站4號出口","type":"station","lat":35.15782,"lng":129.06003},{"order":3,"time":"09:10","name":"海雲台站5號出口","type":"station","lat":35.16396,"lng":129.15853}],"return":[{"order":1,"name":"南浦洞／札嘎其","type":"station","lat":35.09663,"lng":129.0308},{"order":2,"name":"釜山站4號出口","type":"station","lat":35.11449,"lng":129.03933},{"order":3,"name":"西面站4號出口","type":"station","lat":35.15782,"lng":129.06003},{"order":4,"name":"海雲台站5號出口","type":"station","lat":35.16396,"lng":129.15853}],"notes":["訂購時請選擇距離住宿最近的出口。下車依回程路線順序進行；在釜山站（08:10）或西面（08:30）上車的旅客當日行程最長（約10小時），海雲台上車者最短（略少於10小時）。"]}'::jsonb, true),
  updated_at = NOW()
WHERE slug = 'busan-top-attractions-day-tour' AND locale = 'zh-TW'
  AND detail_payload #>> '{"pickup_dropoff","departure","0","time"}' IS DISTINCT FROM '08:10';

COMMIT;

-- Verify (expect three rows per locale, in this order):
--   SELECT locale,
--          jsonb_array_elements(detail_payload -> 'pickup_dropoff' -> 'departure') AS stop
--     FROM public.tour_product_pages
--    WHERE slug = 'busan-top-attractions-day-tour'
--    ORDER BY locale;
