/**
 * V2 redesign Phase 2 — photo-pin marker DOM builder.
 *
 * Builds the `content` HTMLElement passed to Google Maps
 * `AdvancedMarkerElement`. Three tiers per V5 amber discipline + V10a
 * size revision:
 *
 *   • `state = "cart"`  → 56px round photo + amber sequence badge + slate tail
 *   • `state = "out"`   → 14px slate-900 dot with white ring (low-attention)
 *   • `state = "hover"` → 64px (1.14× of 56) with amber outer ring + halo
 *
 * Hover is wired by `POICatalogMap.tsx`: each marker element listens on
 * mouseenter/mouseleave and toggles `data-state="hover"` on the element,
 * which CSS rules in the same builder map to the larger/halo variant
 * without rebuilding the DOM. This keeps marker swap cost zero on hover.
 *
 * Image-load failure → fallback to an amber circle with the first letter
 * of `nameEn`. Photo-pin gate (Phase 0) showed this fallback reads as a
 * legitimate identifier when the source photo is missing.
 */

export type PhotoPinState = "cart" | "out" | "hover" | "preview";

interface BuildPhotoPinArgs {
  /** Image URL for cart/hover variants. Ignored when state is "out". */
  imageUrl: string | null;
  /** 1-indexed cart sequence. Ignored when state is "out". */
  seq: number | null;
  /** Initial state — `out` for unselected POIs, `cart` for selected. */
  state: PhotoPinState;
  /** Used for the image-error fallback letter + aria-label. */
  nameEn: string;
}

/**
 * Returns an `HTMLDivElement` ready to be assigned to
 * `new AdvancedMarkerElement({ content: ... })`.
 *
 * Mutating `el.dataset.state` after construction switches variants via
 * the inline CSS rules generated by `injectPhotoPinStyles()` (called
 * once per page load).
 */
export function buildPhotoPinContent(args: BuildPhotoPinArgs): HTMLElement {
  const { imageUrl, seq, state, nameEn } = args;
  injectPhotoPinStyles();

  const root = document.createElement("div");
  root.className = "ib-photo-pin";
  root.dataset.state = state;
  if (seq != null) root.setAttribute("aria-label", `Stop ${seq}: ${nameEn}`);
  else root.setAttribute("aria-label", nameEn);

  // Out-of-cart = simple slate dot. No photo, no badge, no tail.
  if (state === "out") {
    const dot = document.createElement("span");
    dot.className = "ib-photo-pin__dot";
    root.appendChild(dot);
    return root;
  }

  // Cart / hover = photo pin with sequence badge + tail.
  // Tail (slate triangle pointing down at the actual lat/lng)
  const tail = document.createElement("span");
  tail.className = "ib-photo-pin__tail";
  root.appendChild(tail);

  // Photo ring
  const ring = document.createElement("span");
  ring.className = "ib-photo-pin__ring";

  if (imageUrl) {
    const img = document.createElement("img");
    img.src = imageUrl;
    img.alt = "";
    img.loading = "lazy";
    img.className = "ib-photo-pin__img";
    img.addEventListener("error", () => {
      // Photo failed — swap to letter fallback inside the same ring.
      ring.innerHTML = "";
      ring.appendChild(buildFallbackLetter(nameEn));
    });
    ring.appendChild(img);
  } else {
    ring.appendChild(buildFallbackLetter(nameEn));
  }
  root.appendChild(ring);

  // Sequence badge (amber, bottom-right)
  if (seq != null) {
    const badge = document.createElement("span");
    badge.className = "ib-photo-pin__seq";
    badge.textContent = String(seq);
    root.appendChild(badge);
  }

  return root;
}

function buildFallbackLetter(nameEn: string): HTMLElement {
  const fallback = document.createElement("span");
  fallback.className = "ib-photo-pin__fallback";
  fallback.textContent = (nameEn[0] || "?").toUpperCase();
  return fallback;
}

/**
 * Mutate an existing photo-pin element's state without rebuilding the
 * DOM. Used by hover listeners and cart membership changes that don't
 * affect size/seq.
 */
export function setPhotoPinState(el: HTMLElement, state: PhotoPinState): void {
  el.dataset.state = state;
}

/**
 * Inject the CSS rules that control all three pin variants. Idempotent —
 * subsequent calls are no-ops. CSS is hand-written here rather than via
 * Tailwind because the marker content is created outside React's tree
 * (Google Maps `AdvancedMarkerElement` mounts to its own DOM root), so
 * Tailwind JIT can't scan it.
 */
let stylesInjected = false;
function injectPhotoPinStyles(): void {
  if (stylesInjected) return;
  if (typeof document === "undefined") return; // SSR safety

  const style = document.createElement("style");
  style.setAttribute("data-ib-photo-pin", "v1");
  style.textContent = `
    .ib-photo-pin {
      position: relative;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      transform-origin: 50% calc(100% + 4px);
      transition: transform 200ms ease-out, filter 200ms ease-out;
      cursor: pointer;
    }
    .ib-photo-pin[data-state="cart"]    { width: 56px; height: 56px; }
    .ib-photo-pin[data-state="preview"] { width: 54px; height: 54px; }
    .ib-photo-pin[data-state="hover"]   { width: 64px; height: 64px; transform: scale(1.02); filter: drop-shadow(0 6px 14px rgba(15,23,42,.28)); z-index: 2; }
    .ib-photo-pin[data-state="out"]     { width: 14px; height: 14px; }

    /* Slate dot (out-of-cart) */
    .ib-photo-pin__dot {
      display: block;
      width: 100%;
      height: 100%;
      border-radius: 9999px;
      background: #0f172a;
      box-shadow: 0 0 0 2px #ffffff, 0 1px 3px rgba(15,23,42,.35);
    }

    /* Photo ring (cart / hover) */
    .ib-photo-pin__ring {
      position: relative;
      width: 100%;
      height: 100%;
      overflow: hidden;
      border-radius: 9999px;
      background: #f1f5f9;
      box-shadow:
        0 0 0 3px #ffffff,
        0 8px 18px -2px rgba(15,23,42,.28),
        0 4px 8px -2px rgba(15,23,42,.18);
    }
    .ib-photo-pin[data-state="hover"] .ib-photo-pin__ring {
      box-shadow:
        0 0 0 3px #ffffff,
        0 0 0 6px rgba(245, 158, 11, .55),
        0 12px 22px -4px rgba(15,23,42,.32);
    }
    /* Preview (AI suggestion, not yet adopted) — soft amber outer ring so the
       customer sees WHERE the matched stops sit before pressing Apply. */
    .ib-photo-pin[data-state="preview"] .ib-photo-pin__ring {
      box-shadow:
        0 0 0 2px #ffffff,
        0 0 0 5px rgba(245, 158, 11, .42),
        0 8px 18px -2px rgba(15,23,42,.26);
    }
    .ib-photo-pin__img {
      display: block;
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
    .ib-photo-pin__fallback {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 100%;
      height: 100%;
      background: #f59e0b;
      color: #ffffff;
      font-size: 18px;
      font-weight: 700;
      line-height: 1;
    }

    /* Sequence badge — amber, bottom-right */
    .ib-photo-pin__seq {
      position: absolute;
      right: -2px;
      bottom: -2px;
      min-width: 22px;
      height: 22px;
      padding: 0 6px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      border-radius: 9999px;
      background: #f59e0b;
      color: #ffffff;
      font-size: 11px;
      font-weight: 700;
      line-height: 1;
      box-shadow: 0 0 0 2px #ffffff, 0 1px 2px rgba(15,23,42,.25);
    }
    .ib-photo-pin[data-state="hover"] .ib-photo-pin__seq {
      min-width: 24px;
      height: 24px;
      font-size: 12px;
    }

    /* Tail (slate triangle, pointing at the actual lat/lng) */
    .ib-photo-pin__tail {
      position: absolute;
      left: 50%;
      bottom: -6px;
      transform: translateX(-50%);
      width: 0;
      height: 0;
      border-left: 6px solid transparent;
      border-right: 6px solid transparent;
      border-top: 8px solid #0f172a;
      filter: drop-shadow(0 1px 1px rgba(15,23,42,.25));
    }
    .ib-photo-pin[data-state="hover"] .ib-photo-pin__tail {
      border-left-width: 7px;
      border-right-width: 7px;
      border-top-width: 9px;
      bottom: -7px;
    }

    @media (prefers-reduced-motion: reduce) {
      .ib-photo-pin { transition: none; }
    }
  `;
  document.head.appendChild(style);
  stylesInjected = true;
}

/**
 * Haversine distance in meters between two lat/lng points. Used by
 * Phase 2 pin offset clustering to detect <80m pairs that would
 * otherwise overlap on the map at typical city-zoom levels.
 */
export function haversineMeters(
  a: { lat: number; lng: number },
  b: { lat: number; lng: number }
): number {
  const R = 6371000;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const lat1 = (a.lat * Math.PI) / 180;
  const lat2 = (b.lat * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.sin(dLng / 2) ** 2 * Math.cos(lat1) * Math.cos(lat2);
  return 2 * R * Math.asin(Math.sqrt(h));
}
