/**
 * P7.7 (formerly P5) — the planner's locale copy, lifted out of the component.
 *
 * `PlanEditorClient.tsx` was 3,750 lines and 1,264 of them were these two
 * tables: ten locales x two string sets. That is a third of the file, it never
 * participates in any logic, and it is why opening the component to change one
 * behaviour meant scrolling past a thousand lines of Italian.
 *
 * Split here rather than earlier in P7 on purpose: the preceding tickets were
 * still deciding which strings exist (P7.4 rewrote all ten `emptyStops` when a
 * section moved), and splitting a file while its contents are still moving
 * means splitting it twice.
 *
 * 🔴 Ten locales, one source. `ROOM_LOCALES` is the single list — do not write
 * a second one here. A locale added there and missed here is a compile error,
 * which is the point.
 */
import { ROOM_LOCALES, type RoomLocale } from '@/lib/tour-room/snapshot';

// §D A4.1 — 로케일 목록은 ROOM_LOCALES 하나뿐이다. 여기 다시 적으면
// 로케일이 하나 늘어나는 날 이 파일만 조용히 5개로 남는다.
export const ROOM_LOCALE_VALUES = ROOM_LOCALES;

export interface PlanCopy {
  title: string;
  tourDay: string;
  kstNote: string;
  loading: string;
  joinError: string;
  memberReadOnly: string;
  /** P-D19 — 같은 예약의 다른 기기에서 편집 중일 때 넘겨받는 버튼. */
  claimLead: string;
  confirmedNote: string;
  submittedNote: string;
  delegatedNote: string;
  tabCourses: string;
  tabPick: string;
  tabDelegate: string;
  useCourse: string;
  courseStops: (n: number) => string;
  courseHours: (h: number) => string;
  replaceConfirm: string;
  searchPlaceholder: string;
  googleToggle: string;
  googlePlaceholder: string;
  googleLoading: string;
  add: string;
  added: string;
  yourDay: string;
  emptyStops: string;
  estimated: (total: string) => string;
  timeLabel: string;
  durationLabel: string;
  minutes: (n: number) => string;
  memoPlaceholder: string;
  removeStop: string;
  /** P2 — the ⋯ that holds reorder + remove. */
  stopActions: string;
  moveUp: string;
  moveDown: string;
  needsTitle: string;
  needsHint: string;
  departureTitle: string;
  /** P3 — clear the chosen time from the wheel sheet. */
  timeConfirm: string;
  timeClear: string;
  /** P4 — 좌석 3상태. 없는 기능을 있는 척하지 않고, 있는 정보는 숨기지 않는다. */
  seatTitle: string;
  seatAssigned: (seat: string) => string;
  seatPending: string;
  seatNone: string;
  departureHint: string;
  adults: string;
  children: string;
  childAges: string;
  childAgesPlaceholder: string;
  stroller: string;
  wheelchair: string;
  luggage: string;
  dietaryTitle: string;
  dietary: Record<string, string>;
  allergyPlaceholder: string;
  paceTitle: string;
  pace: Record<'relaxed' | 'standard' | 'packed', string>;
  notePlaceholder: string;
  warningsTitle: string;
  warnOverrun: (overMin: string, budget: string) => string;
  warnClosed: (title: string) => string;
  warnOutOfRegion: (title: string) => string;
  warnCrossIsland: (surcharge: string) => string;
  saving: string;
  saved: string;
  saveError: string;
  submit: string;
  submitting: string;
  delegateTitle: string;
  delegateDesc: string;
  delegateCta: string;
  backToRoom: string;
  allergyCardTitle: string;
  allergyCardHint: string;
}

export const COPY: Record<RoomLocale, PlanCopy> = {
  en: {
    title: 'Plan your tour day',
    tourDay: 'Tour day',
    kstNote: 'All times are Korea time (KST)',
    loading: 'Opening your planner…',
    joinError: 'We couldn’t open this link. Please use the latest link from your email, or message us.',
    memberReadOnly: 'Only the lead traveller can edit the plan — you’ll see the finished day here.',
    claimLead: 'Edit on this device',
    confirmedNote: 'Your guide confirmed this itinerary. To change something, just ask in the tour room chat.',
    submittedNote: 'Sent to your guide — they’ll review and confirm it.',
    delegatedNote: 'You’ve left the course to your guide. Tell us any wishes in the tour room chat!',
    tabCourses: 'Courses',
    tabPick: 'Pick places',
    tabDelegate: 'Guide picks',
    useCourse: 'Start with this course',
    courseStops: (n) => `${n} stops`,
    courseHours: (h) => `~${h}h`,
    replaceConfirm: 'Replace your current stops with this course?',
    searchPlaceholder: 'Search places…',
    googleToggle: 'Can’t find it? Search Google Maps',
    googlePlaceholder: 'Search any place in the region…',
    googleLoading: 'Loading Google search…',
    add: 'Add',
    added: 'Added',
    yourDay: 'Your day',
    emptyStops: 'No stops yet — choose a route below, or add places one by one.',
    estimated: (total) => `Estimated ${total} incl. driving`,
    timeLabel: 'Time (KST)',
    durationLabel: 'Stay',
    minutes: (n) => `${n}min`,
    memoPlaceholder: 'Request for this stop (optional)',
    removeStop: 'Remove stop',
    stopActions: 'Stop options',
    moveUp: 'Move up',
    moveDown: 'Move down',
    needsTitle: 'About your party',
    needsHint: 'Helps your guide prepare — shared only with your guide.',
    departureTitle: 'Departure time (KST)',
    timeConfirm: 'Set this time',
    timeClear: 'Clear time',
    seatTitle: 'Your seat',
    seatAssigned: (seat) => `Seat ${seat}`,
    seatPending: 'Your guide assigns seats on the day.',
    seatNone: 'This tour has no seat assignment — one vehicle for your party.',
    departureHint: 'When your driver picks you up — your day’s included hours count from here.',
    adults: 'Adults',
    children: 'Children',
    childAges: 'Child ages',
    childAgesPlaceholder: 'e.g. 5, 8',
    stroller: 'Stroller',
    wheelchair: 'Wheelchair',
    luggage: 'Large luggage',
    dietaryTitle: 'Dietary',
    dietary: {
      vegetarian: 'Vegetarian',
      vegan: 'Vegan',
      halal: 'Halal',
      no_pork: 'No pork',
      no_seafood: 'No seafood',
      no_shellfish: 'No shellfish',
      no_nuts: 'No nuts',
      gluten_free: 'Gluten-free',
    },
    allergyPlaceholder: 'Allergies (please describe)',
    paceTitle: 'Pace',
    pace: { relaxed: 'Relaxed', standard: 'Standard', packed: 'See a lot' },
    notePlaceholder: 'Anything else for your guide? (optional)',
    warningsTitle: 'Heads-up',
    warnOverrun: (over, budget) =>
      `This plan runs about ${over} over the booked ${budget} — your guide may trim it.`,
    warnClosed: (title) => `${title} looks closed on your tour date.`,
    warnOutOfRegion: (title) => `${title} is outside the usual service area — the guide must confirm.`,
    warnCrossIsland: (surcharge) =>
      `Visiting the East side plus the West/South on the same day is a cross-island day — a ${surcharge} surcharge applies (just a heads-up, it won’t block your plan).`,
    saving: 'Saving…',
    saved: 'Saved',
    saveError: 'Couldn’t save — retrying on your next change.',
    submit: 'Send to my guide',
    submitting: 'Sending…',
    delegateTitle: 'Let your guide build the day',
    delegateDesc:
      'Your guide plans the best route for your date, weather, and crowd levels. You can still share wishes below — they’ll be woven in.',
    delegateCta: 'Leave it to the guide',
    backToRoom: 'Open the tour room',
    allergyCardTitle: '🍽️ Restaurant card (Korean)',
    allergyCardHint: 'Show this to restaurant staff — it explains your dietary needs in Korean.',
  },
  ko: {
    title: '오늘의 일정 만들기',
    tourDay: '투어일',
    kstNote: '모든 시간은 한국시간(KST) 기준이에요',
    loading: '플래너를 여는 중…',
    joinError: '링크를 열 수 없어요. 이메일의 최신 링크로 다시 시도하거나 채팅으로 문의해 주세요.',
    memberReadOnly: '일정 편집은 대표 여행자만 할 수 있어요 — 완성된 일정이 여기에 표시돼요.',
    claimLead: '이 기기에서 편집하기',
    confirmedNote: '가이드가 일정을 확정했어요. 변경하고 싶은 게 있으면 투어룸 채팅으로 알려주세요.',
    submittedNote: '가이드에게 전달했어요 — 확인 후 확정해 드려요.',
    delegatedNote: '가이드에게 코스를 맡겼어요. 바라는 점은 투어룸 채팅으로 알려주세요!',
    tabCourses: '추천 코스',
    tabPick: '직접 고르기',
    tabDelegate: '가이드에게 맡기기',
    useCourse: '이 코스로 시작',
    courseStops: (n) => `${n}곳`,
    courseHours: (h) => `약 ${h}시간`,
    replaceConfirm: '지금 담은 일정을 이 코스로 바꿀까요?',
    searchPlaceholder: '장소 검색…',
    googleToggle: '찾는 곳이 없나요? Google 지도에서 검색',
    googlePlaceholder: '지역 내 아무 장소나 검색…',
    googleLoading: 'Google 검색 로딩 중…',
    add: '담기',
    added: '담음',
    yourDay: '나의 하루',
    emptyStops: '아직 담은 곳이 없어요 — 아래에서 코스를 고르거나 장소를 하나씩 담아보세요.',
    estimated: (total) => `이동 포함 예상 ${total}`,
    timeLabel: '시간 (KST)',
    durationLabel: '체류',
    minutes: (n) => `${n}분`,
    memoPlaceholder: '이 장소 요청사항 (선택)',
    removeStop: '삭제',
    stopActions: '정류지 옵션',
    moveUp: '위로',
    moveDown: '아래로',
    needsTitle: '여행 정보',
    needsHint: '가이드 준비에만 사용돼요 — 가이드에게만 공유됩니다.',
    departureTitle: '출발 시각 (KST)',
    timeConfirm: '이 시각으로',
    timeClear: '시각 지우기',
    seatTitle: '내 좌석',
    seatAssigned: (seat) => `${seat}번 좌석`,
    seatPending: '좌석은 가이드가 당일 배정해요.',
    seatNone: '이 투어는 좌석 지정이 없어요 — 일행 전용 차량 한 대예요.',
    departureHint: '기사님이 픽업하는 시각이에요 — 오늘의 포함 시간이 여기서부터 계산돼요.',
    adults: '성인',
    children: '아동',
    childAges: '아이 나이',
    childAgesPlaceholder: '예: 5, 8',
    stroller: '유모차',
    wheelchair: '휠체어',
    luggage: '대형 짐',
    dietaryTitle: '식이',
    dietary: {
      vegetarian: '채식',
      vegan: '비건',
      halal: '할랄',
      no_pork: '돼지고기 X',
      no_seafood: '해산물 X',
      no_shellfish: '조개·갑각류 X',
      no_nuts: '견과류 X',
      gluten_free: '글루텐프리',
    },
    allergyPlaceholder: '알레르기 (자세히 적어주세요)',
    paceTitle: '페이스',
    pace: { relaxed: '여유롭게', standard: '보통', packed: '알차게' },
    notePlaceholder: '가이드에게 전할 말 (선택)',
    warningsTitle: '확인해 주세요',
    warnOverrun: (over, budget) => `예약 시간(${budget})보다 약 ${over} 길어요 — 가이드가 조정할 수 있어요.`,
    warnClosed: (title) => `${title}은(는) 투어일에 휴무로 보여요.`,
    warnOutOfRegion: (title) => `${title}은(는) 기본 서비스 권역 밖이에요 — 가이드 확인이 필요해요.`,
    warnCrossIsland: (surcharge) =>
      `동+서/남 지역을 같은 날 함께 방문 → 크로스 아일랜드 추가요금 ${surcharge} (안내용, 차단 아님)`,
    saving: '저장 중…',
    saved: '저장됨',
    saveError: '저장에 실패했어요 — 다음 수정 때 다시 시도해요.',
    submit: '가이드에게 보내기',
    submitting: '보내는 중…',
    delegateTitle: '가이드가 하루를 설계해 드려요',
    delegateDesc:
      '투어일의 날씨·혼잡도·동선을 고려해 가이드가 최적 코스를 준비해요. 아래에 바라는 점을 남기면 반영돼요.',
    delegateCta: '가이드에게 맡기기',
    backToRoom: '투어룸 열기',
    allergyCardTitle: '🍽️ 식당용 카드 (한국어)',
    allergyCardHint: '식당 직원에게 보여주세요 — 식이 정보를 한국어로 설명해요.',
  },
  ja: {
    title: 'ツアーの一日をプランする',
    tourDay: 'ツアー日',
    kstNote: '時刻はすべて韓国時間(KST)です',
    loading: 'プランナーを開いています…',
    joinError: 'リンクを開けませんでした。メールの最新リンクからお試しください。',
    memberReadOnly: 'プラン編集は代表者のみ可能です。完成した行程がここに表示されます。',
    claimLead: 'この端末で編集する',
    confirmedNote: 'ガイドが行程を確定しました。変更はツアールームのチャットでご相談ください。',
    submittedNote: 'ガイドに送信しました。確認のうえ確定します。',
    delegatedNote: 'コースはガイドにお任せいただきました。ご希望はチャットでどうぞ!',
    tabCourses: 'おすすめコース',
    tabPick: '自分で選ぶ',
    tabDelegate: 'ガイドに任せる',
    useCourse: 'このコースで始める',
    courseStops: (n) => `${n}か所`,
    courseHours: (h) => `約${h}時間`,
    replaceConfirm: '現在のプランをこのコースに置き換えますか?',
    searchPlaceholder: 'スポットを検索…',
    googleToggle: '見つからない場合は Google マップで検索',
    googlePlaceholder: '地域内の場所を検索…',
    googleLoading: 'Google 検索を読み込み中…',
    add: '追加',
    added: '追加済み',
    yourDay: '私の一日',
    emptyStops: 'まだスポットがありません。下からコースを選ぶか、場所を一つずつ追加してください。',
    estimated: (total) => `移動込みの目安 ${total}`,
    timeLabel: '時刻 (KST)',
    durationLabel: '滞在',
    minutes: (n) => `${n}分`,
    memoPlaceholder: 'このスポットへのご要望(任意)',
    removeStop: '削除',
    stopActions: 'スポットの操作',
    moveUp: '上へ',
    moveDown: '下へ',
    needsTitle: '旅の情報',
    needsHint: 'ガイドの準備にのみ使用され、ガイドにのみ共有されます。',
    departureTitle: '出発時刻 (KST)',
    timeConfirm: 'この時刻にする',
    timeClear: '時刻をクリア',
    seatTitle: 'お座席',
    seatAssigned: (seat) => `${seat}番`,
    seatPending: '座席は当日ガイドが割り当てます。',
    seatNone: 'このツアーに座席指定はありません（ご一行専用の1台です）。',
    departureHint: 'ドライバーがお迎えする時刻です。本日の含まれる時間はここから計算されます。',
    adults: '大人',
    children: '子ども',
    childAges: 'お子さまの年齢',
    childAgesPlaceholder: '例: 5, 8',
    stroller: 'ベビーカー',
    wheelchair: '車いす',
    luggage: '大きな荷物',
    dietaryTitle: '食事制限',
    dietary: {
      vegetarian: 'ベジタリアン',
      vegan: 'ヴィーガン',
      halal: 'ハラール',
      no_pork: '豚肉NG',
      no_seafood: '海鮮NG',
      no_shellfish: '貝・甲殻類NG',
      no_nuts: 'ナッツNG',
      gluten_free: 'グルテンフリー',
    },
    allergyPlaceholder: 'アレルギー(詳しくご記入ください)',
    paceTitle: 'ペース',
    pace: { relaxed: 'ゆったり', standard: '標準', packed: 'たっぷり' },
    notePlaceholder: 'ガイドへの伝言(任意)',
    warningsTitle: 'ご確認ください',
    warnOverrun: (over, budget) => `予約時間(${budget})より約${over}長いプランです。ガイドが調整する場合があります。`,
    warnClosed: (title) => `${title}はツアー日に休業のようです。`,
    warnOutOfRegion: (title) => `${title}は通常のサービス圏外です。ガイドの確認が必要です。`,
    warnCrossIsland: (surcharge) =>
      `東側と西/南側を同じ日に巡るクロスアイランド行程です → 追加料金${surcharge}（ご案内のみ・ブロックはしません）`,
    saving: '保存中…',
    saved: '保存済み',
    saveError: '保存できませんでした。次の変更時に再試行します。',
    submit: 'ガイドに送る',
    submitting: '送信中…',
    delegateTitle: 'ガイドが一日を設計します',
    delegateDesc: '天気・混雑・動線を考慮して最適なコースをご用意します。ご希望は下に残せば反映されます。',
    delegateCta: 'ガイドに任せる',
    backToRoom: 'ツアールームを開く',
    allergyCardTitle: '🍽️ レストラン用カード(韓国語)',
    allergyCardHint: 'お店のスタッフに見せてください — 食事制限を韓国語で説明します。',
  },
  zh: {
    title: '规划您的旅行日',
    tourDay: '出行日',
    kstNote: '所有时间均为韩国时间(KST)',
    loading: '正在打开行程规划…',
    joinError: '无法打开此链接。请使用邮件中的最新链接,或在聊天中联系我们。',
    memberReadOnly: '只有主要旅客可以编辑行程——完成后会显示在这里。',
    claimLead: '在本设备上编辑',
    confirmedNote: '导游已确定行程。如需调整,请在旅行房间聊天中告诉我们。',
    submittedNote: '已发送给导游——确认后将为您敲定。',
    delegatedNote: '已交给导游安排。有任何心愿请在聊天中告诉我们!',
    tabCourses: '推荐路线',
    tabPick: '自己挑选',
    tabDelegate: '交给导游',
    useCourse: '以此路线开始',
    courseStops: (n) => `${n}站`,
    courseHours: (h) => `约${h}小时`,
    replaceConfirm: '用此路线替换当前行程吗?',
    searchPlaceholder: '搜索景点…',
    googleToggle: '找不到?用 Google 地图搜索',
    googlePlaceholder: '搜索区域内任何地点…',
    googleLoading: '正在加载 Google 搜索…',
    add: '加入',
    added: '已加入',
    yourDay: '我的一天',
    emptyStops: '还没有加入景点——在下方选择路线，或逐个添加地点。',
    estimated: (total) => `含车程预计 ${total}`,
    timeLabel: '时间 (KST)',
    durationLabel: '停留',
    minutes: (n) => `${n}分钟`,
    memoPlaceholder: '对此地点的要求(可选)',
    removeStop: '删除',
    stopActions: '地点选项',
    moveUp: '上移',
    moveDown: '下移',
    needsTitle: '出行信息',
    needsHint: '仅用于导游准备,只与导游共享。',
    departureTitle: '出发时间 (KST)',
    timeConfirm: '就用这个时间',
    timeClear: '清除时间',
    seatTitle: '我的座位',
    seatAssigned: (seat) => `${seat}号座`,
    seatPending: '座位由导游在当天安排。',
    seatNone: '本行程没有座位指定——一辆车专属于您一行。',
    departureHint: '司机接您的时间——今天的包含时长从此刻开始计算。',
    adults: '成人',
    children: '儿童',
    childAges: '孩子年龄',
    childAgesPlaceholder: '如: 5, 8',
    stroller: '婴儿车',
    wheelchair: '轮椅',
    luggage: '大件行李',
    dietaryTitle: '饮食',
    dietary: {
      vegetarian: '素食',
      vegan: '纯素',
      halal: '清真',
      no_pork: '不吃猪肉',
      no_seafood: '不吃海鲜',
      no_shellfish: '不含贝类',
      no_nuts: '不含坚果',
      gluten_free: '无麸质',
    },
    allergyPlaceholder: '过敏情况(请详细说明)',
    paceTitle: '节奏',
    pace: { relaxed: '轻松', standard: '标准', packed: '多看多玩' },
    notePlaceholder: '想对导游说的话(可选)',
    warningsTitle: '请注意',
    warnOverrun: (over, budget) => `此行程比预订时长(${budget})多约${over}——导游可能会调整。`,
    warnClosed: (title) => `${title}在出行日似乎休息。`,
    warnOutOfRegion: (title) => `${title}在常规服务范围之外——需导游确认。`,
    warnCrossIsland: (surcharge) =>
      `同一天同时游览东部与西/南部属于跨岛行程 → 需加收${surcharge}（仅作提示，不会阻止行程）`,
    saving: '保存中…',
    saved: '已保存',
    saveError: '保存失败——下次修改时会重试。',
    submit: '发送给导游',
    submitting: '发送中…',
    delegateTitle: '让导游为您设计一天',
    delegateDesc: '导游会结合天气、人流和路线为您准备最佳行程。在下方留下心愿即可被采纳。',
    delegateCta: '交给导游',
    backToRoom: '打开旅行房间',
    allergyCardTitle: '🍽️ 餐厅出示卡(韩语)',
    allergyCardHint: '出示给餐厅工作人员——用韩语说明您的饮食要求。',
  },
  'zh-TW': {
    title: '規劃您的一日行程',
    tourDay: '出遊日',
    kstNote: '所有時間均為韓國時間 (KST)',
    loading: '正在開啟行程規劃…',
    joinError: '無法開啟這個連結。請使用電子郵件中的最新連結，或在聊天中與我們聯絡。',
    memberReadOnly: '只有主要旅客可以編輯行程——完成後會顯示在這裡。',
    claimLead: '在本裝置上編輯',
    confirmedNote: '導遊已確認行程。如需調整，請在旅遊房間聊天中告訴我們。',
    submittedNote: '已傳送給導遊——確認後就會為您定案。',
    delegatedNote: '已交給導遊安排。有任何心願請在聊天中告訴我們！',
    tabCourses: '推薦路線',
    tabPick: '自己挑選',
    tabDelegate: '交給導遊',
    useCourse: '從這條路線開始',
    courseStops: (n) => `${n}站`,
    courseHours: (h) => `約${h}小時`,
    replaceConfirm: '要用這條路線取代目前的行程嗎？',
    searchPlaceholder: '搜尋景點…',
    googleToggle: '找不到嗎？用 Google 地圖搜尋',
    googlePlaceholder: '搜尋區域內的任何地點…',
    googleLoading: '正在載入 Google 搜尋…',
    add: '加入',
    added: '已加入',
    yourDay: '我的一天',
    emptyStops: '還沒有加入景點——在下方選擇路線，或逐一加入地點。',
    estimated: (total) => `含車程預估 ${total}`,
    timeLabel: '時間 (KST)',
    durationLabel: '停留',
    minutes: (n) => `${n}分鐘`,
    memoPlaceholder: '對這個地點的需求（選填）',
    removeStop: '刪除',
    stopActions: '地點選項',
    moveUp: '上移',
    moveDown: '下移',
    needsTitle: '旅遊資訊',
    needsHint: '僅供導遊準備行程使用，只會與導遊分享。',
    departureTitle: '出發時間 (KST)',
    timeConfirm: '就用這個時間',
    timeClear: '清除時間',
    seatTitle: '我的座位',
    seatAssigned: (seat) => `${seat}號座`,
    seatPending: '座位由導遊在當天安排。',
    seatNone: '本行程沒有座位指定——一輛車專屬於您一行。',
    departureHint: '司機接您的時間——今天包含的時數從這時開始計算。',
    adults: '成人',
    children: '兒童',
    childAges: '孩子年齡',
    childAgesPlaceholder: '例如：5, 8',
    stroller: '嬰兒推車',
    wheelchair: '輪椅',
    luggage: '大件行李',
    dietaryTitle: '飲食',
    dietary: {
      vegetarian: '素食',
      vegan: '純素',
      halal: '清真',
      no_pork: '不吃豬肉',
      no_seafood: '不吃海鮮',
      no_shellfish: '不吃貝類',
      no_nuts: '不吃堅果',
      gluten_free: '無麩質',
    },
    allergyPlaceholder: '過敏情況（請詳細說明）',
    paceTitle: '步調',
    pace: { relaxed: '悠閒', standard: '標準', packed: '多看多玩' },
    notePlaceholder: '想對導遊說的話（選填）',
    warningsTitle: '請留意',
    warnOverrun: (over, budget) => `這份行程比預訂時數（${budget}）多出約${over}——導遊可能會調整。`,
    warnClosed: (title) => `${title}在出遊日似乎公休。`,
    warnOutOfRegion: (title) => `${title}在一般服務範圍之外——需要導遊確認。`,
    warnCrossIsland: (surcharge) =>
      `同一天同時遊覽東部與西/南部屬於跨島行程 → 需加收${surcharge}（僅作提醒，不會阻擋行程）`,
    saving: '儲存中…',
    saved: '已儲存',
    saveError: '儲存失敗——下次修改時會再試一次。',
    submit: '傳送給導遊',
    submitting: '傳送中…',
    delegateTitle: '讓導遊為您設計一天',
    delegateDesc: '導遊會考量天氣、人潮和路線，為您準備最合適的行程。在下方留下想法就會納入安排。',
    delegateCta: '交給導遊',
    backToRoom: '開啟旅遊房間',
    allergyCardTitle: '🍽️ 餐廳出示卡（韓文）',
    allergyCardHint: '出示給餐廳工作人員——以韓文說明您的飲食需求。',
  },
  es: {
    title: 'Planea tu día de tour',
    tourDay: 'Día del tour',
    kstNote: 'Todas las horas son hora de Corea (KST)',
    loading: 'Abriendo tu planificador…',
    joinError: 'No pudimos abrir este enlace. Usa el enlace más reciente de tu correo o escríbenos.',
    memberReadOnly: 'Solo el viajero principal puede editar el plan; aquí verás el día terminado.',
    claimLead: 'Editar en este dispositivo',
    confirmedNote: 'Tu guía confirmó el itinerario. Para cambios, escríbenos en el chat del tour.',
    submittedNote: 'Enviado a tu guía: lo revisará y confirmará.',
    delegatedNote: 'Dejaste el recorrido en manos del guía. ¡Comparte tus deseos en el chat!',
    tabCourses: 'Rutas',
    tabPick: 'Elegir lugares',
    tabDelegate: 'Dejarlo al guía',
    useCourse: 'Empezar con esta ruta',
    courseStops: (n) => `${n} paradas`,
    courseHours: (h) => `~${h}h`,
    replaceConfirm: '¿Reemplazar tus paradas actuales con esta ruta?',
    searchPlaceholder: 'Buscar lugares…',
    googleToggle: '¿No lo encuentras? Busca en Google Maps',
    googlePlaceholder: 'Busca cualquier lugar de la región…',
    googleLoading: 'Cargando búsqueda de Google…',
    add: 'Añadir',
    added: 'Añadido',
    yourDay: 'Tu día',
    emptyStops: 'Aún no hay paradas: elige una ruta abajo o añade lugares uno a uno.',
    estimated: (total) => `Estimado ${total} incl. trayectos`,
    timeLabel: 'Hora (KST)',
    durationLabel: 'Estancia',
    minutes: (n) => `${n}min`,
    memoPlaceholder: 'Petición para esta parada (opcional)',
    removeStop: 'Eliminar',
    stopActions: 'Opciones de la parada',
    moveUp: 'Subir',
    moveDown: 'Bajar',
    needsTitle: 'Sobre tu grupo',
    needsHint: 'Solo para preparar tu tour; se comparte únicamente con tu guía.',
    departureTitle: 'Hora de salida (KST)',
    timeConfirm: 'Usar esta hora',
    timeClear: 'Borrar la hora',
    seatTitle: 'Tu asiento',
    seatAssigned: (seat) => `Asiento ${seat}`,
    seatPending: 'Tu guía asigna los asientos el mismo día.',
    seatNone: 'Este tour no asigna asientos: un vehículo para tu grupo.',
    departureHint: 'Cuando tu conductor te recoge — las horas incluidas del día cuentan desde aquí.',
    adults: 'Adultos',
    children: 'Niños',
    childAges: 'Edades de los niños',
    childAgesPlaceholder: 'ej.: 5, 8',
    stroller: 'Carriola',
    wheelchair: 'Silla de ruedas',
    luggage: 'Equipaje grande',
    dietaryTitle: 'Dieta',
    dietary: {
      vegetarian: 'Vegetariano',
      vegan: 'Vegano',
      halal: 'Halal',
      no_pork: 'Sin cerdo',
      no_seafood: 'Sin mariscos',
      no_shellfish: 'Sin crustáceos',
      no_nuts: 'Sin frutos secos',
      gluten_free: 'Sin gluten',
    },
    allergyPlaceholder: 'Alergias (descríbelas)',
    paceTitle: 'Ritmo',
    pace: { relaxed: 'Relajado', standard: 'Estándar', packed: 'Ver mucho' },
    notePlaceholder: '¿Algo más para tu guía? (opcional)',
    warningsTitle: 'Atención',
    warnOverrun: (over, budget) =>
      `Este plan supera en ~${over} las ${budget} reservadas; tu guía podría ajustarlo.`,
    warnClosed: (title) => `${title} parece cerrado en tu fecha de tour.`,
    warnOutOfRegion: (title) => `${title} está fuera del área habitual; el guía debe confirmarlo.`,
    warnCrossIsland: (surcharge) =>
      `Visitar el este junto con el oeste/sur el mismo día es un día cruzado de la isla — se aplica un recargo de ${surcharge} (solo es un aviso, no bloquea tu plan).`,
    saving: 'Guardando…',
    saved: 'Guardado',
    saveError: 'No se pudo guardar; se reintentará con tu próximo cambio.',
    submit: 'Enviar a mi guía',
    submitting: 'Enviando…',
    delegateTitle: 'Deja que tu guía diseñe el día',
    delegateDesc:
      'Tu guía prepara la mejor ruta según fecha, clima y multitudes. Comparte tus deseos abajo y los tendrá en cuenta.',
    delegateCta: 'Dejarlo al guía',
    backToRoom: 'Abrir la sala del tour',
    allergyCardTitle: '🍽️ Tarjeta para restaurantes (coreano)',
    allergyCardHint: 'Muéstrala al personal del restaurante: explica tu dieta en coreano.',
  },
  fr: {
    title: 'Planifiez votre journée de tour',
    tourDay: 'Jour du tour',
    kstNote: 'Toutes les heures sont en heure de Corée (KST)',
    loading: 'Ouverture de votre planificateur…',
    joinError: 'Impossible d’ouvrir ce lien. Utilisez le lien le plus récent de votre e-mail, ou écrivez-nous.',
    memberReadOnly: 'Seul le voyageur principal peut modifier le programme — la journée finalisée s’affichera ici.',
    claimLead: 'Modifier sur cet appareil',
    confirmedNote: 'Votre guide a confirmé cet itinéraire. Pour un changement, écrivez-nous dans le chat du tour.',
    submittedNote: 'Envoyé à votre guide — il le vérifiera et le confirmera.',
    delegatedNote: 'Vous avez confié le parcours à votre guide. Partagez vos envies dans le chat du tour!',
    tabCourses: 'Circuits',
    tabPick: 'Choisir les lieux',
    tabDelegate: 'Confier au guide',
    useCourse: 'Partir de ce circuit',
    courseStops: (n) => `${n} étapes`,
    courseHours: (h) => `~${h} h`,
    replaceConfirm: 'Remplacer vos étapes actuelles par ce circuit?',
    searchPlaceholder: 'Rechercher un lieu…',
    googleToggle: 'Introuvable? Recherchez sur Google Maps',
    googlePlaceholder: 'Cherchez n’importe quel lieu de la région…',
    googleLoading: 'Chargement de la recherche Google…',
    add: 'Ajouter',
    added: 'Ajouté',
    yourDay: 'Votre journée',
    emptyStops: 'Aucune étape pour l’instant — choisissez un circuit ci-dessous ou ajoutez des lieux un à un.',
    estimated: (total) => `Environ ${total}, trajets inclus`,
    timeLabel: 'Heure (KST)',
    durationLabel: 'Sur place',
    minutes: (n) => `${n} min`,
    memoPlaceholder: 'Demande pour cette étape (facultatif)',
    removeStop: 'Retirer l’étape',
    stopActions: 'Options de l’étape',
    moveUp: 'Monter',
    moveDown: 'Descendre',
    needsTitle: 'Votre groupe',
    needsHint: 'Aide votre guide à se préparer — partagé uniquement avec lui.',
    departureTitle: 'Heure de départ (KST)',
    timeConfirm: 'Choisir cette heure',
    timeClear: 'Effacer l’heure',
    seatTitle: 'Votre place',
    seatAssigned: (seat) => `Place ${seat}`,
    seatPending: 'Votre guide attribue les places le jour même.',
    seatNone: 'Ce tour n’attribue pas de places : un véhicule pour votre groupe.',
    departureHint: 'L’heure de votre prise en charge — les heures incluses de la journée comptent à partir de là.',
    adults: 'Adultes',
    children: 'Enfants',
    childAges: 'Âge des enfants',
    childAgesPlaceholder: 'ex. 5, 8',
    stroller: 'Poussette',
    wheelchair: 'Fauteuil roulant',
    luggage: 'Gros bagages',
    dietaryTitle: 'Régime',
    dietary: {
      vegetarian: 'Végétarien',
      vegan: 'Végétalien',
      halal: 'Halal',
      no_pork: 'Sans porc',
      no_seafood: 'Sans fruits de mer',
      no_shellfish: 'Sans crustacés',
      no_nuts: 'Sans fruits à coque',
      gluten_free: 'Sans gluten',
    },
    allergyPlaceholder: 'Allergies (précisez-les)',
    paceTitle: 'Rythme',
    pace: { relaxed: 'Tranquille', standard: 'Standard', packed: 'Bien rempli' },
    notePlaceholder: 'Autre chose pour votre guide? (facultatif)',
    warningsTitle: 'À noter',
    warnOverrun: (over, budget) =>
      `Ce programme dépasse d’environ ${over} la durée réservée (${budget}) — votre guide pourra l’ajuster.`,
    warnClosed: (title) => `${title} semble fermé à la date de votre tour.`,
    warnOutOfRegion: (title) => `${title} est hors de la zone habituelle — le guide doit confirmer.`,
    warnCrossIsland: (surcharge) =>
      `Visiter l’est et l’ouest/le sud le même jour, c’est traverser toute l’île — un supplément de ${surcharge} s’applique (simple info, votre programme n’est pas bloqué).`,
    saving: 'Enregistrement…',
    saved: 'Enregistré',
    saveError: 'Échec de l’enregistrement — nouvel essai à votre prochaine modification.',
    submit: 'Envoyer à mon guide',
    submitting: 'Envoi…',
    delegateTitle: 'Laissez votre guide composer la journée',
    delegateDesc:
      'Votre guide prépare le meilleur parcours selon la date, la météo et l’affluence. Partagez vos envies ci-dessous — elles seront prises en compte.',
    delegateCta: 'Confier au guide',
    backToRoom: 'Ouvrir l’espace tour',
    allergyCardTitle: '🍽️ Carte restaurant (coréen)',
    allergyCardHint: 'Montrez-la au personnel du restaurant — elle explique votre régime en coréen.',
  },
  de: {
    title: 'Planen Sie Ihren Tourtag',
    tourDay: 'Tourtag',
    kstNote: 'Alle Zeiten in koreanischer Zeit (KST)',
    loading: 'Planer wird geöffnet…',
    joinError: 'Dieser Link ließ sich nicht öffnen. Bitte nutzen Sie den neuesten Link aus Ihrer E-Mail oder schreiben Sie uns.',
    memberReadOnly: 'Nur der Hauptreisende kann den Plan bearbeiten — der fertige Tag erscheint hier.',
    claimLead: 'Auf diesem Gerät bearbeiten',
    confirmedNote: 'Ihr Guide hat diese Route bestätigt. Änderungswünsche einfach im Tour-Chat mitteilen.',
    submittedNote: 'An Ihren Guide gesendet — er prüft und bestätigt.',
    delegatedNote: 'Sie haben die Route Ihrem Guide überlassen. Wünsche gern im Tour-Chat teilen!',
    tabCourses: 'Routen',
    tabPick: 'Orte wählen',
    tabDelegate: 'Guide wählt',
    useCourse: 'Mit dieser Route starten',
    courseStops: (n) => `${n} Stopps`,
    courseHours: (h) => `~${h} Std.`,
    replaceConfirm: 'Ihre aktuellen Stopps durch diese Route ersetzen?',
    searchPlaceholder: 'Orte suchen…',
    googleToggle: 'Nicht dabei? Auf Google Maps suchen',
    googlePlaceholder: 'Beliebigen Ort in der Region suchen…',
    googleLoading: 'Google-Suche lädt…',
    add: 'Hinzufügen',
    added: 'Hinzugefügt',
    yourDay: 'Ihr Tag',
    emptyStops: 'Noch keine Stopps — wählen Sie unten eine Route oder fügen Sie Orte einzeln hinzu.',
    estimated: (total) => `Geschätzt ${total} inkl. Fahrtzeit`,
    timeLabel: 'Zeit (KST)',
    durationLabel: 'Aufenthalt',
    minutes: (n) => `${n} Min.`,
    memoPlaceholder: 'Wunsch für diesen Stopp (optional)',
    removeStop: 'Stopp entfernen',
    stopActions: 'Optionen für den Stopp',
    moveUp: 'Nach oben',
    moveDown: 'Nach unten',
    needsTitle: 'Ihre Gruppe',
    needsHint: 'Hilft Ihrem Guide bei der Vorbereitung — nur mit ihm geteilt.',
    departureTitle: 'Abfahrtszeit (KST)',
    timeConfirm: 'Diese Zeit wählen',
    timeClear: 'Zeit löschen',
    seatTitle: 'Ihr Sitzplatz',
    seatAssigned: (seat) => `Platz ${seat}`,
    seatPending: 'Ihr Guide vergibt die Plätze am Tag selbst.',
    seatNone: 'Diese Tour vergibt keine Sitzplätze — ein Fahrzeug für Ihre Gruppe.',
    departureHint: 'Wann Ihr Fahrer Sie abholt — ab hier zählen die inkludierten Stunden des Tages.',
    adults: 'Erwachsene',
    children: 'Kinder',
    childAges: 'Alter der Kinder',
    childAgesPlaceholder: 'z. B. 5, 8',
    stroller: 'Kinderwagen',
    wheelchair: 'Rollstuhl',
    luggage: 'Großes Gepäck',
    dietaryTitle: 'Ernährung',
    dietary: {
      vegetarian: 'Vegetarisch',
      vegan: 'Vegan',
      halal: 'Halal',
      no_pork: 'Kein Schwein',
      no_seafood: 'Keine Meeresfrüchte',
      no_shellfish: 'Keine Schalentiere',
      no_nuts: 'Keine Nüsse',
      gluten_free: 'Glutenfrei',
    },
    allergyPlaceholder: 'Allergien (bitte beschreiben)',
    paceTitle: 'Tempo',
    pace: { relaxed: 'Entspannt', standard: 'Standard', packed: 'Viel sehen' },
    notePlaceholder: 'Noch etwas für Ihren Guide? (optional)',
    warningsTitle: 'Hinweis',
    warnOverrun: (over, budget) =>
      `Dieser Plan überschreitet die gebuchte Zeit (${budget}) um rund ${over} — Ihr Guide passt ihn ggf. an.`,
    warnClosed: (title) => `${title} scheint an Ihrem Tourtag geschlossen zu sein.`,
    warnOutOfRegion: (title) => `${title} liegt außerhalb des üblichen Gebiets — der Guide muss das bestätigen.`,
    warnCrossIsland: (surcharge) =>
      `Osten plus Westen/Süden am selben Tag heißt einmal quer über die Insel — es gilt ein Zuschlag von ${surcharge} (nur ein Hinweis, Ihr Plan wird nicht blockiert).`,
    saving: 'Wird gespeichert…',
    saved: 'Gespeichert',
    saveError: 'Speichern fehlgeschlagen — bei der nächsten Änderung versuchen wir es erneut.',
    submit: 'An meinen Guide senden',
    submitting: 'Wird gesendet…',
    delegateTitle: 'Lassen Sie Ihren Guide den Tag planen',
    delegateDesc:
      'Ihr Guide plant die beste Route für Datum, Wetter und Andrang. Wünsche können Sie unten teilen — sie fließen ein.',
    delegateCta: 'Dem Guide überlassen',
    backToRoom: 'Tour-Raum öffnen',
    allergyCardTitle: '🍽️ Karte fürs Restaurant (Koreanisch)',
    allergyCardHint: 'Zeigen Sie sie dem Restaurantpersonal — sie erklärt Ihre Ernährung auf Koreanisch.',
  },
  ru: {
    title: 'Спланируйте свой день тура',
    tourDay: 'День тура',
    kstNote: 'Время указано в часовом поясе Кореи (KST)',
    loading: 'Открываем планировщик…',
    joinError: 'Не удалось открыть эту ссылку. Используйте самую свежую ссылку из письма или напишите нам.',
    memberReadOnly: 'Редактировать план может только главный путешественник — готовый день появится здесь.',
    claimLead: 'Редактировать на этом устройстве',
    confirmedNote: 'Гид подтвердил маршрут. Если хотите что-то изменить, напишите в чат тура.',
    submittedNote: 'Отправлено гиду — он проверит и подтвердит.',
    delegatedNote: 'Вы доверили маршрут гиду. Пожелания пишите в чат тура!',
    tabCourses: 'Маршруты',
    tabPick: 'Выбрать места',
    tabDelegate: 'Доверить гиду',
    useCourse: 'Начать с этого маршрута',
    courseStops: (n) => `Остановок: ${n}`,
    courseHours: (h) => `~${h} ч`,
    replaceConfirm: 'Заменить текущие места этим маршрутом?',
    searchPlaceholder: 'Поиск мест…',
    googleToggle: 'Не нашли? Поищите в Google Картах',
    googlePlaceholder: 'Найдите любое место в регионе…',
    googleLoading: 'Загрузка поиска Google…',
    add: 'Добавить',
    added: 'Добавлено',
    yourDay: 'Ваш день',
    emptyStops: 'Пока пусто — выберите маршрут ниже или добавляйте места по одному.',
    estimated: (total) => `Примерно ${total} с учетом дороги`,
    timeLabel: 'Время (KST)',
    durationLabel: 'На месте',
    minutes: (n) => `${n} мин`,
    memoPlaceholder: 'Пожелание к этому месту (необязательно)',
    removeStop: 'Удалить место',
    stopActions: 'Действия с остановкой',
    moveUp: 'Выше',
    moveDown: 'Ниже',
    needsTitle: 'О вашей группе',
    needsHint: 'Поможет гиду подготовиться — видит только ваш гид.',
    departureTitle: 'Время выезда (KST)',
    timeConfirm: 'Выбрать это время',
    timeClear: 'Убрать время',
    seatTitle: 'Ваше место',
    seatAssigned: (seat) => `Место ${seat}`,
    seatPending: 'Гид распределяет места в день тура.',
    seatNone: 'В этом туре места не распределяются — отдельный автомобиль для вашей группы.',
    departureHint: 'Когда водитель вас заберет — включенные часы дня считаются с этого момента.',
    adults: 'Взрослые',
    children: 'Дети',
    childAges: 'Возраст детей',
    childAgesPlaceholder: 'напр. 5, 8',
    stroller: 'Детская коляска',
    wheelchair: 'Инвалидная коляска',
    luggage: 'Крупный багаж',
    dietaryTitle: 'Питание',
    dietary: {
      vegetarian: 'Вегетарианское',
      vegan: 'Веганское',
      halal: 'Халяль',
      no_pork: 'Без свинины',
      no_seafood: 'Без морепродуктов',
      no_shellfish: 'Без моллюсков',
      no_nuts: 'Без орехов',
      gluten_free: 'Без глютена',
    },
    allergyPlaceholder: 'Аллергии (опишите подробнее)',
    paceTitle: 'Темп',
    pace: { relaxed: 'Спокойный', standard: 'Обычный', packed: 'Насыщенный' },
    notePlaceholder: 'Что-то еще для гида? (необязательно)',
    warningsTitle: 'Обратите внимание',
    warnOverrun: (over, budget) =>
      `План примерно на ${over} длиннее забронированного времени (${budget}) — гид может его сократить.`,
    warnClosed: (title) => `${title}, похоже, закрыт в день вашего тура.`,
    warnOutOfRegion: (title) => `${title} вне обычной зоны обслуживания — нужно подтверждение гида.`,
    warnCrossIsland: (surcharge) =>
      `Восток и запад/юг в один день — это поездка через весь остров, действует доплата ${surcharge} (это просто предупреждение, план не блокируется).`,
    saving: 'Сохраняем…',
    saved: 'Сохранено',
    saveError: 'Не удалось сохранить — повторим при следующем изменении.',
    submit: 'Отправить гиду',
    submitting: 'Отправляем…',
    delegateTitle: 'Пусть гид спланирует день за вас',
    delegateDesc:
      'Гид подберет лучший маршрут с учетом даты, погоды и загруженности. Пожелания можно оставить ниже — гид их учтет.',
    delegateCta: 'Доверить гиду',
    backToRoom: 'Открыть комнату тура',
    allergyCardTitle: '🍽️ Карточка для ресторана (на корейском)',
    allergyCardHint: 'Покажите ее персоналу ресторана — она объясняет ваши ограничения по-корейски.',
  },
  it: {
    title: 'Pianifica il tuo giorno di tour',
    tourDay: 'Giorno del tour',
    kstNote: 'Tutti gli orari sono in ora coreana (KST)',
    loading: 'Apertura del tuo planner…',
    joinError: 'Non siamo riusciti ad aprire questo link. Usa il link più recente della tua email o scrivici.',
    memberReadOnly: 'Solo il viaggiatore principale può modificare il piano — qui vedrai la giornata completata.',
    claimLead: 'Modifica su questo dispositivo',
    confirmedNote: 'La tua guida ha confermato l’itinerario. Per cambiare qualcosa, chiedi pure nella chat della stanza del tour.',
    submittedNote: 'Inviato alla tua guida — lo controllerà e confermerà.',
    delegatedNote: 'Hai affidato il percorso alla tua guida. Racconta i tuoi desideri nella chat della stanza del tour!',
    tabCourses: 'Percorsi',
    tabPick: 'Scegli i luoghi',
    tabDelegate: 'Sceglie la guida',
    useCourse: 'Parti da questo percorso',
    courseStops: (n) => `${n} tappe`,
    courseHours: (h) => `~${h} h`,
    replaceConfirm: 'Sostituire le tappe attuali con questo percorso?',
    searchPlaceholder: 'Cerca luoghi…',
    googleToggle: 'Non lo trovi? Cerca su Google Maps',
    googlePlaceholder: 'Cerca qualsiasi luogo della regione…',
    googleLoading: 'Caricamento della ricerca Google…',
    add: 'Aggiungi',
    added: 'Aggiunto',
    yourDay: 'La tua giornata',
    emptyStops: 'Ancora nessuna tappa — scegli un percorso qui sotto o aggiungi i luoghi uno a uno.',
    estimated: (total) => `Totale stimato ${total}, spostamenti inclusi`,
    timeLabel: 'Ora (KST)',
    durationLabel: 'Sosta',
    minutes: (n) => `${n} min`,
    memoPlaceholder: 'Richiesta per questa tappa (facoltativo)',
    removeStop: 'Rimuovi tappa',
    stopActions: 'Opzioni della tappa',
    moveUp: 'Sposta su',
    moveDown: 'Sposta giù',
    needsTitle: 'Il tuo gruppo',
    needsHint: 'Aiuta la guida a prepararsi — condiviso solo con la tua guida.',
    departureTitle: 'Orario di partenza (KST)',
    timeConfirm: 'Usa questo orario',
    timeClear: 'Cancella l’ora',
    seatTitle: 'Il suo posto',
    seatAssigned: (seat) => `Posto ${seat}`,
    seatPending: 'La guida assegna i posti il giorno stesso.',
    seatNone: 'Questo tour non assegna posti: un veicolo per il suo gruppo.',
    departureHint: 'Quando l’autista viene a prenderti — le ore incluse della giornata contano da qui.',
    adults: 'Adulti',
    children: 'Bambini',
    childAges: 'Età dei bambini',
    childAgesPlaceholder: 'es. 5, 8',
    stroller: 'Passeggino',
    wheelchair: 'Sedia a rotelle',
    luggage: 'Bagagli grandi',
    dietaryTitle: 'Alimentazione',
    dietary: {
      vegetarian: 'Vegetariano',
      vegan: 'Vegano',
      halal: 'Halal',
      no_pork: 'Niente maiale',
      no_seafood: 'Niente frutti di mare',
      no_shellfish: 'Niente crostacei',
      no_nuts: 'Niente frutta a guscio',
      gluten_free: 'Senza glutine',
    },
    allergyPlaceholder: 'Allergie (descrivile)',
    paceTitle: 'Ritmo',
    pace: { relaxed: 'Rilassato', standard: 'Standard', packed: 'Vedere tanto' },
    notePlaceholder: 'Altro per la tua guida? (facoltativo)',
    warningsTitle: 'Da sapere',
    warnOverrun: (over, budget) =>
      `Il piano supera di circa ${over} le ${budget} prenotate — la guida potrebbe accorciarlo.`,
    warnClosed: (title) => `${title} sembra chiuso nella data del tuo tour.`,
    warnOutOfRegion: (title) => `${title} è fuori dall’area abituale — serve la conferma della guida.`,
    warnCrossIsland: (surcharge) =>
      `Visitare l’est più l’ovest/sud nello stesso giorno significa attraversare tutta l’isola — si applica un supplemento di ${surcharge} (solo un avviso, il piano non viene bloccato).`,
    saving: 'Salvataggio…',
    saved: 'Salvato',
    saveError: 'Salvataggio non riuscito — riproviamo alla prossima modifica.',
    submit: 'Invia alla mia guida',
    submitting: 'Invio…',
    delegateTitle: 'Lascia che la guida costruisca la giornata',
    delegateDesc:
      'La guida prepara il percorso migliore in base a data, meteo e affluenza. Puoi comunque lasciare i tuoi desideri qui sotto — ne terrà conto.',
    delegateCta: 'Lascia fare alla guida',
    backToRoom: 'Apri la stanza del tour',
    allergyCardTitle: '🍽️ Scheda per il ristorante (coreano)',
    allergyCardHint: 'Mostrala al personale del ristorante — spiega le tue esigenze alimentari in coreano.',
  },
};

/**
 * Status + course-preview strings the PlanCopy blocks above don't carry.
 * Kept as its own 5-locale table (P-D10) — the previous single-locale English
 * fallback shipped "Preview course / Total / Driving / Loading…" untranslated
 * to every non-English guest.
 */
export interface PlanStatusCopy {
  saveRateLimited: string;
  templatesLoading: string;
  templatesEmpty: string;
  templatesError: string;
  placesLoading: string;
  placesEmpty: string;
  placesError: string;
  googleError: string;
  previewCourse: string;
  previewTitle: string;
  previewStops: string;
  previewTotal: string;
  previewDriving: string;
  previewClose: string;
  replaceApply: string;
  cancel: string;
  tourItinTitle: string;
  tourItinSub: string;
  tourItinApplyAll: string;
  tourItinAdd: string;
  tourItinAdded: string;
  tourItinDetails: string;
  /** P0 — 전세 상품의 "코스 택1". 정류지가 아니라 선택지다. */
  courseOptionTitle: string;
  courseOptionSub: string;
  courseOptionApply: string;
  courseOptionCustom: string;
}

export const PLAN_STATUS_COPY: Record<RoomLocale, PlanStatusCopy> = {
  en: {
    saveRateLimited: 'Too many quick saves. Please wait a moment, then try again.',
    templatesLoading: 'Loading recommended courses…',
    templatesEmpty: 'No recommended courses are ready for this region yet.',
    templatesError: 'Recommended courses could not be loaded.',
    placesLoading: 'Loading places…',
    placesEmpty: 'No places match this search.',
    placesError: 'Places could not be loaded. You can still search Google Maps.',
    googleError: 'Google Maps search is unavailable right now.',
    previewCourse: 'Preview course',
    previewTitle: 'Course preview',
    previewStops: 'Stops',
    previewTotal: 'Total',
    previewDriving: 'Driving',
    previewClose: 'Close course preview',
    replaceApply: 'Replace',
    cancel: 'Cancel',
    tourItinTitle: 'This tour’s itinerary',
    tourItinSub: 'The route your guide runs. Add stops to your wish-list, or start from the whole course.',
    tourItinApplyAll: 'Start from this itinerary',
    tourItinAdd: 'Add',
    tourItinAdded: 'Added',
    tourItinDetails: 'Details',
    courseOptionTitle: 'Choose your route',
    courseOptionSub: 'This charter runs one route for the day. Pick one to fill your plan — you can still edit every stop after.',
    courseOptionApply: 'Use this route',
    courseOptionCustom: 'Choose places myself',
  },
  ko: {
    saveRateLimited: '저장이 너무 잦아요. 잠시 후 다시 시도해 주세요.',
    templatesLoading: '추천 코스를 불러오는 중…',
    templatesEmpty: '아직 이 지역의 추천 코스가 준비되지 않았어요.',
    templatesError: '추천 코스를 불러오지 못했어요.',
    placesLoading: '장소를 불러오는 중…',
    placesEmpty: '검색과 일치하는 장소가 없어요.',
    placesError: '장소를 불러오지 못했어요. Google 지도 검색은 계속 쓸 수 있어요.',
    googleError: '지금은 Google 지도 검색을 사용할 수 없어요.',
    previewCourse: '코스 미리보기',
    previewTitle: '코스 미리보기',
    previewStops: '장소',
    previewTotal: '총 시간',
    previewDriving: '이동',
    previewClose: '코스 미리보기 닫기',
    replaceApply: '대체',
    cancel: '취소',
    tourItinTitle: '이 투어의 일정',
    tourItinSub: '가이드가 안내하는 코스예요. 원하는 곳을 담거나, 이 일정으로 바로 시작해 보세요.',
    tourItinApplyAll: '이 일정으로 시작하기',
    tourItinAdd: '담기',
    tourItinAdded: '담김',
    tourItinDetails: '자세히',
    courseOptionTitle: '코스를 하나 고르세요',
    courseOptionSub: '이 상품은 하루에 코스 하나를 돕니다. 하나를 고르면 일정이 채워지고, 이후 정류지는 자유롭게 고칠 수 있어요.',
    courseOptionApply: '이 코스로 하기',
    courseOptionCustom: '직접 고르기',
  },
  ja: {
    saveRateLimited: '保存が頻繁すぎます。少し待ってから再試行してください。',
    templatesLoading: 'おすすめコースを読み込み中…',
    templatesEmpty: 'この地域のおすすめコースはまだありません。',
    templatesError: 'おすすめコースを読み込めませんでした。',
    placesLoading: 'スポットを読み込み中…',
    placesEmpty: '検索に一致するスポットがありません。',
    placesError: 'スポットを読み込めませんでした。Google マップ検索は引き続き使えます。',
    googleError: '現在、Google マップ検索は利用できません。',
    previewCourse: 'コースを見る',
    previewTitle: 'コースプレビュー',
    previewStops: 'スポット',
    previewTotal: '合計',
    previewDriving: '移動',
    previewClose: 'コースプレビューを閉じる',
    replaceApply: '置き換える',
    cancel: 'キャンセル',
    tourItinTitle: 'このツアーの行程',
    tourItinSub: 'ガイドが案内するコースです。気になるスポットを追加するか、この行程から始めましょう。',
    tourItinApplyAll: 'この行程で始める',
    tourItinAdd: '追加',
    tourItinAdded: '追加済み',
    tourItinDetails: '詳細',
    courseOptionTitle: 'コースを1つお選びください',
    courseOptionSub: 'このチャーターは1日1コースです。1つ選ぶと日程が埋まり、あとから各スポットを編集できます。',
    courseOptionApply: 'このコースにする',
    courseOptionCustom: '自分で選ぶ',
  },
  zh: {
    saveRateLimited: '保存太频繁了。请稍候再试。',
    templatesLoading: '正在加载推荐路线…',
    templatesEmpty: '该地区暂无推荐路线。',
    templatesError: '无法加载推荐路线。',
    placesLoading: '正在加载景点…',
    placesEmpty: '没有匹配的景点。',
    placesError: '无法加载景点。您仍可使用 Google 地图搜索。',
    googleError: '当前无法使用 Google 地图搜索。',
    previewCourse: '预览路线',
    previewTitle: '路线预览',
    previewStops: '景点',
    previewTotal: '总计',
    previewDriving: '车程',
    previewClose: '关闭路线预览',
    replaceApply: '替换',
    cancel: '取消',
    tourItinTitle: '本次行程路线',
    tourItinSub: '导游将带您走的路线。可添加想去的景点，或直接以此行程开始。',
    tourItinApplyAll: '以此行程开始',
    tourItinAdd: '添加',
    tourItinAdded: '已添加',
    tourItinDetails: '详情',
    courseOptionTitle: '请选择一条路线',
    courseOptionSub: '该包车行程每天走一条路线。选择后将自动填入日程，之后仍可逐一修改。',
    courseOptionApply: '就选这条路线',
    courseOptionCustom: '我自己选地点',
  },
  'zh-TW': {
    saveRateLimited: '儲存太頻繁了。請稍候再試。',
    templatesLoading: '正在載入推薦路線…',
    templatesEmpty: '這個地區目前還沒有推薦路線。',
    templatesError: '無法載入推薦路線。',
    placesLoading: '正在載入景點…',
    placesEmpty: '沒有符合的景點。',
    placesError: '無法載入景點。您仍可使用 Google 地圖搜尋。',
    googleError: '目前無法使用 Google 地圖搜尋。',
    previewCourse: '預覽路線',
    previewTitle: '路線預覽',
    previewStops: '景點',
    previewTotal: '總計',
    previewDriving: '車程',
    previewClose: '關閉路線預覽',
    replaceApply: '取代',
    cancel: '取消',
    tourItinTitle: '本次行程路線',
    tourItinSub: '導遊將帶您走的路線。可以加入想去的景點，或直接從這份行程開始。',
    tourItinApplyAll: '從這份行程開始',
    tourItinAdd: '加入',
    tourItinAdded: '已加入',
    tourItinDetails: '詳情',
    courseOptionTitle: '請選擇一條路線',
    courseOptionSub: '本包車行程每天走一條路線。選擇後會自動填入日程，之後仍可逐一修改。',
    courseOptionApply: '就選這條路線',
    courseOptionCustom: '我自己選地點',
  },
  es: {
    saveRateLimited: 'Demasiados guardados seguidos. Espera un momento e inténtalo de nuevo.',
    templatesLoading: 'Cargando rutas recomendadas…',
    templatesEmpty: 'Aún no hay rutas recomendadas para esta zona.',
    templatesError: 'No se pudieron cargar las rutas recomendadas.',
    placesLoading: 'Cargando lugares…',
    placesEmpty: 'No hay lugares que coincidan.',
    placesError: 'No se pudieron cargar los lugares. Aún puedes buscar en Google Maps.',
    googleError: 'La búsqueda de Google Maps no está disponible ahora.',
    previewCourse: 'Ver la ruta',
    previewTitle: 'Vista previa de la ruta',
    previewStops: 'Paradas',
    previewTotal: 'Total',
    previewDriving: 'Trayecto',
    previewClose: 'Cerrar la vista previa',
    replaceApply: 'Reemplazar',
    cancel: 'Cancelar',
    tourItinTitle: 'El itinerario de este tour',
    tourItinSub: 'La ruta que sigue tu guía. Añade paradas a tu lista o empieza con todo el itinerario.',
    tourItinApplyAll: 'Empezar con este itinerario',
    tourItinAdd: 'Añadir',
    tourItinAdded: 'Añadido',
    tourItinDetails: 'Detalles',
    courseOptionTitle: 'Elige tu ruta',
    courseOptionSub: 'Este chárter recorre una ruta al día. Elige una para completar tu plan; luego podrás editar cada parada.',
    courseOptionApply: 'Usar esta ruta',
    courseOptionCustom: 'Elegir yo los lugares',
  },
  fr: {
    saveRateLimited: 'Enregistrements trop rapprochés. Patientez un instant, puis réessayez.',
    templatesLoading: 'Chargement des circuits recommandés…',
    templatesEmpty: 'Aucun circuit recommandé pour cette région pour l’instant.',
    templatesError: 'Impossible de charger les circuits recommandés.',
    placesLoading: 'Chargement des lieux…',
    placesEmpty: 'Aucun lieu ne correspond à cette recherche.',
    placesError: 'Impossible de charger les lieux. Vous pouvez toujours chercher sur Google Maps.',
    googleError: 'La recherche Google Maps est indisponible pour le moment.',
    previewCourse: 'Voir le circuit',
    previewTitle: 'Aperçu du circuit',
    previewStops: 'Étapes',
    previewTotal: 'Total',
    previewDriving: 'Trajets',
    previewClose: 'Fermer l’aperçu du circuit',
    replaceApply: 'Remplacer',
    cancel: 'Annuler',
    tourItinTitle: 'L’itinéraire de ce tour',
    tourItinSub: 'Le parcours suivi par votre guide. Ajoutez des étapes à votre liste, ou partez de l’itinéraire complet.',
    tourItinApplyAll: 'Partir de cet itinéraire',
    tourItinAdd: 'Ajouter',
    tourItinAdded: 'Ajouté',
    tourItinDetails: 'Détails',
    courseOptionTitle: 'Choisissez votre itinéraire',
    courseOptionSub: 'Cette formule parcourt un itinéraire par jour. Choisissez-en un pour remplir votre programme ; vous pourrez ensuite modifier chaque étape.',
    courseOptionApply: 'Choisir cet itinéraire',
    courseOptionCustom: 'Choisir moi-même les lieux',
  },
  de: {
    saveRateLimited: 'Zu viele Speicherungen kurz nacheinander. Bitte kurz warten und erneut versuchen.',
    templatesLoading: 'Empfohlene Routen werden geladen…',
    templatesEmpty: 'Für diese Region gibt es noch keine empfohlenen Routen.',
    templatesError: 'Empfohlene Routen konnten nicht geladen werden.',
    placesLoading: 'Orte werden geladen…',
    placesEmpty: 'Keine Orte passen zu dieser Suche.',
    placesError: 'Orte konnten nicht geladen werden. Die Google-Maps-Suche funktioniert weiterhin.',
    googleError: 'Die Google-Maps-Suche ist gerade nicht verfügbar.',
    previewCourse: 'Route ansehen',
    previewTitle: 'Routenvorschau',
    previewStops: 'Stopps',
    previewTotal: 'Gesamt',
    previewDriving: 'Fahrtzeit',
    previewClose: 'Routenvorschau schließen',
    replaceApply: 'Ersetzen',
    cancel: 'Abbrechen',
    tourItinTitle: 'Die Route dieser Tour',
    tourItinSub: 'Die Strecke, die Ihr Guide fährt. Fügen Sie Stopps zu Ihrer Liste hinzu oder starten Sie mit der ganzen Route.',
    tourItinApplyAll: 'Mit dieser Route starten',
    tourItinAdd: 'Hinzufügen',
    tourItinAdded: 'Hinzugefügt',
    tourItinDetails: 'Details',
    courseOptionTitle: 'Wählen Sie Ihre Route',
    courseOptionSub: 'Diese Charter-Tour fährt eine Route pro Tag. Wählen Sie eine, um den Plan zu füllen — jeden Stopp können Sie danach ändern.',
    courseOptionApply: 'Diese Route nehmen',
    courseOptionCustom: 'Orte selbst auswählen',
  },
  ru: {
    saveRateLimited: 'Слишком частое сохранение. Подождите немного и попробуйте снова.',
    templatesLoading: 'Загружаем рекомендованные маршруты…',
    templatesEmpty: 'Для этого региона пока нет рекомендованных маршрутов.',
    templatesError: 'Не удалось загрузить рекомендованные маршруты.',
    placesLoading: 'Загружаем места…',
    placesEmpty: 'По этому запросу мест не найдено.',
    placesError: 'Не удалось загрузить места. Поиск в Google Картах по-прежнему доступен.',
    googleError: 'Поиск в Google Картах сейчас недоступен.',
    previewCourse: 'Посмотреть маршрут',
    previewTitle: 'Предпросмотр маршрута',
    previewStops: 'Остановки',
    previewTotal: 'Всего',
    previewDriving: 'Дорога',
    previewClose: 'Закрыть предпросмотр маршрута',
    replaceApply: 'Заменить',
    cancel: 'Отмена',
    tourItinTitle: 'Маршрут этого тура',
    tourItinSub: 'Так пройдет тур с гидом. Добавьте места в свой список или начните сразу со всего маршрута.',
    tourItinApplyAll: 'Начать с этого маршрута',
    tourItinAdd: 'Добавить',
    tourItinAdded: 'Добавлено',
    tourItinDetails: 'Подробнее',
    courseOptionTitle: 'Выберите маршрут',
    courseOptionSub: 'В этой аренде — один маршрут на день. Выберите его, чтобы заполнить план; каждую остановку потом можно изменить.',
    courseOptionApply: 'Выбрать этот маршрут',
    courseOptionCustom: 'Выбрать места самому',
  },
  it: {
    saveRateLimited: 'Troppi salvataggi ravvicinati. Attendi un attimo e riprova.',
    templatesLoading: 'Caricamento dei percorsi consigliati…',
    templatesEmpty: 'Per questa zona non ci sono ancora percorsi consigliati.',
    templatesError: 'Impossibile caricare i percorsi consigliati.',
    placesLoading: 'Caricamento dei luoghi…',
    placesEmpty: 'Nessun luogo corrisponde alla ricerca.',
    placesError: 'Impossibile caricare i luoghi. Puoi comunque cercare su Google Maps.',
    googleError: 'La ricerca su Google Maps non è disponibile al momento.',
    previewCourse: 'Vedi il percorso',
    previewTitle: 'Anteprima del percorso',
    previewStops: 'Tappe',
    previewTotal: 'Totale',
    previewDriving: 'Spostamenti',
    previewClose: 'Chiudi l’anteprima del percorso',
    replaceApply: 'Sostituisci',
    cancel: 'Annulla',
    tourItinTitle: 'L’itinerario di questo tour',
    tourItinSub: 'Il percorso seguito dalla tua guida. Aggiungi tappe alla tua lista o parti dall’itinerario completo.',
    tourItinApplyAll: 'Parti da questo itinerario',
    tourItinAdd: 'Aggiungi',
    tourItinAdded: 'Aggiunto',
    tourItinDetails: 'Dettagli',
    courseOptionTitle: 'Scelga il suo itinerario',
    courseOptionSub: 'Questo servizio percorre un itinerario al giorno. Ne scelga uno per comporre il programma; potrà modificare ogni tappa dopo.',
    courseOptionApply: 'Usa questo itinerario',
    courseOptionCustom: 'Scelgo io i luoghi',
  },
};
