// AUTO-GENERATED by scripts/build-catalog-cards.mjs — DO NOT EDIT.
// catalog_card pages for the "zh" locale only. Loaded lazily by
// staticTourCatalogCards.lazy.ts so client bundles ship one locale, not six.

import type { SlimCatalogPage } from "./catalogCards.generated";

export const PAGES: Record<string, SlimCatalogPage> = {
  "busan-cruise-shore-excursion-bus-tour": {
    "catalog_card": {
      "slug": "busan-cruise-shore-excursion-bus-tour",
      "title": "釜山邮轮靠岸：沿海巴士观光",
      "subtitle": "乘坐大型巴士游览釜山沿海8个景点，提供邮轮码头接送，并根据您所乘邮轮的启航时间合理安排返回行程。",
      "region": "釜山",
      "duration": "9小时",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "邮轮岸上游",
        "大型巴士",
        "港口接送",
        "保证返回"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "每人起价49美元（原价55美元，优惠11%）",
      "shortCardDescription": "专为邮轮旅客打造的釜山沿海大巴一日游：提供邮轮码头接送，游览8个标志性景点（海东龙宫寺、联合国纪念公墓、札嘎其市场、BIFF广场、国际市场、甘川文化村、松岛海水浴场、龙头山公园），并保证在邮轮启航前返回。经济实惠之选——与小团产品路线相同，采用大型巴士。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-gyeongju-unesco-legacy-tour-national-museum": {
    "catalog_card": {
      "slug": "busan-gyeongju-unesco-legacy-tour-national-museum",
      "title": "釜山出发庆州UNESCO遗产一日游",
      "subtitle": "从釜山出发，一天游览韩国千年古都——UNESCO古寺、国立博物馆、韩屋村，最后以月精桥夜景收尾。",
      "region": "庆州（从釜山出发）",
      "duration": "11.5小时",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "UNESCO",
        "含国立博物馆",
        "小团体",
        "从釜山出发"
      ],
      "heroImage": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "thumbnail": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "priceLabel": "每人 US$39（原价$50，22% 优惠）",
      "shortCardDescription": "从釜山出发前往庆州的小团体一日游。庆州是新罗王国长达992年的都城（公元前57年至公元935年），也是韩国UNESCO世界遗产最为集中的城市。行程路线：阿弘山竹林 → 佛国寺（UNESCO）→ 庆州包饭午餐 → 庆州国立博物馆 → 校村韩屋村 → 月精桥。全程配备英语／中文双语持证导游；提供小型厢式车接送；佛国寺及博物馆门票均免费。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-outskirts-tongdosa-amethyst-yeongnam-day-tour": {
    "catalog_card": {
      "slug": "busan-outskirts-tongdosa-amethyst-yeongnam-day-tour",
      "title": "釜山郊区：通度寺 + 紫水晶洞窟 + 岭南阿尔卑斯",
      "subtitle": "联合国教科文组织遗址寺庙、紫水晶洞窟、冰谷缆车与甘川——乘坐大巴，11小时畅游釜山郊区。",
      "region": "釜山 → 梁山 → 蔚山 → 密阳 → 釜山",
      "duration": "11小时",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "联合国教科文组织世界遗产",
        "巴士游览",
        "3处上车地点",
        "11小时全天行程"
      ],
      "heroImage": "/images/itinerary/tongdosa-iljumun.webp",
      "thumbnail": "/images/itinerary/tongdosa-iljumun.webp",
      "priceLabel": "",
      "shortCardDescription": "11小时釜山郊区大巴一日游，途经梁山（通度寺，2018年联合国教科文组织世界文化遗产）、蔚山（紫水晶洞窟主题公园，可选游船）、密阳（岭南阿尔卑斯冰谷缆车），最终在釜山甘川文化村收尾。三处上车地点（釜山站／西面／海云台）；行程结束时可选择在札嘎其下车。"
    },
    "price": {
      "amountLabel": "85"
    }
  },
  "busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju": {
    "catalog_card": {
      "slug": "busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju",
      "title": "釜山：梅花与樱花（梁山+庆州）",
      "subtitle": "8.5小时季节性接驳游，涵盖通度寺（UNESCO山寺+树龄350年慈藏梅）、院洞梅花村、佛国寺（UNESCO）及普门湖。仅限2月25日 – 4月10日运营。",
      "region": "梁山+庆州（从釜山出发）",
      "duration": "8.5小时",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "春季限定",
        "梅花+樱花",
        "2处UNESCO世界遗产",
        "釜山上车接送"
      ],
      "heroImage": "/images/itinerary/tongdosa-iljumun.webp",
      "thumbnail": "/images/itinerary/tongdosa-iljumun.webp",
      "priceLabel": "",
      "shortCardDescription": "8.5小时釜山出发双花期接驳游，途经梁山与庆州。默认行程游览通度寺（UNESCO山寺，韩国三宝寺刹，内有树龄350年慈藏梅）、院洞梅花村（温室快闪餐厅享用水芹五花肉午餐）、佛国寺（UNESCO世界遗产）及普门湖（8公里樱花环湖路）。运营时间比纯樱花游更长：约2月25日 – 4月10日，同时涵盖梅花与樱花花期。每日路线根据梅花及樱花实际开放状况灵活调整侧重。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-private-car-charter-cruise-shore": {
    "catalog_card": {
      "slug": "busan-private-car-charter-cruise-shore",
      "title": "釜山邮轮岸上私人包车",
      "subtitle": "由持牌英语司机导游陪同，乘坐空调私家车，自由规划您的釜山专属一日行程——保证准时返回船上。",
      "region": "釜山（邮轮港 + 市区）",
      "duration": "8小时",
      "stopsCount": 5,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "私人游",
        "可定制路线",
        "含邮轮码头接送"
      ],
      "heroImage": "/images/tours/taejongdae/chatgpt-image-2026-5-10-12-26-45.webp",
      "thumbnail": "/images/tours/taejongdae/chatgpt-image-2026-5-10-12-26-45.webp",
      "priceLabel": "",
      "shortCardDescription": "为釜山邮轮旅客提供的8小时私人包车服务，配备持牌英语司机导游。默认行程涵盖联合国纪念公墓、太宗台悬崖、甘川文化村、龙头山公园及扎嘎其市场，全程可定制。可在邮轮码头、KTX车站或釜山市区任意酒店接送，保证准时返回船上。"
    },
    "price": {
      "amountLabel": "364"
    }
  },
  "busan-small-group-sightseeing-tour-cruise-passengers": {
    "catalog_card": {
      "slug": "busan-small-group-sightseeing-tour-cruise-passengers",
      "title": "釜山邮轮岸上小团游",
      "subtitle": "从邮轮码头出发，9小时共乘面包车游览釜山五大标志性景点。",
      "region": "釜山",
      "duration": "9小时",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "邮轮岸上游",
        "小型共乘面包车",
        "码头接送",
        "9小时行程"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "从釜山邮轮码头出发的共乘面包车一日游，9小时内涵盖城市最受欢迎的五大景点：联合国纪念公墓（朝鲜战争背景）、太宗台海岸悬崖、在釜山当地餐厅用午餐、甘川文化村（彩绘山城）、龙头山公园（可选釜山塔瞭望台）以及札嘎其市场。接送时间根据您所乘船只的下船时间灵活调配。持证英语／中文导游随行。"
    },
    "price": {
      "amountLabel": "84"
    }
  },
  "busan-spring-cherry-blossom-gyeongju-highlights-day-tour": {
    "catalog_card": {
      "slug": "busan-spring-cherry-blossom-gyeongju-highlights-day-tour",
      "title": "釜山至庆州：赏樱之旅",
      "subtitle": "8.5小时从釜山出发的季节性班车，前往庆州最大的赏樱胜地——普门湖、大陵苑、佛国寺。仅限3月28日至4月10日运营。",
      "region": "庆州（从釜山出发）",
      "duration": "8.5小时",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "春季限定",
        "赏樱之旅",
        "联合国教科文组织遗址",
        "釜山接送"
      ],
      "heroImage": "/images/itinerary/bomun-lake-cherry-blossom-promenade.webp",
      "thumbnail": "/images/itinerary/bomun-lake-cherry-blossom-promenade.webp",
      "priceLabel": "",
      "shortCardDescription": "8.5小时从釜山出发的班车游，前往庆州最大的春季赏樱胜地。默认路线涵盖普门湖（8公里樱花树环绕的湖畔漫步）、瞻星台与大陵苑历史核心区（联合国教科文组织庆州历史地区），以及佛国寺（联合国教科文组织世界遗产，四月中旬盛开八重樱）。每天上午根据当日花况报告确认2至3个停靠点。行程仅限3月28日至4月10日运营——若花期明显延误或已结束，提供全额退款。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-top-attractions-day-tour": {
    "catalog_card": {
      "slug": "busan-top-attractions-day-tour",
      "title": "釜山精华景点一日游",
      "subtitle": "一天游览釜山经典七站，行程均衡，设三个接送地点。",
      "region": "釜山",
      "duration": "10.5小时",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团",
        "适合初次游客",
        "釜山经典",
        "全年开放"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "一日七站小团游，涵盖釜山经典线路：海东龙宫寺海边寺庙、青沙浦及蓝线公园（可选天空胶囊缆车）、釜山本地午餐、联合国纪念公墓、甘川文化村彩绘山坡，以及札嘎其海鲜市场。釜山市中心设三个接送地点；持证英语导游；小型巴士（最多约12人）。所有景点门票均免费，仅午餐及可选项目需当日现场付款。"
    },
    "price": {
      "amountLabel": "34"
    }
  },
  "east-signature-nature-core": {
    "catalog_card": {
      "slug": "east-signature-nature-core",
      "title": "济州岛东部：火山、海岸与民俗村",
      "subtitle": "从济州石文化公园到城山日出峰，畅游济州岛东部最均衡的初访路线。",
      "region": "济州岛东部",
      "duration": "8小时",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团",
        "适合初次游客",
        "济州岛东部经典"
      ],
      "heroImage": "/images/tours/jeju-stone-park/kakaotalk-20260510-230028438-19.webp",
      "thumbnail": "/images/tours/jeju-stone-park/kakaotalk-20260510-230028438-19.webp",
      "priceLabel": "",
      "shortCardDescription": "这条轻松易行的济州岛东部一日游路线，从石文化与火山地貌出发，途经海岸与城山日出峰，最后以日出乐园和城邑民俗村收尾，让整日行程更加丰富完整。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "from-busan-gyeongju-ancient-capital-day-tour": {
    "catalog_card": {
      "slug": "from-busan-gyeongju-ancient-capital-day-tour",
      "title": "釜山出发庆州千年古都一日游",
      "subtitle": "以更悠闲的节奏游览庆州六大经典景点，更早返回。",
      "region": "庆州（从釜山出发）",
      "duration": "10.5小时",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团体",
        "节奏悠闲",
        "从釜山出发",
        "提前返回"
      ],
      "heroImage": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "thumbnail": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "priceLabel": "每人 US$39（原价$50，22% 优惠）",
      "shortCardDescription": "从釜山出发前往庆州的小团体一日游，庆州是新罗王国的古都（公元前57年—公元935年）。与UNESCO遗产版本相同的经典六景路线（阿虎山竹林 → 佛国寺UNESCO → 庆州拌饭午餐 → 国立博物馆 → 校村韩屋村 → 月精桥），但节奏更为悠闲，返回时间更早（约18:50）。配备英语/中文双语认证导游；小型厢式车；全程免费入场（仅阿虎山₩5,000及午餐费用需当天自付）。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "from-incheon-seoul-day-tour-cruise-guests": {
    "catalog_card": {
      "slug": "from-incheon-seoul-day-tour-cruise-guests",
      "title": "仁川邮轮→首尔一日游",
      "subtitle": "从仁川邮轮码头出发，游览首尔中心区的文化遗产、韩屋、市场与工艺品精华线路。",
      "region": "首尔（从仁川邮轮码头出发）",
      "duration": "9小时",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "邮轮岸上游览",
        "小型共乘面包车",
        "仁川港接送",
        "9小时行程窗口"
      ],
      "heroImage": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "thumbnail": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "priceLabel": "每人 US$69（原价$76，9% 优惠）",
      "shortCardDescription": "从仁川邮轮码头出发的共乘面包车一日游，在9小时内游览首尔核心市区的标志性景点：景福宫（周二改为昌德宫）、北村韩屋村、广藏市场午餐（首尔最上镜的街头美食街）及仁寺洞文化街。接送时间根据您所乘船只的具体下船时间灵活安排；持证英语/中文双语导游；含约75分钟返程车程。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "incheon-seoul-private-car-shore-excursion-cruise": {
    "catalog_card": {
      "slug": "incheon-seoul-private-car-shore-excursion-cruise",
      "title": "仁川→首尔 邮轮私人包车",
      "subtitle": "邮轮旅客私人包车——仁川登船口接送，全程可定制首尔一日游，码头送达并预留60分钟返航缓冲时间。",
      "region": "首尔（从仁川邮轮码头出发）",
      "duration": "8小时",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "私人",
        "邮轮",
        "靠港游",
        "首尔精华游",
        "可定制",
        "保证返船"
      ],
      "heroImage": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "thumbnail": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "priceLabel": "",
      "shortCardDescription": "8小时私人包车行程完全以您的船只返航时间为准，而非固定日程安排。在仁川邮轮码头登船口接送，配备英语导游司机，路线灵活可定制，途经景福宫、北村韩屋村及仁寺洞，自选午餐地点，游览首尔塔及明洞或曹溪寺。导游司机在返航前预留60分钟交通缓冲时间，确保您绝不错过班船。"
    },
    "price": {
      "amountLabel": "424"
    }
  },
  "jeju-cherry-blossom-tour-east-route": {
    "catalog_card": {
      "slug": "jeju-cherry-blossom-tour-east-route",
      "title": "济州岛东部：赏樱之旅",
      "subtitle": "从花海大道到熔岩洞穴，再到日出峰。",
      "region": "济州岛东部",
      "duration": "8小时",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "仅限春季",
        "樱花季",
        "济州岛东部"
      ],
      "heroImage": "/images/tours/ilchulland/chatgpt-image-2026-5-8-07-45-52.webp",
      "thumbnail": "/images/tours/ilchulland/chatgpt-image-2026-5-8-07-45-52.webp",
      "priceLabel": "",
      "shortCardDescription": "限定春季济州岛东线，途经樱花大道、10公里油菜花之路、熔岩洞穴，以及标志性的城山火山口。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "jeju-cruise-shore-excursion-bus-tour": {
    "catalog_card": {
      "slug": "jeju-cruise-shore-excursion-bus-tour",
      "title": "济州邮轮靠岸：旅游大巴游",
      "subtitle": "根据停靠港口选择路线的邮轮一日游，可选济州港或江汀港线路",
      "region": "济州（依停靠港口而定）",
      "duration": "8小时",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "邮轮游览",
        "按港口分线路",
        "经济型邮轮",
        "旅游大巴"
      ],
      "heroImage": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "thumbnail": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "priceLabel": "",
      "shortCardDescription": "这是一款根据停靠港口灵活调整路线的旅游大巴邮轮靠岸游。济州港（北部）走东海岸UNESCO路线，途经城山日出峰；江汀港（南部）走汉拿山1100高地+南海岸地质景观+偶来市场路线。两条路线均预留充裕时间返回邮轮码头。"
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "jeju-cruise-shore-excursion-small-group-tour": {
    "catalog_card": {
      "slug": "jeju-cruise-shore-excursion-small-group-tour",
      "title": "济州邮轮岸上 小团游",
      "subtitle": "根据港口灵活调整路线的邮轮一日游，涵盖济州港与江汀港两种线路",
      "region": "济州（视靠港而定）",
      "duration": "8小时",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "邮轮岸上游",
        "智能港口路线规划",
        "高端邮轮",
        "小团"
      ],
      "heroImage": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "thumbnail": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "priceLabel": "",
      "shortCardDescription": "根据邮轮靠港口灵活调整路线的小团靠港游。济州港（北部）走东海岸UNESCO路线，途经城山日出峰；江汀港（南部）走汉拿山1100高地＋南海岸地质奇观＋偶来市场路线。两条线路均留有充裕时间返回邮轮码头。"
    },
    "price": {
      "amountLabel": "77"
    }
  },
  "jeju-eastern-unesco-spots-day-tour": {
    "catalog_card": {
      "slug": "jeju-eastern-unesco-spots-day-tour",
      "title": "济州东部UNESCO一日游",
      "subtitle": "小团迷你巴士，英语·中文导游 — 以9小时东部环线游览咸德海水浴场·城邑民俗村·城山日出峰（联合国教科文组织）·海女潜水表演·万丈窟（联合国教科文组织）。",
      "region": "济州东部",
      "duration": "9小时",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团",
        "济州",
        "济州东部",
        "世界遗产",
        "超值定价",
        "所有门票已包含"
      ],
      "heroImage": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "thumbnail": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "priceLabel": "",
      "shortCardDescription": "以9小时小团环游济州东部联合国教科文组织景点。涵盖咸德海水浴场、城邑民俗村（联合国教科文组织民俗）、城山日出峰与万丈窟 — 2007年共同登录的两处联合国教科文组织世界自然遗产，以及海女潜水表演（取消时改为海女博物馆）。含全部门票，持证英语·中文导游。"
    },
    "price": {
      "amountLabel": "49"
    }
  },
  "jeju-grand-highlights-loop": {
    "catalog_card": {
      "slug": "jeju-grand-highlights-loop",
      "title": "济州精华环岛游",
      "subtitle": "济州三处联合国教科文组织遗址、海女现场表演、海崖与直泻入海的瀑布——一天尽览全岛最精华的景致。",
      "region": "济州全岛线路",
      "duration": "10–10.5小时",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团",
        "3处联合国教科文组织遗址",
        "最适合一日游客"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "",
      "shortCardDescription": "一条高强度的全岛线路，串联三处联合国教科文组织世界遗产——汉拿山、城山日出峰与万丈窟熔岩洞，并融入海女徒手潜水现场表演、柱状节理海崖以及直泻入海的正房瀑布。济州的标志性精华，浓缩于一日之内。"
    },
    "price": {
      "amountLabel": "93"
    }
  },
  "jeju-hydrangea-festival-tour-east-route": {
    "catalog_card": {
      "slug": "jeju-hydrangea-festival-tour-east-route",
      "title": "济州绣球花节：东部",
      "subtitle": "绣球花节庆+UNESCO东济州，夏季限定小团一日游。",
      "region": "济州东部",
      "duration": "9小时",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团",
        "济州",
        "绣球花",
        "季节限定",
        "夏季限定",
        "世界遗产",
        "节庆活动"
      ],
      "heroImage": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "thumbnail": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "priceLabel": "",
      "shortCardDescription": "夏季限定东济州小团一日游，以岛内绣球花节庆为主题：城山日出峰（UNESCO）、山房山绣球花节、涉地可支海岸及成音浦港游船。6月下旬至7月下旬运营，正值绣球花盛放期。"
    },
    "price": {
      "amountLabel": "64"
    }
  },
  "jeju-hydrangea-festival-tour-southwest-route": {
    "catalog_card": {
      "slug": "jeju-hydrangea-festival-tour-southwest-route",
      "title": "济州绣球花节：西南",
      "subtitle": "从海滩到柱状峭壁，再到绣球花隧道。",
      "region": "济州西南",
      "duration": "9小时",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "仅限夏季",
        "绣球花季",
        "济州西南"
      ],
      "heroImage": "/images/tours/hyeopjae-beach/kakaotalk-20260510-230009595-01.webp",
      "thumbnail": "/images/tours/hyeopjae-beach/kakaotalk-20260510-230009595-01.webp",
      "priceLabel": "",
      "shortCardDescription": "仅限夏季的济州岛西南路线——翠绿海滩、绣球花节花园、联合国教科文组织柱状节理带、三级瀑布、绣球花隧道及茶园。"
    },
    "price": {
      "amountLabel": "64"
    }
  },
  "jeju-island-private-car-charter-tour": {
    "catalog_card": {
      "slug": "jeju-island-private-car-charter-tour",
      "title": "济州岛私人包车",
      "subtitle": "与持牌司导及空调私家车，自由规划您的济州一日行程。",
      "region": "济州（东线、西线或南线）",
      "duration": "9小时",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "私人游",
        "可定制路线",
        "含酒店接送"
      ],
      "heroImage": "/images/tours/jeju-private/jeju-private-thumbnail-carnival-coast.webp",
      "thumbnail": "/images/tours/jeju-private/jeju-private-thumbnail-carnival-coast.webp",
      "priceLabel": "",
      "shortCardDescription": "济州9小时私人包车，配备持牌司导。三条推荐路线（东线、西线、南线）涵盖岛上最受欢迎的景点，也可从联合国教科文组织地标、韩剧取景地、海滩、茶田及传统市场中自由搭配行程。全岛范围内均含酒店接送服务。"
    },
    "price": {
      "amountLabel": "254"
    }
  },
  "jeju-southern-top-unesco-spots-tour": {
    "catalog_card": {
      "slug": "jeju-southern-top-unesco-spots-tour",
      "title": "济州南部西归浦招牌一日游",
      "subtitle": "济州南部西归浦海岸线——正房瀑布、外突岩偶来路线、药泉寺、汉拿山。",
      "region": "济州南部",
      "duration": "9小时",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团出行",
        "济州",
        "济州南部",
        "西归浦",
        "价格实惠",
        "无购物"
      ],
      "heroImage": "/images/tours/jeongbang-falls/kakaotalk-20260510-230028438-15.webp",
      "thumbnail": "/images/tours/jeongbang-falls/kakaotalk-20260510-230028438-15.webp",
      "priceLabel": "",
      "shortCardDescription": "畅游济州南部西归浦标志性景点的小团一日游——亚洲唯一直落入海的正房瀑布、外突岩奇岩与偶来7号路线海岸漫步、东亚最大寺院药泉寺、雪绿茶博物馆，以及汉拿山御乘生岳步道。提供济州市区及机场四处上车地点，配备持证英语/中文导游，除正房瀑布外几乎全程免费入场，无购物压力。"
    },
    "price": {
      "amountLabel": "49"
    }
  },
  "jeju-west-south-full-day-authentic-tour": {
    "catalog_card": {
      "slug": "jeju-west-south-full-day-authentic-tour",
      "title": "济州西南深度一日游",
      "subtitle": "汉拿山联合国教科文组织高地、柱状节理带、松岳山山脊、天帝渊瀑布、O'sulloc茶园与协涯海滩——一天尽览济州西部与南部精华。",
      "region": "济州西部与南部",
      "duration": "9小时",
      "stopsCount": 9,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团",
        "济州",
        "济州西部与南部",
        "UNESCO",
        "咖啡文化",
        "海岸"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "每人 US$59（原价$69，14% 优惠）",
      "shortCardDescription": "一日小团游，将济州西海岸与南海岸串联成一条环线——汉拿山1100海拔湿地（联合国教科文组织）、六边形柱状节理带、松岳山全景观景台、天帝渊瀑布、O'sulloc茶博物馆，以及西海岸的协涯海滩咖啡街。与南部联合国教科文组织线路为同一运营商，但更注重生活方式体验——\"火山地貌邂逅壮观海岸线与时尚海滨咖啡馆\"。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "jeju-winter-southwest-tangerine-snow-camellia-tour": {
    "catalog_card": {
      "slug": "jeju-winter-southwest-tangerine-snow-camellia-tour",
      "title": "济州冬季：柑橘、雪景与山茶花",
      "subtitle": "汉拿山雪景、盛花期山茶花之丘、亲手采摘柑橘，加上柱状节理带与天帝渊——9小时尽览济州冬季西南风光。",
      "region": "济州西南部",
      "duration": "9小时",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团",
        "济州",
        "冬季",
        "季节限定",
        "橘子",
        "山茶花",
        "雪"
      ],
      "heroImage": "/images/tours/jeju-tangerine-farm/photo-001.webp",
      "thumbnail": "/images/tours/jeju-tangerine-farm/photo-001.webp",
      "priceLabel": "",
      "shortCardDescription": "这是一条仅在冬季（12月至2月）运营的济州西南部一日游线路，以济州冬季三大独特体验为核心：汉拿山山坡的皑皑白雪、山茶花之丘盛开的红色山茶花，以及在真实果园亲手采摘济州柑橘。线路还涵盖天帝渊瀑布、柱状节理带及雪绿茶博物馆。提供济州市酒店接送，配备持证英语/中文导游。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "pocheon-sanjeong-lake-herb-island-art-valley": {
    "catalog_card": {
      "slug": "pocheon-sanjeong-lake-herb-island-art-valley",
      "title": "抱川：山亭湖·香草岛·艺术谷",
      "subtitle": "山间湖泊、地中海香草花园，以及由采石场变身的艺术公园——首尔周边最宁静的季节性一日游。",
      "region": "抱川（首尔一日游）",
      "duration": "10小时",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "自然摄影之旅",
        "四季特色",
        "浪漫夜灯"
      ],
      "heroImage": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "thumbnail": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "priceLabel": "",
      "shortCardDescription": "从首尔出发前往抱川的悠闲季节性一日游，京畿道乡村以湖泊、香草花园和壮观的艺术公园景观而闻名。行程涵盖群山环抱的山井湖、香草岛地中海风格的花园与夜间灯光，以及乘坐单轨列车可达的抱川艺术谷采石场观景台。比南怡岛人少，以摄影为主线，追求宁静而非打卡冲刺。"
    },
    "price": {
      "amountLabel": "54"
    }
  },
  "seoul-dmz-private-3rd-tunnel-suspension-bridge": {
    "catalog_card": {
      "slug": "seoul-dmz-private-3rd-tunnel-suspension-bridge",
      "title": "首尔非军事区私人游：第三隧道与悬索桥",
      "subtitle": "朝鲜半岛分裂边境与150米山间悬索桥，首尔出发，一天私人专属体验。",
      "region": "坡州（首尔一日游）",
      "duration": "8–9小时",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "私人包团游",
        "非军事区 + 悬索桥",
        "含酒店接送"
      ],
      "heroImage": "/images/tours/imjingak/chatgpt-image-2026-5-10-10-40-40.webp",
      "thumbnail": "/images/tours/imjingak/chatgpt-image-2026-5-10-10-40-40.webp",
      "priceLabel": "",
      "shortCardDescription": "私人一日游，将韩国历史底蕴最深厚的景点与最上镜的山间桥梁完美结合。上午游览非军事区（临津阁和平公园、第三渗透隧道、都罗展望台），下午漫步150米甘岳山红色悬索桥。进入非军事区须携带护照。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-private-nami-morning-calm-petite-france": {
    "catalog_card": {
      "slug": "seoul-private-nami-morning-calm-petite-france",
      "title": "首尔私人游：南怡岛、晨静园与小法国",
      "subtitle": "韩国最受欢迎的三处一日游打卡胜地，乘坐私家车从容游览，无需跟随团体巴士的节奏。",
      "region": "加平（首尔一日游）",
      "duration": "9至10小时",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "私人游",
        "韩剧取景地",
        "情侣与家庭"
      ],
      "heroImage": "/images/tours/nami-island/kakaotalk-20260510-222949305-04.webp",
      "thumbnail": "/images/tours/nami-island/kakaotalk-20260510-222949305-04.webp",
      "priceLabel": "",
      "shortCardDescription": "从首尔出发的私人一日游，涵盖南怡岛林荫渡船体验、晨静园主题花园漫步，以及充满色彩的小王子风情村小法国。酒店接送、私家车出行，悠闲的游览节奏，带您以最舒适的方式体验经典的加平环线之旅。"
    },
    "price": {
      "amountLabel": "194"
    }
  },
  "seoul-seoraksan-naksansa-temple-naksan-beach-day-trip": {
    "catalog_card": {
      "slug": "seoul-seoraksan-naksansa-temple-naksan-beach-day-trip",
      "title": "首尔出发 江原道：雪岳山 + 洛山寺 + 洛山海水浴场",
      "subtitle": "在这场12小时的首尔一日游中，尽览雪岳山的花岗岩山峰、千年海边古寺，以及松林环抱的东海海滩。",
      "region": "首尔 → 江原道（雪岳山与襄阳）",
      "duration": "12小时",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "首尔出发一日游",
        "空调大巴",
        "每周一及周四",
        "12小时行程"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "From US$52 per person (was $58, 10% off)",
      "shortCardDescription": "从首尔出发的12小时大巴东海海岸一日游：徒步雪岳山国家公园，参观悬崖边的洛山寺，漫步松林环抱的洛山海水浴场。每周一及周四出发，配备英语导游，提供弘大或明洞往返接送服务。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-seoraksan-nami-island-morning-calm-day-tour": {
    "catalog_card": {
      "slug": "seoul-seoraksan-nami-island-morning-calm-day-tour",
      "title": "首尔：雪岳山 + 南怡岛 + 晨静园",
      "subtitle": "雪岳山、南怡岛林荫小道与晨静园主题花园，尽在13小时首尔一日游中一览无余。",
      "region": "首尔 → 江原道 → 京畿道",
      "duration": "13小时",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "首尔出发一日游",
        "大型旅游大巴",
        "全程门票已含",
        "13小时全天行程"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "每人起价59美元（原价82美元，立省28%）",
      "shortCardDescription": "从首尔出发的13小时大巴一日游，涵盖韩国三大最热门一日游目的地：雪岳山国立公园（韩国唯一的UNESCO生物圈保护区）、南怡岛（《冬季恋歌》取景地的水杉大道）以及晨静园（拥有5,000种植物的韩国标志性私家植物园）。全程门票已含；配备英语导游；在弘益大学站或明洞站接送。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-seoraksan-national-park-sokcho-beach-day-trip": {
    "catalog_card": {
      "slug": "seoul-seoraksan-national-park-sokcho-beach-day-trip",
      "title": "雪岳山与束草海滩一日游",
      "subtitle": "从首尔出发，前往韩国最受欢迎的国家公园及东海岸城市束草的小团一日游。",
      "region": "雪岳山，江原道",
      "duration": "12小时",
      "stopsCount": 5,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团出行",
        "自然",
        "风景优美",
        "海滩",
        "海鲜市场",
        "秋叶红枫",
        "一日游"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "",
      "shortCardDescription": "从首尔出发，前往韩国最受欢迎的国家公园及东海岸城市束草的小团一日游。行程将雪岳山的花岗岩山峰、山谷与佛教文化，同束草的海鲜市场和海滩完美结合——这种山海交融的体验只有东海岸才能给你。全程12小时，含英语导游及往返交通。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suburbs-private-chartered-car-10hr": {
    "catalog_card": {
      "slug": "seoul-suburbs-private-chartered-car-10hr",
      "title": "首尔私人包车",
      "subtitle": "与持牌私人司机兼导游一起，自由规划您在首尔或近郊的专属一日行程。",
      "region": "首尔及近郊",
      "duration": "10小时",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "私人游览",
        "全程可定制",
        "免费接送首尔酒店"
      ],
      "heroImage": "/images/tours/seoul-private-charter/seoul-private-carnival-han-river-night.webp",
      "thumbnail": "/images/tours/seoul-private-charter/seoul-private-carnival-han-river-night.webp",
      "priceLabel": "",
      "shortCardDescription": "尊享10小时私人包车服务，自由规划您的首尔一日行程。可选择三条推荐路线之一——南怡岛+晨静庭园+小法国+江村铁路自行车、非军事区+坡州奥特莱斯，或爱宝乐园+韩国民俗村——也可提交您自己的行程安排。入住首尔市区酒店可享免费接送服务。"
    },
    "price": {
      "amountLabel": "184"
    }
  },
  "seoul-suwon-hwaseong-folk-village-starfield-library": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-folk-village-starfield-library",
      "title": "水原：华城、民俗村与星空图书馆",
      "subtitle": "从首尔出发前往京畿道的文化小团一日游，涵盖韩国历史遗产与现代生活的四个截然不同的面貌：被列入联合国教科文组织……",
      "region": "京畿道（首尔以南）",
      "duration": "10小时",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团",
        "文化",
        "UNESCO",
        "遗产",
        "图书馆",
        "民俗村",
        "一日游"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "从首尔出发前往京畿道的文化小团一日游，涵盖韩国历史遗产与现代生活的四个截然不同的面貌：被列入联合国教科文组织世界遗产名录的水原华城（18世纪城墙与城门）、经修复的华城行宫及其朝鲜时代情景再现表演、龙仁沉浸式露天韩国民俗村，以及气势恢宏的四层星空水原图书馆。全程10小时，含交通及门票。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library",
      "title": "水原：华城、光明洞窟与星空图书馆",
      "subtitle": "首尔出发的小团文化一日游，带您领略京畿道四种截然不同的风貌：UNESCO世界遗产水原华城……",
      "region": "京畿道（首尔以南）",
      "duration": "9小时",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小团出行",
        "文化",
        "UNESCO",
        "洞窟",
        "图书馆",
        "购物",
        "一日游"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "首尔出发的小团文化一日游，带您领略京畿道三种截然不同的风貌：UNESCO世界遗产水原华城，拥有18世纪城墙与行宫；光明洞窟内震撼人心的LED灯光地下主题公园（昔日日据时代金矿）；四层楼高的水原星空图书馆。全程9小时，含交通及门票。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suwon-hwaseong-waujeongsa-starfield": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-waujeongsa-starfield",
      "title": "水原：华城、卧牛精舍与星野图书馆",
      "subtitle": "联合国教科文组织要塞、山间寺庙与网红图书馆——一次首尔一日游，尽览韩国的历史、精神与现代。",
      "region": "水原与龙仁",
      "duration": "9至10小时",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "联合国教科文组织遗产",
        "文化遗产与现代融合一日游",
        "含门票"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "从首尔出发的小团一日游，探索韩国三个截然不同的面貌：列入联合国教科文组织世界遗产名录的水原华城（18世纪军事建筑）、以摄影闻名的星野水原图书馆（当代文化地标），以及龙仁卧牛精舍（巨型露天佛像与石钟）。遗产价值丰富，含交通及门票。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "southwest-hallasan-osulloc-aewol": {
    "catalog_card": {
      "slug": "southwest-hallasan-osulloc-aewol",
      "title": "济州西南：汉拿山·雪绿茶·涯月·梨湖泰乌",
      "subtitle": "1100高地湿地栈道、火山悬崖、瀑布小径、茶园，以及涯月·梨湖泰乌日落收尾",
      "region": "济州岛西南部",
      "duration": "9小时",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "适合初次造访济州的旅客",
        "济州西南部"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "",
      "shortCardDescription": "一条均衡的济州西南一日路线，串联汉拿山1100高地湿地、火山海岸线、天帝渊瀑布、雪绿茶茶园、涯月咖啡街与梨湖泰乌日落。"
    },
    "price": {
      "amountLabel": "49"
    }
  }
};
