// AUTO-GENERATED by scripts/build-catalog-cards.mjs — DO NOT EDIT.
// catalog_card pages for the "ja" locale only. Loaded lazily by
// staticTourCatalogCards.lazy.ts so client bundles ship one locale, not six.

import type { SlimCatalogPage } from "./catalogCards.generated";

export const PAGES: Record<string, SlimCatalogPage> = {
  "busan-cruise-shore-excursion-bus-tour": {
    "catalog_card": {
      "slug": "busan-cruise-shore-excursion-bus-tour",
      "title": "釜山クルーズ寄港地：沿岸バスツアー",
      "subtitle": "大型バスで巡る釜山沿岸8スポット周遊、クルーズターミナル送迎付き、船の出港時刻に合わせた帰港スケジュール。",
      "region": "釜山",
      "duration": "9時間",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "クルーズ観光",
        "大型バス",
        "港での送迎",
        "帰港保証"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "お一人様49米ドルから（通常55ドル、11%オフ）",
      "shortCardDescription": "クルーズ乗客のために設計された大型バス釜山沿岸日帰りツアー：クルーズターミナル送迎、厳選8スポット（海東龍宮寺、国連記念公園、チャガルチ市場、BIFFスクエア、国際市場、甘川文化村、松島ビーチ、龍頭山公園）、出港前帰港保証付き。バジェットプラン — 少人数制商品と同じルートを大型バスで。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-gyeongju-unesco-legacy-tour-national-museum": {
    "catalog_card": {
      "slug": "busan-gyeongju-unesco-legacy-tour-national-museum",
      "title": "釜山発・慶州ユネスコ遺産ツアー",
      "subtitle": "釜山から行く、韓国の千年の都を1日で — ユネスコ寺院、国立博物館、韓屋村、橋めぐり。",
      "region": "慶州（釜山発）",
      "duration": "11.5時間",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "UNESCO",
        "国立博物館付き",
        "少人数制",
        "釜山発"
      ],
      "heroImage": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "thumbnail": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "priceLabel": "1名様 US$39（定価$50、22%オフ）",
      "shortCardDescription": "釜山発・少人数制慶州日帰りツアー。慶州は992年間（紀元前57年〜935年）にわたり新羅王国の都として栄え、韓国で最もユネスコ世界遺産が集中するエリアです。ルート：アホプサン竹林 → 仏国寺（ユネスコ）→ 慶州サムパプランチ → 慶州国立博物館 → 校村韓屋村 → 月精橋。英語・中国語対応の公認ガイド付き、ミニバン使用、仏国寺・博物館の入場料は無料。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-outskirts-tongdosa-amethyst-yeongnam-day-tour": {
    "catalog_card": {
      "slug": "busan-outskirts-tongdosa-amethyst-yeongnam-day-tour",
      "title": "釜山郊外：通度寺 + アメジスト洞窟 + 嶺南アルプス",
      "subtitle": "ユネスコ世界遺産の寺院、アメジスト洞窟、氷谷ケーブルカー、甘川文化村 — 11時間のコーチツアーで釜山郊外を一日で巡る。",
      "region": "釜山 → 梁山 → 蔚山 → 密陽 → 釜山",
      "duration": "11時間",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "ユネスコ世界遺産",
        "バスツアー",
        "3か所でピックアップ",
        "11時間の日帰り"
      ],
      "heroImage": "/images/itinerary/tongdosa-iljumun.webp",
      "thumbnail": "/images/itinerary/tongdosa-iljumun.webp",
      "priceLabel": "",
      "shortCardDescription": "梁山（通度寺、2018年ユネスコ世界遺産）、蔚山（ボート乗船オプション付きアメジスト洞窟テーマパーク）、密陽（嶺南アルプス氷谷ケーブルカー）を経て、釜山の甘川文化村で締めくくる11時間の郊外コーチ日帰りツアー。ピックアップは3か所（釜山駅 / 西面 / 海雲台）、終了時にチャガルチでの途中下車オプションあり。"
    },
    "price": {
      "amountLabel": "85"
    }
  },
  "busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju": {
    "catalog_card": {
      "slug": "busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju",
      "title": "釜山：梅＆桜（梁山＋慶州）",
      "subtitle": "通度寺（ユネスコ山寺＋樹齢350年のジャジャンメ梅）、院洞梅の花村、仏国寺（ユネスコ）、普門湖を巡る8.5時間の季節限定シャトルツアー。運行期間：2月25日〜4月10日のみ。",
      "region": "梁山＋慶州（釜山発）",
      "duration": "8.5時間",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "春季限定",
        "梅＋桜",
        "ユネスコ登録2か所",
        "釜山発着"
      ],
      "heroImage": "/images/itinerary/tongdosa-iljumun.webp",
      "thumbnail": "/images/itinerary/tongdosa-iljumun.webp",
      "priceLabel": "",
      "shortCardDescription": "梁山と慶州を巡る釜山発8.5時間の二季節シャトルツアー。基本コースでは、通度寺（ユネスコ山寺・韓国三宝寺院の一つ、樹齢350年のジャジャンメ梅）、院洞梅の花村（ビニールハウスのポップアップレストランでミナリサムギョプサルのランチ）、仏国寺（ユネスコ世界遺産）、普門湖（8km桜並木周遊）を訪れます。桜のみのツアーより運行期間が広く、約2月25日〜4月10日に梅と桜の両シーズンをカバー。当日の梅・桜の開花状況に応じてルートの重点を調整します。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-private-car-charter-cruise-shore": {
    "catalog_card": {
      "slug": "busan-private-car-charter-cruise-shore",
      "title": "釜山クルーズ寄港地・プライベートカー",
      "subtitle": "公認英語対応ドライバーガイドとエアコン完備のプライベート車両で、あなただけの釜山の一日を—時間厳守の帰港保証付き。",
      "region": "釜山（クルーズ港＋市内中心部）",
      "duration": "8時間",
      "stopsCount": 5,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "プライベートツアー",
        "カスタマイズ可能なルート",
        "クルーズターミナル送迎込み"
      ],
      "heroImage": "/images/tours/taejongdae/chatgpt-image-2026-5-10-12-26-45.webp",
      "thumbnail": "/images/tours/taejongdae/chatgpt-image-2026-5-10-12-26-45.webp",
      "priceLabel": "",
      "shortCardDescription": "公認英語対応ドライバーガイド付きの、釜山クルーズ乗客向け8時間プライベートカーチャーター。標準行程はUN記念公園、太宗台、甘川文化村、龍頭山公園、チャガルチ市場をカバー。完全カスタマイズ可能。クルーズターミナル、KTX駅、釜山市内の主要ホテルからの送迎；時間厳守での帰港を保証。"
    },
    "price": {
      "amountLabel": "364"
    }
  },
  "busan-small-group-sightseeing-tour-cruise-passengers": {
    "catalog_card": {
      "slug": "busan-small-group-sightseeing-tour-cruise-passengers",
      "title": "釜山クルーズ寄港地・少人数ツアー",
      "subtitle": "クルーズターミナルから出発、乗合バンで9時間、釜山を代表する5つのスポットを巡る。",
      "region": "釜山",
      "duration": "9時間",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "クルーズ寄港地観光",
        "小型乗合バン",
        "港でのピックアップ",
        "9時間の行程"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "釜山クルーズターミナル発の乗合バン日帰りツアーで、人気の5スポットを9時間で巡ります：国連記念公園（朝鮮戦争の歴史）、太宗台の海岸断崖、地元レストランでの昼食、甘川文化村（カラフルな丘の街）、龍頭山公園（釜山タワー展望台はオプション）、チャガルチ市場。お客様の船の下船時刻に合わせたピックアップ。英語・中国語対応の認定ガイド付き。"
    },
    "price": {
      "amountLabel": "84"
    }
  },
  "busan-spring-cherry-blossom-gyeongju-highlights-day-tour": {
    "catalog_card": {
      "slug": "busan-spring-cherry-blossom-gyeongju-highlights-day-tour",
      "title": "釜山から慶州へ：桜ツアー",
      "subtitle": "釜山から慶州の主要桜スポット（普門湖・大陵苑・仏国寺）を巡る8.5時間の季節限定シャトルツアー。3月28日〜4月10日限定運行。",
      "region": "慶州（釜山発）",
      "duration": "8.5時間",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "春限定",
        "桜ツアー",
        "ユネスコ世界遺産",
        "釜山発着"
      ],
      "heroImage": "/images/itinerary/bomun-lake-cherry-blossom-promenade.webp",
      "thumbnail": "/images/itinerary/bomun-lake-cherry-blossom-promenade.webp",
      "priceLabel": "",
      "shortCardDescription": "慶州の主要な春の桜スポットを巡る、釜山発8.5時間のシャトルツアー。基本ルートは、普門湖（桜並木が続く8kmの湖畔散策）、瞻星台＋大陵苑の歴史エリア（ユネスコ・慶州歴史地区）、仏国寺（ユネスコ世界遺産・4月中旬には八重桜が見頃を迎える）をカバーします。当日の開花情報をもとに、毎朝2〜3か所の立ち寄りスポットを確定します。ツアーは3月28日〜4月10日限定運行——開花が大幅に遅れる、またはすでに終了している場合は全額返金いたします。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-top-attractions-day-tour": {
    "catalog_card": {
      "slug": "busan-top-attractions-day-tour",
      "title": "釜山トップ観光地・日帰りツアー",
      "subtitle": "乗車場所3か所で、1日バランスよく巡る釜山の定番7スポットツアー。",
      "region": "釜山",
      "duration": "10.5時間",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "小グループ",
        "初めての方にも安心",
        "釜山定番",
        "通年催行"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "釜山の定番スポットを巡る1日7か所の小グループツアー：海辺に立つ海東龍宮寺、チョンサポ＆ブルーラインパーク（スカイカプセルはオプション）、釜山の地元ランチ、国連記念公園、甘川文化村の色鮮やかな丘の街並み、チャガルチ魚市場。釜山中心部の3か所から乗車可能。公認英語ガイド付き、ミニコーチ（最大約12名）。各観光地の入場料は無料。ランチとオプション券のみ当日払い。"
    },
    "price": {
      "amountLabel": "34"
    }
  },
  "east-signature-nature-core": {
    "catalog_card": {
      "slug": "east-signature-nature-core",
      "title": "済州島東部：火山・海岸・民俗村",
      "subtitle": "済州石文化公園から城山日出峰まで、済州島東部で最もバランスの取れた初めての方向けルートをたどります。",
      "region": "済州島東部",
      "duration": "8時間",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "スモールグループ",
        "初めての方にも安心",
        "済州島東部シグネチャー"
      ],
      "heroImage": "/images/tours/jeju-stone-park/kakaotalk-20260510-230028438-19.webp",
      "thumbnail": "/images/tours/jeju-stone-park/kakaotalk-20260510-230028438-19.webp",
      "priceLabel": "",
      "shortCardDescription": "石の文化と火山の背景からスタートし、海岸と城山日出峰を経て、イルチュルランドと城邑民俗村で締めくくる、充実した1日を過ごせるわかりやすい済州島東部の日帰りルートです。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "from-busan-gyeongju-ancient-capital-day-tour": {
    "catalog_card": {
      "slug": "from-busan-gyeongju-ancient-capital-day-tour",
      "title": "釜山発・慶州古都ツアー",
      "subtitle": "慶州の定番6スポットをゆったりとしたペースで、早めの帰着。",
      "region": "慶州（釜山発）",
      "duration": "10.5時間",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "少人数グループ",
        "ゆったりとしたペース",
        "釜山発",
        "早めの帰着"
      ],
      "heroImage": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "thumbnail": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "priceLabel": "1名様 US$39（定価$50、22%オフ）",
      "shortCardDescription": "釜山から新羅王国の古都・慶州（紀元前57年〜935年）への少人数日帰りツアー。ユネスコレガシー版と同じ定番6スポットルート（アホプサン竹林 → 仏国寺ユネスコ → 慶州サムバップランチ → 国立博物館 → 校村韓屋村 → 月精橋）を、よりゆったりとしたペースで巡り、早めの帰着（約18:50）。英語・中国語対応の認定ガイド付き、ミニバン使用、全施設入場料込み（アホプサンの₩5,000とランチのみ当日払い）。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "from-incheon-seoul-day-tour-cruise-guests": {
    "catalog_card": {
      "slug": "from-incheon-seoul-day-tour-cruise-guests",
      "title": "仁川クルーズ発・ソウル日帰りツアー",
      "subtitle": "仁川クルーズターミナル発、ソウル中心部の歴史遺産・韓屋・市場・工芸品を巡るコース。",
      "region": "ソウル（仁川クルーズターミナル発）",
      "duration": "9時間",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "クルーズ陸上観光",
        "小型シェアバン",
        "仁川港でのお迎え",
        "9時間のウィンドウ"
      ],
      "heroImage": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "thumbnail": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "priceLabel": "1名様 US$69（定価$76、9%オフ）",
      "shortCardDescription": "仁川クルーズターミナル発のシェアバン日帰りツアー。9時間のウィンドウでソウルの主要スポットを一挙に巡ります：景福宮（火曜日は昌徳宮）、北村韓屋村、広蔵市場でのランチ（ソウルで最も写真映えするストリートフードの路地）、そして仁寺洞文化通り。お客様のクルーズ船の下船時刻に合わせたピックアップ。認定英語・中国語ガイド付き。帰路の車移動約75分を含みます。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "incheon-seoul-private-car-shore-excursion-cruise": {
    "catalog_card": {
      "slug": "incheon-seoul-private-car-shore-excursion-cruise",
      "title": "仁川→ソウル・クルーズプライベートカー",
      "subtitle": "クルーズ旅客向けプライベート専用車チャーター — 仁川のタラップでお出迎え、完全カスタマイズのソウル観光、出港60分前バッファー付きでターミナルまでお送り。",
      "region": "ソウル（仁川クルーズターミナル発）",
      "duration": "8時間",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "プライベート",
        "クルーズ",
        "寄港地観光",
        "ソウル主要スポット",
        "カスタマイズ可能",
        "帰船保証"
      ],
      "heroImage": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "thumbnail": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "priceLabel": "",
      "shortCardDescription": "船の出港時刻に合わせて組み立てる、8時間のプライベート専用車チャーター。固定スケジュールはありません。仁川クルーズターミナルのタラップでお出迎えし、英語対応のドライバーガイドが景福宮・北村韓屋村＋仁寺洞・お好みのランチ・Nソウルタワー・明洞または曹渓寺をご案内します。ドライバーガイドは出港時刻の60分前を交通渋滞バッファーとして確保するため、乗り遅れの心配はありません。"
    },
    "price": {
      "amountLabel": "424"
    }
  },
  "jeju-cherry-blossom-tour-east-route": {
    "catalog_card": {
      "slug": "jeju-cherry-blossom-tour-east-route",
      "title": "済州島東部：桜ツアー",
      "subtitle": "桜並木から溶岩洞窟、日出峰へ。",
      "region": "済州島東部",
      "duration": "8時間",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "春限定",
        "桜の季節",
        "済州島東部"
      ],
      "heroImage": "/images/tours/ilchulland/chatgpt-image-2026-5-8-07-45-52.webp",
      "thumbnail": "/images/tours/ilchulland/chatgpt-image-2026-5-8-07-45-52.webp",
      "priceLabel": "",
      "shortCardDescription": "桜並木、10kmの菜の花ロード、溶岩洞窟、そして城山の象徴的なクレーターを巡る、春限定の済州島東部ルート。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "jeju-cruise-shore-excursion-bus-tour": {
    "catalog_card": {
      "slug": "jeju-cruise-shore-excursion-bus-tour",
      "title": "済州クルーズ寄港地：コーチツアー",
      "subtitle": "済州港・江汀港を選べる、寄港地別クルーズ日帰りツアー",
      "region": "済州（寄港地により異なる）",
      "duration": "8時間",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "クルーズ寄港地観光",
        "寄港地別ルート設定",
        "お手頃クルーズ",
        "大型コーチ"
      ],
      "heroImage": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "thumbnail": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "priceLabel": "",
      "shortCardDescription": "寄港地に合わせてルートが変わる、大型コーチによるクルーズ寄港地バスツアー。済州港（北部）は城山日出峰を経由する東海岸ユネスコルート、江汀港（南部）はハルラ山1100＋南海岸の地質スポット＋オルレ市場ルートをご案内。いずれも余裕を持ってクルーズターミナルに帰着します。"
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "jeju-cruise-shore-excursion-small-group-tour": {
    "catalog_card": {
      "slug": "jeju-cruise-shore-excursion-small-group-tour",
      "title": "済州クルーズ寄港地・少人数ツアー",
      "subtitle": "済州港・江汀港の2ルートに対応した寄港地対応クルーズ日帰りツアー",
      "region": "済州島（寄港地により異なる）",
      "duration": "8時間",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "クルーズ観光",
        "寄港地対応ルーティング",
        "プレミアムクルーズ",
        "少人数グループ"
      ],
      "heroImage": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "thumbnail": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "priceLabel": "",
      "shortCardDescription": "寄港地に合わせてルートが変わる少人数グループ制クルーズ寄港地観光です。済州港（北部）発は城山日出峰を経由する東海岸ユネスコルート、江汀港（南部）発は漢拏山1100高地＋南海岸の地質スポット＋オルレ市場を巡るルートをご案内します。どちらもクルーズターミナルへ余裕を持って帰港します。"
    },
    "price": {
      "amountLabel": "77"
    }
  },
  "jeju-eastern-unesco-spots-day-tour": {
    "catalog_card": {
      "slug": "jeju-eastern-unesco-spots-day-tour",
      "title": "済州東部ユネスコ日帰りツアー",
      "subtitle": "少人数ミニバス、英語・中国語ガイド — 咸徳ビーチ・城邑民俗村・城山日出峰（ユネスコ）・海女の素潜り実演・万丈窟（ユネスコ）を9時間の東部ループで一周します。",
      "region": "東済州",
      "duration": "9時間",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "スモールグループ",
        "済州島",
        "東済州",
        "ユネスコ",
        "お得",
        "全入場料込み"
      ],
      "heroImage": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "thumbnail": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "priceLabel": "",
      "shortCardDescription": "済州東部のユネスコ見どころを9時間の少人数で一周します。咸徳ソウボン海水浴場、城邑民俗村（ユネスコ民俗）、城山日出峰と万丈窟 — 2007年にともに登録された2つのユネスコ世界自然遺産、そして海女の素潜り実演（中止時は海女博物館）を含みます。全入場料込み、英語・中国語対応の認定ガイド付き。"
    },
    "price": {
      "amountLabel": "49"
    }
  },
  "jeju-grand-highlights-loop": {
    "catalog_card": {
      "slug": "jeju-grand-highlights-loop",
      "title": "済州グランドハイライトループ",
      "subtitle": "済州の3つのユネスコ遺産、海女（ヘニョ）の実演、海岸の断崖、そして海へ落ちる瀑布——島の真の最高峰を1日で。",
      "region": "済州全島ルート",
      "duration": "10〜10.5時間",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "少人数制",
        "ユネスコ3遺産",
        "日帰り旅行者に最適"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "",
      "shortCardDescription": "3つのユネスコ世界遺産——漢拏山(ハルラサン)、城山日出峰、万丈窟溶岩洞窟——を、生きた海女（ヘニョ）の素潜り実演、柱状節理の断崖、海へ落ちる正房瀑布とつなぐ、密度の高い全島ルート。済州を象徴するハイライトを、1日に凝縮しました。"
    },
    "price": {
      "amountLabel": "93"
    }
  },
  "jeju-hydrangea-festival-tour-east-route": {
    "catalog_card": {
      "slug": "jeju-hydrangea-festival-tour-east-route",
      "title": "済州アジサイ祭り・東ルート",
      "subtitle": "アジサイ、城山、溶岩洞窟 — 済州東部の夏の一日。",
      "region": "済州東部",
      "duration": "9時間（夏限定）",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "夏限定",
        "済州",
        "アジサイ祭り",
        "ユネスコ",
        "東ルート"
      ],
      "heroImage": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "thumbnail": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "priceLabel": "",
      "shortCardDescription": "済州東部アジサイ祭りシーズン（6〜8月）の少人数日帰りツアー。咸徳海岸→城邑民俗村→城山日出峰（ユネスコ）→日出ランド（アジサイ祭り＋密川洞窟）→ヒュアリ自然公園（韓国有数のアジサイ見どころ）。9時間、済州市内ホテル発着。"
    },
    "price": {
      "amountLabel": "64"
    }
  },
  "jeju-hydrangea-festival-tour-southwest-route": {
    "catalog_card": {
      "slug": "jeju-hydrangea-festival-tour-southwest-route",
      "title": "済州アジサイ祭り・南西ルート",
      "subtitle": "ビーチから柱状節理帯へ、そしてアジサイのトンネルへ。",
      "region": "済州島南西部",
      "duration": "9時間",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "夏季限定",
        "アジサイのシーズン",
        "済州島南西部"
      ],
      "heroImage": "/images/tours/hyeopjae-beach/kakaotalk-20260510-230009595-01.webp",
      "thumbnail": "/images/tours/hyeopjae-beach/kakaotalk-20260510-230009595-01.webp",
      "priceLabel": "",
      "shortCardDescription": "夏季限定・済州島南西部ルート — エメラルドのビーチ、アジサイ祭りの庭園、ユネスコ世界遺産の柱状節理帯、三段の滝、アジサイのトンネル、そして茶畑。"
    },
    "price": {
      "amountLabel": "64"
    }
  },
  "jeju-island-private-car-charter-tour": {
    "catalog_card": {
      "slug": "jeju-island-private-car-charter-tour",
      "title": "済州プライベートカーチャーター",
      "subtitle": "公認ドライバーガイドとエアコン付きプライベート車両で、自分だけの済州の一日をデザインしましょう。",
      "region": "済州（東・西・南）",
      "duration": "9時間",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "プライベートツアー",
        "カスタマイズ可能なルート",
        "ホテル送迎込み"
      ],
      "heroImage": "/images/tours/jeju-private/jeju-private-thumbnail-carnival-coast.webp",
      "thumbnail": "/images/tours/jeju-private/jeju-private-thumbnail-carnival-coast.webp",
      "priceLabel": "",
      "shortCardDescription": "公認ドライバーガイド付きの済州9時間プライベートチャーター車。おすすめの3コース（東・西・南）では島の人気スポットを巡ることができます。また、ユネスコ世界遺産、韓国ドラマのロケ地、ビーチ、茶畑、伝統市場からオリジナルコースを自由に組み立てることも可能です。島内どこでもホテル送迎が含まれています。"
    },
    "price": {
      "amountLabel": "254"
    }
  },
  "jeju-southern-top-unesco-spots-tour": {
    "catalog_card": {
      "slug": "jeju-southern-top-unesco-spots-tour",
      "title": "済州南部ソギポ シグネチャー日帰りツアー",
      "subtitle": "済州南部ソギポ海岸コース — 正房瀑布、外突き岩のオルレ道、薬泉寺、漢拏山。",
      "region": "済州南部",
      "duration": "9時間",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "少人数グループ",
        "済州",
        "済州南部",
        "ソギポ",
        "お手頃価格",
        "買い物なし"
      ],
      "heroImage": "/images/tours/jeongbang-falls/kakaotalk-20260510-230028438-15.webp",
      "thumbnail": "/images/tours/jeongbang-falls/kakaotalk-20260510-230028438-15.webp",
      "priceLabel": "",
      "shortCardDescription": "済州南部ソギポの定番スポットを少人数で巡る日帰りツアー — アジアで唯一海へ直接落ちる正房瀑布、外突き岩の奇岩とオルレ7コースの海岸散策、東アジア最大の寺院・薬泉寺、オソルロックティーミュージアム、そして漢拏山御乗生岳の登山道。済州市内全域と空港を含む4か所のピックアップポイント、英語・中国語の認定ガイド同行、正房瀑布以外はほぼ全コース入場無料、買い物の押し売りなし。"
    },
    "price": {
      "amountLabel": "49"
    }
  },
  "jeju-west-south-full-day-authentic-tour": {
    "catalog_card": {
      "slug": "jeju-west-south-full-day-authentic-tour",
      "title": "済州西南部・オーセンティック日帰り",
      "subtitle": "漢拏山ユネスコ高地、柱状節理帯、松岳山の火口縁、天帝淵滝、オソルロックのお茶、そして協財海岸——済州島の西部と南部を、バランスよく1日で満喫。",
      "region": "済州島西部・南部",
      "duration": "9時間",
      "stopsCount": 9,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "少人数グループ",
        "済州島",
        "済州島西部・南部",
        "UNESCO",
        "カフェ文化",
        "海岸"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "1名様 US$59（定価$69、14%オフ）",
      "shortCardDescription": "済州島の西海岸と南海岸を一度に巡る少人数日帰りツアー。漢拏山1100高地湿地（ユネスコ）、六角形の柱状節理帯、松岳山のパノラマ展望台、天帝淵滝、オソルロックティーミュージアム、そして西海岸の協財海岸カフェエリアをご案内します。南部ユネスコツアーと同じ運営会社ですが、よりライフスタイル志向のコンセプトで構成——「火山の景観とドラマティックな海岸線、トレンディな海辺カフェが融合する」旅をお届けします。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "jeju-winter-southwest-tangerine-snow-camellia-tour": {
    "catalog_card": {
      "slug": "jeju-winter-southwest-tangerine-snow-camellia-tour",
      "title": "済州の冬：みかん・雪・椿",
      "subtitle": "漢拏山の雪、カメリアヒルの満開、みかん狩り体験、そして柱状節理帯と天帝淵——済州南西部の冬を9時間で満喫。",
      "region": "済州南西部",
      "duration": "9時間",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "少人数グループ",
        "済州",
        "冬",
        "季節限定",
        "みかん",
        "椿（つばき）",
        "雪"
      ],
      "heroImage": "/images/tours/jeju-tangerine-farm/photo-001.webp",
      "thumbnail": "/images/tours/jeju-tangerine-farm/photo-001.webp",
      "priceLabel": "",
      "shortCardDescription": "12月から2月にかけて済州島南西部を巡る季節限定の日帰りツアーです。冬の済州ならではの三つの魅力を中心に構成されています：漢拏山の斜面に広がる雪景色、カメリアヒルで満開を迎える赤い椿、そして現役の農園でのみかん（ギュル）狩り体験。コースには天帝淵の滝、柱状節理帯、オソルロック・ティーミュージアムも含まれます。済州市内のホテルから送迎あり、英語・中国語対応の公認ガイドが同行します。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "pocheon-sanjeong-lake-herb-island-art-valley": {
    "catalog_card": {
      "slug": "pocheon-sanjeong-lake-herb-island-art-valley",
      "title": "抱川：山正湖・ハーブ・アートバレー",
      "subtitle": "山の湖、地中海式ハーブガーデン、採石場を転用したアートパーク——ソウルから行く、最もゆったりとした季節の日帰り旅行。",
      "region": "ポチョン（ソウル日帰り旅行）",
      "duration": "10時間",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "自然＆フォトトリップ",
        "季節のハイライト",
        "ロマンティックなイルミネーション"
      ],
      "heroImage": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "thumbnail": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "priceLabel": "",
      "shortCardDescription": "ソウルから京畿道の田舎・ポチョンへのゆったりとした季節の日帰り旅行。湖、ハーブガーデン、そしてドラマチックなアートパークの風景で知られるこの地を巡るルートは、山に囲まれた山井湖、地中海スタイルのガーデンと夜のイルミネーションが魅力のハーブアイランド、モノレールでアクセスするポチョン・アートバレーの採石場展望台を組み合わせています。南怡島より混雑が少なく、名所を駆け足で回るのではなく、写真撮影を中心とした落ち着いた旅を楽しめます。"
    },
    "price": {
      "amountLabel": "54"
    }
  },
  "seoul-dmz-private-3rd-tunnel-suspension-bridge": {
    "catalog_card": {
      "slug": "seoul-dmz-private-3rd-tunnel-suspension-bridge",
      "title": "ソウルDMZプライベート：第3トンネル＆橋",
      "subtitle": "韓国の分断された国境と150メートルの山岳吊り橋を、ソウル発プライベートデイツアーで一度に体験。",
      "region": "坡州（ソウルデイトリップ）",
      "duration": "8〜9時間",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "プライベートツアー",
        "DMZ＋吊り橋",
        "ホテルピックアップ込み"
      ],
      "heroImage": "/images/tours/imjingak/chatgpt-image-2026-5-10-10-40-40.webp",
      "thumbnail": "/images/tours/imjingak/chatgpt-image-2026-5-10-10-40-40.webp",
      "priceLabel": "",
      "shortCardDescription": "韓国で最も重みのある歴史的スポットと、最も絵になる山岳吊り橋のひとつを組み合わせたプライベートデイトリップ。午前はDMZ（臨津閣平和公園、第3浸透トンネル、都羅展望台）を訪れ、午後は150メートルのガマクサン・レッド吊り橋を渡ります。DMZエリアへの入場にはパスポートが必要です。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-private-nami-morning-calm-petite-france": {
    "catalog_card": {
      "slug": "seoul-private-nami-morning-calm-petite-france",
      "title": "ソウル貸切：ナミ島、モーニングカーム＆プチフランス",
      "subtitle": "韓国で最も写真映えする日帰りスポット3か所を、バスツアーのような慌ただしさなく、貸切車でゆったりと巡ります。",
      "region": "加平（ソウル日帰り）",
      "duration": "9〜10時間",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "貸切ツアー",
        "韓国ドラマのロケ地",
        "カップル・ファミリー向け"
      ],
      "heroImage": "/images/tours/nami-island/kakaotalk-20260510-222949305-04.webp",
      "thumbnail": "/images/tours/nami-island/kakaotalk-20260510-222949305-04.webp",
      "priceLabel": "",
      "shortCardDescription": "ソウル発の貸切日帰りツアーで、ナミ島の並木道とフェリー体験、晨園のテーマガーデン散策、そしてカラフルな星の王子さまの村・プチフランスをお楽しみいただけます。ホテル送迎・貸切車・ゆったりとしたペースで、定番の加平ルートを最高の快適さでご案内します。"
    },
    "price": {
      "amountLabel": "194"
    }
  },
  "seoul-seoraksan-naksansa-temple-naksan-beach-day-trip": {
    "catalog_card": {
      "slug": "seoul-seoraksan-naksansa-temple-naksan-beach-day-trip",
      "title": "ソウル発 江原道：雪岳山＋洛山寺＋洛山ビーチ",
      "subtitle": "雪岳山の花崗岩の峰々、千年の歴史を誇る海辺の古刹、そして松林に抱かれた東海ビーチを、ソウル発12時間の日帰りトリップで一度に。",
      "region": "ソウル → 江原道（雪岳山＆襄陽）",
      "duration": "12時間",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "ソウル発日帰り旅行",
        "エアコン付きコーチ",
        "毎週月曜・木曜",
        "12時間の旅"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "From US$52 per person (was $58, 10% off)",
      "shortCardDescription": "ソウルから東海岸へのコーチ12時間日帰りトリップ：雪岳山国立公園をハイキングし、断崖絶壁の洛山寺を訪れ、松林に囲まれた洛山ビーチを散策。毎週月曜・木曜出発、英語ガイド付き、弘大または明洞からの往復送迎込み。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-seoraksan-nami-island-morning-calm-day-tour": {
    "catalog_card": {
      "slug": "seoul-seoraksan-nami-island-morning-calm-day-tour",
      "title": "ソウル発：雪岳山 ＋ 南怡島 ＋ 晨静苑",
      "subtitle": "雪岳山、南怡島の並木道、晨静苑のテーマガーデンを、ソウル発13時間の日帰りツアーでまとめて堪能。",
      "region": "ソウル → 江原道 → 京畿道",
      "duration": "13時間",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "ソウルからの日帰り旅行",
        "大型バス",
        "入場料すべて込み",
        "13時間の行程"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "お一人様 US$59〜（通常$82、28%割引）",
      "shortCardDescription": "ソウル発13時間バス日帰りツアーで、韓国で最も写真に撮られる3大スポットを訪問：雪岳山国立公園（韓国唯一のユネスコ生物圏保護区）、南怡島（冬のソナタのメタセコイア並木）、晨静苑（5,000種類の植物を誇る韓国を代表するプライベート樹木園）。入場料すべて込み、英語ガイド付き、弘大入口駅または明洞駅よりピックアップ。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-seoraksan-national-park-sokcho-beach-day-trip": {
    "catalog_card": {
      "slug": "seoul-seoraksan-national-park-sokcho-beach-day-trip",
      "title": "雪岳山＆束草ビーチ日帰りツアー",
      "subtitle": "ソウルから韓国で最も愛される国立公園と、東海岸の都市・束草への少人数日帰り旅行です。",
      "region": "雪岳山、江原道",
      "duration": "12時間",
      "stopsCount": 5,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "少人数",
        "自然",
        "絶景",
        "ビーチ",
        "水産市場",
        "紅葉",
        "日帰り旅行"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "",
      "shortCardDescription": "ソウルから韓国で最も愛される国立公園と、東海岸の都市・束草への少人数日帰り旅行です。雪岳山の花崗岩の峰々、渓谷、仏教文化遺産と、束草の水産市場・ビーチを組み合わせたルートは、東海岸ならではの山と海の絶景体験です。英語ガイド付き、往復送迎込みの12時間ツアー。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suburbs-private-chartered-car-10hr": {
    "catalog_card": {
      "slug": "seoul-suburbs-private-chartered-car-10hr",
      "title": "ソウルプライベートカーチャーター",
      "subtitle": "プライベート専任ドライバーガイドと共に、ソウルまたは近郊での一日を自由にデザインしてください。",
      "region": "ソウル＆近郊",
      "duration": "10時間",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "プライベートツアー",
        "完全カスタマイズ可能",
        "ソウルホテル無料送迎"
      ],
      "heroImage": "/images/tours/seoul-private-charter/seoul-private-carnival-han-river-night.webp",
      "thumbnail": "/images/tours/seoul-private-charter/seoul-private-carnival-han-river-night.webp",
      "priceLabel": "",
      "shortCardDescription": "ソウル近郊での一日を自分でプランニングできる、プレミアム10時間プライベートカーチャーター。おすすめ3ルートからお選びください――ナミ島＋晨静苑＋プチフランス＋江村レールバイク、DMZ＋坡州アウトレット、またはエバーランド＋韓国民俗村――または、ご自身のプランをご送付いただくことも可能です。ソウル市内のホテル滞在のお客様には、無料ホテル送迎が含まれます。"
    },
    "price": {
      "amountLabel": "184"
    }
  },
  "seoul-suwon-hwaseong-folk-village-starfield-library": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-folk-village-starfield-library",
      "title": "水原：華城・民俗村＆スターフィールド",
      "subtitle": "ソウルから京畿道へ向かう少人数文化日帰り旅行。韓国の歴史遺産と現代の暮らしの対照的な4つの側面をめぐります：ユネスコ登録の…",
      "region": "京畿道（ソウル南部）",
      "duration": "10時間",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "少人数グループ",
        "文化",
        "UNESCO",
        "歴史遺産",
        "ライブラリー",
        "民俗村",
        "日帰り旅行"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "ソウルから京畿道へ向かう少人数文化日帰り旅行。韓国の歴史遺産と現代の暮らしの対照的な4つの側面をめぐります：ユネスコ世界遺産に登録された水原華城（18世紀の城壁と城門）、朝鮮時代の再現イベントが催される復元された華城行宮、龍仁にある没入感あふれる野外型韓国民俗村、そして圧倒的な存在感を放つ4フロアのスターフィールドライブラリー水原。交通費と入場料込みの10時間ツアー。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library",
      "title": "水原：華城、光明洞窟＆スターフィールド",
      "subtitle": "ソウル発の少人数制文化日帰りツアーで、京畿道の対照的な4つの魅力を巡ります：ユネスコ世界遺産・水原華城…",
      "region": "京畿道（ソウル南部）",
      "duration": "9時間",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "少人数制",
        "文化",
        "UNESCO",
        "洞窟",
        "図書館",
        "ショッピング",
        "日帰り旅行"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "ソウル発の少人数制文化日帰りツアーで、京畿道の対照的な3つの魅力を巡ります。18世紀の城壁と行宮を有するユネスコ世界遺産・水原華城、旧日本時代の金鉱跡に広がるLEDライトアップの地下テーマパーク「光明洞窟」、4フロアにわたるスターフィールドライブラリー水原。交通費・入場料込みの9時間コースです。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suwon-hwaseong-waujeongsa-starfield": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-waujeongsa-starfield",
      "title": "水原：華城・臥牛精舎＆スターフィールド",
      "subtitle": "ユネスコ登録の城郭、山の寺院、話題の図書館——韓国の過去・精神・現在をソウル発日帰りで一度に体験。",
      "region": "水原・龍仁",
      "duration": "9〜10時間",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "ユネスコ世界遺産",
        "世界遺産＋現代文化の日帰り旅行",
        "入場料込み"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "ソウル発の少人数制日帰りツアーで、対照的な韓国の3つの魅力を巡ります：ユネスコ世界遺産に登録された水原華城（18世紀の軍事建築）、フォトジェニックなスターフィールド水原図書館（現代の文化的名所）、龍仁の臥牛精舎（巨大な野外仏像と石鐘）。交通・入場料込みで、充実した世界遺産体験をお届けします。"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "southwest-hallasan-osulloc-aewol": {
    "catalog_card": {
      "slug": "southwest-hallasan-osulloc-aewol",
      "title": "済州島南西部：漢拏山・オソルロク・愛月・梨湖テウ",
      "subtitle": "1100高地湿地のデッキ歩道、火山性断崖、滝のトレイル、茶畑、そして愛月・梨湖テウの夕日でのフィナーレ",
      "region": "済州島南西部",
      "duration": "9時間",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "済州島初訪問者に最適",
        "済州島南西部"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "",
      "shortCardDescription": "漢拏山1100高地の湿地、火山性海岸線、天帝淵滝、オソルロクの茶畑、愛月カフェ通り、梨湖テウの夕日をつなぐ、バランスの取れた済州島南西部の1日コース。"
    },
    "price": {
      "amountLabel": "49"
    }
  }
};
