// AUTO-GENERATED by scripts/build-catalog-cards.mjs — DO NOT EDIT.
// catalog_card pages for the "en" locale only. Loaded lazily by
// staticTourCatalogCards.lazy.ts so client bundles ship one locale, not six.

import type { SlimCatalogPage } from "./catalogCards.generated";

export const PAGES: Record<string, SlimCatalogPage> = {
  "busan-cruise-shore-excursion-bus-tour": {
    "catalog_card": {
      "slug": "busan-cruise-shore-excursion-bus-tour",
      "title": "Busan Cruise Shore: Coastal Bus Tour",
      "subtitle": "8-stop Busan coastal circuit on a large coach, with cruise-terminal pickup and return planned around your ship's sail-away.",
      "region": "Busan",
      "duration": "8 hours",
      "stopsCount": 9,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Cruise excursion",
        "Large coach",
        "Pickup at port",
        "Return guaranteed"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "A large-coach Busan coastal day tour built for cruise passengers: cruise terminal pickup, 9 signature stops (Haedong Yonggungsa, UN Memorial Cemetery, Jagalchi Market, BIFF Square, Gukje Market, Gamcheon Culture Village, Songdo Beach, Yongdusan Park), and a return-before-sail-away guarantee. Budget tier — same circuit as the small-group product, larger coach."
    },
    "price": {
      "amountLabel": "58.79"
    }
  },
  "busan-gyeongju-unesco-legacy-tour-national-museum": {
    "catalog_card": {
      "slug": "busan-gyeongju-unesco-legacy-tour-national-museum",
      "title": "Busan to Gyeongju: UNESCO Heritage Day Tour",
      "subtitle": "A full-day cultural route from Busan to Gyeongju with Ahopsan Forest, Bulguksa Temple, Gyochon Village, royal tombs, National Museum or Donggung Palace, and Woljeonggyo Bridge.",
      "region": "Gyeongju (from Busan)",
      "duration": "11.5 hours",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "UNESCO",
        "Includes National Museum",
        "Small group",
        "From Busan"
      ],
      "heroImage": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "thumbnail": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "priceLabel": "From US$39 per person (was $50, 22% off)",
      "shortCardDescription": "A culture-rich Gyeongju day trip from Busan. Start with Ahopsan Forest, continue to Bulguksa Temple, walk through Gyochon Village and the House of Choi area, see Silla royal-tomb scenery around Daereungwon and Hwangnidan-gil, then finish with the National Museum or Donggung Palace option and Woljeonggyo Bridge."
    },
    "price": {
      "amountLabel": "39"
    }
  },
  "busan-outskirts-tongdosa-amethyst-yeongnam-day-tour": {
    "catalog_card": {
      "slug": "busan-outskirts-tongdosa-amethyst-yeongnam-day-tour",
      "title": "Busan Outskirts: Tongdosa + Amethyst Cave + Yeongnam Alps",
      "subtitle": "UNESCO temple, amethyst cave, ice valley cable car, and Gamcheon — Busan's outskirts in a single 11-hour coach day.",
      "region": "Busan → Yangsan → Ulsan → Miryang → Busan",
      "duration": "11 hours",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "UNESCO World Heritage",
        "Bus tour",
        "Pickup at 3 stations",
        "11-hour day"
      ],
      "heroImage": "/images/itinerary/tongdosa-iljumun.webp",
      "thumbnail": "/images/itinerary/tongdosa-iljumun.webp",
      "priceLabel": "From US$85 per person (was $93, 9% off)",
      "shortCardDescription": "An 11-hour Busan outskirts coach day tour into Yangsan (Tongdosa Temple, UNESCO World Heritage Site 2018), Ulsan (Amethyst Cave Theme Park with optional boat ride), Miryang (Yeongnam Alps Ice Valley Cable Car), and finishing at Gamcheon Culture Village in Busan. Three pickup points (Busan Station / Seomyeon / Haeundae); optional Jagalchi hop-off at the end."
    },
    "price": {
      "amountLabel": "85"
    }
  },
  "busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju": {
    "catalog_card": {
      "slug": "busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju",
      "title": "Busan: Plum & Cherry Blossom (Yangsan+Gyeongju)",
      "subtitle": "An 8.5-hour seasonal shuttle covering Tongdosa Temple (UNESCO Sansa + 350-year Jajangmae plum), Wondong Plum Blossom Village, Bulguksa Temple (UNESCO), and Bomun Lake. Operating Feb 25 – Apr 10 only.",
      "region": "Yangsan + Gyeongju (from Busan)",
      "duration": "8.5 hours",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Spring Seasonal",
        "Plum + Cherry Blossom",
        "2 UNESCO Sites",
        "Busan Pickup"
      ],
      "heroImage": "/images/itinerary/tongdosa-iljumun.webp",
      "thumbnail": "/images/itinerary/tongdosa-iljumun.webp",
      "priceLabel": "",
      "shortCardDescription": "An 8.5-hour Busan-departure dual-season shuttle covering Yangsan and Gyeongju. The default itinerary visits Tongdosa Temple (UNESCO Sansa, Korea's Three Jewel Temple, with the 350-year Jajangmae plum tree), Wondong Plum Blossom Village (Minari Samgyeopsal lunch in greenhouse pop-up restaurants), Bulguksa Temple (UNESCO World Heritage), and Bomun Lake (8 km cherry blossom loop). Wider operating window than cherry-only tours: ~Feb 25 – Apr 10 covers both plum and cherry blossom peaks. Daily route shifts emphasis based on plum vs cherry bloom status."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-private-car-charter-cruise-shore": {
    "catalog_card": {
      "slug": "busan-private-car-charter-cruise-shore",
      "title": "Busan Cruise Shore: Private Car Charter",
      "subtitle": "A private Busan shore day with cruise-port pickup, flexible sightseeing, and a route planned around your ship’s arrival and all-aboard time.",
      "region": "Busan (cruise port + downtown)",
      "duration": "8 hours",
      "stopsCount": 5,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Private Tour",
        "Customizable Route",
        "Cruise Pickup Included"
      ],
      "heroImage": "/images/tours/taejongdae/chatgpt-image-2026-5-10-12-26-45.webp",
      "thumbnail": "/images/tours/taejongdae/chatgpt-image-2026-5-10-12-26-45.webp",
      "priceLabel": "",
      "shortCardDescription": "A private Busan shore excursion for cruise guests. Choose the places that matter most — Haedong Yonggungsa, Cheongsapo, Blue Line Park, UN Memorial Cemetery, Gamcheon Culture Village, Songdo, Nampo-dong, Jagalchi Market, and more — then adjust the day with your guide around your ship schedule."
    },
    "price": {
      "amountLabel": "456.99"
    }
  },
  "busan-small-group-sightseeing-tour-cruise-passengers": {
    "catalog_card": {
      "slug": "busan-small-group-sightseeing-tour-cruise-passengers",
      "title": "Busan Cruise Shore: Small-Group Tour",
      "subtitle": "A cruise-aligned small-group Busan route with port pickup, local highlights, and return planned around your ship’s departure time.",
      "region": "Busan",
      "duration": "8 hours",
      "stopsCount": 9,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Cruise excursion",
        "Small shared van",
        "Pickup at port",
        "8-hour shore day"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "A small-group Busan shore excursion for cruise passengers, in a van capped at 12. Nine stops in an eight-hour day: Haedong Yonggungsa, the UN Memorial Cemetery, lunch at your own expense, then Jagalchi Market, BIFF Square and Gukje Market on foot, Gamcheon Culture Village, the Songdo Cloud Trails skywalk with the cable car up to Sky Park as an on-site choice, and Yongdusan Park. Pickup is at whichever cruise terminal your ship berths at, and the return is timed to your all-aboard."
    },
    "price": {
      "amountLabel": "68.95"
    }
  },
  "busan-small-group-yonggungsa-skycapsule-gamcheon-tour": {
    "catalog_card": {
      "slug": "busan-small-group-yonggungsa-skycapsule-gamcheon-tour",
      "title": "Busan Small-Group: Sea Temple, Sky Capsule & Culture Villages",
      "subtitle": "Small-group day tour of Busan's coastal icons and hillside villages — Haedong Yonggungsa seaside temple, the Cheongsapo Daritdol glass skywalk, the Blueline Park Sky Capsule ride (ticket optional at booking), Gamcheon Culture Village, and the quiet Dakbatgol mural village with its wish-stairs monorail.",
      "region": "Busan",
      "duration": "≈ 10 hours",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small group",
        "Busan",
        "Sky Capsule",
        "Coastal",
        "Culture villages"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunrise-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunrise-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "A small-group Busan day built around the coast and the hillside villages: Haedong Yonggungsa seaside temple in its quiet morning window, the free glass-floor Daritdol Observatory at Cheongsapo, the Blueline Park Sky Capsule ride from Cheongsapo to Mipo (ticket included or excluded — choose at booking), lunch, Gamcheon Culture Village, and the little-known Dakbatgol mural village where a free monorail glides up the 'wish stairs'. Every anchor except the optional capsule is free admission."
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "busan-spring-cherry-blossom-gyeongju-highlights-day-tour": {
    "catalog_card": {
      "slug": "busan-spring-cherry-blossom-gyeongju-highlights-day-tour",
      "title": "Busan to Gyeongju: Cherry Blossom Tour",
      "subtitle": "An 8.5-hour seasonal shuttle from Busan to Gyeongju's biggest cherry blossom spots — Bomun Lake, Daereungwon, Bulguksa Temple. Operating Mar 28 – Apr 10 only.",
      "region": "Gyeongju (from Busan)",
      "duration": "8.5 hours",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Spring Seasonal",
        "Cherry Blossom Tour",
        "UNESCO Sites",
        "Busan Pickup"
      ],
      "heroImage": "/images/itinerary/bomun-lake-cherry-blossom-promenade.webp",
      "thumbnail": "/images/itinerary/bomun-lake-cherry-blossom-promenade.webp",
      "priceLabel": "",
      "shortCardDescription": "An 8.5-hour Busan-departure shuttle tour to Gyeongju's biggest spring cherry blossom spots. The default route covers Bomun Lake (8 km of cherry tree-lined lakeside walking), the Cheomseongdae + Daereungwon historic core (UNESCO Gyeongju Historic Areas), and Bulguksa Temple (UNESCO World Heritage with mid-April yaezakura double cherry blossom). 2–3 stops are confirmed each morning based on the day's bloom report. Tour operates Mar 28 to Apr 10 only — full refund if bloom is materially delayed or finished."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-top-attractions-day-tour": {
    "catalog_card": {
      "slug": "busan-top-attractions-day-tour",
      "title": "Busan Top Attractions Day Tour",
      "subtitle": "A 9.5-hour Busan highlights route with Haedong Yonggungsa Temple, Cheongsapo, Haeundae Blue Line Park area, UN Memorial Cemetery, Gamcheon Culture Village, and Jagalchi Market.",
      "region": "Busan",
      "duration": "10.5 hours",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small group",
        "First-time friendly",
        "Busan classic",
        "Year-round"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "A balanced Busan city tour for first-time visitors: seaside temple, Cheongsapo coastal viewpoint, optional Blue Line Park/Sky Capsule area, Korean War memorial history, colorful Gamcheon Culture Village, and a market-area finish near Jagalchi/Nampo-dong."
    },
    "price": {
      "amountLabel": "34"
    }
  },
  "east-signature-nature-core": {
    "catalog_card": {
      "slug": "east-signature-nature-core",
      "title": "East Jeju: Volcano, Coast & Folk Village",
      "subtitle": "From Jeju Stone Park to Seongsan Ilchulbong, follow East Jeju’s most balanced first-time route.",
      "region": "East Jeju",
      "duration": "8 hours",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small group",
        "First-Time Friendly",
        "East Jeju Signature"
      ],
      "heroImage": "/images/tours/jeju-stone-park/kakaotalk-20260510-230028438-19.webp",
      "thumbnail": "/images/tours/jeju-stone-park/kakaotalk-20260510-230028438-19.webp",
      "priceLabel": "From US$59 per person (was $69, 14% off)",
      "shortCardDescription": "An easy-to-follow East Jeju day route that starts with stone culture and volcanic context, moves through the coast and Seongsan Ilchulbong, and finishes with Ilchulland and Seongeup Folk Village for a more complete day."
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "from-busan-gyeongju-ancient-capital-day-tour": {
    "catalog_card": {
      "slug": "from-busan-gyeongju-ancient-capital-day-tour",
      "title": "Busan to Gyeongju: Ancient Capital",
      "subtitle": "Small-group mini-van · English-speaking guide — Ahopsan Bamboo Forest, Bulguksa (UNESCO), Gyochon Hanok Village + Choi Family House + Woljeonggyo, Daereungwon + Hwangnidan-gil, and Gyeongju National Museum (Donggung & Wolji night view in winter), all in one day.",
      "region": "Gyeongju (from Busan)",
      "duration": "11.5 hours",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small group",
        "Calmer pace",
        "From Busan",
        "Winter night view"
      ],
      "heroImage": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "thumbnail": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "priceLabel": "From US$39 per person (was $50, 22% off)",
      "shortCardDescription": "A small-group Gyeongju day tour leaving from three Busan subway stations. The afternoon is walked with the van parked — Choi Family House to Woljeonggyo, Daereungwon to Hwangnidan-gil. It ends at Gyeongju National Museum, or at the Donggung & Wolji night view in winter."
    },
    "price": {
      "amountLabel": "39"
    }
  },
  "from-incheon-seoul-day-tour-cruise-guests": {
    "catalog_card": {
      "slug": "from-incheon-seoul-day-tour-cruise-guests",
      "title": "Incheon to Seoul: Cruise Day Tour",
      "subtitle": "Seoul's central heritage, hanok, market, and crafts circuit from your Incheon cruise terminal.",
      "region": "Seoul (from Incheon cruise terminal)",
      "duration": "9 hours",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Cruise excursion",
        "Small shared van",
        "Pickup at Incheon port",
        "9-hour window"
      ],
      "heroImage": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "thumbnail": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "priceLabel": "From US$69 per person (was $76, 9% off)",
      "shortCardDescription": "Shared-van day tour from Incheon Cruise Terminal hitting Seoul's headline central-city stops in a single 9-hour window: Gyeongbokgung Palace (or Changdeokgung on Tuesdays), Bukchon Hanok Village, lunch at Gwangjang Market (the city's most-photographed streetfood alley), and Insadong cultural street. Pickup calibrated to your specific ship's disembarkation; certified English/Chinese-speaking guide; ≈75 min return drive built in."
    },
    "price": {
      "amountLabel": "69"
    }
  },
  "incheon-seoul-private-car-shore-excursion-cruise": {
    "catalog_card": {
      "slug": "incheon-seoul-private-car-shore-excursion-cruise",
      "title": "Incheon to Seoul: Cruise Private Car",
      "subtitle": "Private car charter for cruise passengers — gangway pickup at Incheon, fully customizable Seoul day, terminal drop-off with 60-minute sailaway buffer.",
      "region": "Seoul (from Incheon cruise terminal)",
      "duration": "8 hours",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Private",
        "Cruise",
        "Shore excursion",
        "Seoul highlights",
        "Customizable",
        "Guaranteed return"
      ],
      "heroImage": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "thumbnail": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "priceLabel": "",
      "shortCardDescription": "An 8-hour private car charter built around your ship's all-aboard time, not a fixed schedule. Gangway pickup at Incheon Cruise Terminal, English-speaking driver-guide, and a customizable route through Gyeongbokgung Palace, Bukchon Hanok Village + Insadong, lunch of your choice, N Seoul Tower, and Myeongdong or Jogyesa Temple. The driver-guide holds a 60-minute traffic buffer before sailaway so you never miss the ship."
    },
    "price": {
      "amountLabel": "424"
    }
  },
  "jeju-cherry-blossom-tour-east-route": {
    "catalog_card": {
      "slug": "jeju-cherry-blossom-tour-east-route",
      "title": "Jeju East: Cherry Blossom Tour",
      "subtitle": "Blossom streets to lava tube to sunrise peak.",
      "region": "East Jeju",
      "duration": "8 hours",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Spring only",
        "Cherry blossom season",
        "East Jeju"
      ],
      "heroImage": "/images/tours/ilchulland/chatgpt-image-2026-5-8-07-45-52.webp",
      "thumbnail": "/images/tours/ilchulland/chatgpt-image-2026-5-8-07-45-52.webp",
      "priceLabel": "From US$59 per person (was $69, 14% off)",
      "shortCardDescription": "Spring-only east Jeju route through cherry blossom streets, the 10km canola road, a lava tube cave, and the iconic Seongsan crater."
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "jeju-cruise-shore-excursion-bus-tour": {
    "catalog_card": {
      "slug": "jeju-cruise-shore-excursion-bus-tour",
      "title": "Jeju Cruise Shore: Coach Tour",
      "subtitle": "Port-based cruise day tour with Jeju and Gangjeong route options",
      "region": "Jeju (port-dependent)",
      "duration": "8 hours",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Cruise excursion",
        "Port-based routing",
        "Budget cruise",
        "Large coach"
      ],
      "heroImage": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "thumbnail": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "priceLabel": "",
      "shortCardDescription": "A bus tour (large coach) cruise shore excursion that adapts the route to your cruise port. Jeju Port (north) runs an east-coast UNESCO route via Seongsan Ilchulbong; Gangjeong Port (south) runs a Hallasan 1100 + south-coast geology + Olle Market route. Both return to the cruise terminal with comfortable buffer."
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "jeju-cruise-shore-excursion-small-group-tour": {
    "catalog_card": {
      "slug": "jeju-cruise-shore-excursion-small-group-tour",
      "title": "Jeju Cruise Shore: Small-Group Tour",
      "subtitle": "Port-based cruise day tour with Jeju and Gangjeong route options",
      "region": "Jeju (port-dependent)",
      "duration": "8 hours",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Cruise excursion",
        "Port-based routing",
        "Premium cruise",
        "Small group"
      ],
      "heroImage": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "thumbnail": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "priceLabel": "",
      "shortCardDescription": "A small group tour cruise shore excursion that adapts the route to your cruise port. Jeju Port (north) runs an east-coast UNESCO route via Seongsan Ilchulbong; Gangjeong Port (south) runs a Hallasan 1100 + south-coast geology + Olle Market route. Both return to the cruise terminal with comfortable buffer."
    },
    "price": {
      "amountLabel": "77"
    }
  },
  "jeju-eastern-unesco-spots-day-tour": {
    "catalog_card": {
      "slug": "jeju-eastern-unesco-spots-day-tour",
      "title": "Jeju East UNESCO Day Tour",
      "subtitle": "Small-group minibus with English/Chinese guide — Manjanggul (UNESCO) in its quiet opening hour, Seongeup Folk Village, Seongsan Ilchulbong (UNESCO), the haenyeo diving performance, and a Hamdeok Beach finale in a 9-hour eastern route.",
      "region": "Eastern Jeju",
      "duration": "9 hours",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small group",
        "Jeju",
        "East Jeju",
        "UNESCO",
        "Value priced",
        "All admissions included"
      ],
      "heroImage": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "thumbnail": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "priceLabel": "",
      "shortCardDescription": "Loop eastern Jeju's UNESCO sights in a 9-hour small group — now routed cave-first: Manjanggul right after opening (the quietest hour in the lava tube), Seongeup Folk Village, Seongsan Ilchulbong and the haenyeo diving performance (Haenyeo Museum if canceled), then a late-afternoon finale at Hamdeok Seoubong Beach. Two UNESCO World Natural Heritage sites inscribed together in 2007, all admissions included, certified English/Chinese-speaking guide."
    },
    "price": {
      "amountLabel": "49"
    }
  },
  "jeju-grand-highlights-loop": {
    "catalog_card": {
      "slug": "jeju-grand-highlights-loop",
      "title": "Jeju Grand Highlights Loop",
      "subtitle": "Jeju's three UNESCO sites, a live haenyeo show, sea-cliffs and an ocean waterfall — the island's absolute best in one day.",
      "region": "Jeju Full-Island Route",
      "duration": "10–10.5 hours",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small group",
        "3 UNESCO Sites",
        "Best for One-Day Visitors"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "",
      "shortCardDescription": "A high-intensity full-island route linking three UNESCO World Heritage sites — Hallasan, Seongsan Ilchulbong and Manjanggul lava tube — with a living haenyeo free-diving show, the Jusangjeolli columnar cliffs and the ocean-falling Jeongbang Waterfall. Jeju's signature highlights, concentrated into a single day."
    },
    "price": {
      "amountLabel": "80"
    }
  },
  "jeju-hydrangea-festival-tour-east-route": {
    "catalog_card": {
      "slug": "jeju-hydrangea-festival-tour-east-route",
      "title": "Jeju Hydrangea Festival: East",
      "subtitle": "Hydrangea festivals + UNESCO east Jeju, summer-only small-group day.",
      "region": "Eastern Jeju",
      "duration": "9 hours",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small group",
        "Jeju",
        "Hydrangea",
        "Seasonal",
        "Summer",
        "UNESCO",
        "Festival"
      ],
      "heroImage": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "thumbnail": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "priceLabel": "",
      "shortCardDescription": "A seasonal small-group day-tour of east Jeju built around the island's hydrangea festivals (late May to mid-July, peak mid-June) at Hueree Natural Park and Ilchul Land. The route also covers two UNESCO World Heritage sites — Seongsan Ilchulbong (Sunrise Peak) and Seongeup Folk Village — plus Hamdeok Beach and the Micheon Cave lava tube. Hotel pickup in Jeju City, English/Chinese-speaking licensed guide-driver."
    },
    "price": {
      "amountLabel": "64"
    }
  },
  "jeju-hydrangea-festival-tour-southwest-route": {
    "catalog_card": {
      "slug": "jeju-hydrangea-festival-tour-southwest-route",
      "title": "Jeju Hydrangea Festival: Southwest",
      "subtitle": "Beach to columnar cliff to hydrangea tunnel.",
      "region": "Southwest Jeju",
      "duration": "9 hours",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Summer Only",
        "Hydrangea Season",
        "Southwest Jeju"
      ],
      "heroImage": "/images/tours/hyeopjae-beach/kakaotalk-20260510-230009595-01.webp",
      "thumbnail": "/images/tours/hyeopjae-beach/kakaotalk-20260510-230009595-01.webp",
      "priceLabel": "",
      "shortCardDescription": "Summer-only southwest Jeju route — emerald beach, hydrangea festival gardens, UNESCO columnar cliff, three-tier waterfall, hydrangea tunnel, and tea fields."
    },
    "price": {
      "amountLabel": "64"
    }
  },
  "jeju-island-private-car-charter-tour": {
    "catalog_card": {
      "slug": "jeju-island-private-car-charter-tour",
      "title": "Jeju Private Car Charter",
      "subtitle": "Design your own Jeju day with a licensed driver-guide and an air-conditioned private vehicle.",
      "region": "Jeju (East, West, or South)",
      "duration": "9 hours",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Private Tour",
        "Customizable Route",
        "Hotel Pickup Included"
      ],
      "heroImage": "/images/tours/jeju-private/jeju-private-thumbnail-carnival-coast.webp",
      "thumbnail": "/images/tours/jeju-private/jeju-private-thumbnail-carnival-coast.webp",
      "priceLabel": "",
      "shortCardDescription": "A 9-hour private car charter for Jeju with a licensed driver-guide. Three recommended routes (East, West, South) cover the island's most-loved sights, or build your own from UNESCO landmarks, K-drama spots, beaches, tea fields, and traditional markets. Hotel pickup is included anywhere on the island."
    },
    "price": {
      "amountLabel": "254"
    }
  },
  "jeju-southern-top-unesco-spots-tour": {
    "catalog_card": {
      "slug": "jeju-southern-top-unesco-spots-tour",
      "title": "Jeju Southern (Seogwipo) Signature Day Tour",
      "subtitle": "South Jeju Seogwipo coastal loop — Jeongbang Falls, Oedolgae Olle Trail, Yakcheonsa Temple, Hallasan.",
      "region": "Southern Jeju",
      "duration": "9 hours",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small group",
        "Jeju",
        "South Jeju",
        "Seogwipo",
        "Value priced",
        "No shopping"
      ],
      "heroImage": "/images/tours/jeongbang-falls/kakaotalk-20260510-230028438-15.webp",
      "thumbnail": "/images/tours/jeongbang-falls/kakaotalk-20260510-230028438-15.webp",
      "priceLabel": "",
      "shortCardDescription": "A small-group day tour through southern Jeju's signature Seogwipo stops — Jeongbang Falls, Asia's only waterfall that drops directly into the sea, the Oedolgae rock pinnacle with a coastal walk on Olle Route 7, East Asia's largest temple Yakcheonsa, the O'sulloc Tea Museum, and the Hallasan Eoseungsaengak Trail. Four pickup points across Jeju City and the airport, certified English/Chinese-speaking guide, free admission at almost every stop except Jeongbang Falls, no shopping pressure."
    },
    "price": {
      "amountLabel": "49"
    }
  },
  "jeju-west-south-full-day-authentic-tour": {
    "catalog_card": {
      "slug": "jeju-west-south-full-day-authentic-tour",
      "title": "Jeju West & South: Authentic Day Tour",
      "subtitle": "Hallasan UNESCO highland, Jusangjeolli Cliff, Songaksan rim, Cheonjeyeon Falls, O'sulloc tea, and Hyeopjae Beach — Jeju's west and south in one balanced day.",
      "region": "West & South Jeju",
      "duration": "9 hours",
      "stopsCount": 9,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small Group",
        "Jeju",
        "West & South Jeju",
        "UNESCO",
        "Café Culture",
        "Coastal"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "From US$59 per person (was $69, 14% off)",
      "shortCardDescription": "A small-group day tour pairing Jeju's western and southern coasts in a single loop — Hallasan's 1100 Altitude Wetland (UNESCO), the hexagonal Jusangjeolli Cliff, Songaksan's panoramic viewpoint, Cheonjeyeon Waterfall, O'sulloc Tea Museum, and the Hyeopjae Beach café strip on the west coast. A lifestyle-oriented framing — 'volcanic landscapes meet dramatic coastlines and trendy seaside cafés.'"
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "jeju-winter-southwest-tangerine-snow-camellia-tour": {
    "catalog_card": {
      "slug": "jeju-winter-southwest-tangerine-snow-camellia-tour",
      "title": "Jeju Winter: Tangerine, Snow & Camellia",
      "subtitle": "Snow on Hallasan, peak-bloom Camellia Hill, hands-on tangerine picking, plus Jusangjeolli and Cheonjeyeon — Jeju's winter southwest in 9 hours.",
      "region": "Southwest Jeju",
      "duration": "9 hours",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small Group",
        "Jeju",
        "Winter",
        "Seasonal",
        "Tangerine",
        "Camellia",
        "Snow"
      ],
      "heroImage": "/images/tours/jeju-tangerine-farm/photo-001.webp",
      "thumbnail": "/images/tours/jeju-tangerine-farm/photo-001.webp",
      "priceLabel": "From US$59 per person (was $69, 14% off)",
      "shortCardDescription": "A seasonal winter day-tour of southwest Jeju (December through February) built around the three things only Jeju does well in winter: snow on Hallasan's slopes, red camellias in full bloom at Camellia Hill, and pick-your-own Jeju tangerines (gyul) at a working orchard. The route also covers Cheonjeyeon Falls, Jusangjeolli columnar cliffs, and the Osulloc Tea Museum. Hotel pickup in Jeju City, English/Chinese-speaking licensed guide."
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "pocheon-sanjeong-lake-herb-island-art-valley": {
    "catalog_card": {
      "slug": "pocheon-sanjeong-lake-herb-island-art-valley",
      "title": "Pocheon & Yeoncheon: Lake, Waterfall & Quarry Art Valley",
      "subtitle": "A mountain-ringed lake walk, an 18 m waterfall over basalt columns, and an emerald quarry lake — two UNESCO Global Geopark geosites in one unhurried day from Seoul.",
      "region": "Pocheon & Yeoncheon (Seoul Day Trip)",
      "duration": "10 hours",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Seoul day trip",
        "Mon · Thu · Sat",
        "UNESCO Geopark",
        "Waterfall",
        "Lake walk",
        "Small group"
      ],
      "heroImage": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "thumbnail": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "priceLabel": "",
      "shortCardDescription": "A calmer Seoul day-trip built on real geology. Walk the flat 3.2 km loop around Sanjeong Lake under Myeongseongsan, eat Pocheon's own Idong galbi, then cross an 80 m suspension bridge to face Jaein Falls as it drops 18 m over basalt columns, and finish inside Pocheon Art Valley's granite quarry, where spring water has filled the pit into the emerald Cheonjuho. Jaein Falls and Art Valley are both geosites of the Hantangang UNESCO Global Geopark — the same landscape seen from its two opposite halves. Departs Mondays, Thursdays and Saturdays."
    },
    "price": {
      "amountLabel": "54"
    }
  },
  "seoul-dmz-private-3rd-tunnel-suspension-bridge": {
    "catalog_card": {
      "slug": "seoul-dmz-private-3rd-tunnel-suspension-bridge",
      "title": "Seoul DMZ Private: 3rd Tunnel & Bridge",
      "subtitle": "Korea's divided border and a 220-meter mountain suspension bridge in one private day from Seoul.",
      "region": "Paju (Seoul Day Trip)",
      "duration": "8–9 hours",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Private Tour",
        "DMZ + Suspension Bridge",
        "Hotel Pickup Included"
      ],
      "heroImage": "/images/tours/imjingak/chatgpt-image-2026-5-10-10-40-40.webp",
      "thumbnail": "/images/tours/imjingak/chatgpt-image-2026-5-10-10-40-40.webp",
      "priceLabel": "From US$419 per vehicle (1–3 pax)",
      "shortCardDescription": "A private day-trip pairing Korea's heaviest historical site with one of its most photogenic mountain bridges. Morning at the DMZ (Imjingak Peace Park, 3rd Infiltration Tunnel, Dora Observatory), then an afternoon walk across the 220-meter Gamaksan Red Suspension Bridge. Passport required for the DMZ portion."
    },
    "price": {
      "amountLabel": "419"
    }
  },
  "seoul-gapyeong-nami-morning-calm-petite-france-day-tour": {
    "catalog_card": {
      "slug": "seoul-gapyeong-nami-morning-calm-petite-france-day-tour",
      "title": "Gapyeong Day Tour from Seoul: Nami Island, Garden of Morning Calm & Petite France",
      "subtitle": "The Gapyeong trio in one coach day — no mountain hike, three admissions included",
      "region": "Seoul → Gyeonggi-do (Gapyeong)",
      "duration": "11.5 hours",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Day trip from Seoul",
        "Gapyeong",
        "Join-in group",
        "K-drama",
        "Gardens"
      ],
      "heroImage": "/images/tours/nami-island/nami-metasequoia-sunset-lake.webp",
      "thumbnail": "/images/tours/nami-island/nami-metasequoia-sunset-lake.webp",
      "priceLabel": "",
      "shortCardDescription": "Seoul's easiest countryside day: Nami Island's metasequoia avenue, a 330,000 m² themed arboretum, and a Little Prince village — all three admissions included, back in Seoul by 19:00."
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "seoul-private-nami-morning-calm-petite-france": {
    "catalog_card": {
      "slug": "seoul-private-nami-morning-calm-petite-france",
      "title": "Seoul Private: Nami, Morning Calm & Petite France",
      "subtitle": "Three of Korea's most photographed day-trip landmarks, in one private vehicle without the bus-tour pace.",
      "region": "Gapyeong (Seoul Day Trip)",
      "duration": "9–10 hours",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Private Tour",
        "K-Drama Filming Locations",
        "Couples & Families"
      ],
      "heroImage": "/images/tours/nami-island/kakaotalk-20260510-222949305-04.webp",
      "thumbnail": "/images/tours/nami-island/kakaotalk-20260510-222949305-04.webp",
      "priceLabel": "",
      "shortCardDescription": "A private day trip from Seoul covering Nami Island's tree-lined ferry experience, the Garden of Morning Calm's themed garden walks, and the colorful Le Petit Prince village of Petite France. Hotel pickup, private vehicle, and a relaxed pace make this the comfort-led version of a classic Gapyeong loop."
    },
    "price": {
      "amountLabel": "194"
    }
  },
  "seoul-seoraksan-naksansa-temple-naksan-beach-day-trip": {
    "catalog_card": {
      "slug": "seoul-seoraksan-naksansa-temple-naksan-beach-day-trip",
      "title": "Gangwon-do Day Tour from Seoul: Seoraksan + Naksansa Temple + Naksan Beach",
      "subtitle": "Seoraksan's granite peaks, a thousand-year seaside temple, and a pine-backed East Sea beach in a single 12-hour Seoul day trip.",
      "region": "Seoul → Gangwon (Seoraksan & Yangyang)",
      "duration": "12 hours",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Day trip from Seoul",
        "Air-conditioned coach",
        "Mondays & Thursdays",
        "12-hour day"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "From US$53 per person (was $58, 9% off)",
      "shortCardDescription": "A 12-hour coach day trip from Seoul to the East Sea coast: hike Seoraksan National Park, visit the cliffside Naksansa Temple, and walk pine-backed Naksan Beach. Departs Mondays and Thursdays with an English-speaking guide and round-trip transfers from Hongik or Myeongdong."
    },
    "price": {
      "amountLabel": "53"
    }
  },
  "seoul-seoraksan-nami-island-morning-calm-day-tour": {
    "catalog_card": {
      "slug": "seoul-seoraksan-nami-island-morning-calm-day-tour",
      "title": "Seoul: Seoraksan + Nami + Morning Calm",
      "subtitle": "Seoraksan mountain, Nami's tree-lined island, and Morning Calm's themed garden in a single 13-hour Seoul day trip.",
      "region": "Seoul → Gangwon → Gyeonggi",
      "duration": "13 hours",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Day trip from Seoul",
        "Large coach",
        "All admissions included",
        "13-hour day"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "US$71 per person",
      "shortCardDescription": "A 13-hour coach day tour from Seoul covering Korea's three most-photographed day-trip stops: Seoraksan National Park (Korea's first UNESCO Biosphere Reserve), Nami Island (Winter Sonata's Metasequoia Lane), and the Garden of Morning Calm (Korea's signature private arboretum with 5,000 plant species). All admissions included; English-speaking guide; pickup at Hongik University Station or Myeongdong Station."
    },
    "price": {
      "amountLabel": "71"
    }
  },
  "seoul-seoraksan-national-park-sokcho-beach-day-trip": {
    "catalog_card": {
      "slug": "seoul-seoraksan-national-park-sokcho-beach-day-trip",
      "title": "Seoraksan & Sokcho Beach Day Trip",
      "subtitle": "A small-group day-trip from Seoul to Korea's most-loved national park and the East Sea coastal city of Sokcho.",
      "region": "Seoraksan, Gangwon-do",
      "duration": "12 hours",
      "stopsCount": 5,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small Group",
        "Nature",
        "Scenic",
        "Beach",
        "Seafood Market",
        "Autumn Foliage",
        "Day Trip"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "From US$49 per person (was $57, 14% off)",
      "shortCardDescription": "A small-group day-trip from Seoul to Korea's most-loved national park and the East Sea coastal city of Sokcho. The route pairs Seoraksan's granite peaks, valleys, and Buddhist heritage with the seafood market and beach of Sokcho — a mountain-and-ocean combination only the east coast offers. 12 hours with English-speaking guide and round-trip transport."
    },
    "price": {
      "amountLabel": "49"
    }
  },
  "seoul-suburbs-private-chartered-car-10hr": {
    "catalog_card": {
      "slug": "seoul-suburbs-private-chartered-car-10hr",
      "title": "Seoul Private Car Charter",
      "subtitle": "Design your own day around Seoul or its suburbs with a private licensed driver-guide.",
      "region": "Seoul & Suburbs",
      "duration": "10 hours",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Private Tour",
        "Fully Customizable",
        "Free Seoul Hotel Pickup"
      ],
      "heroImage": "/images/tours/seoul-private-charter/seoul-private-carnival-han-river-night.webp",
      "thumbnail": "/images/tours/seoul-private-charter/seoul-private-carnival-han-river-night.webp",
      "priceLabel": "",
      "shortCardDescription": "A premium 10-hour private car charter that lets you build your own Seoul-area day. Choose one of three recommended routes—Nami Island + Morning Calm + Petite France + Gangchon Railbike, DMZ + Paju Outlet, or Everland + Korean Folk Village—or send your own itinerary. Free hotel pickup is included for Seoul downtown stays."
    },
    "price": {
      "amountLabel": "184"
    }
  },
  "seoul-suwon-hwaseong-folk-village-starfield-library": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-folk-village-starfield-library",
      "title": "Suwon: Hwaseong, Folk Village & Starfield",
      "subtitle": "A small-group cultural day-trip from Seoul to Gyeonggi Province covering four contrasting sides of Korean heritage and modern life: the UNESCO-listed…",
      "region": "Gyeonggi-do (south of Seoul)",
      "duration": "10 hours",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small Group",
        "Culture",
        "UNESCO",
        "Heritage",
        "Library",
        "Folk Village",
        "Day Trip"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "From US$60 per person (was $66, 9% off)",
      "shortCardDescription": "A small-group cultural day-trip from Seoul to Gyeonggi Province covering four contrasting sides of Korean heritage and modern life: the UNESCO-listed Suwon Hwaseong Fortress (18th-century walls and gates), the restored Hwaseong Haenggung Palace with its Joseon-era reenactments, the immersive open-air Korean Folk Village in Yongin, and the dramatic four-floor Starfield Library Suwon. 10 hours with included transport and admissions."
    },
    "price": {
      "amountLabel": "60"
    }
  },
  "seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library",
      "title": "Suwon: Hwaseong, Gwangmyeong Cave & Starfield",
      "subtitle": "A small-group cultural day-trip from Seoul covering four contrasting sides of Gyeonggi Province: the UNESCO-listed Suwon Hwaseong Fortress with its…",
      "region": "Gyeonggi-do (south of Seoul)",
      "duration": "9 hours",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Small Group",
        "Culture",
        "UNESCO",
        "Cave",
        "Library",
        "Shopping",
        "Day Trip"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "From US$53 per person (was $59, 10% off)",
      "shortCardDescription": "A small-group cultural day-trip from Seoul covering three contrasting sides of Gyeonggi Province: the UNESCO-listed Suwon Hwaseong Fortress with its 18th-century walls and Haenggung Palace, the dramatic LED-lit underground theme park inside Gwangmyeong Cave (a former Japanese-era gold mine), the four-floor Starfield Library Suwon. 9 hours with included transport and admissions."
    },
    "price": {
      "amountLabel": "53"
    }
  },
  "seoul-suwon-hwaseong-waujeongsa-starfield": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-waujeongsa-starfield",
      "title": "Suwon: Hwaseong, Waujeongsa & Starfield",
      "subtitle": "UNESCO fortress, mountain temple, and viral library—Korea's past, spirit, and present in one Seoul day-trip.",
      "region": "Suwon & Yongin",
      "duration": "9–10 hours",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "UNESCO Heritage",
        "Heritage + Modern Day Trip",
        "Admission Included"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "From US$51 per person (was $54, 6% off)",
      "shortCardDescription": "A small-group day-trip from Seoul covering three contrasting sides of Korea: the UNESCO-listed Suwon Hwaseong Fortress (18th-century military architecture), the photogenic Starfield Suwon Library (contemporary cultural icon), and Waujeongsa Temple in Yongin (giant outdoor Buddha and stone bell). Strong heritage value with included transport and admission."
    },
    "price": {
      "amountLabel": "51"
    }
  },
  "seoul-winter-seoraksan-nami-eobi-ice-valley-day-tour": {
    "catalog_card": {
      "slug": "seoul-winter-seoraksan-nami-eobi-ice-valley-day-tour",
      "title": "Winter Special from Seoul: Seoraksan, Nami Island & Eobi Valley Ice Wall",
      "subtitle": "A winter-only coach day — snow on Korea's most famous peak, Nami under frost, and a village-built ice wall",
      "region": "Seoul → Gangwon-do → Gyeonggi-do (Gapyeong)",
      "duration": "13.5 hours",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Winter only",
        "Seasonal",
        "Day trip from Seoul",
        "Seoraksan",
        "Ice wall"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "",
      "shortCardDescription": "Runs in deep winter only: Seoraksan under snow, Nami Island's frosted tree avenues, and the 25-metre ice wall that Gapyeong villagers grow on a valley rock face each January."
    },
    "price": {
      "amountLabel": "69"
    }
  },
  "southwest-hallasan-osulloc-aewol": {
    "catalog_card": {
      "slug": "southwest-hallasan-osulloc-aewol",
      "title": "Southwest Jeju: Hallasan, O'Sulloc, Aewol & Iho Tewoo",
      "subtitle": "The 1100 Highland wetland boardwalk, volcanic cliffs, a waterfall trail, tea fields, and an Aewol–Iho Tewoo sunset finish",
      "region": "Jeju Southwest",
      "duration": "9 hours",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Great for First-Time Jeju Visitors",
        "Jeju Southwest"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "",
      "shortCardDescription": "A well-balanced Jeju southwest day route linking the Hallasan 1100 Highland wetland, volcanic coastline, Cheonjeyeon Waterfall, O'Sulloc tea fields, Aewol Cafe Street, and the Iho Tewoo sunset."
    },
    "price": {
      "amountLabel": "49"
    }
  }
};
