// AUTO-GENERATED by scripts/build-catalog-cards.mjs — DO NOT EDIT.
// catalog_card pages for the "ko" locale only. Loaded lazily by
// staticTourCatalogCards.lazy.ts so client bundles ship one locale, not six.

import type { SlimCatalogPage } from "./catalogCards.generated";

export const PAGES: Record<string, SlimCatalogPage> = {
  "busan-cruise-shore-excursion-bus-tour": {
    "catalog_card": {
      "slug": "busan-cruise-shore-excursion-bus-tour",
      "title": "부산 크루즈 기항지: 해안 버스 투어",
      "subtitle": "대형 버스로 떠나는 부산 해안 8개 코스 순환 투어, 크루즈 터미널 픽업과 선박 출항 시간에 맞춘 귀환 일정 포함.",
      "region": "부산",
      "duration": "9시간",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "크루즈 기항지 투어",
        "대형 버스",
        "항구 픽업",
        "귀환 보장"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "1인 US$49부터 (정가 $55, 11% 할인)",
      "shortCardDescription": "크루즈 승객을 위해 설계된 대형 버스 부산 해안 당일 투어: 크루즈 터미널 픽업, 8개 대표 명소(해동용궁사, UN기념공원, 자갈치시장, BIFF광장, 국제시장, 감천문화마을, 송도해수욕장, 용두산공원) 방문, 출항 전 귀환 보장. 합리적인 가격대 — 소규모 그룹 상품과 동일한 코스, 대형 버스 이용."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-gyeongju-unesco-legacy-tour-national-museum": {
    "catalog_card": {
      "slug": "busan-gyeongju-unesco-legacy-tour-national-museum",
      "title": "부산 → 경주 유네스코 유산 투어",
      "subtitle": "부산 출발 하루로 만나는 한국의 천년 수도 — 유네스코 사찰, 국립박물관, 한옥마을, 그리고 교량 야경까지",
      "region": "경주 (부산 출발)",
      "duration": "11.5시간",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "UNESCO",
        "국립박물관 포함",
        "소규모 그룹",
        "부산 출발"
      ],
      "heroImage": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "thumbnail": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "priceLabel": "1인 US$39 (정가 $50, 22% 할인)",
      "shortCardDescription": "신라왕국의 수도로 992년(기원전 57년~서기 935년)간 번성했으며 한국에서 유네스코 세계유산이 가장 밀집된 도시 경주로 떠나는 소규모 부산 출발 당일 투어. 코스: 아홉산 대나무 숲 → 불국사 (유네스코) → 경주 쌈밥 점심 → 국립경주박물관 → 교촌 한옥마을 → 월정교. 영어·중국어 구사 공인 가이드, 미니밴, 불국사 및 박물관 입장료 무료."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-outskirts-tongdosa-amethyst-yeongnam-day-tour": {
    "catalog_card": {
      "slug": "busan-outskirts-tongdosa-amethyst-yeongnam-day-tour",
      "title": "부산 외곽: 통도사 + 자수정 동굴 + 영남 알프스",
      "subtitle": "유네스코 사찰, 자수정 동굴, 얼음골 케이블카, 감천 — 단 하루 11시간으로 떠나는 부산 외곽 투어.",
      "region": "부산 → 양산 → 울산 → 밀양 → 부산",
      "duration": "11시간",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "유네스코 세계문화유산",
        "버스 투어",
        "3개 정류장 픽업",
        "11시간 일정"
      ],
      "heroImage": "/images/itinerary/tongdosa-iljumun.webp",
      "thumbnail": "/images/itinerary/tongdosa-iljumun.webp",
      "priceLabel": "",
      "shortCardDescription": "양산(통도사, 2018 유네스코 세계문화유산), 울산(자수정 동굴 테마파크, 선택 보트 탑승), 밀양(영남 알프스 얼음골 케이블카)을 거쳐 부산 감천문화마을에서 마무리하는 11시간 부산 외곽 코치 당일 투어. 픽업 3개소(부산역 / 서면 / 해운대) 운영; 마지막에 자갈치 선택 하차 가능."
    },
    "price": {
      "amountLabel": "85"
    }
  },
  "busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju": {
    "catalog_card": {
      "slug": "busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju",
      "title": "부산: 매화 & 벚꽃 (양산+경주)",
      "subtitle": "통도사(유네스코 산사 + 수령 350년 자장매), 원동 매화마을, 불국사(유네스코), 보문호를 포함하는 8.5시간 시즌 셔틀 투어. 2월 25일 ~ 4월 10일만 운행.",
      "region": "양산 + 경주 (부산 출발)",
      "duration": "8.5시간",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "봄 시즌 한정",
        "매화 + 벚꽃",
        "유네스코 등재 2곳",
        "부산 픽업"
      ],
      "heroImage": "/images/itinerary/tongdosa-iljumun.webp",
      "thumbnail": "/images/itinerary/tongdosa-iljumun.webp",
      "priceLabel": "",
      "shortCardDescription": "양산과 경주를 아우르는 8.5시간 부산 출발 이중 시즌 셔틀 투어입니다. 기본 일정은 통도사(유네스코 산사·한국 삼보 사찰, 수령 350년 자장매 보유), 원동 매화마을(비닐하우스 팝업 식당에서 미나리 삼겹살 점심 식사), 불국사(유네스코 세계문화유산), 보문호(8km 벚꽃 산책로)를 방문합니다. 벚꽃 전용 투어보다 넓은 운행 기간으로, 약 2월 25일 ~ 4월 10일 동안 매화와 벚꽃 절정 시기를 모두 커버합니다. 매화와 벚꽃의 개화 상황에 따라 매일 코스 비중을 탄력적으로 조정합니다."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-private-car-charter-cruise-shore": {
    "catalog_card": {
      "slug": "busan-private-car-charter-cruise-shore",
      "title": "부산 크루즈 기항지 프라이빗 차량",
      "subtitle": "공인 영어 구사 드라이버 가이드와 에어컨이 완비된 프라이빗 차량으로 나만의 부산 하루를 설계하세요 — 정시 귀환 보장.",
      "region": "부산 (크루즈 항구 + 시내)",
      "duration": "8시간",
      "stopsCount": 5,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "프라이빗 투어",
        "맞춤형 루트",
        "크루즈 픽업 포함"
      ],
      "heroImage": "/images/tours/taejongdae/chatgpt-image-2026-5-10-12-26-45.webp",
      "thumbnail": "/images/tours/taejongdae/chatgpt-image-2026-5-10-12-26-45.webp",
      "priceLabel": "",
      "shortCardDescription": "공인 영어 구사 드라이버 가이드와 함께하는 크루즈 승객을 위한 8시간 부산 프라이빗 전세차. 기본 일정은 UN기념공원, 태종대 절벽, 감천문화마을, 용두산공원, 자갈치시장으로 구성됩니다. 완전 맞춤 변경 가능. 크루즈 터미널, KTX역, 또는 부산 시내 호텔 어디서든 픽업 가능; 선박으로의 정시 귀환 보장."
    },
    "price": {
      "amountLabel": "364"
    }
  },
  "busan-small-group-sightseeing-tour-cruise-passengers": {
    "catalog_card": {
      "slug": "busan-small-group-sightseeing-tour-cruise-passengers",
      "title": "부산 크루즈 기항지 소그룹 투어",
      "subtitle": "크루즈 터미널에서 출발해 하루 9시간, 공유 밴으로 부산의 대표 명소 다섯 곳을 한 번에.",
      "region": "부산",
      "duration": "9시간",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "크루즈 기항지 투어",
        "소형 공유 밴",
        "항구 픽업",
        "9시간 일정"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "부산 크루즈 터미널에서 출발해 9시간 동안 가장 인기 있는 다섯 곳을 공유 밴으로 둘러보는 당일 투어: 유엔기념공원(한국전쟁 역사), 태종대 해안 절벽, 현지 부산 식당에서의 점심, 감천문화마을(색채 가득한 산복 마을), 부산타워 전망대 관람이 가능한 용두산공원, 그리고 자갈치시장. 승선한 선박의 하선 일정에 맞춰 픽업 시간을 조율해 드립니다. 영어·중국어 공인 가이드 동행."
    },
    "price": {
      "amountLabel": "84"
    }
  },
  "busan-spring-cherry-blossom-gyeongju-highlights-day-tour": {
    "catalog_card": {
      "slug": "busan-spring-cherry-blossom-gyeongju-highlights-day-tour",
      "title": "부산 → 경주: 벚꽃 투어",
      "subtitle": "부산에서 경주의 대표 벚꽃 명소인 보문호, 대릉원, 불국사를 잇는 8.5시간 시즌 한정 셔틀 투어. 3월 28일~4월 10일만 운행.",
      "region": "경주 (부산 출발)",
      "duration": "8.5시간",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "봄 시즌 한정",
        "벚꽃 투어",
        "유네스코 유적지",
        "부산 픽업"
      ],
      "heroImage": "/images/itinerary/bomun-lake-cherry-blossom-promenade.webp",
      "thumbnail": "/images/itinerary/bomun-lake-cherry-blossom-promenade.webp",
      "priceLabel": "",
      "shortCardDescription": "경주의 대표 봄 벚꽃 명소를 찾아가는 부산 출발 8.5시간 셔틀 투어. 기본 코스는 보문호(호반을 따라 이어지는 8km 벚꽃길), 첨성대·대릉원 역사 지구(유네스코 경주 역사 지역), 불국사(4월 중순 겹벚꽃 야에자쿠라로 유명한 유네스코 세계문화유산)를 포함합니다. 당일 개화 상황 보고에 따라 매일 아침 2~3곳의 방문지가 확정됩니다. 투어는 3월 28일~4월 10일만 운행되며, 개화가 현저히 지연되거나 종료된 경우 전액 환불해 드립니다."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-top-attractions-day-tour": {
    "catalog_card": {
      "slug": "busan-top-attractions-day-tour",
      "title": "부산 핵심 명소 일일 투어",
      "subtitle": "3개 픽업 포인트로 즐기는, 균형 잡힌 하루 부산 클래식 7개 코스.",
      "region": "부산",
      "duration": "10.5시간",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소그룹",
        "첫 방문자 맞춤",
        "부산 클래식",
        "연중 운영"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "해동 용궁사 해변 사원, 청사포 & 블루라인 파크(스카이 캡슐 선택 가능), 부산 현지 점심식사, UN 기념 공원, 감천문화마을 알록달록 산비탈, 자갈치 수산시장을 포함한 7개 코스 소그룹 당일 투어. 부산 중심부 3개 픽업 포인트 제공, 공인 영어 가이드 동행, 미니버스 운행(최대 약 12명). 모든 관광지 입장료 무료; 점심 및 선택 티켓만 현장 결제."
    },
    "price": {
      "amountLabel": "34"
    }
  },
  "east-signature-nature-core": {
    "catalog_card": {
      "slug": "east-signature-nature-core",
      "title": "제주 동부: 화산, 해안 & 민속마을",
      "subtitle": "제주 돌문화공원부터 성산일출봉까지, 제주 동부에서 가장 균형 잡힌 첫 여행 코스를 따라가 보세요.",
      "region": "제주 동부",
      "duration": "8시간",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소그룹",
        "첫 여행자 추천",
        "제주 동부 시그니처"
      ],
      "heroImage": "/images/tours/jeju-stone-park/kakaotalk-20260510-230028438-19.webp",
      "thumbnail": "/images/tours/jeju-stone-park/kakaotalk-20260510-230028438-19.webp",
      "priceLabel": "",
      "shortCardDescription": "돌문화와 화산 지형으로 시작해 해안과 성산일출봉을 거쳐 일출랜드와 성읍민속마을로 마무리되는, 더욱 알찬 하루를 위한 제주 동부 당일 코스입니다."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "from-busan-gyeongju-ancient-capital-day-tour": {
    "catalog_card": {
      "slug": "from-busan-gyeongju-ancient-capital-day-tour",
      "title": "부산 → 경주 고도 일일 투어",
      "subtitle": "여유로운 페이스로 즐기는 경주의 클래식 6개 명소와 이른 귀환.",
      "region": "경주 (부산 출발)",
      "duration": "10.5시간",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소규모 그룹",
        "여유로운 페이스",
        "부산 출발",
        "이른 귀환"
      ],
      "heroImage": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "thumbnail": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "priceLabel": "1인 US$39 (정가 $50, 22% 할인)",
      "shortCardDescription": "신라 왕국의 고도(古都) 경주(기원전 57년~935년)로 떠나는 부산 출발 소규모 당일 투어. 유네스코 레거시 버전과 동일한 클래식 6개 명소 코스(아홉산 숲 대나무숲 → 불국사 유네스코 → 경주 쌈밥 점심 → 국립박물관 → 교촌 한옥마을 → 월정교)로 진행되지만, 여유로운 페이스와 이른 귀환(약 18:50)이 특징입니다. 영어·중국어 가능 공인 가이드, 미니밴 제공, 전 일정 입장료 무료(아홉산 ₩5,000 및 점심 식사는 현장 결제)."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "from-incheon-seoul-day-tour-cruise-guests": {
    "catalog_card": {
      "slug": "from-incheon-seoul-day-tour-cruise-guests",
      "title": "인천 크루즈 → 서울 일일 투어",
      "subtitle": "인천 크루즈 터미널에서 출발하는 서울의 문화유산, 한옥, 시장, 공예 핵심 코스.",
      "region": "서울 (인천 크루즈 터미널 출발)",
      "duration": "9시간",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "크루즈 기항지 관광",
        "소형 합승 밴",
        "인천 항구 픽업",
        "9시간 일정"
      ],
      "heroImage": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "thumbnail": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "priceLabel": "1인 US$69 (정가 $76, 9% 할인)",
      "shortCardDescription": "인천 크루즈 터미널 출발, 9시간 일정으로 서울의 대표 도심 명소를 소형 밴으로 둘러보는 당일 투어: 경복궁(화요일에는 창덕궁 방문), 북촌 한옥마을, 광장시장 점심(서울에서 가장 많이 촬영되는 길거리 음식 골목), 인사동 문화거리. 승선하신 선박의 하선 시간에 맞춰 픽업 조정; 공인 영어·중국어 가이드 동행; 왕복 약 75분 이동 시간 포함."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "incheon-seoul-private-car-shore-excursion-cruise": {
    "catalog_card": {
      "slug": "incheon-seoul-private-car-shore-excursion-cruise",
      "title": "인천 크루즈 → 서울 프라이빗 차량",
      "subtitle": "크루즈 여행객을 위한 프라이빗 차량 — 인천 갱웨이 픽업, 완전 맞춤형 서울 일정, 출항 60분 전 터미널 도착 보장.",
      "region": "서울 (인천 크루즈 터미널 출발)",
      "duration": "8시간",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "프라이빗",
        "크루즈",
        "기항지 관광",
        "서울 주요 명소",
        "맞춤형",
        "귀선 보장"
      ],
      "heroImage": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "thumbnail": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "priceLabel": "",
      "shortCardDescription": "정해진 일정이 아닌, 출항 시간에 맞춰 설계된 8시간 프라이빗 차량 투어. 인천 크루즈 터미널 갱웨이 픽업, 영어 구사 드라이버 가이드, 경복궁, 북촌 한옥마을 + 인사동, 원하시는 점심 식사, N서울타워, 명동 또는 조계사로 이어지는 맞춤형 코스. 드라이버 가이드가 출항 전 60분의 교통 여유 시간을 확보하여 절대 배를 놓치지 않습니다."
    },
    "price": {
      "amountLabel": "424"
    }
  },
  "jeju-cherry-blossom-tour-east-route": {
    "catalog_card": {
      "slug": "jeju-cherry-blossom-tour-east-route",
      "title": "제주 동부: 벚꽃 투어",
      "subtitle": "벚꽃 거리에서 용암 동굴을 지나 일출봉까지.",
      "region": "제주 동부",
      "duration": "8시간",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "봄 한정",
        "벚꽃 시즌",
        "제주 동부"
      ],
      "heroImage": "/images/tours/ilchulland/chatgpt-image-2026-5-8-07-45-52.webp",
      "thumbnail": "/images/tours/ilchulland/chatgpt-image-2026-5-8-07-45-52.webp",
      "priceLabel": "",
      "shortCardDescription": "봄에만 운영하는 제주 동부 코스: 벚꽃 거리, 10km 유채꽃 길, 용암 동굴, 그리고 상징적인 성산 분화구를 둘러봅니다."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "jeju-cruise-shore-excursion-bus-tour": {
    "catalog_card": {
      "slug": "jeju-cruise-shore-excursion-bus-tour",
      "title": "제주 크루즈 기항지: 코치 투어",
      "subtitle": "제주항·강정항 루트를 선택할 수 있는 항구 기반 크루즈 당일 투어",
      "region": "제주 (기항지에 따라 상이)",
      "duration": "8시간",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "크루즈 기항지 투어",
        "항구별 맞춤 루트",
        "실속형 크루즈",
        "대형 코치"
      ],
      "heroImage": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "thumbnail": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "priceLabel": "",
      "shortCardDescription": "크루즈 기항지에 따라 루트가 달라지는 대형 코치 버스 투어입니다. 제주항(북부)은 성산일출봉을 경유하는 동해안 유네스코 루트, 강정항(남부)은 한라산 1100 + 남해안 지질 + 올레 시장 코스로 운행합니다. 두 코스 모두 여유 있는 시간에 맞춰 크루즈 터미널로 귀환합니다."
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "jeju-cruise-shore-excursion-small-group-tour": {
    "catalog_card": {
      "slug": "jeju-cruise-shore-excursion-small-group-tour",
      "title": "제주 크루즈 기항지 소그룹 투어",
      "subtitle": "제주항·강정항 루트 분기형 크루즈 당일 투어",
      "region": "제주 (항구에 따라 상이)",
      "duration": "8시간",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "크루즈 기항지 투어",
        "항구별 맞춤 루트",
        "프리미엄 크루즈",
        "소그룹"
      ],
      "heroImage": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "thumbnail": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "priceLabel": "",
      "shortCardDescription": "입항 항구에 따라 루트가 달라지는 소그룹 크루즈 기항지 투어입니다. 제주항(북쪽)은 성산일출봉을 경유하는 동해안 유네스코 루트로, 강정항(남쪽)은 한라산 1100고지 + 남해안 지질 명소 + 올레시장 루트로 운행됩니다. 두 루트 모두 여유 있게 크루즈 터미널로 귀환합니다."
    },
    "price": {
      "amountLabel": "77"
    }
  },
  "jeju-eastern-unesco-spots-day-tour": {
    "catalog_card": {
      "slug": "jeju-eastern-unesco-spots-day-tour",
      "title": "제주 동부 유네스코 일일 투어",
      "subtitle": "소그룹 미니버스, 영어·중국어 가이드 — 함덕해변·성읍민속마을·성산일출봉(유네스코)·해녀 물질공연·만장굴(유네스코)을 9시간 동부 루프로 일주합니다.",
      "region": "동제주",
      "duration": "9시간",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소그룹",
        "제주",
        "제주 동부",
        "유네스코",
        "합리적 가격",
        "전 입장료 포함"
      ],
      "heroImage": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "thumbnail": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "priceLabel": "",
      "shortCardDescription": "제주 동부 유네스코 명소를 9시간 소그룹으로 일주합니다. 함덕 서우봉해변, 성읍민속마을(유네스코 민속), 성산일출봉과 만장굴 — 2007년 함께 등재된 두 유네스코 세계자연유산, 그리고 해녀 물질공연(취소 시 해녀박물관) 포함. 전 입장료 포함, 공인 영어·중국어 가이드."
    },
    "price": {
      "amountLabel": "49"
    }
  },
  "jeju-grand-highlights-loop": {
    "catalog_card": {
      "slug": "jeju-grand-highlights-loop",
      "title": "제주 그랜드 하이라이트 루프",
      "subtitle": "제주의 유네스코 3대 명소, 생생한 해녀 물질 시연, 해안 절벽과 바다로 떨어지는 폭포까지 — 제주 최고의 명소를 하루에 만나는 투어.",
      "region": "제주 전 지역 코스",
      "duration": "10~10.5시간",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소그룹",
        "유네스코 3대 명소",
        "당일 여행객에게 최적"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "",
      "shortCardDescription": "한라산, 성산일출봉, 만장굴 용암동굴까지 유네스코 세계유산 3곳을 연결하고, 살아 있는 해녀 물질 시연, 주상절리 절벽, 바다로 떨어지는 정방폭포를 더한 고밀도 전 지역 코스입니다. 제주의 대표 명소를 하루에 응축한 일정입니다."
    },
    "price": {
      "amountLabel": "93"
    }
  },
  "jeju-hydrangea-festival-tour-east-route": {
    "catalog_card": {
      "slug": "jeju-hydrangea-festival-tour-east-route",
      "title": "제주 동부 수국 축제 투어",
      "subtitle": "함덕해변, 성읍민속마을, 성산일출봉, 일출랜드 수국 축제, 휴애리 자연생활공원 수국 하이라이트를 소그룹으로.",
      "region": "동제주",
      "duration": "9시간",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소그룹",
        "제주",
        "수국",
        "시즌 한정",
        "여름 한정",
        "유네스코",
        "축제"
      ],
      "heroImage": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "thumbnail": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "priceLabel": "",
      "shortCardDescription": "제주 동부 수국 시즌 한정(5월 말~7월 중순) 소그룹 투어. 함덕해변, 성읍민속마을(유네스코), 성산일출봉(유네스코), 일출랜드 수국 축제+미천굴, 휴애리 자연생활공원 수국 포함."
    },
    "price": {
      "amountLabel": "64"
    }
  },
  "jeju-hydrangea-festival-tour-southwest-route": {
    "catalog_card": {
      "slug": "jeju-hydrangea-festival-tour-southwest-route",
      "title": "제주 서남부 수국 축제 투어",
      "subtitle": "해변에서 주상절리를 거쳐 수국 터널까지.",
      "region": "제주 서부",
      "duration": "9시간",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "여름 한정",
        "수국 시즌",
        "제주 서부"
      ],
      "heroImage": "/images/tours/hyeopjae-beach/kakaotalk-20260510-230009595-01.webp",
      "thumbnail": "/images/tours/hyeopjae-beach/kakaotalk-20260510-230009595-01.webp",
      "priceLabel": "",
      "shortCardDescription": "여름 한정 제주 서부 코스 — 에메랄드빛 해변, 수국 축제 정원, 유네스코 주상절리, 3단 폭포, 수국 터널, 차밭."
    },
    "price": {
      "amountLabel": "64"
    }
  },
  "jeju-island-private-car-charter-tour": {
    "catalog_card": {
      "slug": "jeju-island-private-car-charter-tour",
      "title": "제주 프라이빗 차량 투어",
      "subtitle": "공인 드라이버 가이드와 에어컨이 구비된 프라이빗 차량으로 나만의 제주 하루를 설계하세요.",
      "region": "제주 (동부, 서부, 또는 남부)",
      "duration": "9시간",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "프라이빗 투어",
        "맞춤형 코스",
        "호텔 픽업 포함"
      ],
      "heroImage": "/images/tours/jeju-private/jeju-private-thumbnail-carnival-coast.webp",
      "thumbnail": "/images/tours/jeju-private/jeju-private-thumbnail-carnival-coast.webp",
      "priceLabel": "",
      "shortCardDescription": "공인 드라이버 가이드와 함께하는 9시간 제주 프라이빗 전세 차량. 세 가지 추천 코스(동부, 서부, 남부)로 제주의 인기 명소를 둘러보거나, 유네스코 랜드마크, K-드라마 촬영지, 해변, 차밭, 전통 시장 등으로 나만의 코스를 완성해보세요. 섬 어디서든 호텔 픽업이 포함됩니다."
    },
    "price": {
      "amountLabel": "254"
    }
  },
  "jeju-southern-top-unesco-spots-tour": {
    "catalog_card": {
      "slug": "jeju-southern-top-unesco-spots-tour",
      "title": "제주 남부 서귀포 시그니처 당일 투어",
      "subtitle": "제주 남부 서귀포 해안 코스 — 정방폭포, 외돌개 올레길, 약천사, 한라산.",
      "region": "제주 남부",
      "duration": "9시간",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소그룹",
        "제주",
        "제주 남부",
        "서귀포",
        "합리적인 가격",
        "쇼핑 없음"
      ],
      "heroImage": "/images/tours/jeongbang-falls/kakaotalk-20260510-230028438-15.webp",
      "thumbnail": "/images/tours/jeongbang-falls/kakaotalk-20260510-230028438-15.webp",
      "priceLabel": "",
      "shortCardDescription": "제주 남부 서귀포의 대표 명소를 소그룹으로 둘러보는 당일 투어 — 아시아에서 유일하게 바다로 직접 떨어지는 정방폭포, 외돌개 기암과 올레 7코스 해안 산책, 동아시아 최대 사찰 약천사, 오설록 티 뮤지엄, 그리고 한라산 어승생악 탐방로. 제주시 전역 및 공항 포함 4곳의 픽업 포인트, 공인 영어·중국어 가이드 동반, 정방폭포 외 거의 전 코스 무료 입장, 쇼핑 강요 없음."
    },
    "price": {
      "amountLabel": "49"
    }
  },
  "jeju-west-south-full-day-authentic-tour": {
    "catalog_card": {
      "slug": "jeju-west-south-full-day-authentic-tour",
      "title": "제주 서·남부 정통 일일 투어",
      "subtitle": "한라산 유네스코 고지, 주상절리대, 송악산 분화구 능선, 천제연 폭포, 오설록 차밭, 협재 해변 — 제주의 서부와 남부를 하루에 균형 있게 담다.",
      "region": "제주 서부 & 남부",
      "duration": "9시간",
      "stopsCount": 9,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소그룹",
        "제주",
        "제주 서부 & 남부",
        "UNESCO",
        "카페 문화",
        "해안"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "1인 US$59 (정가 $69, 14% 할인)",
      "shortCardDescription": "제주의 서부와 남부 해안을 하나의 코스로 연결하는 소그룹 일일 투어 — 한라산 1100 고지 습지 (유네스코), 육각형 주상절리대, 송악산 파노라마 전망대, 천제연 폭포, 오설록 티 뮤지엄, 그리고 서쪽 해안의 협재 해변 카페 거리. 남부 유네스코 투어와 동일한 운영사이지만, 보다 라이프스타일 지향적인 콘셉트 — '화산 지형과 웅장한 해안선, 그리고 트렌디한 바닷가 카페의 만남.'"
    },
    "price": {
      "amountLabel": ""
    }
  },
  "jeju-winter-southwest-tangerine-snow-camellia-tour": {
    "catalog_card": {
      "slug": "jeju-winter-southwest-tangerine-snow-camellia-tour",
      "title": "제주 겨울: 귤, 눈 & 동백",
      "subtitle": "한라산 설경, 카멜리아힐 동백 만개, 귤 직접 따기 체험, 주상절리와 천제연까지 — 9시간으로 즐기는 제주 서남부 겨울 여행.",
      "region": "제주 서남부",
      "duration": "9시간",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소그룹",
        "제주",
        "겨울",
        "시즌 한정",
        "귤",
        "동백",
        "눈"
      ],
      "heroImage": "/images/tours/jeju-tangerine-farm/photo-001.webp",
      "thumbnail": "/images/tours/jeju-tangerine-farm/photo-001.webp",
      "priceLabel": "",
      "shortCardDescription": "12월부터 2월까지 운영되는 제주 서남부 겨울 당일 투어로, 제주의 겨울을 대표하는 세 가지 매력을 중심으로 구성됩니다: 한라산 기슭의 설경, 카멜리아힐의 붉은 동백 만개, 그리고 실제 과수원에서 직접 따는 제주 귤(감귤) 체험. 코스에는 천제연폭포, 주상절리, 오설록 티 뮤지엄도 포함됩니다. 제주시 내 호텔 픽업 제공, 영어·중국어 가능 공인 가이드 동행."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "pocheon-sanjeong-lake-herb-island-art-valley": {
    "catalog_card": {
      "slug": "pocheon-sanjeong-lake-herb-island-art-valley",
      "title": "포천: 산정호수·허브아일랜드·아트밸리",
      "subtitle": "산속 호수, 지중해풍 허브 정원, 채석장이 변신한 아트파크—서울에서 떠나는 가장 여유로운 계절 당일 여행.",
      "region": "포천 (서울 당일 여행)",
      "duration": "10시간",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "자연 & 사진 여행",
        "계절별 볼거리",
        "낭만적인 야간 조명"
      ],
      "heroImage": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "thumbnail": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "priceLabel": "",
      "shortCardDescription": "호수, 허브 정원, 그리고 인상적인 아트파크 풍경으로 유명한 경기도 포천으로 떠나는 여유로운 계절 당일 여행. 산으로 둘러싸인 산정호수, 지중해풍 정원과 야간 조명이 매력적인 허브아일랜드, 모노레일로 오르는 포천 아트밸리 채석장 전망대를 차례로 둘러봅니다. 남이섬보다 한적하며, 명소를 빠르게 도는 것이 아닌 사진 중심의 여유로운 일정으로 구성되어 있습니다."
    },
    "price": {
      "amountLabel": "54"
    }
  },
  "seoul-dmz-private-3rd-tunnel-suspension-bridge": {
    "catalog_card": {
      "slug": "seoul-dmz-private-3rd-tunnel-suspension-bridge",
      "title": "서울 DMZ 프라이빗: 제3땅굴 & 출렁다리",
      "subtitle": "한국의 분단 국경과 150m 산악 출렁다리를 하루에 — 서울 출발 프라이빗 당일 투어.",
      "region": "파주 (서울 당일치기)",
      "duration": "8~9시간",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "프라이빗 투어",
        "DMZ + 출렁다리",
        "호텔 픽업 포함"
      ],
      "heroImage": "/images/tours/imjingak/chatgpt-image-2026-5-10-10-40-40.webp",
      "thumbnail": "/images/tours/imjingak/chatgpt-image-2026-5-10-10-40-40.webp",
      "priceLabel": "",
      "shortCardDescription": "한국에서 가장 역사적 무게를 지닌 장소와 가장 아름다운 산악 출렁다리를 함께 경험하는 프라이빗 당일 투어. 오전에는 DMZ(임진각 평화공원, 제3침투 땅굴, 도라산 전망대)를 둘러보고, 오후에는 150m 감악산 붉은 출렁다리를 건넙니다. DMZ 구간 입장 시 여권이 필요합니다."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-private-nami-morning-calm-petite-france": {
    "catalog_card": {
      "slug": "seoul-private-nami-morning-calm-petite-france",
      "title": "서울 프라이빗: 남이섬, 아침고요수목원 & 쁘띠프랑스",
      "subtitle": "한국에서 가장 많이 사진에 담기는 당일치기 명소 세 곳을, 단체 버스 투어의 번잡함 없이 프라이빗 차량으로 여유롭게.",
      "region": "가평 (서울 당일치기)",
      "duration": "9~10시간",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "프라이빗 투어",
        "한국 드라마 촬영지",
        "커플 & 가족"
      ],
      "heroImage": "/images/tours/nami-island/kakaotalk-20260510-222949305-04.webp",
      "thumbnail": "/images/tours/nami-island/kakaotalk-20260510-222949305-04.webp",
      "priceLabel": "",
      "shortCardDescription": "남이섬의 가로수길 페리 체험, 아침고요수목원의 테마 정원 산책, 어린왕자 마을 쁘띠프랑스의 알록달록한 풍경까지 하루에 담는 서울 출발 프라이빗 당일 투어. 호텔 픽업, 프라이빗 차량, 여유로운 일정으로 즐기는 가평 코스의 프리미엄 버전."
    },
    "price": {
      "amountLabel": "194"
    }
  },
  "seoul-seoraksan-naksansa-temple-naksan-beach-day-trip": {
    "catalog_card": {
      "slug": "seoul-seoraksan-naksansa-temple-naksan-beach-day-trip",
      "title": "서울 출발 강원도: 설악산 + 낙산사 + 낙산해수욕장",
      "subtitle": "설악산의 화강암 봉우리, 천년 해안 사찰, 소나무 숲이 감싼 동해 해변을 단 하루 12시간 서울 당일 여행으로 만나보세요.",
      "region": "서울 → 강원도 (설악산 & 양양)",
      "duration": "12시간",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "서울 출발 당일 여행",
        "에어컨 완비 코치버스",
        "매주 월요일 & 목요일",
        "12시간 일정"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "From US$52 per person (was $58, 10% off)",
      "shortCardDescription": "서울에서 동해안까지 12시간 코치 당일 여행: 설악산 국립공원 하이킹, 절벽 위의 낙산사 방문, 소나무 숲 낙산해수욕장 산책. 매주 월요일과 목요일 출발, 영어 가이드 동반, 홍대 또는 명동에서 왕복 이동 포함."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-seoraksan-nami-island-morning-calm-day-tour": {
    "catalog_card": {
      "slug": "seoul-seoraksan-nami-island-morning-calm-day-tour",
      "title": "서울: 설악산 + 남이섬 + 아침고요",
      "subtitle": "설악산, 남이섬의 가로수길, 아침고요수목원의 테마 정원을 서울 출발 13시간 당일 여행 하나로 모두 경험하세요.",
      "region": "서울 → 강원 → 경기",
      "duration": "13시간",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "서울 출발 당일 여행",
        "대형 코치",
        "입장료 전액 포함",
        "13시간 당일 일정"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "1인 US$59부터 (정가 $82, 28% 할인)",
      "shortCardDescription": "서울 출발 13시간 코치 당일 투어로, 한국에서 가장 많이 촬영되는 당일 여행지 세 곳을 모두 방문합니다: 설악산 국립공원(한국 유일의 유네스코 생물권보전지역), 남이섬(겨울연가의 메타세쿼이아길), 아침고요수목원(5,000여 종의 식물을 보유한 한국 대표 프라이빗 수목원). 전 일정 입장료 포함, 영어 안내 가이드, 홍익대입구역 또는 명동역 픽업."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-seoraksan-national-park-sokcho-beach-day-trip": {
    "catalog_card": {
      "slug": "seoul-seoraksan-national-park-sokcho-beach-day-trip",
      "title": "설악산 & 속초 해변 당일치기",
      "subtitle": "서울에서 한국에서 가장 사랑받는 국립공원과 동해안 도시 속초로 떠나는 소그룹 당일치기 여행.",
      "region": "설악산, 강원도",
      "duration": "12시간",
      "stopsCount": 5,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소그룹",
        "자연",
        "절경",
        "해변",
        "수산시장",
        "단풍",
        "당일치기"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "",
      "shortCardDescription": "서울에서 한국에서 가장 사랑받는 국립공원과 동해안 도시 속초로 떠나는 소그룹 당일치기 여행. 설악산의 화강암 봉우리, 계곡, 불교 유산과 속초의 수산시장 및 해변을 함께 즐길 수 있으며, 동해안에서만 경험할 수 있는 산과 바다의 조합입니다. 영어 가이드와 왕복 교통을 포함한 12시간 투어."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suburbs-private-chartered-car-10hr": {
    "catalog_card": {
      "slug": "seoul-suburbs-private-chartered-car-10hr",
      "title": "서울 프라이빗 차량 전세",
      "subtitle": "서울 또는 근교에서 나만의 하루를 설계하세요. 공인 드라이버 가이드와 함께하는 프라이빗 투어입니다.",
      "region": "서울 & 근교",
      "duration": "10시간",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "프라이빗 투어",
        "완전 맞춤형",
        "서울 호텔 픽업 무료"
      ],
      "heroImage": "/images/tours/seoul-private-charter/seoul-private-carnival-han-river-night.webp",
      "thumbnail": "/images/tours/seoul-private-charter/seoul-private-carnival-han-river-night.webp",
      "priceLabel": "",
      "shortCardDescription": "나만의 서울 근교 하루를 완성할 수 있는 프리미엄 10시간 프라이빗 전세 차량 투어입니다. 세 가지 추천 코스 중 선택하세요—남이섬 + 아침고요수목원 + 쁘띠프랑스 + 강촌레일바이크, DMZ + 파주 아울렛, 에버랜드 + 한국민속촌—또는 직접 원하는 일정을 보내주셔도 됩니다. 서울 도심 숙박 고객에게는 호텔 픽업이 무료로 제공됩니다."
    },
    "price": {
      "amountLabel": "184"
    }
  },
  "seoul-suwon-hwaseong-folk-village-starfield-library": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-folk-village-starfield-library",
      "title": "수원: 화성, 민속촌 & 스타필드",
      "subtitle": "서울에서 출발하는 소그룹 문화 당일 투어로, 경기도의 네 가지 대조적인 한국 유산과 현대 생활을 경험합니다: 유네스코 세계유산으로 등재된…",
      "region": "경기도 (서울 남쪽)",
      "duration": "10시간",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소그룹",
        "문화",
        "UNESCO",
        "유산",
        "도서관",
        "민속촌",
        "당일 여행"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "서울에서 출발하는 소그룹 문화 당일 투어로, 경기도의 네 가지 대조적인 한국 유산과 현대 생활을 경험합니다: 유네스코 세계유산으로 등재된 수원 화성(18세기 성벽과 성문), 조선 시대 재현 행사가 펼쳐지는 화성행궁, 용인의 몰입형 야외 한국민속촌, 그리고 웅장한 4층 규모의 스타필드 수원 도서관. 교통 및 입장료 포함 10시간 투어."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library",
      "title": "수원: 화성, 광명동굴 & 스타필드",
      "subtitle": "경기도의 대조적인 네 가지 매력을 경험하는 서울 출발 소그룹 문화 당일 여행: 유네스코 세계문화유산 수원 화성과…",
      "region": "경기도 (서울 남쪽)",
      "duration": "9시간",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "소그룹",
        "문화",
        "UNESCO",
        "동굴",
        "도서관",
        "쇼핑",
        "당일 여행"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "경기도의 대조적인 세 가지 매력을 경험하는 서울 출발 소그룹 문화 당일 여행: 18세기 성곽과 행궁을 품은 유네스코 세계문화유산 수원 화성, 일제강점기 금광이었던 광명동굴 내 화려한 LED 지하 테마파크, 4층 규모의 스타필드 라이브러리 수원. 교통 및 입장료 포함, 총 9시간 진행."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suwon-hwaseong-waujeongsa-starfield": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-waujeongsa-starfield",
      "title": "수원: 화성, 와우정사 & 스타필드",
      "subtitle": "유네스코 성곽, 산사, 그리고 화제의 도서관—하나의 서울 당일 여행으로 만나는 한국의 과거, 정신, 그리고 현재.",
      "region": "수원 & 용인",
      "duration": "9~10시간",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "유네스코 세계유산",
        "문화유산 + 현대 당일 여행",
        "입장료 포함"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "서울 출발 소그룹 당일 여행으로 한국의 세 가지 대조적인 면을 경험하세요: 유네스코 세계유산으로 등재된 수원 화성(18세기 군사 건축물), 사진 명소로 유명한 스타필드 수원 도서관(현대 문화 아이콘), 그리고 용인 와우정사(거대한 야외 불상과 석종). 교통 및 입장료가 포함된 높은 문화유산 가치의 여행입니다."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "southwest-hallasan-osulloc-aewol": {
    "catalog_card": {
      "slug": "southwest-hallasan-osulloc-aewol",
      "title": "제주 서남부: 한라산·오설록·애월·이호테우",
      "subtitle": "1100고지 습지 데크길, 화산 절벽, 폭포 트레일, 차밭, 그리고 애월·이호테우 일몰 마무리",
      "region": "제주 서남부",
      "duration": "9시간",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "제주 첫 방문자에게 적합",
        "제주 서남부"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "",
      "shortCardDescription": "한라산 1100고지 습지, 화산 해안선, 천제연 폭포, 오설록 차밭, 애월 카페거리, 이호테우 일몰을 잇는 균형 잡힌 제주 서남부 하루 코스."
    },
    "price": {
      "amountLabel": "49"
    }
  }
};
