// AUTO-GENERATED by scripts/build-catalog-cards.mjs — DO NOT EDIT.
// catalog_card pages for the "de" locale only. Loaded lazily by
// staticTourCatalogCards.lazy.ts so client bundles ship one locale, not six.

import type { SlimCatalogPage } from "./catalogCards.generated";

export const PAGES: Record<string, SlimCatalogPage> = {
  "busan-small-group-yonggungsa-skycapsule-gamcheon-tour": {
    "catalog_card": {
      "slug": "busan-small-group-yonggungsa-skycapsule-gamcheon-tour",
      "title": "Busan Kleingruppe: Meerestempel, Sky Capsule & Kulturdörfer",
      "subtitle": "Kleingruppen-Tagestour zu Busans Küstenikonen und Hangdörfern — der Haedong-Yonggungsa-Tempel am Meer, der Glas-Skywalk des Cheongsapo-Daritdol-Observatoriums, die Fahrt mit der Sky Capsule im Blueline Park (Ticket bei der Buchung wählbar), das Kulturdorf Gamcheon und das stille Dakbatgol-Wandmalereidorf mit seiner Monorail an der „Wunschtreppe“ (소망계단).",
      "region": "Busan",
      "duration": "≈ 9 Stunden",
      "stopsCount": 9,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Kleingruppe",
        "Busan",
        "Sky Capsule",
        "Küste",
        "Kulturdörfer"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunrise-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunrise-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "Ein Busan-Tag in der Kleingruppe, aufgebaut um die Küste und die Hangdörfer: der Haedong-Yonggungsa-Tempel am Meer in seinem ruhigen Morgenfenster, das kostenlose Daritdol-Observatorium mit Glasboden in Cheongsapo, die Fahrt mit der Sky Capsule im Blueline Park von Cheongsapo nach Mipo (Ticket inbegriffen oder nicht — Sie wählen bei der Buchung), Mittagessen, das Kulturdorf Gamcheon und das kaum bekannte Dakbatgol-Wandmalereidorf, wo eine kostenlose Monorail die „Wunschtreppe“ hinaufgleitet. Jeder Ankerpunkt außer der optionalen Kapsel ist eintrittsfrei."
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "pocheon-sanjeong-lake-herb-island-art-valley": {
    "catalog_card": {
      "slug": "pocheon-sanjeong-lake-herb-island-art-valley",
      "title": "Pocheon & Yeoncheon: See, Wasserfall & Kunsttal im Steinbruch",
      "subtitle": "Ein Rundweg um einen von Bergen umringten See, ein 18 m hoher Wasserfall über Säulenbasalt und ein smaragdgrüner Steinbruchsee — zwei Geostätten des UNESCO Global Geopark Hantangang an einem unaufgeregten Tag ab Seoul.",
      "region": "Pocheon & Yeoncheon (Tagesausflug ab Seoul)",
      "duration": "10 Stunden",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Tagesausflug ab Seoul",
        "Mo · Do · Sa",
        "UNESCO-Geopark",
        "Wasserfall",
        "Seerundweg",
        "Kleine Gruppe"
      ],
      "heroImage": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "thumbnail": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "priceLabel": "",
      "shortCardDescription": "Ein ruhigerer Tagesausflug ab Seoul, der auf echter Geologie aufbaut. Gehen Sie den flachen 3,2 km langen Rundweg um den Sanjeong-See unterhalb des Myeongseongsan, essen Sie Pocheons eigenes Idong-Galbi, überqueren Sie dann eine 80 m lange Hängebrücke direkt vor dem Jaein-Wasserfall, der 18 m über Säulenbasalt in die Tiefe stürzt, und lassen Sie den Tag im Granitsteinbruch des Pocheon Art Valley ausklingen, wo Quellwasser die Grube zum smaragdgrünen Cheonjuho-See gefüllt hat. Der Jaein-Wasserfall und das Art Valley sind beide Geostätten des UNESCO Global Geopark Hantangang — dieselbe Landschaft, gesehen von ihren beiden gegenüberliegenden Hälften. Abfahrt montags, donnerstags und samstags."
    },
    "price": {
      "amountLabel": "54"
    }
  },
  "seoul-gapyeong-nami-morning-calm-petite-france-day-tour": {
    "catalog_card": {
      "slug": "seoul-gapyeong-nami-morning-calm-petite-france-day-tour",
      "title": "Gapyeong-Tagestour ab Seoul: Insel Nami, Garden of Morning Calm & Petite France",
      "subtitle": "Das Gapyeong-Trio an einem Bustag — keine Bergwanderung, drei Eintritte inklusive",
      "region": "Seoul → Gyeonggi-do (Gapyeong)",
      "duration": "11,5 Stunden",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Tagesausflug ab Seoul",
        "Gapyeong",
        "Gruppentour zum Zusteigen",
        "K-Drama",
        "Gärten"
      ],
      "heroImage": "/images/tours/nami-island/nami-metasequoia-sunset-lake.webp",
      "thumbnail": "/images/tours/nami-island/nami-metasequoia-sunset-lake.webp",
      "priceLabel": "",
      "shortCardDescription": "Seouls unkompliziertester Landtag: die Metasequoien-Allee der Insel Nami, ein 330,000 m² großes Themen-Arboretum und ein Dorf zum Kleinen Prinzen — alle drei Eintritte inklusive, zurück in Seoul bis 19:00."
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "seoul-winter-seoraksan-nami-eobi-ice-valley-day-tour": {
    "catalog_card": {
      "slug": "seoul-winter-seoraksan-nami-eobi-ice-valley-day-tour",
      "title": "Winter-Special ab Seoul: Seoraksan, Insel Nami & die Eiswand im Eobi-Tal",
      "subtitle": "Ein Bustag nur im Winter — Schnee auf Koreas berühmtestem Gipfel, Nami unter Raureif und eine vom Dorf gebaute Eiswand",
      "region": "Seoul → Gangwon-do → Gyeonggi-do (Gapyeong)",
      "duration": "13,5 Stunden",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Nur im Winter",
        "Saisonal",
        "Tagesausflug ab Seoul",
        "Seoraksan",
        "Eiswand"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "",
      "shortCardDescription": "Läuft nur im tiefen Winter: Seoraksan unter Schnee, die bereiften Baumalleen der Insel Nami und die 25 Meter hohe Eiswand, die Dorfbewohner in Gapyeong jeden Januar an einer Felswand im Tal wachsen lassen."
    },
    "price": {
      "amountLabel": "69"
    }
  }
};
