// AUTO-GENERATED by scripts/build-catalog-cards.mjs — DO NOT EDIT.
// catalog_card pages for the "es" locale only. Loaded lazily by
// staticTourCatalogCards.lazy.ts so client bundles ship one locale, not six.

import type { SlimCatalogPage } from "./catalogCards.generated";

export const PAGES: Record<string, SlimCatalogPage> = {
  "busan-cruise-shore-excursion-bus-tour": {
    "catalog_card": {
      "slug": "busan-cruise-shore-excursion-bus-tour",
      "title": "Excursión en tierra desde Busan en crucero: Tour en autobús por la costa",
      "subtitle": "Circuito costero por Busan de 8 paradas en autocar grande, con recogida en la terminal de cruceros y regreso planificado en función de la hora de salida de su barco.",
      "region": "Busan",
      "duration": "9 horas",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Excursión en crucero",
        "Autocar grande",
        "Recogida en el puerto",
        "Regreso garantizado"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "Desde US$49 por persona (antes $55, 11% de descuento)",
      "shortCardDescription": "Tour diario costero por Busan en autocar grande diseñado para pasajeros de crucero: recogida en la terminal de cruceros, 8 paradas emblemáticas (Haedong Yonggungsa, Cementerio Memorial de la ONU, Mercado de Jagalchi, Plaza BIFF, Mercado de Gukje, Pueblo Cultural de Gamcheon, Playa de Songdo, Parque Yongdusan) y garantía de regreso antes de la salida del barco. Categoría económica — mismo recorrido que el producto en grupo reducido, autocar más grande."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-gyeongju-unesco-legacy-tour-national-museum": {
    "catalog_card": {
      "slug": "busan-gyeongju-unesco-legacy-tour-national-museum",
      "title": "Busan→Gyeongju: Patrimonio UNESCO",
      "subtitle": "La capital milenaria de Corea en un solo día desde Busan — templo UNESCO, museo nacional, aldea hanok y cierre en el puente.",
      "region": "Gyeongju (desde Busan)",
      "duration": "11,5 horas",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "UNESCO",
        "Incluye el Museo Nacional",
        "Grupo reducido",
        "Desde Busan"
      ],
      "heroImage": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "thumbnail": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "priceLabel": "Desde US$39 por persona (antes $50, 22% descuento)",
      "shortCardDescription": "Tour de un día en grupo reducido de Busan a Gyeongju, capital del Reino Silla durante 992 años (57 a. C.–935 d. C.) y la mayor concentración de sitios Patrimonio de la Humanidad de la UNESCO en Corea. Ruta: Bosque de Bambú de Ahopsan → Templo Bulguksa (UNESCO) → Almuerzo ssambap en Gyeongju → Museo Nacional de Gyeongju → Aldea Hanok de Gyochon → Puente Woljeonggyo. Guía certificado con dominio del inglés y chino; minivan; entrada gratuita al Templo Bulguksa y al museo."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-outskirts-tongdosa-amethyst-yeongnam-day-tour": {
    "catalog_card": {
      "slug": "busan-outskirts-tongdosa-amethyst-yeongnam-day-tour",
      "title": "Alrededores de Busan: Tongdosa + Cueva de Amatista + Alpes de Yeongnam",
      "subtitle": "Templo UNESCO, cueva de amatista, teleférico del valle de hielo y Gamcheon — los alrededores de Busan en un solo día de 11 horas en autobús.",
      "region": "Busan → Yangsan → Ulsan → Miryang → Busan",
      "duration": "11 horas",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Patrimonio Mundial UNESCO",
        "Excursión en autobús",
        "Recogida en 3 estaciones",
        "Día de 11 horas"
      ],
      "heroImage": "/images/itinerary/tongdosa-iljumun.webp",
      "thumbnail": "/images/itinerary/tongdosa-iljumun.webp",
      "priceLabel": "",
      "shortCardDescription": "Una excursión de un día de 11 horas en autobús por los alrededores de Busan hacia Yangsan (Templo Tongdosa, Patrimonio Mundial UNESCO 2018), Ulsan (Parque Temático Cueva de Amatista con paseo en bote opcional), Miryang (Teleférico del Valle de Hielo de los Alpes de Yeongnam) y con final en el Pueblo Cultural de Gamcheon en Busan. Tres puntos de recogida (Estación de Busan / Seomyeon / Haeundae); bajada opcional en Jagalchi al final."
    },
    "price": {
      "amountLabel": "85"
    }
  },
  "busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju": {
    "catalog_card": {
      "slug": "busan-plum-cherry-blossom-day-tour-to-yangsan-gyeongju",
      "title": "Busan: Floración de Ciruelos y Cerezos (Yangsan+Gyeongju)",
      "subtitle": "Un servicio de transporte estacional de 8,5 horas que incluye el Templo Tongdosa (UNESCO Sansa + ciruelo Jajangmae de 350 años), el Pueblo de Floración de Ciruelos Wondong, el Templo Bulguksa (UNESCO) y el Lago Bomun. Solo disponible del 25 de feb al 10 de abr.",
      "region": "Yangsan + Gyeongju (desde Busan)",
      "duration": "8,5 horas",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Temporada de Primavera",
        "Floración de Ciruelos y Cerezos",
        "2 Sitios UNESCO",
        "Recogida en Busan"
      ],
      "heroImage": "/images/itinerary/tongdosa-iljumun.webp",
      "thumbnail": "/images/itinerary/tongdosa-iljumun.webp",
      "priceLabel": "",
      "shortCardDescription": "Un servicio de transporte de doble temporada de 8,5 horas con salida desde Busan que cubre Yangsan y Gyeongju. El itinerario estándar visita el Templo Tongdosa (UNESCO Sansa, el Templo de las Tres Joyas de Corea, con el ciruelo Jajangmae de 350 años), el Pueblo de Floración de Ciruelos Wondong (almuerzo de Minari Samgyeopsal en restaurantes emergentes de invernadero), el Templo Bulguksa (Patrimonio Mundial de la UNESCO) y el Lago Bomun (circuito de cerezos en flor de 8 km). Período de operación más amplio que los tours exclusivos de cerezos: ~25 de feb – 10 de abr cubre los picos de floración tanto de ciruelos como de cerezos. La ruta diaria ajusta el énfasis según el estado de floración de ciruelos versus cerezos."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-private-car-charter-cruise-shore": {
    "catalog_card": {
      "slug": "busan-private-car-charter-cruise-shore",
      "title": "Busan Crucero: Coche Privado",
      "subtitle": "Diseña tu propio día en Busan con un conductor-guía autorizado de habla inglesa y un vehículo privado con aire acondicionado — regreso puntual garantizado.",
      "region": "Busan (puerto de crucero + centro de la ciudad)",
      "duration": "8 horas",
      "stopsCount": 5,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Tour Privado",
        "Ruta Personalizable",
        "Recogida en Crucero Incluida"
      ],
      "heroImage": "/images/tours/taejongdae/chatgpt-image-2026-5-10-12-26-45.webp",
      "thumbnail": "/images/tours/taejongdae/chatgpt-image-2026-5-10-12-26-45.webp",
      "priceLabel": "",
      "shortCardDescription": "Alquiler privado de auto de 8 horas para pasajeros de crucero en Busan con conductor-guía autorizado de habla inglesa. El itinerario predeterminado incluye el Cementerio Memorial de las Naciones Unidas, los acantilados de Taejongdae, la Aldea Cultural de Gamcheon, el Parque Yongdusan y el Mercado de Jagalchi. Totalmente personalizable. Recogida en la terminal de cruceros, la estación KTX o cualquier hotel céntrico de Busan; el regreso puntual al barco está garantizado."
    },
    "price": {
      "amountLabel": "364"
    }
  },
  "busan-small-group-sightseeing-tour-cruise-passengers": {
    "catalog_card": {
      "slug": "busan-small-group-sightseeing-tour-cruise-passengers",
      "title": "Busan Crucero: Grupo Pequeño",
      "subtitle": "Cinco lugares emblemáticos de Busan desde su terminal de cruceros en un día de 9 horas en furgoneta compartida.",
      "region": "Busan",
      "duration": "9 horas",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Excursión en crucero",
        "Furgoneta compartida pequeña",
        "Recogida en el puerto",
        "Ventana de 9 horas"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "Tour de día en furgoneta compartida desde la terminal de cruceros de Busan que incluye las cinco paradas más solicitadas de la ciudad en una ventana de 9 horas: Cementerio Memorial de la ONU (contexto de la Guerra de Corea), acantilados costeros de Taejongdae, almuerzo en un restaurante local de Busan, Pueblo Cultural de Gamcheon (la ladera pintada), Parque Yongdusan con observatorio opcional en la Torre de Busan, y Mercado de Jagalchi. Recogida coordinada con el desembarco específico de su barco. Guía certificado con habla inglesa y china."
    },
    "price": {
      "amountLabel": "84"
    }
  },
  "busan-spring-cherry-blossom-gyeongju-highlights-day-tour": {
    "catalog_card": {
      "slug": "busan-spring-cherry-blossom-gyeongju-highlights-day-tour",
      "title": "De Busan a Gyeongju: Tour de cerezos en flor",
      "subtitle": "Una lanzadera de temporada de 8,5 horas desde Busan hasta los principales lugares de cerezos en flor de Gyeongju — Lago Bomun, Daereungwon, Templo Bulguksa. Solo opera del 28 de mar al 10 de abr.",
      "region": "Gyeongju (desde Busan)",
      "duration": "8,5 horas",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Temporada de primavera",
        "Tour de cerezos en flor",
        "Sitios UNESCO",
        "Recogida en Busan"
      ],
      "heroImage": "/images/itinerary/bomun-lake-cherry-blossom-promenade.webp",
      "thumbnail": "/images/itinerary/bomun-lake-cherry-blossom-promenade.webp",
      "priceLabel": "",
      "shortCardDescription": "Un tour en lanzadera de 8,5 horas con salida desde Busan a los principales lugares de cerezos en flor de primavera en Gyeongju. El itinerario predeterminado incluye el Lago Bomun (8 km de paseo junto al lago bordeado de cerezos), el núcleo histórico de Cheomseongdae + Daereungwon (Áreas Históricas de Gyeongju, Patrimonio UNESCO), y el Templo Bulguksa (Patrimonio Mundial UNESCO con la doble flor de cerezo yaezakura de mediados de abril). Se confirman 2–3 paradas cada mañana según el informe de floración del día. El tour opera solo del 28 de marzo al 10 de abril — reembolso completo si la floración se retrasa considerablemente o ya ha terminado."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "busan-top-attractions-day-tour": {
    "catalog_card": {
      "slug": "busan-top-attractions-day-tour",
      "title": "Busan: Imprescindibles del Día",
      "subtitle": "El circuito clásico de siete paradas de Busan en un día equilibrado con tres puntos de recogida.",
      "region": "Busan",
      "duration": "10,5 horas",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Grupo pequeño",
        "Apto para primera visita",
        "Clásico de Busan",
        "Todo el año"
      ],
      "heroImage": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "thumbnail": "/images/tours/haedong-yonggungsa/haedong-yonggungsa-sunset-cliff.webp",
      "priceLabel": "",
      "shortCardDescription": "Tour de un día en grupo pequeño con 7 paradas que recorre el circuito clásico de Busan: el templo costero de Haedong Yonggungsa, Cheongsapo y el Parque Blue Line (Sky Capsule opcional), almuerzo local en Busan, Cementerio Memorial de la ONU, las laderas pintadas del Pueblo Cultural de Gamcheon y el Mercado de Pescado Jagalchi. Tres puntos de recogida en el centro de Busan; guía certificado de habla inglesa; minibús (≈12 personas máx.). La entrada a todos los sitios es gratuita; solo el almuerzo y las entradas opcionales se pagan el día del tour."
    },
    "price": {
      "amountLabel": "34"
    }
  },
  "east-signature-nature-core": {
    "catalog_card": {
      "slug": "east-signature-nature-core",
      "title": "Este de Jeju: Volcán, Costa y Aldea Folclórica",
      "subtitle": "Desde el Parque de Piedras de Jeju hasta Seongsan Ilchulbong, sigue la ruta más completa y equilibrada para conocer el este de Jeju por primera vez.",
      "region": "Este de Jeju",
      "duration": "8 horas",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Grupo pequeño",
        "Ideal para Primera Visita",
        "Signature del Este de Jeju"
      ],
      "heroImage": "/images/tours/jeju-stone-park/kakaotalk-20260510-230028438-19.webp",
      "thumbnail": "/images/tours/jeju-stone-park/kakaotalk-20260510-230028438-19.webp",
      "priceLabel": "",
      "shortCardDescription": "Un itinerario de día por el este de Jeju fácil de seguir que comienza con la cultura de la piedra y el contexto volcánico, recorre la costa y Seongsan Ilchulbong, y termina con Ilchulland y la Aldea Folclórica de Seongeup para una jornada más completa."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "from-busan-gyeongju-ancient-capital-day-tour": {
    "catalog_card": {
      "slug": "from-busan-gyeongju-ancient-capital-day-tour",
      "title": "Busan→Gyeongju: Capital Antigua",
      "subtitle": "Las seis paradas clásicas de Gyeongju a un ritmo más tranquilo y con regreso más temprano.",
      "region": "Gyeongju (desde Busán)",
      "duration": "10,5 horas",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Grupo pequeño",
        "Ritmo más tranquilo",
        "Desde Busán",
        "Regreso más temprano"
      ],
      "heroImage": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "thumbnail": "/images/tours/ahopsan-bamboo/chatgpt-image-2026-5-10-12-22-47.webp",
      "priceLabel": "Desde US$39 por persona (antes $50, 22% descuento)",
      "shortCardDescription": "Tour en grupo pequeño de un día desde Busán a Gyeongju, la antigua capital del reino Silla (57 a. C.–935 d. C.). El mismo recorrido clásico de seis atracciones que la versión UNESCO Legacy (Bosque de Bambú de Ahopsan → Templo Bulguksa UNESCO → Almuerzo ssambap en Gyeongju → Museo Nacional → Aldea Hanok de Gyochon → Puente Woljeonggyo), pero a un ritmo más tranquilo y con regreso más temprano (≈18:50). Guía certificado de habla inglesa/china; minivan; entradas gratuitas en todo el recorrido (solo Ahopsan ₩5.000 y el almuerzo se pagan en el día)."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "from-incheon-seoul-day-tour-cruise-guests": {
    "catalog_card": {
      "slug": "from-incheon-seoul-day-tour-cruise-guests",
      "title": "Incheon→Seúl: Tour de Crucero",
      "subtitle": "El circuito central de patrimonio, hanok, mercado y artesanía de Seúl desde su terminal de cruceros en Incheon.",
      "region": "Seúl (desde la terminal de cruceros de Incheon)",
      "duration": "9 horas",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Excursión en crucero",
        "Furgoneta compartida pequeña",
        "Recogida en el puerto de Incheon",
        "Ventana de 9 horas"
      ],
      "heroImage": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "thumbnail": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "priceLabel": "Desde US$69 por persona (antes $76, 9% descuento)",
      "shortCardDescription": "Excursión de un día en furgoneta compartida desde la Terminal de Cruceros de Incheon visitando los principales puntos turísticos del centro de Seúl en una ventana de 9 horas: Palacio Gyeongbokgung (o Changdeokgung los martes), Pueblo Hanok de Bukchon, almuerzo en el Mercado Gwangjang (el callejón de comida callejera más fotografiado de la ciudad) y la calle cultural de Insadong. Recogida coordinada con el desembarco específico de su barco; guía certificado con inglés y chino; ≈75 min de trayecto de regreso incluidos."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "incheon-seoul-private-car-shore-excursion-cruise": {
    "catalog_card": {
      "slug": "incheon-seoul-private-car-shore-excursion-cruise",
      "title": "Incheon→Seúl: Coche Privado Crucero",
      "subtitle": "Alquiler de auto privado para pasajeros de crucero — recogida en la pasarela de Incheon, día en Seúl totalmente personalizable, regreso a la terminal con 60 minutos de margen antes del zarpe.",
      "region": "Seúl (desde la terminal de cruceros de Incheon)",
      "duration": "8 horas",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Privado",
        "Crucero",
        "Excursión en tierra",
        "Los mejores atractivos de Seúl",
        "Personalizable",
        "Regreso garantizado"
      ],
      "heroImage": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "thumbnail": "/images/tours/gyeongbokgung/kakaotalk-20260510-222949305-09.webp",
      "priceLabel": "",
      "shortCardDescription": "Un alquiler de auto privado de 8 horas diseñado en torno a la hora de embarque de su crucero, no a un horario fijo. Recogida en la pasarela de la Terminal de Cruceros de Incheon, guía-conductor de habla inglesa e itinerario personalizable por el Palacio Gyeongbokgung, el Pueblo Hanok de Bukchon + Insadong, almuerzo a su elección, la Torre N de Seúl y Myeongdong o el Templo Jogyesa. El guía-conductor mantiene un margen de 60 minutos antes del zarpe para que nunca pierda el barco."
    },
    "price": {
      "amountLabel": "424"
    }
  },
  "jeju-cherry-blossom-tour-east-route": {
    "catalog_card": {
      "slug": "jeju-cherry-blossom-tour-east-route",
      "title": "Jeju Este: Tour de flores de cerezo",
      "subtitle": "De las calles en flor a la cueva de lava y al pico del amanecer.",
      "region": "Este de Jeju",
      "duration": "8 horas",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Solo en primavera",
        "Temporada de flores de cerezo",
        "Este de Jeju"
      ],
      "heroImage": "/images/tours/ilchulland/chatgpt-image-2026-5-8-07-45-52.webp",
      "thumbnail": "/images/tours/ilchulland/chatgpt-image-2026-5-8-07-45-52.webp",
      "priceLabel": "",
      "shortCardDescription": "Ruta por el este de Jeju, solo en primavera, a través de calles de cerezos en flor, la carretera de colza de 10 km, una cueva de tubo de lava y el icónico cráter de Seongsan."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "jeju-cruise-shore-excursion-bus-tour": {
    "catalog_card": {
      "slug": "jeju-cruise-shore-excursion-bus-tour",
      "title": "Excursión en tierra desde crucero en Jeju: Tour en autocar",
      "subtitle": "Tour de día desde crucero según el puerto, con opciones de ruta por Jeju y Gangjeong",
      "region": "Jeju (según el puerto de atraque)",
      "duration": "8 horas",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Excursión desde crucero",
        "Ruta según el puerto",
        "Crucero económico",
        "Autocar grande"
      ],
      "heroImage": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "thumbnail": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "priceLabel": "",
      "shortCardDescription": "Tour en autobús (autocar grande) desde crucero que adapta la ruta según el puerto de llegada. El Puerto de Jeju (norte) recorre una ruta UNESCO por la costa este pasando por Seongsan Ilchulbong; el Puerto de Gangjeong (sur) recorre una ruta por Hallasan 1100 + geología de la costa sur + Mercado Olle. Ambas rutas regresan a la terminal de cruceros con tiempo de margen suficiente."
    },
    "price": {
      "amountLabel": "59"
    }
  },
  "jeju-cruise-shore-excursion-small-group-tour": {
    "catalog_card": {
      "slug": "jeju-cruise-shore-excursion-small-group-tour",
      "title": "Jeju Crucero: Grupo Pequeño",
      "subtitle": "Tour de un día desde crucero con ruta adaptada al puerto, con variantes para Jeju y Gangjeong",
      "region": "Jeju (según puerto de llegada)",
      "duration": "8 horas",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Excursión desde crucero",
        "Ruta adaptada al puerto",
        "Crucero premium",
        "Grupo pequeño"
      ],
      "heroImage": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "thumbnail": "/images/tours/seongsan-ilchulbong/kakaotalk-20260510-230028438-06.webp",
      "priceLabel": "",
      "shortCardDescription": "Un tour en grupo pequeño desde crucero que adapta la ruta según el puerto de llegada. El Puerto de Jeju (norte) sigue una ruta costera este del Patrimonio UNESCO con parada en Seongsan Ilchulbong; el Puerto de Gangjeong (sur) incluye la ruta Hallasan 1100 + geología de la costa sur + Mercado Olle. Ambas rutas regresan a la terminal del crucero con tiempo de margen confortable."
    },
    "price": {
      "amountLabel": "77"
    }
  },
  "jeju-eastern-unesco-lugares-day-tour": {
    "catalog_card": {
      "slug": "jeju-eastern-unesco-lugares-day-tour",
      "title": "Jeju Este: UNESCO Día",
      "subtitle": "Minibús de grupo pequeño, guía en inglés y chino — recorre en un bucle por el este de 9 horas la playa Hamdeok, la Aldea Folclórica de Seongeup, Seongsan Ilchulbong (UNESCO), el espectáculo de buceo de las haenyeo y Manjanggul (UNESCO).",
      "region": "Jeju Este",
      "duration": "9 horas",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Grupo pequeño",
        "Jeju Este",
        "UNESCO",
        "Haenyeo",
        "Entradas incluidas"
      ],
      "heroImage": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "thumbnail": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "priceLabel": "",
      "shortCardDescription": "Recorre los lugares UNESCO del este de Jeju en un bucle en grupo pequeño de 9 horas. Incluye la playa Hamdeok Seoubong, la Aldea Folclórica de Seongeup (patrimonio folclórico UNESCO), Seongsan Ilchulbong y Manjanggul — los dos sitios del Patrimonio Natural Mundial de la UNESCO inscritos juntos en 2007 — y el espectáculo de buceo de las haenyeo (Museo de las Haenyeo si se cancela). Todas las entradas incluidas, guía certificado en inglés y chino."
    },
    "price": {
      "amountLabel": "49"
    }
  },
  "jeju-grand-highlights-loop": {
    "catalog_card": {
      "slug": "jeju-grand-highlights-loop",
      "title": "Gran Circuito de los Mejores Atractivos de Jeju",
      "subtitle": "Los tres sitios UNESCO de Jeju, un espectáculo de haenyeo en vivo, acantilados marinos y una cascada que cae al océano: lo mejor de la isla en un solo día.",
      "region": "Ruta por toda la isla de Jeju",
      "duration": "10–10,5 horas",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Grupo pequeño",
        "3 sitios UNESCO",
        "Ideal para visitantes de un solo día"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "",
      "shortCardDescription": "Una ruta intensa por toda la isla que enlaza tres sitios del Patrimonio Mundial de la UNESCO —Hallasan, Seongsan Ilchulbong y el tubo de lava de Manjanggul— con un espectáculo en vivo de buceo libre de las haenyeo, los acantilados columnares de Jusangjeolli y la cascada Jeongbang que cae al océano. Los atractivos emblemáticos de Jeju, concentrados en un solo día."
    },
    "price": {
      "amountLabel": "93"
    }
  },
  "jeju-hydrangea-festival-tour-east-route": {
    "catalog_card": {
      "slug": "jeju-hydrangea-festival-tour-east-route",
      "title": "Hortensias Jeju Este",
      "subtitle": "El azul de las hortensias, el verde esmeralda del mar y el dorado del Pico del Amanecer — verano en el este de Jeju.",
      "region": "Jeju Este (temporada hortensias)",
      "duration": "9 horas (solo jun-ago)",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Solo verano",
        "Festival hortensias",
        "Jeju Este",
        "Seongsan UNESCO",
        "Grupo pequeño"
      ],
      "heroImage": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "thumbnail": "/images/tours/hamdeok-beach/kakaotalk-20260510-230028438.webp",
      "priceLabel": "",
      "shortCardDescription": "El azul del verano de Jeju en un día: Playa Hamdeok (aguas esmeralda) → Aldea Folclórica Seongeup (1423) → Seongsan Ilchulbong (triple UNESCO) → Ilchul Land (Festival de Hortensias + Cueva Micheon) → Parque Natural Hueree (el mayor espectáculo de hortensias del sur de Jeju). Solo temporada de hortensias (junio-agosto). Grupo pequeño, recogida en hotel."
    },
    "price": {
      "amountLabel": "64"
    }
  },
  "jeju-hydrangea-festival-tour-southwest-route": {
    "catalog_card": {
      "slug": "jeju-hydrangea-festival-tour-southwest-route",
      "title": "Hortensias Jeju Suroeste",
      "subtitle": "De la playa al acantilado columnar y al túnel de hortensias.",
      "region": "Suroeste de Jeju",
      "duration": "9 horas",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Solo en verano",
        "Temporada de hortensias",
        "Suroeste de Jeju"
      ],
      "heroImage": "/images/tours/hyeopjae-beach/kakaotalk-20260510-230009595-01.webp",
      "thumbnail": "/images/tours/hyeopjae-beach/kakaotalk-20260510-230009595-01.webp",
      "priceLabel": "",
      "shortCardDescription": "Ruta exclusiva de verano por el suroeste de Jeju — playa esmeralda, jardines del festival de hortensias, acantilado columnar de la UNESCO, cascada de tres niveles, túnel de hortensias y campos de té."
    },
    "price": {
      "amountLabel": "64"
    }
  },
  "jeju-island-private-car-charter-tour": {
    "catalog_card": {
      "slug": "jeju-island-private-car-charter-tour",
      "title": "Jeju: Coche Privado",
      "subtitle": "Diseña tu propio día en Jeju con un conductor-guía licenciado y un vehículo privado con aire acondicionado.",
      "region": "Jeju (Este, Oeste o Sur)",
      "duration": "9 horas",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Tour Privado",
        "Ruta Personalizable",
        "Recogida en el Hotel Incluida"
      ],
      "heroImage": "/images/tours/jeju-private/jeju-private-thumbnail-carnival-coast.webp",
      "thumbnail": "/images/tours/jeju-private/jeju-private-thumbnail-carnival-coast.webp",
      "priceLabel": "",
      "shortCardDescription": "Alquiler de auto privado de 9 horas en Jeju con conductor-guía licenciado. Tres rutas recomendadas (Este, Oeste, Sur) recorren los lugares más emblemáticos de la isla, o crea la tuya propia entre monumentos de la UNESCO, escenarios de k-dramas, playas, campos de té y mercados tradicionales. La recogida en el hotel está incluida en cualquier punto de la isla."
    },
    "price": {
      "amountLabel": "254"
    }
  },
  "jeju-southern-top-unesco-spots-tour": {
    "catalog_card": {
      "slug": "jeju-southern-top-unesco-spots-tour",
      "title": "Excursión de un día emblemática por el sur de Jeju (Seogwipo)",
      "subtitle": "Circuito costero del sur de Jeju (Seogwipo) — Cascada Jeongbang, Sendero Olle de Oedolgae, Templo Yakcheonsa, Hallasan.",
      "region": "Sur de Jeju",
      "duration": "9 horas",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Grupo reducido",
        "Jeju",
        "Sur de Jeju",
        "Seogwipo",
        "Precio accesible",
        "Sin compras"
      ],
      "heroImage": "/images/tours/jeongbang-falls/kakaotalk-20260510-230028438-15.webp",
      "thumbnail": "/images/tours/jeongbang-falls/kakaotalk-20260510-230028438-15.webp",
      "priceLabel": "",
      "shortCardDescription": "Una excursión de un día en grupo reducido por los principales puntos emblemáticos del sur de Jeju (Seogwipo): la Cascada Jeongbang, la única de Asia que cae directamente al mar, la roca Oedolgae y el paseo costero del Sendero Olle Ruta 7, el Templo Yakcheonsa (el mayor de Asia Oriental), el Museo del Té Osulloc y el Sendero Eoseungsaengak del Hallasan. Cuatro puntos de recogida en toda la Ciudad de Jeju y el aeropuerto, guía certificado en inglés y chino, entrada gratuita en casi todas las paradas salvo la Cascada Jeongbang, sin presión de compras."
    },
    "price": {
      "amountLabel": "49"
    }
  },
  "jeju-west-south-full-day-authentic-tour": {
    "catalog_card": {
      "slug": "jeju-west-south-full-day-authentic-tour",
      "title": "Jeju Oeste-Sur: Auténtico",
      "subtitle": "Tierras altas UNESCO de Hallasan, Acantilado Jusangjeolli, borde del cráter de Songaksan, Cascadas Cheonjeyeon, té O'sulloc y playa Hyeopjae — el oeste y sur de Jeju en un día equilibrado.",
      "region": "Oeste y sur de Jeju",
      "duration": "9 horas",
      "stopsCount": 9,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Grupo pequeño",
        "Jeju",
        "Oeste y sur de Jeju",
        "UNESCO",
        "Cultura del café",
        "Costero"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "Desde US$59 por persona (antes $69, 14% descuento)",
      "shortCardDescription": "Un tour en grupo pequeño que combina las costas occidental y meridional de Jeju en un solo circuito: el Humedal de Altitud 1100 de Hallasan (UNESCO), el Acantilado Jusangjeolli de columnas hexagonales, el mirador panorámico de Songaksan, la Cascada Cheonjeyeon, el Museo del Té O'sulloc y la franja de cafés de la playa Hyeopjae en la costa oeste. Mismo operador que el tour UNESCO del sur, pero con un enfoque más orientado al estilo de vida: \"paisajes volcánicos que se encuentran con costas dramáticas y modernos cafés junto al mar.\""
    },
    "price": {
      "amountLabel": ""
    }
  },
  "jeju-winter-southwest-tangerine-snow-camellia-tour": {
    "catalog_card": {
      "slug": "jeju-winter-southwest-tangerine-snow-camellia-tour",
      "title": "Jeju en Invierno: Mandarinas, Nieve y Camelias",
      "subtitle": "Nieve en Hallasan, Camellia Hill en plena floración, recolección práctica de mandarinas, más Jusangjeolli y Cheonjeyeon — el suroeste de Jeju en invierno en 9 horas.",
      "region": "Suroeste de Jeju",
      "duration": "9 horas",
      "stopsCount": 8,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Grupo Reducido",
        "Jeju",
        "Invierno",
        "Temporada",
        "Mandarina",
        "Camelia",
        "Nieve"
      ],
      "heroImage": "/images/tours/jeju-tangerine-farm/photo-001.webp",
      "thumbnail": "/images/tours/jeju-tangerine-farm/photo-001.webp",
      "priceLabel": "",
      "shortCardDescription": "Un recorrido de día de temporada invernal por el suroeste de Jeju (de diciembre a febrero) centrado en las tres experiencias únicas de Jeju en invierno: nieve en las laderas de Hallasan, camelias rojas en plena floración en Camellia Hill y recolección propia de mandarinas de Jeju (gyul) en un huerto en activo. El itinerario también incluye las Cascadas de Cheonjeyeon, los acantilados de columnas basálticas de Jusangjeolli y el Museo del Té Osulloc. Recogida en hotel en Jeju City; guía oficial con habla inglesa y china."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "pocheon-sanjeong-lake-herb-island-art-valley": {
    "catalog_card": {
      "slug": "pocheon-sanjeong-lake-herb-island-art-valley",
      "title": "Pocheon: Lago, Hierbas y Cantera",
      "subtitle": "Lago de montaña, jardines de hierbas mediterráneos y una cantera convertida en parque de arte: la excursión de día más tranquila y estacional desde Seúl.",
      "region": "Pocheon (Excursión de un día desde Seúl)",
      "duration": "10 horas",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Naturaleza y Fotografía",
        "Destacados de Temporada",
        "Luces Románticas Nocturnas"
      ],
      "heroImage": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "thumbnail": "/images/tours/sanjeong-lake/chatgpt-image-2026-5-10-10-42-25.webp",
      "priceLabel": "",
      "shortCardDescription": "Una relajada excursión estacional de un día desde Seúl a Pocheon, el campo de Gyeonggi conocido por sus lagos, jardines de hierbas y dramáticos paisajes de parque artístico. El recorrido combina las aguas rodeadas de montañas del Lago Sanjeong, los jardines de estilo mediterráneo y las luces nocturnas de Herb Island, y el observatorio de la cantera de Pocheon Art Valley accesible en monorraíl. Menos concurrido que la Isla Nami y pensado para disfrutar de la calma fotográfica en lugar de ir de atracción en atracción."
    },
    "price": {
      "amountLabel": "54"
    }
  },
  "seoul-dmz-private-3rd-tunnel-suspension-bridge": {
    "catalog_card": {
      "slug": "seoul-dmz-private-3rd-tunnel-suspension-bridge",
      "title": "DMZ Seúl Privado: 3er Túnel y Puente",
      "subtitle": "La frontera dividida de Corea y un puente colgante de montaña de 150 metros en un día privado desde Seúl.",
      "region": "Paju (Excursión de un día desde Seúl)",
      "duration": "8–9 horas",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Tour Privado",
        "DMZ + Puente Colgante",
        "Recogida en el Hotel Incluida"
      ],
      "heroImage": "/images/tours/imjingak/chatgpt-image-2026-5-10-10-40-40.webp",
      "thumbnail": "/images/tours/imjingak/chatgpt-image-2026-5-10-10-40-40.webp",
      "priceLabel": "",
      "shortCardDescription": "Una excursión privada de un día que combina el lugar histórico más solemne de Corea con uno de sus puentes de montaña más fotogénicos. Mañana en el DMZ (Parque de la Paz de Imjingak, 3er Túnel de Infiltración, Observatorio Dora), y por la tarde un paseo sobre el Puente Colgante Rojo de Gamaksan de 150 metros. Se requiere pasaporte para la sección del DMZ."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-private-nami-morning-calm-petite-france": {
    "catalog_card": {
      "slug": "seoul-private-nami-morning-calm-petite-france",
      "title": "Tour Privado desde Seúl: Nami, Morning Calm y Petite France",
      "subtitle": "Tres de los destinos de excursión de un día más fotografiados de Corea, en un vehículo privado y sin el ritmo acelerado de los tours en autobús.",
      "region": "Gapyeong (Excursión de un día desde Seúl)",
      "duration": "9 a 10 horas",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Tour Privado",
        "Lugares de Rodaje de K-Dramas",
        "Parejas y Familias"
      ],
      "heroImage": "/images/tours/nami-island/kakaotalk-20260510-222949305-04.webp",
      "thumbnail": "/images/tours/nami-island/kakaotalk-20260510-222949305-04.webp",
      "priceLabel": "",
      "shortCardDescription": "Una excursión privada de un día desde Seúl que incluye la experiencia del ferry entre los árboles de la Isla Nami, los paseos temáticos por los jardines del Garden of Morning Calm y el colorido pueblo de El Principito en Petite France. La recogida en hotel, el vehículo privado y el ritmo tranquilo hacen de esta la versión más cómoda del clásico circuito por Gapyeong."
    },
    "price": {
      "amountLabel": "194"
    }
  },
  "seoul-seoraksan-naksansa-temple-naksan-beach-day-trip": {
    "catalog_card": {
      "slug": "seoul-seoraksan-naksansa-temple-naksan-beach-day-trip",
      "title": "Gangwon-do desde Seúl: Seoraksan + Templo Naksansa + Playa de Naksan",
      "subtitle": "Los picos de granito de Seoraksan, un templo milenario junto al mar y una playa del Mar del Este bordeada de pinos, todo en una sola excursión de 12 horas desde Seúl.",
      "region": "Seúl → Gangwon (Seoraksan y Yangyang)",
      "duration": "12 horas",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Excursión de un día desde Seúl",
        "Autocar con aire acondicionado",
        "Lunes y jueves",
        "Día de 12 horas"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "From US$52 per person (was $58, 10% off)",
      "shortCardDescription": "Una excursión de 12 horas en autocar desde Seúl hasta la costa del Mar del Este: senderismo en el Parque Nacional Seoraksan, visita al Templo Naksansa en los acantilados y paseo por la Playa de Naksan bordeada de pinos. Sale los lunes y jueves con guía en inglés y traslados de ida y vuelta desde Hongik o Myeongdong."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-seoraksan-nami-island-morning-calm-day-tour": {
    "catalog_card": {
      "slug": "seoul-seoraksan-nami-island-morning-calm-day-tour",
      "title": "Seúl: Seoraksan + Nami + Calma Matutina",
      "subtitle": "La montaña Seoraksan, la isla arbolada de Nami y el jardín temático de la Calma Matutina en una sola excursión de 13 horas desde Seúl.",
      "region": "Seúl → Gangwon → Gyeonggi",
      "duration": "13 horas",
      "stopsCount": 3,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Excursión de un día desde Seúl",
        "Autobús de gran capacidad",
        "Todas las entradas incluidas",
        "Día de 13 horas"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "Desde 59 USD por persona (antes $82, 28% de descuento)",
      "shortCardDescription": "Un tour de un día en autobús de 13 horas desde Seúl que recorre las tres paradas más fotografiadas de Corea: el Parque Nacional Seoraksan (la única Reserva de Biosfera de la UNESCO en Corea), la Isla Nami (el Paseo de las Metasecuoyas de Winter Sonata) y el Jardín de la Calma Matutina (el arboreto privado más emblemático de Corea con 5.000 especies de plantas). Todas las entradas incluidas; guía en inglés; recogida en la Estación de la Universidad Hongik o en la Estación de Myeongdong."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-seoraksan-national-park-sokcho-beach-day-trip": {
    "catalog_card": {
      "slug": "seoul-seoraksan-national-park-sokcho-beach-day-trip",
      "title": "Excursión de un día a Seoraksan y la Playa de Sokcho",
      "subtitle": "Una excursión de un día en grupo reducido desde Seúl hasta el parque nacional más querido de Corea y la ciudad costera de Sokcho, a orillas del Mar del Este.",
      "region": "Seoraksan, Gangwon-do",
      "duration": "12 horas",
      "stopsCount": 5,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Grupo Pequeño",
        "Naturaleza",
        "Pintoresco",
        "Playa",
        "Mercado de Mariscos",
        "Follaje Otoñal",
        "Excursión de un día"
      ],
      "heroImage": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "thumbnail": "/images/tours/seoraksan-national-park/seoraksan-ridge-view.webp",
      "priceLabel": "",
      "shortCardDescription": "Una excursión de un día en grupo reducido desde Seúl hasta el parque nacional más querido de Corea y la ciudad costera de Sokcho, a orillas del Mar del Este. El recorrido combina los picos de granito, los valles y el patrimonio budista de Seoraksan con el mercado de mariscos y la playa de Sokcho — una combinación de montaña y océano que solo ofrece la costa este. 12 horas con guía de habla inglesa y transporte de ida y vuelta."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suburbs-private-chartered-car-10hr": {
    "catalog_card": {
      "slug": "seoul-suburbs-private-chartered-car-10hr",
      "title": "Chárter de Auto Privado en Seúl",
      "subtitle": "Diseña tu propio día por Seúl o sus alrededores con un conductor-guía privado y con licencia.",
      "region": "Seúl y Alrededores",
      "duration": "10 horas",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Tour Privado",
        "Totalmente Personalizable",
        "Recogida Gratuita en Hotel en Seúl"
      ],
      "heroImage": "/images/tours/seoul-private-charter/seoul-private-carnival-han-river-night.webp",
      "thumbnail": "/images/tours/seoul-private-charter/seoul-private-carnival-han-river-night.webp",
      "priceLabel": "",
      "shortCardDescription": "Un chárter de auto privado premium de 10 horas que te permite diseñar tu propio día por la zona de Seúl. Elige una de las tres rutas recomendadas —Isla Nami + Morning Calm + Petite France + Gangchon Railbike, DMZ + Paju Outlet, o Everland + Pueblo Folclórico Coreano— o envía tu propio itinerario. La recogida gratuita en hotel está incluida para estancias en el centro de Seúl."
    },
    "price": {
      "amountLabel": "184"
    }
  },
  "seoul-suwon-hwaseong-folk-village-starfield-library": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-folk-village-starfield-library",
      "title": "Suwon: Hwaseong, Pueblo Folclórico y Starfield",
      "subtitle": "Una excursión cultural de día en grupo reducido desde Seúl hasta la provincia de Gyeonggi, que abarca cuatro facetas contrastantes del patrimonio coreano y la vida moderna: la declarada Patrimonio de la Humanidad…",
      "region": "Gyeonggi-do (al sur de Seúl)",
      "duration": "10 horas",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Grupo Reducido",
        "Cultura",
        "UNESCO",
        "Patrimonio",
        "Biblioteca",
        "Pueblo Folclórico",
        "Excursión de un día"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "Una excursión cultural de día en grupo reducido desde Seúl hasta la provincia de Gyeonggi, que abarca cuatro facetas contrastantes del patrimonio coreano y la vida moderna: la Fortaleza Suwon Hwaseong (Patrimonio de la Humanidad UNESCO, con murallas y puertas del siglo XVIII), el restaurado Palacio Hwaseong Haenggung con sus recreaciones de la era Joseon, el envolvente Pueblo Folclórico Coreano al aire libre en Yongin, y la espectacular Biblioteca Starfield Suwon de cuatro plantas. 10 horas con transporte y entradas incluidos."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-gwangmyeong-cave-starfield-library",
      "title": "Suwon: Hwaseong, Cueva Gwangmyeong y Starfield",
      "subtitle": "Una excursión cultural de un día en grupo reducido desde Seúl que recorre cuatro facetas contrastantes de la provincia de Gyeonggi: la Fortaleza Suwon Hwaseong declarada Patrimonio de la UNESCO, con sus…",
      "region": "Gyeonggi-do (al sur de Seúl)",
      "duration": "9 horas",
      "stopsCount": 6,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Grupo reducido",
        "Cultura",
        "UNESCO",
        "Cueva",
        "Biblioteca",
        "Compras",
        "Excursión de un día"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "Una excursión cultural de un día en grupo reducido desde Seúl que recorre tres facetas contrastantes de la provincia de Gyeonggi: la Fortaleza Suwon Hwaseong declarada Patrimonio de la UNESCO, con sus murallas del siglo XVIII y el Palacio Haenggung; el impresionante parque temático subterráneo iluminado con LED en el interior de la Cueva Gwangmyeong (una antigua mina de oro de la época japonesa); la Biblioteca Starfield de Suwon de cuatro pisos. 9 horas con transporte y entradas incluidos."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "seoul-suwon-hwaseong-waujeongsa-starfield": {
    "catalog_card": {
      "slug": "seoul-suwon-hwaseong-waujeongsa-starfield",
      "title": "Suwon: Hwaseong, Waujeongsa y Starfield",
      "subtitle": "Fortaleza UNESCO, templo de montaña y biblioteca viral: el pasado, el espíritu y el presente de Corea en una excursión de un día desde Seúl.",
      "region": "Suwon y Yongin",
      "duration": "9–10 horas",
      "stopsCount": 4,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Patrimonio UNESCO",
        "Excursión de un día: Patrimonio + Modernidad",
        "Entradas incluidas"
      ],
      "heroImage": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "thumbnail": "/images/tours/suwon-hwaseong/kakaotalk-20260510-222949305.webp",
      "priceLabel": "",
      "shortCardDescription": "Una excursión en grupo reducido desde Seúl que recorre tres facetas contrastantes de Corea: la Fortaleza de Suwon Hwaseong, declarada Patrimonio UNESCO (arquitectura militar del siglo XVIII), la fotogénica Biblioteca Starfield Suwon (icono cultural contemporáneo) y el Templo Waujeongsa en Yongin (gigantesco Buda al aire libre y campana de piedra). Gran valor patrimonial con transporte y entradas incluidos."
    },
    "price": {
      "amountLabel": ""
    }
  },
  "southwest-hallasan-osulloc-aewol": {
    "catalog_card": {
      "slug": "southwest-hallasan-osulloc-aewol",
      "title": "Suroeste de Jeju: Hallasan, O'Sulloc, Aewol e Iho Tewoo",
      "subtitle": "Pasarela del humedal de las Tierras Altas 1100, acantilados volcánicos, sendero a la cascada, campos de té y un final al atardecer en Aewol e Iho Tewoo",
      "region": "Suroeste de Jeju",
      "duration": "9 horas",
      "stopsCount": 7,
      "rating": 0,
      "reviewCount": 0,
      "badges": [
        "Ideal para visitantes de Jeju por primera vez",
        "Suroeste de Jeju"
      ],
      "heroImage": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "thumbnail": "/images/tours/hallasan-1100/kakaotalk-20260510-230009595-21.webp",
      "priceLabel": "",
      "shortCardDescription": "Una ruta equilibrada de un día por el suroeste de Jeju que enlaza el humedal de las Tierras Altas 1100 de Hallasan, la costa volcánica, la Cascada Cheonjeyeon, los campos de té O'Sulloc, la calle de cafeterías de Aewol y el atardecer en Iho Tewoo."
    },
    "price": {
      "amountLabel": "49"
    }
  }
};
