export {
  GEMINI_ITINERARY_SYSTEM_PROMPT,
  GEMINI_ITINERARY_USER_PROMPT_TEMPLATE,
} from './gemini-itinerary.prompts';
export {
  CLAUDE_ITINERARY_REVIEW_SYSTEM_PROMPT,
  CLAUDE_ITINERARY_REVIEW_USER_TEMPLATE,
} from './claude-itinerary.prompts';
