import type { TourMatchingProfileRow } from "@/lib/tour-product-match/types";

/**
 * In-app seed — mirrors `tour_matching_profiles` for live `/tour-product/[slug]` SKUs.
 */
export const SEED_TOUR_MATCHING_PROFILES: TourMatchingProfileRow[] = [
  {
    product_id: "east-signature-nature-core",
    product_type: "small_group",
    route_type: "fixed_route",
    region_type: "east",
    region_tags: ["jeju_east"],
    theme_tags: ["volcano", "coast", "village", "culture", "geology", "first_time_friendly", "iconic_landmarks"],
    poi_tags: ["stone_park", "seopjikoji", "seongsan_ilchulbong", "ilchulland", "seongeup_folk_village"],
    pace_level: 3,
    walking_level: 3,
    scenic_level: 5,
    photo_level: 4,
    culture_level: 4,
    relax_level: 3,
    first_time_fit: 5,
    family_fit: 4,
    senior_fit: 4,
    couple_fit: 4,
    active_traveler_fit: 4,
    one_day_fit: 4,
    same_day_flight_fit: 2,
    rain_fit: 3,
    value_for_money_fit: 5,
    iconic_landmark_fit: 5,
    cafe_fit: 2,
    adult_family_fit: 4,
    young_kids_fit: 3,
    senior_active_fit: 3,
    senior_general_fit: 4,
    mobility_friendly_fit: 3,
    stroller_fit: 3,
    indoor_ratio: 42,
    weather_sensitivity: 3,
    local_culture_fit: 4,
    shopping_fit: 2,
    storytelling_fit: 4,
    comfort_level: 3,
    budget_fit: 4,
    premium_fit: 3,
    small_group_fit: 5,
    private_fit: 1,
    bus_fit: 2,
    price_band: "mid",
    pickup_base: "jeju_city",
    return_time_band: "17:30-18:00",
    duration_band: "8h",
    min_recommended_age: 8,
    hard_constraints: {
      avoidIf: ["monday_departure_required", "tight_same_day_departure", "strictly_indoor_preference"],
      notIdealFor: ["very_low_mobility", "stroller_heavy"],
    },
    walking_notes: [
      "moderate overall across a full 8-hour day",
      "seongsan summit is optional but is the steepest segment",
    ],
    keywords: [
      "east jeju",
      "east jeju small group",
      "first-time jeju",
      "seongsan ilchulbong",
      "seopjikoji",
      "jeju stone park",
    ],
    synonym_hints: [
      "iconic east",
      "balanced day",
      "classic jeju east",
      "geology coast culture",
      "east volcano coast village",
      "first trip east jeju",
      "east coast highlights",
    ],
    profile_version: 3,
    is_active: true,
  },
  {
    product_id: "jeju-grand-highlights-loop",
    product_type: "small_group",
    route_type: "fixed_route",
    region_type: "full_island",
    region_tags: ["jeju_all_around", "hallasan_to_seongsan"],
    theme_tags: ["hallasan", "basalt", "waterfall", "crater", "fast_paced", "one_day"],
    poi_tags: ["eoseungsaengak", "jusangjeolli", "jeongbang", "seongsan"],
    pace_level: 5,
    walking_level: 4,
    scenic_level: 5,
    photo_level: 5,
    culture_level: 2,
    relax_level: 2,
    first_time_fit: 4,
    family_fit: 2,
    senior_fit: 2,
    couple_fit: 4,
    active_traveler_fit: 5,
    one_day_fit: 5,
    same_day_flight_fit: 1,
    rain_fit: 4,
    value_for_money_fit: 3,
    iconic_landmark_fit: 4,
    cafe_fit: 2,
    adult_family_fit: 3,
    young_kids_fit: 2,
    senior_active_fit: 3,
    senior_general_fit: 2,
    mobility_friendly_fit: 2,
    stroller_fit: 2,
    indoor_ratio: 28,
    weather_sensitivity: 4,
    local_culture_fit: 2,
    shopping_fit: 2,
    storytelling_fit: 3,
    comfort_level: 2,
    budget_fit: 3,
    premium_fit: 3,
    small_group_fit: 5,
    private_fit: 1,
    bus_fit: 2,
    price_band: "mid",
    pickup_base: "jeju_city",
    return_time_band: "17:40-18:15",
    duration_band: "9.5h",
    min_recommended_age: 10,
    hard_constraints: {
      avoidIf: ["needs_slow_pace", "tight_same_day_departure", "strict_same_day_flight_schedule"],
      notIdealFor: ["stroller_heavy", "very_low_mobility", "toddlers"],
    },
    walking_notes: ["uphill at Hallasan", "steps at Jeongbang", "optional Seongsan summit"],
    keywords: [
      "jeju one day",
      "jeju full island loop",
      "hallasan",
      "seongsan",
      "jusangjeolli",
      "jeongbang",
      "grand tour jeju",
      "fast paced jeju",
      "jeju highlights",
    ],
    synonym_hints: [
      "full island loop",
      "highlights in one day",
      "busy but iconic",
      "see more in one day",
      "fast highlights route",
    ],
    profile_version: 3,
    is_active: true,
  },
];
