-- =============================================================================
-- east-signature-nature-core — matching profile v2 (sync with authoring JSON)
-- =============================================================================
-- Source: east-signature-nature-core.with-matching-profile.en.json (matching_profile)
-- Runtime reco still reads tour_matching_profiles; detail_payload may embed copy for review only.
-- =============================================================================

BEGIN;

INSERT INTO public.tour_matching_profiles (
  product_id,
  product_type,
  route_type,
  region_type,
  region_tags,
  theme_tags,
  poi_tags,
  pace_level,
  walking_level,
  scenic_level,
  photo_level,
  culture_level,
  relax_level,
  first_time_fit,
  family_fit,
  senior_fit,
  couple_fit,
  active_traveler_fit,
  one_day_fit,
  same_day_flight_fit,
  rain_fit,
  value_for_money_fit,
  iconic_landmark_fit,
  cafe_fit,
  pickup_base,
  return_time_band,
  duration_band,
  min_recommended_age,
  hard_constraints,
  walking_notes,
  keywords,
  synonym_hints,
  profile_version,
  is_active
)
VALUES (
  'east-signature-nature-core',
  'small_group',
  'fixed_route',
  'east',
  '["jeju_east"]'::JSONB,
  '["volcano","coast","village","culture","geology","first_time_friendly","iconic_landmarks"]'::JSONB,
  '["stone_park","seopjikoji","seongsan_ilchulbong","ilchulland","seongeup_folk_village"]'::JSONB,
  3,
  3,
  5,
  4,
  4,
  3,
  5,
  4,
  4,
  4,
  4,
  4,
  2,
  3,
  5,
  5,
  2,
  'jeju_city',
  '17:30-18:00',
  '8h',
  8,
  '{"avoidIf":["monday_departure_required","tight_same_day_departure"],"notIdealFor":["very_low_mobility","stroller_heavy_if_summit_focus"]}'::JSONB,
  '["moderate overall across a full 8-hour day","seongsan summit is optional but is the steepest segment","stone park is mostly flat; ilchulland includes mixed and sometimes damp surfaces","comfortable grip shoes are strongly recommended"]'::JSONB,
  '["east jeju","east jeju small group","first-time jeju","seongsan ilchulbong","seopjikoji","jeju stone park","ilchulland","seongeup folk village","volcano coast village","unesco crater","jeju east day tour"]'::JSONB,
  '["iconic east","balanced day","classic jeju east","geology coast culture","east volcano coast village","first trip east jeju"]'::JSONB,
  2,
  TRUE
)
ON CONFLICT (product_id) DO UPDATE SET
  product_type = EXCLUDED.product_type,
  route_type = EXCLUDED.route_type,
  region_type = EXCLUDED.region_type,
  region_tags = EXCLUDED.region_tags,
  theme_tags = EXCLUDED.theme_tags,
  poi_tags = EXCLUDED.poi_tags,
  pace_level = EXCLUDED.pace_level,
  walking_level = EXCLUDED.walking_level,
  scenic_level = EXCLUDED.scenic_level,
  photo_level = EXCLUDED.photo_level,
  culture_level = EXCLUDED.culture_level,
  relax_level = EXCLUDED.relax_level,
  first_time_fit = EXCLUDED.first_time_fit,
  family_fit = EXCLUDED.family_fit,
  senior_fit = EXCLUDED.senior_fit,
  couple_fit = EXCLUDED.couple_fit,
  active_traveler_fit = EXCLUDED.active_traveler_fit,
  one_day_fit = EXCLUDED.one_day_fit,
  same_day_flight_fit = EXCLUDED.same_day_flight_fit,
  rain_fit = EXCLUDED.rain_fit,
  value_for_money_fit = EXCLUDED.value_for_money_fit,
  iconic_landmark_fit = EXCLUDED.iconic_landmark_fit,
  cafe_fit = EXCLUDED.cafe_fit,
  pickup_base = EXCLUDED.pickup_base,
  return_time_band = EXCLUDED.return_time_band,
  duration_band = EXCLUDED.duration_band,
  min_recommended_age = EXCLUDED.min_recommended_age,
  hard_constraints = EXCLUDED.hard_constraints,
  walking_notes = EXCLUDED.walking_notes,
  keywords = EXCLUDED.keywords,
  synonym_hints = EXCLUDED.synonym_hints,
  profile_version = EXCLUDED.profile_version,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

COMMIT;
