/**
 * East Signature Nature Core → Supabase 시드 파일 생성
 * 출력: supabase/manual/generated/east-signature-nature-core-detail-payload.json
 *       supabase/manual/generated/insert-tour-product-page-east-signature.generated.sql
 *
 * 실행: npm run gen:tour-product-seed
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { eastSignatureNatureCoreStaticProduct } from "../components/product-tour-static/catalog/staticTourProductRegistry";
import { buildEastSignatureDetailPayloadForSupabase } from "../components/product-tour-static/east-signature-nature-core/buildDetailPayloadForSeed";
import { eastSignatureNatureCoreProduct } from "../components/product-tour-static/east-signature-nature-core/staticProductData";
import { eastSignatureNatureCoreDetailViewModel } from "../components/product-tour-static/east-signature-nature-core/eastSignatureNatureCoreDetailViewModel";
function sqlStr(s: string) {
  return `'${s.replace(/'/g, "''")}'`;
}

const reg = eastSignatureNatureCoreStaticProduct;
const prod = eastSignatureNatureCoreProduct;
const payload = buildEastSignatureDetailPayloadForSupabase();
const jsonStr = JSON.stringify(payload);
const sqlJsonLiteral = sqlStr(jsonStr);

const slug = reg.slug;
const listCurrency = String(prod.price.currency).toUpperCase();
const parsedList = Number(String(prod.price.amountLabel).replace(/,/g, ""));
const offerAmountMinor =
  listCurrency === "USD"
    ? Math.round(parsedList * 100)
    : Math.round(parsedList);
const offerCurrency = listCurrency === "USD" ? "USD" : "KRW";
const offerAmountSql =
  Number.isFinite(offerAmountMinor) && offerAmountMinor > 0
    ? String(offerAmountMinor)
    : listCurrency === "USD"
      ? "5800"
      : "78300";

const sql = `-- AUTO-GENERATED by npm run gen:tour-product-seed — 재생성 시 덮어씀
BEGIN;

INSERT INTO public.tour_product_pages (
  slug, locale, is_published, sort_order, tour_id,
  title, subtitle, region_label, duration_label, stops_count,
  rating_avg, review_count, badges, hero_image_url, thumbnail_url,
  card_short_description, seo_title, meta_description,
  headline_line_1, headline_line_2,
  price_amount_label, price_currency, price_per,
  detail_payload
) VALUES (
  ${sqlStr(slug)},
  'en',
  TRUE,
  0,
  (SELECT id FROM public.tours WHERE slug = ${sqlStr(slug)} LIMIT 1),
  ${sqlStr(reg.title)},
  ${sqlStr(reg.subtitle)},
  ${sqlStr(reg.region)},
  ${sqlStr(reg.duration)},
  ${reg.stopsCount},
  ${reg.rating},
  ${reg.reviewCount},
  ARRAY[${reg.badges.map((b) => sqlStr(b)).join(", ")}]::text[],
  ${sqlStr(reg.heroImage)},
  ${sqlStr(reg.thumbnail)},
  ${sqlStr(reg.shortCardDescription)},
  ${sqlStr(`${reg.title} | AtoC Korea`)},
  ${sqlStr(prod.description)},
  ${sqlStr(eastSignatureNatureCoreDetailViewModel.headlineLine1)},
  ${sqlStr(eastSignatureNatureCoreDetailViewModel.headlineLine2)},
  ${sqlStr(prod.price.amountLabel)},
  ${sqlStr(prod.price.currency)},
  ${sqlStr(prod.price.per)},
  ${sqlJsonLiteral}::jsonb
)
ON CONFLICT (slug, locale) DO UPDATE SET
  is_published = EXCLUDED.is_published,
  tour_id = EXCLUDED.tour_id,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  region_label = EXCLUDED.region_label,
  duration_label = EXCLUDED.duration_label,
  stops_count = EXCLUDED.stops_count,
  rating_avg = EXCLUDED.rating_avg,
  review_count = EXCLUDED.review_count,
  badges = EXCLUDED.badges,
  hero_image_url = EXCLUDED.hero_image_url,
  thumbnail_url = EXCLUDED.thumbnail_url,
  card_short_description = EXCLUDED.card_short_description,
  seo_title = EXCLUDED.seo_title,
  meta_description = EXCLUDED.meta_description,
  headline_line_1 = EXCLUDED.headline_line_1,
  headline_line_2 = EXCLUDED.headline_line_2,
  price_amount_label = EXCLUDED.price_amount_label,
  price_currency = EXCLUDED.price_currency,
  price_per = EXCLUDED.price_per,
  detail_payload = EXCLUDED.detail_payload,
  updated_at = NOW();

INSERT INTO public.tour_product_offers (
  tour_product_page_id, label, amount_minor, currency, stripe_price_id, is_active, is_default
)
SELECT
  p.id,
  'Default (seed)',
  ${offerAmountSql},
  ${sqlStr(offerCurrency)},
  NULL,
  TRUE,
  TRUE
FROM public.tour_product_pages p
WHERE p.slug = ${sqlStr(slug)} AND p.locale = 'en'
  AND NOT EXISTS (
    SELECT 1 FROM public.tour_product_offers o
    WHERE o.tour_product_page_id = p.id AND o.is_default = TRUE
  );

COMMIT;
`;

const outDir = join(process.cwd(), "supabase/manual/generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "east-signature-nature-core-detail-payload.json"), JSON.stringify(payload, null, 2), "utf8");
writeFileSync(join(outDir, "insert-tour-product-page-east-signature.generated.sql"), sql, "utf8");

console.log("Wrote:");
console.log(" ", join(outDir, "east-signature-nature-core-detail-payload.json"));
console.log(" ", join(outDir, "insert-tour-product-page-east-signature.generated.sql"));
