import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  CURATED_POI_PROFILE_OVERRIDES,
  CURATED_POI_PROFILE_SOURCE,
  CURATED_POI_PROFILE_VERSION,
} from "../lib/itinerary-match-engine/poi-profile-overrides";
import { BUILDER_POI_META } from "../lib/itinerary-match-engine/poi-taxonomy";

const DEFAULT_OUTPUT =
  "supabase/migrations/20260518143000_promote_itinerary_builder_poi_profiles.sql";

const BUILDER_REGIONS = [
  "busan",
  "yangsan",
  "gyeongju",
  "ulsan",
  "miryang",
  "jeju",
];

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlTextArray(values: string[]): string {
  if (values.length === 0) return "ARRAY[]::text[]";
  return `ARRAY[${values.map(sqlString).join(", ")}]::text[]`;
}

function sqlJsonb(value: unknown): string {
  return `${sqlString(JSON.stringify(value))}::jsonb`;
}

function assertSeedCoverage(): string[] {
  const profileKeys = Object.keys(CURATED_POI_PROFILE_OVERRIDES).sort();
  const metaKeys = Object.keys(BUILDER_POI_META).sort();
  const missingMeta = profileKeys.filter((key) => !BUILDER_POI_META[key]);
  const missingProfile = metaKeys.filter((key) => !CURATED_POI_PROFILE_OVERRIDES[key]);

  if (missingMeta.length || missingProfile.length) {
    throw new Error(
      [
        "Itinerary builder POI seed coverage mismatch.",
        missingMeta.length ? `Missing taxonomy: ${missingMeta.join(", ")}` : "",
        missingProfile.length ? `Missing profiles: ${missingProfile.join(", ")}` : "",
      ]
        .filter(Boolean)
        .join("\n"),
    );
  }

  return profileKeys;
}

export function generateMigrationSql(): string {
  const poiKeys = assertSeedCoverage();
  const rows = poiKeys.map((poiKey) => {
    const profile = CURATED_POI_PROFILE_OVERRIDES[poiKey];
    const meta = BUILDER_POI_META[poiKey];
    return `    (${sqlString(poiKey)}, ${sqlJsonb(profile)}, ${sqlString(meta.kind)}, ${sqlTextArray(meta.subRegions)}, ${sqlString(meta.categoryGroup)}, ${sqlTextArray(meta.rationaleTags)})`;
  });

  const builderRegions = BUILDER_REGIONS.map(sqlString).join(", ");

  return `-- Promote itinerary-builder POI matching profiles from runtime overrides to DB source-of-truth.
-- Generated by scripts/generate-itinerary-builder-poi-profile-migration.ts.
-- Source data: lib/itinerary-match-engine/poi-profile-overrides.ts and poi-taxonomy.ts.

ALTER TABLE public.match_pois
  ADD COLUMN IF NOT EXISTS builder_profile_source text,
  ADD COLUMN IF NOT EXISTS builder_profile_version integer;

CREATE INDEX IF NOT EXISTS idx_match_pois_builder_profile_source
  ON public.match_pois (builder_profile_source)
  WHERE builder_profile_source IS NOT NULL;

CREATE TEMP TABLE _itinerary_builder_curated_pois (
  poi_key text PRIMARY KEY,
  matching_profile jsonb NOT NULL,
  builder_kind text NOT NULL,
  builder_sub_regions text[] NOT NULL,
  builder_category_group text NOT NULL,
  builder_rationale_tags text[] NOT NULL
) ON COMMIT DROP;

INSERT INTO _itinerary_builder_curated_pois
  (poi_key, matching_profile, builder_kind, builder_sub_regions, builder_category_group, builder_rationale_tags)
VALUES
${rows.join(",\n")};

UPDATE public.match_pois AS mp
SET
  matching_profile = curated.matching_profile,
  stop_role = CASE WHEN curated.builder_kind = 'logistics' THEN 'logistics' ELSE 'attraction' END,
  is_attraction = curated.builder_kind = 'attraction',
  builder_profile_source = ${sqlString(CURATED_POI_PROFILE_SOURCE)},
  builder_profile_version = ${CURATED_POI_PROFILE_VERSION},
  poi_meta = COALESCE(mp.poi_meta, '{}'::jsonb) || jsonb_build_object(
    'builder',
    jsonb_build_object(
      'kind', curated.builder_kind,
      'sub_regions', to_jsonb(curated.builder_sub_regions),
      'category_group', curated.builder_category_group,
      'rationale_tags', to_jsonb(curated.builder_rationale_tags),
      'profile_source', ${sqlString(CURATED_POI_PROFILE_SOURCE)},
      'profile_version', ${CURATED_POI_PROFILE_VERSION}
    )
  ),
  updated_at = now()
FROM _itinerary_builder_curated_pois AS curated
WHERE mp.poi_key = curated.poi_key;

-- Keep any non-curated POIs out of the public itinerary builder until reviewed.
UPDATE public.match_pois AS mp
SET
  stop_role = 'hidden',
  is_attraction = false,
  poi_meta = COALESCE(poi_meta, '{}'::jsonb) || jsonb_build_object(
    'builder',
    COALESCE(poi_meta->'builder', '{}'::jsonb) || jsonb_build_object(
      'kind', 'hidden'
    )
  ),
  updated_at = now()
WHERE mp.poi_key NOT IN (SELECT poi_key FROM _itinerary_builder_curated_pois)
  AND (mp.region IN (${builderRegions}) OR mp.region ILIKE 'Jeju%');
`;
}

function parseOutputPath(args: string[]): string {
  const outIndex = args.indexOf("--out");
  if (outIndex === -1) return DEFAULT_OUTPUT;
  const output = args[outIndex + 1];
  if (!output || output.startsWith("--")) {
    throw new Error("Expected a file path after --out.");
  }
  return output;
}

export function main(args = process.argv.slice(2), cwd = process.cwd()): void {
  const outputPath = resolve(cwd, parseOutputPath(args));
  const generatedSql = generateMigrationSql();

  if (args.includes("--check")) {
    const existingSql = readFileSync(outputPath, "utf8").replace(/\r\n/g, "\n");
    if (existingSql !== generatedSql) {
      console.error(`Migration is out of sync with itinerary builder POI seeds: ${outputPath}`);
      process.exit(1);
    }
    console.log(`Migration is in sync: ${outputPath}`);
  } else {
    writeFileSync(outputPath, generatedSql, "utf8");
    console.log(`Wrote itinerary builder POI migration: ${outputPath}`);
  }
}

if (require.main === module) {
  main();
}
