-- =============================================================================
-- tour_matching_profiles — 3 Jeju small-group products (full column set)
-- =============================================================================
-- Run AFTER migrations:
--   20260415180000_tour_matching_profiles_extended_fits.sql
--   20260415210000_tour_matching_profiles_comfort_pricing.sql
-- Use in Supabase SQL Editor to upsert all matching dimensions.
-- =============================================================================

BEGIN;

INSERT INTO public.tour_matching_profiles (
  product_id,
  product_type,
  route_type,
  region_type,
  region_tags,
  theme_tags,
  poi_tags,
  pace_level,
  walking_level,
  scenic_level,
  photo_level,
  culture_level,
  relax_level,
  first_time_fit,
  family_fit,
  senior_fit,
  couple_fit,
  active_traveler_fit,
  one_day_fit,
  same_day_flight_fit,
  rain_fit,
  value_for_money_fit,
  iconic_landmark_fit,
  cafe_fit,
  adult_family_fit,
  young_kids_fit,
  senior_active_fit,
  senior_general_fit,
  mobility_friendly_fit,
  stroller_fit,
  indoor_ratio,
  weather_sensitivity,
  local_culture_fit,
  shopping_fit,
  storytelling_fit,
  comfort_level,
  budget_fit,
  premium_fit,
  small_group_fit,
  private_fit,
  bus_fit,
  price_band,
  pickup_base,
  return_time_band,
  duration_band,
  min_recommended_age,
  hard_constraints,
  walking_notes,
  keywords,
  synonym_hints,
  profile_version,
  is_active
)
VALUES
-- East (unchanged base scores from v2; extended dims filled for new columns)
(
  'east-signature-nature-core',
  'small_group',
  'fixed_route',
  'east',
  '["jeju_east"]'::JSONB,
  '["volcano","coast","village","culture","geology","first_time_friendly","iconic_landmarks"]'::JSONB,
  '["stone_park","seopjikoji","seongsan_ilchulbong","ilchulland","seongeup_folk_village"]'::JSONB,
  3, 3, 5, 4, 4, 3,
  5, 4, 4, 4, 4, 4, 2, 3, 5, 5, 2,
  4, 3, 3, 4, 3,
  3, 42, 3, 5, 2, 4,
  3, 4, 3, 5, 1, 2,
  'mid',
  'jeju_city',
  '17:30-18:00',
  '8h',
  8,
  '{"avoidIf":["monday_departure_required","tight_same_day_departure"],"notIdealFor":["very_low_mobility","stroller_heavy_if_summit_focus"]}'::JSONB,
  '["moderate overall across a full 8-hour day","seongsan summit is optional but is the steepest segment","stone park is mostly flat; ilchulland includes mixed and sometimes damp surfaces","comfortable grip shoes are strongly recommended"]'::JSONB,
  '["east jeju","east jeju small group","first-time jeju","seongsan ilchulbong","seopjikoji","jeju stone park","ilchulland","seongeup folk village","volcano coast village","unesco crater","jeju east day tour"]'::JSONB,
  '["iconic east","balanced day","classic jeju east","geology coast culture","east volcano coast village","first trip east jeju"]'::JSONB,
  2,
  TRUE
),
-- Southwest (author-requested base + extended block; remaining dims tuned)
(
  'southwest-hallasan-osulloc-aewol',
  'small_group',
  'fixed_route',
  'southwest',
  '["jeju_southwest"]'::JSONB,
  '["hallasan", "basalt", "waterfall", "tea", "coast", "cafe"]'::JSONB,
  '["eoseungsaengak", "jusangjeolli", "cheonjeyeon", "osulloc", "aewol"]'::JSONB,
  3, 3, 4, 4, 2, 3,
  5, 3, 3, 4, 4, 3, 2, 3, 4, 4, 4,
  4, 2, 4, 3, 2,
  2, 35, 3, 4, 2, 4,
  3, 4, 2, 5, 1, 2,
  'mid',
  'jeju_city',
  '17:50-18:20',
  '8h',
  8,
  '{"avoidIf":[],"notIdealFor":["very_low_mobility","stroller_heavy_on_trail"]}'::JSONB,
  '["moderate overall","stairs at Hallasan trail and Cheonjeyeon"]'::JSONB,
  '["southwest jeju","hallasan","jusangjeolli","osulloc","aewol","first time"]'::JSONB,
  '["balanced southwest","tea and coast finish"]'::JSONB,
  2,
  TRUE
),
-- Grand highlights loop (base unchanged; extended dims filled)
(
  'jeju-grand-highlights-loop',
  'small_group',
  'fixed_route',
  'full_island',
  '["jeju_all_around","hallasan_to_seongsan"]'::JSONB,
  '["hallasan","basalt","waterfall","crater","fast_paced","one_day"]'::JSONB,
  '["eoseungsaengak","jusangjeolli","jeongbang","seongsan"]'::JSONB,
  5, 4, 5, 5, 2, 2,
  4, 3, 3, 4, 5, 5, 5, 4, 3, 4, 5,
  3, 2, 3, 3, 2,
  2, 28, 4, 2, 2, 3,
  2, 3, 4, 5, 1, 2,
  'mid',
  'jeju_city',
  '17:40-18:15',
  '9.5h',
  10,
  '{"avoidIf":["needs_slow_pace"],"notIdealFor":["stroller_heavy","very_low_mobility","toddlers"]}'::JSONB,
  '["uphill at Hallasan","steps at Jeongbang","optional Seongsan summit"]'::JSONB,
  '["jeju one day","hallasan","seongsan","jusangjeolli","grand tour jeju"]'::JSONB,
  '["full island loop","highlights in one day"]'::JSONB,
  1,
  TRUE
)
ON CONFLICT (product_id) DO UPDATE SET
  product_type = EXCLUDED.product_type,
  route_type = EXCLUDED.route_type,
  region_type = EXCLUDED.region_type,
  region_tags = EXCLUDED.region_tags,
  theme_tags = EXCLUDED.theme_tags,
  poi_tags = EXCLUDED.poi_tags,
  pace_level = EXCLUDED.pace_level,
  walking_level = EXCLUDED.walking_level,
  scenic_level = EXCLUDED.scenic_level,
  photo_level = EXCLUDED.photo_level,
  culture_level = EXCLUDED.culture_level,
  relax_level = EXCLUDED.relax_level,
  first_time_fit = EXCLUDED.first_time_fit,
  family_fit = EXCLUDED.family_fit,
  senior_fit = EXCLUDED.senior_fit,
  couple_fit = EXCLUDED.couple_fit,
  active_traveler_fit = EXCLUDED.active_traveler_fit,
  one_day_fit = EXCLUDED.one_day_fit,
  same_day_flight_fit = EXCLUDED.same_day_flight_fit,
  rain_fit = EXCLUDED.rain_fit,
  value_for_money_fit = EXCLUDED.value_for_money_fit,
  iconic_landmark_fit = EXCLUDED.iconic_landmark_fit,
  cafe_fit = EXCLUDED.cafe_fit,
  adult_family_fit = EXCLUDED.adult_family_fit,
  young_kids_fit = EXCLUDED.young_kids_fit,
  senior_active_fit = EXCLUDED.senior_active_fit,
  senior_general_fit = EXCLUDED.senior_general_fit,
  mobility_friendly_fit = EXCLUDED.mobility_friendly_fit,
  stroller_fit = EXCLUDED.stroller_fit,
  indoor_ratio = EXCLUDED.indoor_ratio,
  weather_sensitivity = EXCLUDED.weather_sensitivity,
  local_culture_fit = EXCLUDED.local_culture_fit,
  shopping_fit = EXCLUDED.shopping_fit,
  storytelling_fit = EXCLUDED.storytelling_fit,
  comfort_level = EXCLUDED.comfort_level,
  budget_fit = EXCLUDED.budget_fit,
  premium_fit = EXCLUDED.premium_fit,
  small_group_fit = EXCLUDED.small_group_fit,
  private_fit = EXCLUDED.private_fit,
  bus_fit = EXCLUDED.bus_fit,
  price_band = EXCLUDED.price_band,
  pickup_base = EXCLUDED.pickup_base,
  return_time_band = EXCLUDED.return_time_band,
  duration_band = EXCLUDED.duration_band,
  min_recommended_age = EXCLUDED.min_recommended_age,
  hard_constraints = EXCLUDED.hard_constraints,
  walking_notes = EXCLUDED.walking_notes,
  keywords = EXCLUDED.keywords,
  synonym_hints = EXCLUDED.synonym_hints,
  profile_version = EXCLUDED.profile_version,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

COMMIT;

SELECT product_id, pace_level, comfort_level, budget_fit, premium_fit, price_band, small_group_fit, profile_version
FROM public.tour_matching_profiles
WHERE product_id IN (
  'east-signature-nature-core',
  'southwest-hallasan-osulloc-aewol',
  'jeju-grand-highlights-loop'
)
ORDER BY product_id;
