/**
 * Curated POI-level matching profiles for the itinerary builder.
 *
 * The DB `match_pois.matching_profile` values were originally derived from
 * parent tour profiles, which leaks tour-level intent onto every stop in a
 * route (for example, a temple inheriting `market_fit=1` because it appears
 * on a food-market tour). This file is the POI-specific correction layer.
 *
 * Runtime is DB-first: rows tagged with `builder_profile_source` use the DB
 * profile as-is. Keep this file as the migration seed source and as a fallback
 * only for unpromoted local/dev data.
 *
 * Keep dimensions factual and local to the stop. Route/package dimensions
 * such as private, cruise, day-trip, and value-for-money do not belong here.
 */

export type CuratedPoiProfile = Record<string, number>;

export const CURATED_POI_PROFILE_SOURCE = "curated_itinerary_builder";
export const CURATED_POI_PROFILE_VERSION = 1;

const DEFAULT_PROFILE: CuratedPoiProfile = {
  first_time_fit: 0.45,
  iconic_landmark_fit: 0.45,
  nature_fit: 0.3,
  beach_fit: 0,
  coastal_fit: 0,
  coastal_cliff_fit: 0,
  cafe_fit: 0,
  food_market_fit: 0,
  market_fit: 0,
  street_food_fit: 0,
  seafood_fit: 0,
  seafood_market_fit: 0,
  unesco_fit: 0,
  unesco_world_heritage_fit: 0,
  world_natural_heritage_fit: 0,
  history_culture_fit: 0.25,
  culture_level: 0.25,
  buddhist_temple_fit: 0,
  museum_fit: 0,
  family_fit: 0.55,
  young_kids_fit: 0.45,
  kid_friendly_fit: 0.45,
  stroller_friendly_fit: 0.35,
  senior_fit: 0.5,
  mobility_friendly_fit: 0.45,
  active_level: 0.35,
  walking_difficulty: 0.35,
  active_traveler_fit: 0.35,
  rain_fit: 0.35,
  indoor_ratio: 0.2,
  photo_fit: 0.55,
  photo_level: 0.55,
  scenic_level: 0.55,
  relaxed_pace_fit: 0.55,
  relax_level: 0.55,
  pace_level: 0.5,
};

const p = (profile: CuratedPoiProfile) => profile;

export const CURATED_POI_PROFILE_OVERRIDES: Record<string, CuratedPoiProfile> = {
  // Busan city core
  jagalchi_market: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.88,
    iconic_landmark_fit: 0.86,
    food_market_fit: 1,
    market_fit: 1,
    street_food_fit: 0.72,
    seafood_fit: 1,
    seafood_market_fit: 1,
    history_culture_fit: 0.45,
    culture_level: 0.55,
    family_fit: 0.72,
    young_kids_fit: 0.5,
    senior_fit: 0.62,
    mobility_friendly_fit: 0.55,
    active_level: 0.25,
    walking_difficulty: 0.25,
    active_traveler_fit: 0.25,
    rain_fit: 0.7,
    indoor_ratio: 0.75,
    photo_fit: 0.72,
    photo_level: 0.72,
    scenic_level: 0.45,
    relaxed_pace_fit: 0.6,
  }),
  gukje_market: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.82,
    iconic_landmark_fit: 0.78,
    food_market_fit: 0.95,
    market_fit: 1,
    street_food_fit: 0.92,
    seafood_fit: 0.25,
    history_culture_fit: 0.65,
    culture_level: 0.72,
    family_fit: 0.7,
    young_kids_fit: 0.48,
    senior_fit: 0.58,
    mobility_friendly_fit: 0.5,
    active_level: 0.3,
    walking_difficulty: 0.32,
    active_traveler_fit: 0.3,
    rain_fit: 0.55,
    indoor_ratio: 0.45,
    photo_fit: 0.62,
    photo_level: 0.62,
    relaxed_pace_fit: 0.58,
  }),
  biff_square: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.74,
    iconic_landmark_fit: 0.72,
    food_market_fit: 0.9,
    market_fit: 0.75,
    street_food_fit: 1,
    history_culture_fit: 0.52,
    culture_level: 0.66,
    family_fit: 0.68,
    young_kids_fit: 0.48,
    senior_fit: 0.56,
    mobility_friendly_fit: 0.5,
    active_level: 0.28,
    walking_difficulty: 0.3,
    active_traveler_fit: 0.28,
    rain_fit: 0.35,
    photo_fit: 0.68,
    photo_level: 0.68,
  }),
  gamcheon_culture_village: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.9,
    iconic_landmark_fit: 0.9,
    history_culture_fit: 0.7,
    culture_level: 0.82,
    photo_fit: 0.95,
    photo_level: 0.95,
    scenic_level: 0.82,
    family_fit: 0.7,
    young_kids_fit: 0.48,
    senior_fit: 0.42,
    mobility_friendly_fit: 0.32,
    active_level: 0.62,
    walking_difficulty: 0.62,
    active_traveler_fit: 0.6,
    relaxed_pace_fit: 0.35,
    rain_fit: 0.25,
    food_market_fit: 0.25,
    street_food_fit: 0.25,
  }),
  haedong_yonggungsa: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.9,
    iconic_landmark_fit: 0.92,
    nature_fit: 0.72,
    coastal_fit: 0.9,
    coastal_cliff_fit: 0.65,
    beach_fit: 0.18,
    buddhist_temple_fit: 0.95,
    history_culture_fit: 0.72,
    culture_level: 0.75,
    photo_fit: 0.95,
    photo_level: 0.95,
    scenic_level: 0.9,
    family_fit: 0.66,
    young_kids_fit: 0.4,
    senior_fit: 0.42,
    mobility_friendly_fit: 0.25,
    active_level: 0.6,
    walking_difficulty: 0.62,
    active_traveler_fit: 0.58,
    rain_fit: 0.2,
    relaxed_pace_fit: 0.38,
  }),
  songdo_beach: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.72,
    iconic_landmark_fit: 0.72,
    nature_fit: 0.62,
    beach_fit: 0.95,
    coastal_fit: 0.95,
    coastal_cliff_fit: 0.55,
    cafe_fit: 0.35,
    photo_fit: 0.82,
    photo_level: 0.82,
    scenic_level: 0.8,
    family_fit: 0.78,
    young_kids_fit: 0.68,
    stroller_friendly_fit: 0.7,
    senior_fit: 0.68,
    mobility_friendly_fit: 0.68,
    active_level: 0.24,
    walking_difficulty: 0.22,
    active_traveler_fit: 0.24,
    relaxed_pace_fit: 0.82,
    rain_fit: 0.18,
  }),
  cheongsapo_blue_line_park: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.82,
    iconic_landmark_fit: 0.78,
    nature_fit: 0.7,
    beach_fit: 0.72,
    coastal_fit: 0.95,
    coastal_cliff_fit: 0.45,
    cafe_fit: 0.65,
    photo_fit: 0.92,
    photo_level: 0.92,
    scenic_level: 0.9,
    family_fit: 0.82,
    young_kids_fit: 0.72,
    stroller_friendly_fit: 0.78,
    senior_fit: 0.76,
    mobility_friendly_fit: 0.78,
    active_level: 0.2,
    walking_difficulty: 0.2,
    active_traveler_fit: 0.2,
    relaxed_pace_fit: 0.86,
    rain_fit: 0.35,
  }),
  taejongdae: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.76,
    iconic_landmark_fit: 0.8,
    nature_fit: 0.86,
    beach_fit: 0.25,
    coastal_fit: 0.9,
    coastal_cliff_fit: 0.85,
    buddhist_temple_fit: 0.25,
    history_culture_fit: 0.42,
    photo_fit: 0.9,
    photo_level: 0.9,
    scenic_level: 0.95,
    family_fit: 0.58,
    young_kids_fit: 0.32,
    senior_fit: 0.35,
    mobility_friendly_fit: 0.25,
    active_level: 0.78,
    walking_difficulty: 0.78,
    active_traveler_fit: 0.78,
    relaxed_pace_fit: 0.28,
    rain_fit: 0.12,
  }),
  un_memorial_cemetery: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.58,
    iconic_landmark_fit: 0.68,
    nature_fit: 0.35,
    history_culture_fit: 0.95,
    culture_level: 0.9,
    museum_fit: 0.55,
    family_fit: 0.52,
    young_kids_fit: 0.2,
    senior_fit: 0.78,
    mobility_friendly_fit: 0.8,
    active_level: 0.18,
    walking_difficulty: 0.18,
    active_traveler_fit: 0.18,
    rain_fit: 0.35,
    indoor_ratio: 0.25,
    photo_fit: 0.45,
    scenic_level: 0.38,
    relaxed_pace_fit: 0.8,
  }),
  yongdusan_park: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.72,
    iconic_landmark_fit: 0.78,
    nature_fit: 0.45,
    history_culture_fit: 0.52,
    culture_level: 0.58,
    photo_fit: 0.72,
    photo_level: 0.72,
    scenic_level: 0.68,
    family_fit: 0.68,
    young_kids_fit: 0.55,
    senior_fit: 0.65,
    mobility_friendly_fit: 0.62,
    active_level: 0.25,
    walking_difficulty: 0.28,
    active_traveler_fit: 0.25,
    relaxed_pace_fit: 0.68,
    rain_fit: 0.25,
  }),
  ahopsan_bamboo_forest: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.45,
    iconic_landmark_fit: 0.55,
    nature_fit: 0.9,
    history_culture_fit: 0.55,
    culture_level: 0.55,
    photo_fit: 0.82,
    photo_level: 0.82,
    scenic_level: 0.85,
    family_fit: 0.55,
    young_kids_fit: 0.3,
    senior_fit: 0.35,
    mobility_friendly_fit: 0.25,
    active_level: 0.68,
    walking_difficulty: 0.68,
    active_traveler_fit: 0.68,
    relaxed_pace_fit: 0.35,
    rain_fit: 0.15,
  }),

  // Busan day-trip cluster
  bulguksa_temple: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.9,
    iconic_landmark_fit: 0.95,
    unesco_fit: 1,
    unesco_world_heritage_fit: 1,
    buddhist_temple_fit: 1,
    history_culture_fit: 0.96,
    culture_level: 0.96,
    nature_fit: 0.5,
    photo_fit: 0.85,
    scenic_level: 0.72,
    family_fit: 0.7,
    young_kids_fit: 0.42,
    senior_fit: 0.56,
    mobility_friendly_fit: 0.42,
    active_level: 0.52,
    walking_difficulty: 0.55,
    active_traveler_fit: 0.52,
    relaxed_pace_fit: 0.48,
    rain_fit: 0.25,
  }),
  tongdosa_temple: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.78,
    iconic_landmark_fit: 0.88,
    unesco_fit: 1,
    unesco_world_heritage_fit: 1,
    buddhist_temple_fit: 1,
    history_culture_fit: 0.92,
    culture_level: 0.92,
    nature_fit: 0.58,
    photo_fit: 0.78,
    scenic_level: 0.72,
    family_fit: 0.72,
    young_kids_fit: 0.46,
    senior_fit: 0.58,
    mobility_friendly_fit: 0.48,
    active_level: 0.45,
    walking_difficulty: 0.48,
    active_traveler_fit: 0.45,
    relaxed_pace_fit: 0.55,
    rain_fit: 0.25,
  }),
  cheomseongdae: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.84,
    iconic_landmark_fit: 0.9,
    unesco_fit: 0.9,
    unesco_world_heritage_fit: 0.9,
    history_culture_fit: 0.95,
    culture_level: 0.92,
    photo_fit: 0.82,
    scenic_level: 0.72,
    family_fit: 0.82,
    young_kids_fit: 0.68,
    stroller_friendly_fit: 0.75,
    senior_fit: 0.78,
    mobility_friendly_fit: 0.78,
    active_level: 0.2,
    walking_difficulty: 0.22,
    active_traveler_fit: 0.2,
    relaxed_pace_fit: 0.78,
    rain_fit: 0.18,
  }),
  gyeongju_national_museum: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.78,
    iconic_landmark_fit: 0.75,
    unesco_fit: 0.55,
    history_culture_fit: 1,
    culture_level: 0.95,
    museum_fit: 1,
    family_fit: 0.78,
    young_kids_fit: 0.62,
    stroller_friendly_fit: 0.82,
    senior_fit: 0.85,
    mobility_friendly_fit: 0.85,
    active_level: 0.15,
    walking_difficulty: 0.15,
    active_traveler_fit: 0.15,
    rain_fit: 0.95,
    indoor_ratio: 0.95,
    photo_fit: 0.55,
    scenic_level: 0.3,
    relaxed_pace_fit: 0.82,
  }),
  gyochon_hanok_village: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.72,
    iconic_landmark_fit: 0.68,
    unesco_fit: 0.55,
    history_culture_fit: 0.88,
    culture_level: 0.9,
    food_market_fit: 0.35,
    street_food_fit: 0.35,
    photo_fit: 0.78,
    scenic_level: 0.55,
    family_fit: 0.74,
    young_kids_fit: 0.6,
    senior_fit: 0.72,
    mobility_friendly_fit: 0.72,
    active_level: 0.22,
    walking_difficulty: 0.25,
    active_traveler_fit: 0.22,
    relaxed_pace_fit: 0.78,
    rain_fit: 0.3,
  }),
  woljeonggyo_bridge: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.7,
    iconic_landmark_fit: 0.78,
    unesco_fit: 0.45,
    history_culture_fit: 0.78,
    culture_level: 0.78,
    photo_fit: 0.92,
    scenic_level: 0.72,
    family_fit: 0.78,
    young_kids_fit: 0.65,
    senior_fit: 0.78,
    mobility_friendly_fit: 0.75,
    active_level: 0.15,
    walking_difficulty: 0.18,
    active_traveler_fit: 0.15,
    relaxed_pace_fit: 0.82,
    rain_fit: 0.2,
  }),
  bomun_lake: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.58,
    iconic_landmark_fit: 0.65,
    nature_fit: 0.72,
    history_culture_fit: 0.25,
    culture_level: 0.3,
    photo_fit: 0.88,
    scenic_level: 0.82,
    family_fit: 0.8,
    young_kids_fit: 0.7,
    senior_fit: 0.75,
    mobility_friendly_fit: 0.75,
    active_level: 0.22,
    walking_difficulty: 0.2,
    active_traveler_fit: 0.22,
    relaxed_pace_fit: 0.86,
    cherry_blossom_fit: 1,
    spring_fit: 0.9,
    rain_fit: 0.18,
  }),
  amethyst_cave_themepark: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.42,
    iconic_landmark_fit: 0.46,
    nature_fit: 0.25,
    history_culture_fit: 0.25,
    culture_level: 0.3,
    museum_fit: 0.45,
    family_fit: 0.82,
    young_kids_fit: 0.78,
    senior_fit: 0.65,
    mobility_friendly_fit: 0.62,
    active_level: 0.25,
    walking_difficulty: 0.3,
    active_traveler_fit: 0.25,
    rain_fit: 0.9,
    indoor_ratio: 0.95,
    photo_fit: 0.55,
    relaxed_pace_fit: 0.68,
  }),
  yeongnam_alps_ice_valley_cable_car: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.48,
    iconic_landmark_fit: 0.58,
    nature_fit: 0.92,
    scenic_level: 0.95,
    photo_fit: 0.88,
    family_fit: 0.68,
    young_kids_fit: 0.42,
    senior_fit: 0.5,
    mobility_friendly_fit: 0.42,
    active_level: 0.65,
    walking_difficulty: 0.58,
    active_traveler_fit: 0.65,
    relaxed_pace_fit: 0.35,
    rain_fit: 0.15,
  }),

  // Jeju
  aewol_cafe_street: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.82,
    iconic_landmark_fit: 0.82,
    nature_fit: 0.62,
    beach_fit: 0.72,
    coastal_fit: 0.95,
    coastal_cliff_fit: 0.4,
    cafe_fit: 1,
    photo_fit: 0.95,
    photo_level: 0.95,
    scenic_level: 0.86,
    family_fit: 0.75,
    young_kids_fit: 0.62,
    stroller_friendly_fit: 0.75,
    senior_fit: 0.72,
    mobility_friendly_fit: 0.72,
    active_level: 0.18,
    walking_difficulty: 0.2,
    active_traveler_fit: 0.18,
    relaxed_pace_fit: 0.95,
    rain_fit: 0.45,
    indoor_ratio: 0.5,
  }),
  hyeopjae_beach: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.78,
    iconic_landmark_fit: 0.82,
    nature_fit: 0.75,
    beach_fit: 1,
    coastal_fit: 1,
    cafe_fit: 0.72,
    photo_fit: 0.9,
    photo_level: 0.9,
    scenic_level: 0.88,
    family_fit: 0.84,
    young_kids_fit: 0.78,
    stroller_friendly_fit: 0.82,
    senior_fit: 0.8,
    mobility_friendly_fit: 0.8,
    active_level: 0.15,
    walking_difficulty: 0.15,
    active_traveler_fit: 0.15,
    relaxed_pace_fit: 0.95,
    rain_fit: 0.16,
  }),
  hamdeok_seoubong_beach: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.8,
    iconic_landmark_fit: 0.82,
    nature_fit: 0.76,
    beach_fit: 1,
    coastal_fit: 1,
    cafe_fit: 0.58,
    photo_fit: 0.9,
    photo_level: 0.9,
    scenic_level: 0.88,
    family_fit: 0.88,
    young_kids_fit: 0.82,
    stroller_friendly_fit: 0.82,
    senior_fit: 0.78,
    mobility_friendly_fit: 0.78,
    active_level: 0.18,
    walking_difficulty: 0.18,
    active_traveler_fit: 0.18,
    relaxed_pace_fit: 0.92,
    rain_fit: 0.16,
  }),
  seongsan_ilchulbong: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.95,
    iconic_landmark_fit: 1,
    nature_fit: 0.95,
    beach_fit: 0.25,
    coastal_fit: 0.75,
    coastal_cliff_fit: 0.7,
    unesco_fit: 1,
    unesco_world_heritage_fit: 1,
    world_natural_heritage_fit: 1,
    history_culture_fit: 0.5,
    culture_level: 0.55,
    photo_fit: 0.95,
    photo_level: 0.95,
    scenic_level: 1,
    family_fit: 0.62,
    young_kids_fit: 0.32,
    senior_fit: 0.32,
    mobility_friendly_fit: 0.18,
    active_level: 0.82,
    walking_difficulty: 0.85,
    active_traveler_fit: 0.82,
    relaxed_pace_fit: 0.22,
    rain_fit: 0.1,
  }),
  seopjikoji: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.8,
    iconic_landmark_fit: 0.82,
    nature_fit: 0.86,
    beach_fit: 0.28,
    coastal_fit: 0.9,
    coastal_cliff_fit: 0.78,
    cafe_fit: 0.45,
    history_culture_fit: 0.35,
    culture_level: 0.42,
    photo_fit: 0.95,
    photo_level: 0.95,
    scenic_level: 0.95,
    family_fit: 0.66,
    young_kids_fit: 0.42,
    senior_fit: 0.52,
    mobility_friendly_fit: 0.45,
    active_level: 0.55,
    walking_difficulty: 0.55,
    active_traveler_fit: 0.55,
    relaxed_pace_fit: 0.48,
    rain_fit: 0.12,
  }),
  daepo_jusangjeolli_cliff: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.82,
    iconic_landmark_fit: 0.86,
    nature_fit: 0.9,
    beach_fit: 0.15,
    coastal_fit: 0.88,
    coastal_cliff_fit: 1,
    unesco_fit: 0.75,
    world_natural_heritage_fit: 0.65,
    photo_fit: 0.9,
    scenic_level: 0.9,
    family_fit: 0.7,
    young_kids_fit: 0.48,
    senior_fit: 0.62,
    mobility_friendly_fit: 0.58,
    active_level: 0.28,
    walking_difficulty: 0.3,
    active_traveler_fit: 0.28,
    relaxed_pace_fit: 0.65,
    rain_fit: 0.15,
  }),
  jeongbang_falls: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.82,
    iconic_landmark_fit: 0.85,
    nature_fit: 0.88,
    beach_fit: 0.25,
    coastal_fit: 0.85,
    coastal_cliff_fit: 0.55,
    photo_fit: 0.9,
    scenic_level: 0.88,
    family_fit: 0.62,
    young_kids_fit: 0.35,
    senior_fit: 0.42,
    mobility_friendly_fit: 0.3,
    active_level: 0.6,
    walking_difficulty: 0.62,
    active_traveler_fit: 0.6,
    relaxed_pace_fit: 0.35,
    rain_fit: 0.12,
  }),
  cheonjeyeon_falls: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.7,
    iconic_landmark_fit: 0.72,
    nature_fit: 0.84,
    coastal_fit: 0.25,
    photo_fit: 0.82,
    scenic_level: 0.82,
    family_fit: 0.62,
    young_kids_fit: 0.38,
    senior_fit: 0.45,
    mobility_friendly_fit: 0.34,
    active_level: 0.58,
    walking_difficulty: 0.6,
    active_traveler_fit: 0.58,
    relaxed_pace_fit: 0.4,
    rain_fit: 0.14,
  }),
  osulloc_tea_museum: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.72,
    iconic_landmark_fit: 0.78,
    nature_fit: 0.58,
    beach_fit: 0,
    coastal_fit: 0,
    cafe_fit: 0.85,
    history_culture_fit: 0.55,
    culture_level: 0.72,
    museum_fit: 0.55,
    family_fit: 0.8,
    young_kids_fit: 0.68,
    stroller_friendly_fit: 0.85,
    senior_fit: 0.85,
    mobility_friendly_fit: 0.85,
    active_level: 0.12,
    walking_difficulty: 0.12,
    active_traveler_fit: 0.12,
    rain_fit: 0.85,
    indoor_ratio: 0.72,
    photo_fit: 0.72,
    scenic_level: 0.62,
    relaxed_pace_fit: 0.9,
  }),
  jeju_stone_park: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.62,
    iconic_landmark_fit: 0.68,
    nature_fit: 0.78,
    beach_fit: 0,
    coastal_fit: 0,
    coastal_cliff_fit: 0,
    history_culture_fit: 0.9,
    culture_level: 0.92,
    museum_fit: 0.72,
    family_fit: 0.72,
    young_kids_fit: 0.6,
    senior_fit: 0.62,
    mobility_friendly_fit: 0.55,
    active_level: 0.38,
    walking_difficulty: 0.4,
    active_traveler_fit: 0.38,
    rain_fit: 0.45,
    indoor_ratio: 0.4,
    photo_fit: 0.75,
    scenic_level: 0.72,
    relaxed_pace_fit: 0.65,
  }),
  seongeup_folk_village: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.68,
    iconic_landmark_fit: 0.7,
    nature_fit: 0.35,
    beach_fit: 0,
    coastal_fit: 0,
    history_culture_fit: 0.9,
    culture_level: 0.92,
    family_fit: 0.72,
    young_kids_fit: 0.55,
    senior_fit: 0.7,
    mobility_friendly_fit: 0.68,
    active_level: 0.22,
    walking_difficulty: 0.25,
    active_traveler_fit: 0.22,
    rain_fit: 0.35,
    photo_fit: 0.72,
    scenic_level: 0.55,
    relaxed_pace_fit: 0.75,
  }),
  jeju_haenyeo_museum: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.62,
    iconic_landmark_fit: 0.68,
    nature_fit: 0.4,
    coastal_fit: 0.5,
    history_culture_fit: 0.9,
    culture_level: 0.92,
    museum_fit: 0.92,
    family_fit: 0.74,
    young_kids_fit: 0.62,
    stroller_friendly_fit: 0.82,
    senior_fit: 0.85,
    mobility_friendly_fit: 0.85,
    active_level: 0.1,
    walking_difficulty: 0.12,
    active_traveler_fit: 0.1,
    rain_fit: 0.95,
    indoor_ratio: 0.95,
    photo_fit: 0.45,
    scenic_level: 0.45,
    relaxed_pace_fit: 0.85,
  }),
  hallasan_1100_wetland: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.7,
    iconic_landmark_fit: 0.76,
    nature_fit: 0.95,
    unesco_fit: 0.82,
    world_natural_heritage_fit: 0.82,
    photo_fit: 0.85,
    scenic_level: 0.88,
    family_fit: 0.78,
    young_kids_fit: 0.65,
    stroller_friendly_fit: 0.75,
    senior_fit: 0.76,
    mobility_friendly_fit: 0.76,
    active_level: 0.18,
    walking_difficulty: 0.18,
    active_traveler_fit: 0.18,
    relaxed_pace_fit: 0.82,
    rain_fit: 0.18,
    winter_fit: 0.8,
    snow_fit: 0.8,
  }),
  hallasan_eoseungsaengak: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.72,
    iconic_landmark_fit: 0.78,
    nature_fit: 0.95,
    unesco_fit: 0.82,
    world_natural_heritage_fit: 0.82,
    photo_fit: 0.88,
    scenic_level: 0.92,
    family_fit: 0.58,
    young_kids_fit: 0.25,
    senior_fit: 0.3,
    mobility_friendly_fit: 0.18,
    active_level: 0.85,
    walking_difficulty: 0.85,
    active_traveler_fit: 0.85,
    relaxed_pace_fit: 0.18,
    rain_fit: 0.08,
  }),
  hallasan_eorimok_trail: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.58,
    iconic_landmark_fit: 0.72,
    nature_fit: 0.95,
    unesco_fit: 0.82,
    world_natural_heritage_fit: 0.82,
    photo_fit: 0.88,
    scenic_level: 0.92,
    family_fit: 0.45,
    young_kids_fit: 0.12,
    senior_fit: 0.18,
    mobility_friendly_fit: 0.08,
    active_level: 1,
    walking_difficulty: 1,
    active_traveler_fit: 1,
    relaxed_pace_fit: 0.08,
    rain_fit: 0.05,
    winter_fit: 0.85,
    snow_fit: 0.85,
  }),
  songaksan: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.7,
    iconic_landmark_fit: 0.78,
    nature_fit: 0.9,
    beach_fit: 0.12,
    coastal_fit: 0.9,
    coastal_cliff_fit: 0.82,
    history_culture_fit: 0.45,
    photo_fit: 0.92,
    scenic_level: 0.95,
    family_fit: 0.55,
    young_kids_fit: 0.22,
    senior_fit: 0.32,
    mobility_friendly_fit: 0.22,
    active_level: 0.78,
    walking_difficulty: 0.78,
    active_traveler_fit: 0.78,
    relaxed_pace_fit: 0.22,
    rain_fit: 0.08,
  }),
  camellia_hill: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.7,
    iconic_landmark_fit: 0.76,
    nature_fit: 0.82,
    cafe_fit: 0.45,
    photo_fit: 0.9,
    scenic_level: 0.8,
    family_fit: 0.82,
    young_kids_fit: 0.72,
    stroller_friendly_fit: 0.75,
    senior_fit: 0.78,
    mobility_friendly_fit: 0.75,
    active_level: 0.28,
    walking_difficulty: 0.3,
    active_traveler_fit: 0.28,
    relaxed_pace_fit: 0.82,
    rain_fit: 0.42,
    winter_camellia_bloom_fit: 1,
    hydrangea_fit: 0.82,
    summer_flowers_hydrangea_fit: 0.82,
  }),
  hallim_park: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.68,
    iconic_landmark_fit: 0.72,
    nature_fit: 0.8,
    cafe_fit: 0.35,
    history_culture_fit: 0.45,
    culture_level: 0.5,
    photo_fit: 0.82,
    scenic_level: 0.75,
    family_fit: 0.82,
    young_kids_fit: 0.72,
    stroller_friendly_fit: 0.68,
    senior_fit: 0.68,
    mobility_friendly_fit: 0.62,
    active_level: 0.42,
    walking_difficulty: 0.45,
    active_traveler_fit: 0.42,
    relaxed_pace_fit: 0.65,
    rain_fit: 0.5,
    indoor_ratio: 0.45,
    hydrangea_fit: 0.85,
    summer_flowers_hydrangea_fit: 0.85,
  }),
  hueree_natural_park: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.62,
    iconic_landmark_fit: 0.68,
    nature_fit: 0.8,
    history_culture_fit: 0.35,
    culture_level: 0.42,
    photo_fit: 0.85,
    scenic_level: 0.72,
    family_fit: 0.9,
    young_kids_fit: 0.9,
    stroller_friendly_fit: 0.72,
    senior_fit: 0.7,
    mobility_friendly_fit: 0.68,
    active_level: 0.3,
    walking_difficulty: 0.32,
    active_traveler_fit: 0.3,
    relaxed_pace_fit: 0.78,
    rain_fit: 0.45,
    hydrangea_fit: 0.9,
    summer_flowers_hydrangea_fit: 0.9,
  }),
  ilchulland_micheon_cave: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.6,
    iconic_landmark_fit: 0.65,
    nature_fit: 0.65,
    history_culture_fit: 0.45,
    culture_level: 0.45,
    museum_fit: 0.45,
    family_fit: 0.82,
    young_kids_fit: 0.72,
    stroller_friendly_fit: 0.7,
    senior_fit: 0.72,
    mobility_friendly_fit: 0.72,
    active_level: 0.28,
    walking_difficulty: 0.28,
    active_traveler_fit: 0.28,
    rain_fit: 0.9,
    indoor_ratio: 0.7,
    photo_fit: 0.65,
    scenic_level: 0.58,
    relaxed_pace_fit: 0.72,
    hydrangea_fit: 0.75,
    summer_flowers_hydrangea_fit: 0.75,
  }),
  ilchulland_themed_gardens: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.52,
    iconic_landmark_fit: 0.55,
    nature_fit: 0.68,
    history_culture_fit: 0.35,
    culture_level: 0.45,
    family_fit: 0.78,
    young_kids_fit: 0.68,
    senior_fit: 0.68,
    mobility_friendly_fit: 0.65,
    active_level: 0.25,
    walking_difficulty: 0.28,
    active_traveler_fit: 0.25,
    rain_fit: 0.45,
    photo_fit: 0.7,
    scenic_level: 0.65,
    relaxed_pace_fit: 0.72,
  }),
  jeju_tangerine_picking_experience: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.55,
    iconic_landmark_fit: 0.55,
    nature_fit: 0.55,
    food_market_fit: 0.25,
    family_fit: 0.9,
    young_kids_fit: 0.92,
    stroller_friendly_fit: 0.72,
    senior_fit: 0.72,
    mobility_friendly_fit: 0.7,
    active_level: 0.22,
    walking_difficulty: 0.25,
    active_traveler_fit: 0.22,
    rain_fit: 0.35,
    photo_fit: 0.75,
    scenic_level: 0.5,
    relaxed_pace_fit: 0.82,
    tangerine_fit: 1,
    tangerine_picking_winter_fit: 1,
    winter_fit: 0.9,
  }),
  jeonnong_ro_cherry_blossom_street: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.58,
    iconic_landmark_fit: 0.62,
    nature_fit: 0.52,
    history_culture_fit: 0.35,
    culture_level: 0.45,
    photo_fit: 0.9,
    scenic_level: 0.78,
    family_fit: 0.76,
    young_kids_fit: 0.68,
    senior_fit: 0.75,
    mobility_friendly_fit: 0.75,
    active_level: 0.15,
    walking_difficulty: 0.15,
    active_traveler_fit: 0.15,
    relaxed_pace_fit: 0.88,
    rain_fit: 0.1,
    cherry_blossom_fit: 1,
    spring_fit: 1,
  }),
  noksan_ro_gasiri_blossom_road: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0.6,
    iconic_landmark_fit: 0.68,
    nature_fit: 0.7,
    photo_fit: 0.95,
    scenic_level: 0.9,
    family_fit: 0.72,
    young_kids_fit: 0.58,
    senior_fit: 0.65,
    mobility_friendly_fit: 0.62,
    active_level: 0.12,
    walking_difficulty: 0.12,
    active_traveler_fit: 0.12,
    relaxed_pace_fit: 0.88,
    rain_fit: 0.08,
    cherry_blossom_fit: 1,
    canola_flower_fit: 1,
    spring_fit: 1,
  }),
  gangjeong_cruise_port: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0,
    iconic_landmark_fit: 0,
    nature_fit: 0,
    history_culture_fit: 0,
    culture_level: 0,
    family_fit: 0,
    active_level: 0,
    walking_difficulty: 0,
    photo_fit: 0,
    scenic_level: 0,
    relaxed_pace_fit: 0,
    cruise_logistics_fit: 1,
  }),
  jeju_cruise_port: p({
    ...DEFAULT_PROFILE,
    first_time_fit: 0,
    iconic_landmark_fit: 0,
    nature_fit: 0,
    history_culture_fit: 0,
    culture_level: 0,
    family_fit: 0,
    active_level: 0,
    walking_difficulty: 0,
    photo_fit: 0,
    scenic_level: 0,
    relaxed_pace_fit: 0,
    cruise_logistics_fit: 1,
  }),
};

export function getCuratedPoiProfile(poiKey: string): CuratedPoiProfile | null {
  return CURATED_POI_PROFILE_OVERRIDES[poiKey] ?? null;
}

export function mergeCuratedPoiProfile(
  poiKey: string,
  dbProfile: Record<string, unknown> | null
): Record<string, unknown> {
  const curated = getCuratedPoiProfile(poiKey);
  if (!curated) return dbProfile ?? {};
  return {
    ...(dbProfile ?? {}),
    ...curated,
    _profile_source: `${CURATED_POI_PROFILE_SOURCE}_v${CURATED_POI_PROFILE_VERSION}`,
  };
}
